import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'Securities Act of 1933',
    shortName: 'Securities Act',
    citation: '15 U.S.C. § 77a et seq.',
    category: 'Securities',
    jurisdiction: 'Federal Statute',
    enactedYear: 1933,
    summary:
      'The Securities Act of 1933 was the first major federal law regulating the offer and sale of securities. It requires companies that want to sell securities to the public to register those securities with the federal government and provide investors with accurate, material information through a prospectus. The law was enacted in the wake of the 1929 stock market crash to restore investor confidence by promoting transparency. It imposes civil liability on issuers, underwriters, and others who make material misstatements or omissions in registration statements. Exemptions exist for private placements, small offerings, and intrastate offerings.',
    keyProvisions: [
      'Requires registration of securities offerings with the SEC before public sale',
      'Mandates delivery of a prospectus containing material information to prospective investors',
      'Prohibits fraud and material misstatements in the offer or sale of securities',
      'Imposes strict liability on issuers for materially false registration statements (Section 11)',
      'Provides civil remedies allowing purchasers to sue for rescission or damages',
      'Creates exemptions for private placements (Section 4(a)(2)) and Regulation D offerings',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/77a',
    relatedLitigation: ['securities'],
  },
  {
    name: 'Securities Exchange Act of 1934',
    shortName: 'Exchange Act',
    citation: '15 U.S.C. § 78a et seq.',
    category: 'Securities',
    jurisdiction: 'Federal Statute',
    enactedYear: 1934,
    summary:
      'The Securities Exchange Act of 1934 created the Securities and Exchange Commission (SEC) and established a comprehensive framework for regulating the trading of securities in secondary markets. It imposes ongoing disclosure obligations on public companies, including annual and quarterly reporting requirements. Rule 10b-5, promulgated under Section 10(b), is the primary federal anti-fraud rule and prohibits any person from making false statements or engaging in deceptive conduct in connection with the purchase or sale of any security. The Act also regulates broker-dealers, stock exchanges, and proxy solicitations. Insider trading enforcement is primarily grounded in Rule 10b-5.',
    keyProvisions: [
      'Created the Securities and Exchange Commission (SEC) as the primary federal securities regulator',
      'Requires public companies to file periodic reports (Forms 10-K, 10-Q, 8-K) with the SEC',
      'Section 10(b) and Rule 10b-5 prohibit fraud, misrepresentation, and insider trading in securities transactions',
      'Regulates broker-dealers, exchanges, and securities clearing organizations',
      'Governs proxy solicitations and tender offers for public companies',
      'Imposes short-swing profit disgorgement on corporate insiders under Section 16(b)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/78a',
    relatedLitigation: ['securities'],
  },
  {
    name: 'Sarbanes-Oxley Act of 2002',
    shortName: 'SOX',
    citation: 'Pub. L. 107-204, 116 Stat. 745',
    category: 'Securities',
    jurisdiction: 'Federal Statute',
    enactedYear: 2002,
    summary:
      'The Sarbanes-Oxley Act of 2002 was enacted in response to major corporate accounting scandals, including Enron and WorldCom, to improve corporate governance and the accuracy of financial disclosures by public companies. It created the Public Company Accounting Oversight Board (PCAOB) to oversee the auditing profession. The law requires CEOs and CFOs to personally certify the accuracy of financial statements and imposed strict criminal penalties for securities fraud and document destruction. It also enhanced protections for whistleblowers who report securities violations. SOX significantly increased the compliance burden for public companies but is widely credited with raising the quality of financial reporting.',
    keyProvisions: [
      'Established the Public Company Accounting Oversight Board (PCAOB) to regulate auditors of public companies',
      'Requires CEO and CFO certification of the accuracy of financial reports (Section 302 and 906)',
      'Mandates internal controls over financial reporting and auditor attestation thereof (Section 404)',
      'Prohibits certain non-audit services by a company\'s auditor to preserve independence',
      'Criminalizes securities fraud, mail fraud, and destruction of audit records with enhanced penalties',
      'Protects corporate whistleblowers from retaliation and extends the statute of limitations for securities fraud',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Sarbanes%E2%80%93Oxley_Act',
    relatedLitigation: ['securities'],
  },
  {
    name: 'Dodd-Frank Wall Street Reform and Consumer Protection Act',
    shortName: 'Dodd-Frank',
    citation: 'Pub. L. 111-203, 124 Stat. 1376',
    category: 'Securities',
    jurisdiction: 'Federal Statute',
    enactedYear: 2010,
    summary:
      'The Dodd-Frank Act was enacted following the 2008 financial crisis to overhaul financial regulation and reduce systemic risk in the U.S. financial system. It created the Consumer Financial Protection Bureau (CFPB) to protect consumers from abusive financial products and the Financial Stability Oversight Council (FSOC) to monitor systemic risk. The Volcker Rule, a key provision, restricts banks from engaging in proprietary trading and from owning hedge funds or private equity funds. Dodd-Frank also strengthened SEC whistleblower incentives, providing financial awards to individuals who report securities violations. The law significantly expanded federal oversight of derivatives markets, credit rating agencies, and systemically important financial institutions.',
    keyProvisions: [
      'Created the Consumer Financial Protection Bureau (CFPB) to regulate consumer financial products and services',
      'Established the Financial Stability Oversight Council (FSOC) to identify and respond to systemic financial risks',
      'The Volcker Rule (Section 619) prohibits banks from proprietary trading and limits their investment in hedge and private equity funds',
      'Expanded SEC whistleblower program with financial awards (10-30% of sanctions over $1 million)',
      'Brought over-the-counter derivatives under federal oversight through mandatory clearing and reporting requirements',
      'Authorized the FDIC to resolve failing systemically important financial institutions outside of bankruptcy',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Dodd%E2%80%93Frank_Wall_Street_Reform_and_Consumer_Protection_Act',
    relatedLitigation: ['securities', 'banking-finance'],
  },
  {
    name: 'Sherman Antitrust Act',
    shortName: 'Sherman Act',
    citation: '15 U.S.C. §§ 1-7',
    category: 'Antitrust',
    jurisdiction: 'Federal Statute',
    enactedYear: 1890,
    summary:
      'The Sherman Antitrust Act of 1890 is the foundational federal antitrust law, prohibiting contracts, combinations, and conspiracies that unreasonably restrain interstate or foreign trade. It also prohibits monopolization and attempted monopolization of any part of trade or commerce. Violations are both civil and criminal offenses, with criminal violations potentially resulting in substantial fines and imprisonment. Courts use two analytical frameworks: the per se rule (for obviously anticompetitive conduct like price-fixing) and the rule of reason (for conduct requiring a full competitive analysis). The Act has been used to break up major corporations and remains a central tool of U.S. competition policy.',
    keyProvisions: [
      'Section 1 prohibits contracts, combinations, or conspiracies in restraint of trade or commerce',
      'Section 2 prohibits monopolization, attempted monopolization, and conspiracies to monopolize',
      'Provides for criminal penalties including fines up to $100 million for corporations and imprisonment for individuals',
      'Permits civil suits by the government and by private parties injured by antitrust violations',
      'Allows courts to issue injunctions and treble damages in private civil actions',
      'Applies per se illegality to hardcore cartel conduct such as price-fixing, bid-rigging, and market allocation',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/1',
    relatedLitigation: ['antitrust'],
  },
  {
    name: 'Clayton Antitrust Act',
    shortName: 'Clayton Act',
    citation: '15 U.S.C. §§ 12-27',
    category: 'Antitrust',
    jurisdiction: 'Federal Statute',
    enactedYear: 1914,
    summary:
      'The Clayton Act of 1914 supplements the Sherman Act by addressing specific anticompetitive practices not clearly covered by the earlier law, including anticompetitive mergers, exclusive dealing arrangements, tying agreements, and interlocking directorates. Section 7 is the primary federal merger control statute, prohibiting acquisitions where the effect may be substantially to lessen competition or tend to create a monopoly. The Act also contains important labor provisions exempting unions from antitrust liability. Private plaintiffs who prove antitrust violations may recover treble damages and attorney fees under the Clayton Act. It was amended by the Hart-Scott-Rodino Act to add pre-merger notification requirements.',
    keyProvisions: [
      'Section 7 prohibits mergers and acquisitions that may substantially lessen competition or tend to create a monopoly',
      'Section 3 restricts exclusive dealing and tying arrangements where the effect may be to substantially lessen competition',
      'Section 8 prohibits interlocking directorates between competing corporations above certain size thresholds',
      'Section 4 provides for private treble-damages actions and attorney fee awards for antitrust violations',
      'Exempts labor unions and agricultural cooperatives from antitrust liability',
      'Authorizes injunctive relief for private parties threatened with antitrust injury',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/12',
    relatedLitigation: ['antitrust'],
  },
  {
    name: 'Federal Trade Commission Act',
    shortName: 'FTC Act',
    citation: '15 U.S.C. §§ 41-58',
    category: 'Antitrust',
    jurisdiction: 'Federal Statute',
    enactedYear: 1914,
    summary:
      'The Federal Trade Commission Act of 1914 created the Federal Trade Commission (FTC) and broadly prohibits unfair methods of competition and unfair or deceptive acts or practices in or affecting commerce. Section 5 is the FTC\'s primary enforcement tool and reaches a wide range of anticompetitive and deceptive conduct, including practices that might not violate the Sherman or Clayton Acts. The FTC uses its authority to challenge anticompetitive mergers, deceptive advertising, and consumer privacy violations. Unlike the Sherman Act, the FTC Act does not provide a private right of action; only the FTC can bring enforcement actions under it. The Act has become increasingly important in regulating digital platforms and data privacy.',
    keyProvisions: [
      'Established the Federal Trade Commission as an independent agency with antitrust and consumer protection authority',
      'Section 5 broadly prohibits unfair methods of competition and unfair or deceptive acts or practices',
      'Authorizes the FTC to issue cease-and-desist orders and seek civil penalties for violations',
      'Grants the FTC authority to challenge anticompetitive mergers and conduct not covered by other antitrust laws',
      'Enables rulemaking to define and prohibit categories of unfair or deceptive practices',
      'No private right of action — enforcement is exclusively through the FTC',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/41',
    relatedLitigation: ['antitrust'],
  },
  {
    name: 'Hart-Scott-Rodino Antitrust Improvements Act',
    shortName: 'HSR Act',
    citation: '15 U.S.C. § 18a',
    category: 'Antitrust',
    jurisdiction: 'Federal Statute',
    enactedYear: 1976,
    summary:
      'The Hart-Scott-Rodino Act of 1976 amended the Clayton Act to require parties to large mergers and acquisitions to notify the FTC and Department of Justice Antitrust Division before completing a transaction and to observe a mandatory waiting period. This pre-merger notification regime allows antitrust authorities to review proposed deals for competitive concerns before they are consummated, making it far easier to challenge anticompetitive mergers. The HSR thresholds are adjusted annually and capture both the size of the transaction and the size of the parties. Parties may not close their transaction during the waiting period, which is typically 30 days, unless they receive early termination of the waiting period or a request for additional information (a "Second Request") is issued.',
    keyProvisions: [
      'Requires pre-merger notification filings with the FTC and DOJ for transactions meeting size-of-transaction and size-of-person thresholds',
      'Imposes a mandatory waiting period (typically 30 days) during which parties cannot close the transaction',
      'Allows agencies to issue a Second Request for additional information, extending the waiting period',
      'Authorizes courts to impose civil penalties (over $50,000 per day) for failure to comply with HSR requirements',
      'Thresholds are adjusted annually based on changes in gross national product',
      'Exemptions exist for certain transactions, including acquisitions of foreign assets with limited U.S. nexus',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/18a',
    relatedLitigation: ['antitrust'],
  },
  {
    name: 'Bankruptcy Code (Title 11 U.S.C.) — Overview',
    shortName: 'Bankruptcy Code',
    citation: '11 U.S.C. § 101 et seq.',
    category: 'Bankruptcy',
    jurisdiction: 'Federal Statute',
    enactedYear: 1978,
    summary:
      'Title 11 of the United States Code, commonly called the Bankruptcy Code, provides the federal legal framework for bankruptcy proceedings and was enacted in 1978 to replace the Bankruptcy Act of 1898. It grants individuals and businesses a fresh start by discharging or restructuring debt under court supervision, while providing an orderly mechanism for distributing assets to creditors. The Code is organized into chapters, with specific chapters applying to different types of debtors: Chapter 7 for liquidation, Chapter 11 for business reorganization, Chapter 12 for family farmers and fishermen, and Chapter 13 for individual wage earners. The automatic stay is one of the most powerful features of bankruptcy, immediately halting most collection actions against the debtor upon filing. Federal bankruptcy courts have exclusive jurisdiction over bankruptcy cases.',
    keyProvisions: [
      'The automatic stay (Section 362) immediately halts most collection actions, lawsuits, and foreclosures upon filing',
      'Creates the bankruptcy estate, comprising all of the debtor\'s legal and equitable interests in property',
      'Establishes priority rules for distributing assets to creditors in a specified order',
      'Authorizes the discharge of eligible debts, relieving the debtor of personal liability',
      'Permits the trustee or debtor-in-possession to avoid fraudulent transfers and preferential payments',
      'Governs the treatment of executory contracts and unexpired leases',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/11',
    relatedLitigation: ['bankruptcy'],
  },
  {
    name: 'Bankruptcy Code — Chapter 7: Liquidation',
    shortName: 'Chapter 7',
    citation: '11 U.S.C. §§ 701-784',
    category: 'Bankruptcy',
    jurisdiction: 'Federal Statute',
    enactedYear: 1978,
    summary:
      'Chapter 7 bankruptcy is the most common form of bankruptcy, providing for the liquidation of a debtor\'s non-exempt assets by a court-appointed trustee, with the proceeds distributed to creditors in priority order. Individuals who qualify (based on the means test) receive a discharge of most unsecured debts within a few months of filing, offering a relatively quick fresh start. Secured creditors retain their liens and may proceed against collateral. Certain debts, such as student loans, recent taxes, and domestic support obligations, are generally non-dischargeable. Businesses can also file Chapter 7 to wind down operations, but they do not receive a discharge — the corporate entity simply ceases to exist after liquidation.',
    keyProvisions: [
      'A trustee is appointed to collect and liquidate the debtor\'s non-exempt assets for distribution to creditors',
      'Individuals must pass the means test to qualify for Chapter 7 relief',
      'Most unsecured debts (credit cards, medical bills) are discharged within 3-6 months of filing',
      'Certain debts — student loans, domestic support, recent taxes, fraud judgments — are non-dischargeable',
      'Debtors may exempt certain property (e.g., home equity, car, retirement accounts) from liquidation',
      'Corporations use Chapter 7 for orderly wind-down but receive no discharge',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/11/chapter-7',
    relatedLitigation: ['bankruptcy'],
  },
  {
    name: 'Bankruptcy Code — Chapter 11: Reorganization',
    shortName: 'Chapter 11',
    citation: '11 U.S.C. §§ 1101-1195',
    category: 'Bankruptcy',
    jurisdiction: 'Federal Statute',
    enactedYear: 1978,
    summary:
      'Chapter 11 allows businesses (and some individuals) to reorganize their debts and operations under court supervision while continuing to operate as a going concern. The debtor typically remains in possession of its assets and operates as a "debtor-in-possession," with the powers of a trustee. The debtor proposes a plan of reorganization that must be confirmed by the court, addressing how creditors will be paid and how the business will be restructured. Creditors vote on the plan and are grouped into classes based on the nature of their claims. The Small Business Reorganization Act of 2019 created Subchapter V, a streamlined Chapter 11 process for small businesses. Chapter 11 has been used by many large corporations, including airlines, retailers, and automakers, to restructure and emerge as viable businesses.',
    keyProvisions: [
      'Debtor typically operates as debtor-in-possession with the powers of a trustee',
      'Debtor has an exclusive period (initially 120 days) to propose a plan of reorganization',
      'The plan must be confirmed by the court after creditor voting and satisfaction of statutory requirements',
      'Cramdown allows plan confirmation over a dissenting class if the plan is fair and equitable',
      'Debtor-in-possession financing (DIP financing) allows the debtor to obtain new credit with court approval',
      'Subchapter V provides a simplified, faster Chapter 11 process for small businesses',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/11/chapter-11',
    relatedLitigation: ['bankruptcy'],
  },
  {
    name: 'Uniform Commercial Code — Overview and Article 2 (Sales)',
    shortName: 'UCC',
    citation: 'UCC Arts. 1-9 (as enacted by individual states)',
    category: 'Commercial',
    jurisdiction: 'State/Uniform',
    enactedYear: 1952,
    summary:
      'The Uniform Commercial Code is a comprehensive set of model statutes governing commercial transactions in the United States, developed jointly by the American Law Institute and the Uniform Law Commission. It has been adopted (with some variations) by all 50 states and the District of Columbia, making commercial law relatively uniform across the country. Article 2 governs the sale of goods and is one of the most frequently litigated parts of the UCC, covering contract formation, warranties, risk of loss, and remedies for breach. Other key articles cover negotiable instruments (Article 3), bank deposits and collections (Article 4), letters of credit (Article 5), and secured transactions (Article 9). The UCC aims to modernize and harmonize commercial law to facilitate interstate commerce.',
    keyProvisions: [
      'Article 1 sets out general definitions and principles applicable to all UCC articles',
      'Article 2 governs contracts for the sale of goods, including formation rules, implied warranties, and breach remedies',
      'Article 2 implied warranty of merchantability requires goods to be fit for ordinary purposes',
      'Article 3 governs negotiable instruments such as checks and promissory notes',
      'Article 9 governs secured transactions in personal property, including attachment and perfection of security interests',
      'UCC gap-fillers supply missing contract terms (price, delivery, payment) when parties have not agreed',
    ],
    officialUrl: 'https://www.law.cornell.edu/ucc',
    relatedLitigation: ['commercial'],
  },
  {
    name: 'National Bank Act',
    shortName: 'NBA',
    citation: '12 U.S.C. § 1 et seq.',
    category: 'Banking & Finance',
    jurisdiction: 'Federal Statute',
    enactedYear: 1864,
    summary:
      'The National Bank Act of 1864 created the federal system of nationally chartered banks and established the Office of the Comptroller of the Currency (OCC) to charter and supervise them. It allowed banks chartered under federal law (national banks) to operate across state lines and preempted state banking laws that would interfere with national banks\' federally authorized powers. The preemption doctrine under the NBA has been a significant source of litigation, particularly regarding whether state consumer protection and usury laws apply to national banks. National banks can generally export the interest rates of their home state to borrowers in other states, a principle established in Marquette National Bank v. First of Omaha Service Corp. The NBA remains the foundational charter for large commercial banks in the United States.',
    keyProvisions: [
      'Authorizes the OCC to charter, regulate, and supervise national banks',
      'Grants national banks broad banking powers, including accepting deposits and making loans',
      'Federal preemption: the NBA preempts state laws that significantly interfere with national bank powers',
      'National banks may export home-state interest rates to out-of-state borrowers (Marquette doctrine)',
      'Sets capital requirements and operational standards for national banks',
      'Establishes the OCC\'s visitorial powers to examine and supervise national banks exclusively',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/12/1',
    relatedLitigation: ['banking-finance'],
  },
  {
    name: 'Truth in Lending Act',
    shortName: 'TILA',
    citation: '15 U.S.C. §§ 1601-1667f',
    category: 'Banking & Finance',
    jurisdiction: 'Federal Statute',
    enactedYear: 1968,
    summary:
      'The Truth in Lending Act requires creditors to clearly disclose the terms and costs of credit to consumers, enabling them to compare credit offers and make informed financial decisions. The most important disclosures are the Annual Percentage Rate (APR) and the finance charge, which must be disclosed in a uniform manner. TILA also grants consumers the right to rescind certain credit transactions secured by their home within three business days. Regulation Z, issued by the Consumer Financial Protection Bureau, implements TILA and provides detailed rules for disclosure, advertising, and billing. Violations of TILA can result in actual damages, statutory damages, and attorney fees in private civil actions.',
    keyProvisions: [
      'Requires disclosure of the Annual Percentage Rate (APR) and total finance charge for consumer credit transactions',
      'Mandates standardized disclosure format to allow consumers to compare credit offers',
      'Grants a three-day right of rescission for certain home-secured loans (e.g., home equity lines of credit)',
      'Regulates credit card billing practices and error resolution procedures',
      'Prohibits misleading credit advertising and requires clear disclosure of key terms in ads',
      'Provides civil liability for creditors who fail to make required disclosures, including statutory damages',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/1601',
    relatedLitigation: ['banking-finance'],
  },
  {
    name: 'Gramm-Leach-Bliley Act',
    shortName: 'GLBA',
    citation: 'Pub. L. 106-102, 15 U.S.C. §§ 6801-6827',
    category: 'Banking & Finance',
    jurisdiction: 'Federal Statute',
    enactedYear: 1999,
    summary:
      'The Gramm-Leach-Bliley Act repealed key provisions of the Glass-Steagall Act of 1933, allowing commercial banks, investment banks, and insurance companies to affiliate under a financial holding company structure. In addition to this structural deregulation, GLBA imposed important privacy and data security requirements on financial institutions. The Financial Privacy Rule requires financial institutions to provide customers with privacy notices explaining what information is collected and how it is shared, and allows customers to opt out of certain information sharing. The Safeguards Rule requires financial institutions to develop and maintain a comprehensive information security program. GLBA significantly reshaped the structure of the U.S. financial services industry and remains the primary federal financial privacy law.',
    keyProvisions: [
      'Repealed Glass-Steagall restrictions, allowing affiliations among commercial banks, securities firms, and insurers',
      'Created the financial holding company (FHC) structure under Federal Reserve oversight',
      'The Financial Privacy Rule requires annual privacy notices to customers and opt-out rights for certain data sharing',
      'The Safeguards Rule requires financial institutions to implement a written information security program',
      'Prohibits pretexting — fraudulently obtaining customer financial information',
      'Subjects financial holding companies to consolidated supervision by the Federal Reserve',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/6801',
    relatedLitigation: ['banking-finance'],
  },
  {
    name: 'Investment Company Act of 1940',
    shortName: 'ICA',
    citation: '15 U.S.C. §§ 80a-1 et seq.',
    category: 'Securities',
    jurisdiction: 'Federal Statute',
    enactedYear: 1940,
    summary:
      'The Investment Company Act of 1940 regulates the organization and activities of investment companies — entities that pool investor funds and invest in securities — including mutual funds, closed-end funds, and exchange-traded funds (ETFs). It requires investment companies that meet certain thresholds to register with the SEC and comply with extensive requirements on governance, disclosure, pricing, and conflicts of interest. The Act mandates independent boards of directors, limits on leverage, and daily pricing of mutual fund shares at net asset value (NAV). Private funds such as hedge funds and private equity funds typically rely on exemptions from registration under the Act, most commonly the Section 3(c)(1) or 3(c)(7) exemptions. The Act works in conjunction with the Investment Advisers Act of 1940 to comprehensively regulate the investment management industry.',
    keyProvisions: [
      'Requires investment companies to register with the SEC and comply with ongoing disclosure and governance requirements',
      'Mandates independent boards of directors for registered investment companies',
      'Requires daily pricing (net asset value) and requires redemption at NAV for open-end funds (mutual funds)',
      'Restricts affiliated transactions, leverage, and conflicts of interest',
      'Exempts private funds (hedge funds, PE funds) from registration under Section 3(c)(1) or 3(c)(7)',
      'Requires custody of fund assets with qualified custodians to protect investor assets',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/80a-1',
    relatedLitigation: ['securities'],
  },
];

export default statutes;
