import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'United States Constitution',
    shortName: 'U.S. Constitution',
    citation: 'U.S. Const.',
    category: 'Constitutional & Courts',
    jurisdiction: 'Constitutional',
    enactedYear: 1788,
    summary:
      'The United States Constitution is the supreme law of the land, establishing the framework for the federal government and protecting fundamental rights. It created three separate branches of government — Congress, the President, and the federal courts — with checks and balances among them. All other laws must conform to the Constitution, and courts can strike down laws that violate it. It has been amended 27 times to expand rights and adjust governance. Understanding the Constitution is essential for any legal study because it sets the boundaries within which all other laws operate.',
    keyProvisions: [
      'Establishes three branches: legislative (Congress), executive (President), and judicial (courts)',
      'Supremacy Clause makes the Constitution the highest law, overriding conflicting state or federal laws',
      'Article III creates the federal judiciary and grants Congress power to establish lower courts',
      'Article I, Section 8 grants Congress enumerated powers, including the Commerce Clause',
      'Separation of powers with checks and balances prevents any one branch from dominating',
      'Amended 27 times, most notably by the Bill of Rights and the Reconstruction Amendments',
    ],
    officialUrl: 'https://www.law.cornell.edu/constitution',
    relatedLitigation: ['constitutional', 'civil-rights', 'court-hierarchy'],
  },
  {
    name: 'Bill of Rights',
    shortName: 'Bill of Rights',
    citation: 'U.S. Const. amends. I–X',
    category: 'Constitutional & Courts',
    jurisdiction: 'Constitutional',
    enactedYear: 1791,
    summary:
      'The Bill of Rights consists of the first ten amendments to the U.S. Constitution, ratified in 1791 to protect individual liberties against government overreach. These amendments guarantee freedoms such as speech, religion, press, and the right to bear arms, as well as due process and protection against unreasonable searches. They were added shortly after ratification of the Constitution in response to concerns that the new federal government was too powerful. Many of the rights in the Bill of Rights have been applied to state governments through the 14th Amendment\'s Due Process Clause — a process called "incorporation." They remain the foundation of civil liberties law in the United States.',
    keyProvisions: [
      'First Amendment: freedom of religion, speech, press, assembly, and petition',
      'Fourth Amendment: protection against unreasonable searches and seizures; requires warrants based on probable cause',
      'Fifth Amendment: right against self-incrimination, double jeopardy, and due process of law',
      'Sixth Amendment: right to a speedy trial, jury, and counsel in criminal cases',
      'Eighth Amendment: prohibits cruel and unusual punishment and excessive bail',
      'Tenth Amendment: powers not granted to the federal government are reserved to states or the people',
    ],
    officialUrl: 'https://www.law.cornell.edu/constitution',
    relatedLitigation: ['constitutional', 'civil-rights', 'court-hierarchy'],
  },
  {
    name: 'Fourteenth Amendment',
    shortName: '14th Amendment',
    citation: 'U.S. Const. amend. XIV',
    category: 'Constitutional & Courts',
    jurisdiction: 'Constitutional',
    enactedYear: 1868,
    summary:
      'Ratified after the Civil War in 1868, the Fourteenth Amendment is one of the most important provisions in the entire Constitution for civil rights law. It guarantees that no state may deny any person the equal protection of the laws or deprive any person of life, liberty, or property without due process of law. Courts have used the Equal Protection Clause to strike down racial segregation, sex discrimination, and other forms of government-sponsored inequality. The Due Process Clause has also been interpreted to apply most of the Bill of Rights to state governments, not just the federal government. It granted citizenship to formerly enslaved people and remains the primary constitutional basis for civil rights litigation against state actors.',
    keyProvisions: [
      'Equal Protection Clause: states cannot deny any person equal protection of the laws',
      'Due Process Clause: states cannot deprive any person of life, liberty, or property without due process',
      'Citizenship Clause: all persons born or naturalized in the U.S. are citizens',
      'Privileges or Immunities Clause: states cannot abridge the privileges or immunities of U.S. citizens',
      'Section 5: Congress has power to enforce the Amendment through appropriate legislation',
      'Used to incorporate most Bill of Rights protections against state governments',
    ],
    officialUrl: 'https://www.law.cornell.edu/constitution/amendmentxiv',
    relatedLitigation: ['constitutional', 'civil-rights', 'employment'],
  },
  {
    name: 'Civil Rights Act of 1964',
    shortName: 'Civil Rights Act',
    citation: 'Pub. L. 88-352, 78 Stat. 241; 42 U.S.C. § 2000a et seq.',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1964,
    summary:
      'The Civil Rights Act of 1964 is landmark federal legislation that outlawed discrimination based on race, color, religion, sex, or national origin in public accommodations, employment, and programs receiving federal funding. It was a major victory of the Civil Rights Movement and has shaped modern anti-discrimination law more than almost any other statute. Title II bans discrimination in hotels, restaurants, and other public places, while Title VI applies to recipients of federal financial assistance. Title VII, its most litigated section, prohibits employment discrimination and led to the creation of the Equal Employment Opportunity Commission (EEOC). The Act gave teeth to the constitutional guarantee of equality by providing enforceable federal remedies.',
    keyProvisions: [
      'Title II: bans discrimination in public accommodations such as hotels, restaurants, and theaters',
      'Title VI: prohibits discrimination by programs and activities receiving federal financial assistance',
      'Title VII: outlaws employment discrimination based on race, color, religion, sex, or national origin',
      'Created the Equal Employment Opportunity Commission (EEOC) to enforce employment provisions',
      'Covers both intentional discrimination and policies that have a disparate impact on protected classes',
      'Applies to employers with 15 or more employees, as well as employment agencies and unions',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/2000a',
    relatedLitigation: ['civil-rights', 'employment'],
  },
  {
    name: 'Voting Rights Act of 1965',
    shortName: 'VRA',
    citation: 'Pub. L. 89-110, 79 Stat. 437; 52 U.S.C. § 10301 et seq.',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1965,
    summary:
      'The Voting Rights Act of 1965 is federal legislation enacted to enforce the 15th Amendment and eliminate racial discrimination in voting. It was passed in response to systematic efforts in the South to disenfranchise Black voters through literacy tests, poll taxes, and violence. Section 2 prohibits any voting practice or procedure that discriminates based on race or color, and it applies nationwide. Section 5, now largely unenforceable after Shelby County v. Holder (2013), required certain jurisdictions with a history of discrimination to get federal pre-approval ("preclearance") before changing voting laws. The Act is considered one of the most effective pieces of civil rights legislation ever enacted.',
    keyProvisions: [
      'Section 2: prohibits any voting practice that results in denial or abridgement of the right to vote based on race',
      'Originally banned literacy tests and other devices used to disenfranchise minority voters',
      'Section 5 (formerly): required covered jurisdictions to obtain federal preclearance before changing voting laws',
      'Authorizes federal examiners and observers to oversee elections in problem areas',
      'Requires bilingual election materials in jurisdictions with large non-English-speaking populations',
      'Has been reauthorized and amended multiple times, most recently in 2006',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Voting_Rights_Act_of_1965',
    relatedLitigation: ['civil-rights', 'constitutional'],
  },
  {
    name: 'Civil Rights Act of 1866',
    shortName: 'Civil Rights Act of 1866 / § 1981',
    citation: '14 Stat. 27; 42 U.S.C. § 1981',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1866,
    summary:
      'The Civil Rights Act of 1866 was the first major civil rights law in United States history, enacted to provide formerly enslaved people with the same legal rights as white citizens. Its core provisions are now codified at 42 U.S.C. § 1981, which guarantees all persons the same right to make and enforce contracts, sue, give evidence, and enjoy the full benefit of laws as is enjoyed by white citizens. Section 1981 is particularly important in employment discrimination cases because it applies to private employers regardless of their size — unlike Title VII, which only covers employers with 15 or more workers. It also allows plaintiffs to sue directly in federal court without first going through the EEOC. Courts have held that § 1981 prohibits racial harassment and retaliation in addition to outright discrimination.',
    keyProvisions: [
      '42 U.S.C. § 1981: guarantees all persons equal right to make and enforce contracts regardless of race',
      'Applies to private conduct, not just government action',
      'No minimum employer size threshold — covers even small employers',
      'Allows direct suit in federal court without EEOC exhaustion requirement',
      'Prohibits racial harassment and retaliation in addition to discriminatory terms of employment',
      'Was the legislative precursor to the 14th Amendment\'s Equal Protection Clause',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/1981',
    relatedLitigation: ['civil-rights', 'employment', 'constitutional'],
  },
  {
    name: '42 U.S.C. § 1983 — Civil Action for Deprivation of Rights',
    shortName: 'Section 1983',
    citation: '42 U.S.C. § 1983',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1871,
    summary:
      'Section 1983, originally part of the Civil Rights Act of 1871 (also called the Ku Klux Klan Act), is the primary federal vehicle for suing government officials and entities that have violated constitutional rights. It allows any person to sue in federal court when someone acting "under color of state law" deprives them of a right guaranteed by the Constitution or federal law. Common § 1983 claims include police misconduct, unlawful arrest, prison abuse, and public school violations of students\' rights. Municipalities and local governments can also be sued under § 1983 if the constitutional violation resulted from an official policy or widespread custom (Monell liability). While government officials often raise the defense of qualified immunity, the statute remains the cornerstone of constitutional civil rights enforcement.',
    keyProvisions: [
      'Creates a federal cause of action against anyone who, under color of state law, deprives a person of constitutional rights',
      'Applies to state and local government officials, including police officers and school administrators',
      'Municipalities can be liable if the violation resulted from an official policy or custom (Monell v. Dep\'t of Social Services)',
      'Qualified immunity doctrine protects officials who did not violate "clearly established" law',
      'Plaintiffs may recover compensatory and punitive damages, as well as attorneys\' fees under 42 U.S.C. § 1988',
      'Does not apply directly to federal government officials — Bivens actions cover federal actor claims',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/1983',
    relatedLitigation: ['civil-rights', 'constitutional', 'court-hierarchy'],
  },
  {
    name: 'Americans with Disabilities Act',
    shortName: 'ADA',
    citation: 'Pub. L. 101-336, 104 Stat. 327; 42 U.S.C. § 12101 et seq.',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1990,
    summary:
      'The Americans with Disabilities Act (ADA) is a comprehensive civil rights law that prohibits discrimination against individuals with disabilities in employment, public accommodations, state and local government services, transportation, and telecommunications. It was modeled on the Civil Rights Act of 1964 and extended anti-discrimination protections to the approximately one in four Americans who live with a disability. Title I covers employment and requires employers with 15 or more employees to provide reasonable accommodations for qualified individuals with disabilities. Title II applies to state and local governments, and Title III covers private businesses open to the public (like stores, hotels, and restaurants). The ADA Amendments Act of 2008 broadened the definition of disability in response to courts that had interpreted it too narrowly.',
    keyProvisions: [
      'Title I: prohibits employment discrimination and requires reasonable accommodations for qualified employees with disabilities',
      'Title II: prohibits discrimination by state and local government entities and requires accessibility',
      'Title III: prohibits discrimination by private businesses open to the public and mandates physical accessibility',
      'Defines disability broadly as a physical or mental impairment that substantially limits a major life activity',
      'Requires interactive process between employer and employee to identify reasonable accommodations',
      'ADA Amendments Act of 2008 (ADAAA) reversed narrow Supreme Court interpretations and expanded coverage',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/12101',
    relatedLitigation: ['civil-rights', 'employment'],
  },
  {
    name: 'Fair Housing Act',
    shortName: 'FHA',
    citation: 'Pub. L. 90-284, Title VIII, 82 Stat. 81; 42 U.S.C. § 3601 et seq.',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1968,
    summary:
      'The Fair Housing Act, enacted as Title VIII of the Civil Rights Act of 1968, prohibits discrimination in the sale, rental, and financing of housing based on race, color, national origin, religion, sex, familial status, or disability. It was signed into law one week after the assassination of Dr. Martin Luther King Jr. and was intended to dismantle the system of residential segregation that had been enforced through both law and private practice. The Act covers most housing in the United States, with narrow exemptions for owner-occupied buildings with four or fewer units and single-family homes sold without a broker. Enforcement can be sought through the Department of Housing and Urban Development (HUD), state and local agencies, or private lawsuit in federal court. Courts recognize both intentional discrimination (disparate treatment) and neutral policies with discriminatory effects (disparate impact) as violations.',
    keyProvisions: [
      'Prohibits discrimination in sale, rental, and financing of housing based on seven protected characteristics',
      'Covers advertising, terms and conditions, and refusal to sell or rent',
      'Requires reasonable accommodations and modifications for persons with disabilities',
      'Disparate impact theory recognized — neutral policies with discriminatory effects can be illegal',
      'HUD and the Department of Justice can investigate and bring enforcement actions',
      'Private plaintiffs may sue for actual damages, punitive damages, and attorneys\' fees',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/3601',
    relatedLitigation: ['civil-rights', 'environmental-justice'],
  },
  {
    name: 'Religious Freedom Restoration Act',
    shortName: 'RFRA',
    citation: 'Pub. L. 103-141, 107 Stat. 1488; 42 U.S.C. § 2000bb et seq.',
    category: 'Civil Rights',
    jurisdiction: 'Federal Statute',
    enactedYear: 1993,
    summary:
      'The Religious Freedom Restoration Act (RFRA) was enacted by Congress in 1993 in response to the Supreme Court\'s decision in Employment Division v. Smith, which held that neutral, generally applicable laws do not violate the Free Exercise Clause of the First Amendment even if they burden religious practice. RFRA restored the pre-Smith "compelling interest" standard, requiring the federal government to demonstrate a compelling governmental interest and use the least restrictive means before substantially burdening a person\'s exercise of religion. Its reach was limited to federal law after the Supreme Court struck down its application to states in City of Boerne v. Flores (1997); many states have enacted their own state RFRAs. RFRA has become one of the most litigated religious liberty statutes, featuring prominently in cases involving contraceptive mandates, COVID restrictions, and other federal regulations.',
    keyProvisions: [
      'Federal government may not substantially burden a person\'s exercise of religion without a compelling governmental interest',
      'Government must use the least restrictive means of achieving that compelling interest',
      'Applies to all federal laws and regulations, including those enacted after RFRA itself',
      'Restores the Sherbert v. Verner / Wisconsin v. Yoder balancing test overruled by Employment Division v. Smith',
      'Provides a defense in federal court and allows suits for injunctive relief and attorneys\' fees',
      'Does not apply to state and local governments (see City of Boerne v. Flores), but state RFRAs may apply',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/2000bb',
    relatedLitigation: ['civil-rights', 'constitutional'],
  },
  {
    name: 'Judiciary Act of 1789',
    shortName: 'Judiciary Act of 1789',
    citation: '1 Stat. 73',
    category: 'Constitutional & Courts',
    jurisdiction: 'Federal Statute',
    enactedYear: 1789,
    summary:
      'The Judiciary Act of 1789 was the first act of Congress to establish the federal court system in the United States. Article III of the Constitution created the Supreme Court but left it to Congress to establish all lower federal courts. The Judiciary Act created the structure that still largely exists today: a Supreme Court at the top, circuit courts in the middle, and district courts at the bottom. It also created the office of Attorney General of the United States and established rules for how cases would move from state courts to federal courts. Section 25, which allowed the Supreme Court to review state court decisions involving federal law, was crucial to establishing the Court\'s supremacy and was tested in landmark cases like Martin v. Hunter\'s Lessee.',
    keyProvisions: [
      'Established the Supreme Court with one Chief Justice and five Associate Justices (later changed by Congress)',
      'Created the original circuit courts and 13 federal district courts',
      'Defined original and appellate jurisdiction of federal courts',
      'Section 25: authorized Supreme Court review of state court decisions involving federal constitutional questions',
      'Created the office of the Attorney General of the United States',
      'Laid the structural foundation for the modern three-tier federal court system',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Judiciary_Act_of_1789',
    relatedLitigation: ['court-hierarchy', 'constitutional'],
  },
  {
    name: 'Federal Question Jurisdiction Statute',
    shortName: '28 U.S.C. § 1331',
    citation: '28 U.S.C. § 1331',
    category: 'Constitutional & Courts',
    jurisdiction: 'Federal Statute',
    enactedYear: 1875,
    summary:
      'Title 28, Chapter 85 of the United States Code, and specifically § 1331, grants federal district courts original jurisdiction over all civil actions arising under the Constitution, laws, or treaties of the United States. This is called "federal question jurisdiction" and is the primary gateway for civil rights, constitutional, and statutory federal claims to enter the federal court system. Before 1875, plaintiffs generally had to show diversity of citizenship to get into federal court on a non-federal claim; the 1875 statute opened the federal courts to anyone with a federal constitutional or statutory claim. Federal question jurisdiction is critical because federal courts are generally considered more receptive to federal rights claims and can provide nationwide precedent. Together with § 1332 (diversity jurisdiction) and § 1367 (supplemental jurisdiction), § 1331 defines the contours of federal court access.',
    keyProvisions: [
      '28 U.S.C. § 1331: federal district courts have original jurisdiction over cases "arising under" the Constitution or federal law',
      'No minimum amount in controversy is required (unlike diversity jurisdiction under § 1332)',
      'The federal claim must appear on the face of the plaintiff\'s well-pleaded complaint',
      'Enables civil rights plaintiffs to bring § 1983, Title VII, ADA, and other federal claims in federal court',
      'Supplemental jurisdiction (§ 1367) allows related state law claims to be heard in the same federal case',
      'Removal jurisdiction (§ 1441) allows defendants to move qualifying state court cases to federal court',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/28/1331',
    relatedLitigation: ['court-hierarchy', 'constitutional', 'civil-rights'],
  },
  {
    name: 'Declaratory Judgment Act',
    shortName: 'DJA',
    citation: '28 U.S.C. § 2201',
    category: 'Constitutional & Courts',
    jurisdiction: 'Federal Statute',
    enactedYear: 1934,
    summary:
      'The Declaratory Judgment Act authorizes federal courts to declare the rights and legal relations of any interested party in a case of actual controversy, even before a wrong has actually been committed. Before this Act, a party who feared their conduct might be unlawful had to either act and risk a lawsuit, or remain inactive and suffer the consequence. A declaratory judgment allows a court to resolve legal uncertainty without requiring one party to first violate the law and be sued. For example, a plaintiff can ask a court to declare a statute unconstitutional before it is enforced against them. Federal courts still require an actual "case or controversy" under Article III, so purely hypothetical disputes are not allowed. Declaratory relief is widely used in civil rights, intellectual property, and contract cases.',
    keyProvisions: [
      '28 U.S.C. § 2201: federal courts may declare the rights of any party in a case of actual controversy',
      'Permits prospective legal clarity without requiring a party to first violate the law',
      'Must still satisfy Article III\'s "case or controversy" requirement — purely hypothetical disputes are barred',
      'Declaratory relief is discretionary — courts may decline to issue a declaration even when jurisdiction exists',
      'Often paired with injunctive relief to both declare rights and prevent future violations',
      'Widely used to challenge the constitutionality of statutes or regulations before enforcement',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/28/2201',
    relatedLitigation: ['constitutional', 'civil-rights', 'court-hierarchy'],
  },
];

export default statutes;
