import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'Federal Mail Fraud Statute',
    shortName: 'Mail Fraud',
    citation: '18 U.S.C. § 1341',
    category: 'White Collar Crime',
    jurisdiction: 'Federal Statute',
    enactedYear: 1872,
    summary:
      'The mail fraud statute makes it a federal crime to use the U.S. Postal Service or any private interstate mail carrier as part of a scheme to defraud. It is one of the broadest and most frequently charged federal criminal statutes, reaching virtually any dishonest scheme that touches the mails. Prosecutors do not need to prove the defendant personally mailed anything—only that mailing was foreseeable as part of the scheme. Convictions carry up to 20 years imprisonment per count, and up to 30 years if a financial institution is the victim. Courts have interpreted "scheme to defraud" expansively to include deprivation of honest services under 18 U.S.C. § 1346.',
    keyProvisions: [
      'Prohibits any scheme or artifice to defraud using the mails or private interstate carriers',
      'Requires proof of: (1) a scheme to defraud, (2) use of the mails, and (3) intent to defraud',
      'Each individual mailing can constitute a separate count',
      'Penalty: up to 20 years per count (30 years if victim is a financial institution)',
      'Predicate offense for RICO charges under 18 U.S.C. § 1961',
      'Extends to deprivation of intangible rights, including honest services (§ 1346)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/1341',
    relatedLitigation: ['white-collar-crime', 'criminal-defense'],
  },
  {
    name: 'Federal Wire Fraud Statute',
    shortName: 'Wire Fraud',
    citation: '18 U.S.C. § 1343',
    category: 'White Collar Crime',
    jurisdiction: 'Federal Statute',
    enactedYear: 1952,
    summary:
      'Wire fraud mirrors the mail fraud statute but applies to schemes carried out through electronic communications—including telephone calls, emails, faxes, text messages, and internet transmissions. Because nearly every modern financial transaction involves electronic communications, wire fraud is an exceptionally powerful prosecutorial tool. A single fraudulent email or phone call can support a separate count. Like mail fraud, wire fraud is a predicate act for RICO, and is frequently charged alongside money laundering, securities fraud, and bank fraud.',
    keyProvisions: [
      'Prohibits schemes to defraud using interstate wire, radio, or television communications',
      'Requires the same three elements as mail fraud: scheme, use of wires, and intent',
      'Covers emails, wire transfers, phone calls, and internet-based communications',
      'Penalty: up to 20 years per count (30 years if victim is a financial institution or during a federal disaster declaration)',
      'Predicate offense for RICO and money laundering statutes',
      'Often charged together with bank fraud (18 U.S.C. § 1344) and securities fraud',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/1343',
    relatedLitigation: ['white-collar-crime', 'criminal-defense'],
  },
  {
    name: 'Racketeer Influenced and Corrupt Organizations Act',
    shortName: 'RICO',
    citation: '18 U.S.C. §§ 1961–1968',
    category: 'White Collar Crime',
    jurisdiction: 'Federal Statute',
    enactedYear: 1970,
    summary:
      'RICO was enacted to combat organized crime but has evolved into a broadly used statute covering any "enterprise" engaged in a "pattern of racketeering activity." A RICO claim requires proof of an enterprise, a pattern of at least two predicate acts within ten years, and a nexus between the defendant, the enterprise, and the racketeering. Criminal RICO carries up to 20 years per count, asset forfeiture, and mandatory restitution. Civil RICO allows private plaintiffs to sue for treble damages and attorney fees, making it attractive in complex commercial litigation well beyond traditional organized crime.',
    keyProvisions: [
      'Defines "racketeering activity" to include over 35 predicate offenses (mail/wire fraud, bribery, extortion, drug trafficking, etc.)',
      'Requires a "pattern" of at least two related predicate acts within 10 years',
      'Criminal penalties: up to 20 years per count plus mandatory forfeiture of proceeds',
      'Civil RICO (§ 1964(c)): private plaintiffs may recover treble damages and attorney fees',
      'Conspiracy liability under § 1962(d) extends to those who agree to participate even without committing predicate acts',
      'Courts apply the "continuity plus relationship" test to determine whether acts constitute a pattern',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/1961',
    relatedLitigation: ['white-collar-crime', 'criminal-defense'],
  },
  {
    name: 'Foreign Corrupt Practices Act',
    shortName: 'FCPA',
    citation: '15 U.S.C. §§ 78dd-1 to 78dd-3; 78ff',
    category: 'White Collar Crime',
    jurisdiction: 'Federal Statute',
    enactedYear: 1977,
    summary:
      'The FCPA prohibits U.S. persons, companies, and certain foreign nationals from bribing foreign government officials to obtain or retain business. It also imposes accounting and internal-controls requirements on companies with securities registered in the United States. The DOJ enforces the anti-bribery provisions criminally; the SEC enforces both anti-bribery and accounting provisions civilly. The FCPA applies extraterritorially: a foreign company listed on a U.S. exchange, or one that takes any act in furtherance of a bribe within the U.S., can be prosecuted. Penalties include heavy fines, disgorgement of profits, deferred prosecution agreements, and incarceration.',
    keyProvisions: [
      'Anti-bribery provisions prohibit payments to foreign officials to obtain or retain business',
      'Books-and-records provisions require accurate accounting and adequate internal controls for issuers',
      'Covers U.S. issuers, domestic concerns, and foreign persons/entities acting within the U.S.',
      'Affirmative defense for payments that are lawful under written local law or constitute reasonable, bona fide promotional expenses',
      'Criminal penalties: up to $2 million per violation for entities; up to $250,000 and 5 years imprisonment for individuals',
      'SEC may seek disgorgement and civil penalties in addition to criminal DOJ prosecution',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/78dd-1',
    relatedLitigation: ['white-collar-crime', 'international-trade'],
  },
  {
    name: 'Controlled Substances Act',
    shortName: 'CSA',
    citation: '21 U.S.C. §§ 801–971',
    category: 'Criminal',
    jurisdiction: 'Federal Statute',
    enactedYear: 1970,
    summary:
      'The Controlled Substances Act is the cornerstone of federal drug policy, classifying regulated substances into five schedules based on medical use, abuse potential, and safety. Schedule I substances (e.g., heroin, LSD, and currently marijuana under federal law) are deemed to have no accepted medical use. Penalties for trafficking vary dramatically by schedule, quantity, and prior criminal history, with mandatory minimum sentences for many offenses. The CSA also governs lawful manufacturing, distribution, and dispensing by registrants such as pharmacies and physicians. Federal prosecution can proceed even when a defendant\'s conduct is lawful under state law.',
    keyProvisions: [
      'Establishes five schedules (I–V) classifying substances by abuse potential and medical utility',
      'Prohibits unauthorized manufacture, distribution, dispensing, or possession with intent to distribute',
      'Mandatory minimum sentences apply to trafficking in specified quantities (e.g., 10 years for 1 kg+ heroin)',
      'Continuing criminal enterprise (CCE) provision (§ 848) targets drug kingpins with enhanced penalties',
      'Allows civil forfeiture of property used in or derived from drug offenses',
      'Regulates legitimate pharmaceutical supply chain through DEA registration requirements',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/21/801',
    relatedLitigation: ['criminal-defense'],
  },
  {
    name: 'Immigration and Nationality Act',
    shortName: 'INA',
    citation: '8 U.S.C. §§ 1101 et seq.',
    category: 'Immigration',
    jurisdiction: 'Federal Statute',
    enactedYear: 1952,
    summary:
      'The INA is the primary federal statute governing immigration to and naturalization in the United States, consolidating and replacing earlier immigration laws. It establishes the categories of immigrants and nonimmigrants, the grounds of inadmissibility and deportability, and the procedures for removal. The INA also governs asylum, refugee admission, employment-based and family-based immigrant visas, and the naturalization process. Major amendments include the Immigration Act of 1990 (diversity visas, employment preferences) and the Illegal Immigration Reform and Immigrant Responsibility Act of 1996 (IIRIRA), which overhauled removal procedures and expanded grounds of deportability.',
    keyProvisions: [
      'Defines immigrant and nonimmigrant visa categories (e.g., H-1B, L-1, F-1, EB-1 through EB-5)',
      'Establishes grounds of inadmissibility (§ 1182) and deportability (§ 1227)',
      'Provides procedures for asylum (§ 1158) and withholding of removal (§ 1231(b)(3))',
      'Governs removal (deportation) hearings before immigration judges with appeal to the BIA',
      'Sets numerical caps on immigrant visas by preference category and country of birth',
      'Criminalizes unlawful entry (8 U.S.C. § 1325) and reentry after removal (8 U.S.C. § 1326)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/8/1101',
    relatedLitigation: ['immigration'],
  },
  {
    name: 'Federal Arbitration Act',
    shortName: 'FAA',
    citation: '9 U.S.C. §§ 1–16',
    category: 'Arbitration',
    jurisdiction: 'Federal Statute',
    enactedYear: 1925,
    summary:
      'The FAA declares arbitration agreements in contracts involving interstate commerce or maritime transactions to be valid, irrevocable, and enforceable, placing them on equal footing with other contracts. It reversed the common-law hostility to arbitration and established a strong federal policy favoring arbitration. Courts must compel arbitration on a showing that a valid arbitration agreement exists and that the dispute falls within its scope. The FAA also provides procedures to stay litigation pending arbitration, confirm arbitration awards, and vacate awards only on very narrow grounds (corruption, fraud, evident partiality, or excess of powers). The Supreme Court has broadly preempted state laws that single out arbitration agreements for disfavored treatment.',
    keyProvisions: [
      'Section 2: arbitration agreements in interstate commerce contracts are valid and enforceable',
      'Section 3: courts must stay litigation when the dispute is subject to arbitration',
      'Section 4: courts must compel arbitration on petition of a party to a valid agreement',
      'Section 9: courts confirm arbitration awards unless grounds for vacatur exist',
      'Section 10: narrow grounds for vacating awards (fraud, corruption, evident partiality, arbitrator exceeded powers)',
      'FAA preempts state laws that discriminate against or specifically disfavor arbitration agreements',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/9/1',
    relatedLitigation: ['international-arbitration', 'class-action'],
  },
  {
    name: 'Convention on the Recognition and Enforcement of Foreign Arbitral Awards',
    shortName: 'New York Convention',
    citation: '9 U.S.C. §§ 201–208 (U.S. implementing legislation); 21 U.S.T. 2517',
    category: 'Arbitration',
    jurisdiction: 'International',
    enactedYear: 1958,
    summary:
      'The New York Convention is the foundational international treaty governing recognition and enforcement of foreign arbitral awards, with over 170 signatory states. It requires contracting states to recognize arbitration agreements and to enforce foreign awards as if they were domestic judgments, subject only to narrow defenses. The U.S. implemented the Convention through Chapter 2 of the FAA (9 U.S.C. §§ 201–208). Grounds to refuse enforcement are exhaustive and include lack of valid agreement, improper notice, award beyond submission, composition of tribunal not per agreement, and violation of public policy. The Convention is the backbone of international commercial arbitration and allows parties to enforce awards across borders with minimal judicial interference.',
    keyProvisions: [
      'Requires signatory states to recognize and enforce written arbitration agreements in international disputes',
      'Mandates enforcement of foreign arbitral awards subject only to the seven enumerated grounds for refusal in Article V',
      'Article V defenses include: invalid agreement, improper notice, award beyond scope, improper tribunal composition, non-binding award, and public policy',
      'U.S. courts have subject-matter jurisdiction over New York Convention claims under 9 U.S.C. § 203',
      'Applies to awards made in the territory of a state other than the state where recognition is sought',
      'Interpreted narrowly by U.S. courts: refusal to enforce is the exception, not the rule',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Convention_on_the_Recognition_and_Enforcement_of_Foreign_Arbitral_Awards',
    relatedLitigation: ['international-arbitration', 'international-trade'],
  },
  {
    name: 'Tariff Act of 1930',
    shortName: 'Smoot-Hawley Tariff Act',
    citation: '19 U.S.C. §§ 1202 et seq.',
    category: 'International Trade',
    jurisdiction: 'Federal Statute',
    enactedYear: 1930,
    summary:
      'The Tariff Act of 1930 is the principal U.S. customs statute, establishing the legal framework for import duties, customs enforcement, and trade remedy proceedings. It contains the Harmonized Tariff Schedule of the United States (HTSUS), which classifies every imported good and assigns applicable duty rates. Title VII of the Act (as amended) provides the antidumping and countervailing duty (CVD) laws, authorizing the Department of Commerce and the International Trade Commission to impose duties on unfairly priced or subsidized foreign goods. Section 337 of the Act empowers the International Trade Commission to investigate and exclude imports that infringe U.S. intellectual property rights. The Act also governs customs fraud, seizures, and penalties administered by U.S. Customs and Border Protection.',
    keyProvisions: [
      'Establishes the Harmonized Tariff Schedule classifying all imported goods for duty purposes',
      'Title VII: antidumping duty provisions allow DOC to find dumping and ITC to find injury',
      'Title VII: countervailing duty provisions address foreign government subsidies to exporters',
      'Section 337: ITC may issue exclusion orders barring imports that infringe U.S. IP rights',
      'Customs fraud provisions (19 U.S.C. § 1592) impose penalties for material false statements in import entries',
      'Customs bonds, seizures, and forfeiture provisions for smuggled or prohibited goods',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/19/1202',
    relatedLitigation: ['international-trade'],
  },
  {
    name: 'Trade Act of 1974',
    citation: '19 U.S.C. §§ 2101 et seq.',
    category: 'International Trade',
    jurisdiction: 'Federal Statute',
    enactedYear: 1974,
    summary:
      'The Trade Act of 1974 modernized U.S. trade law by granting the President broad negotiating authority for reciprocal trade agreements and establishing key remedies against unfair foreign trade practices. Section 201 (safeguard/escape clause) allows the President to impose temporary tariffs or quotas when imports seriously injure a domestic industry. Section 301 (commonly called "Super 301" in later amendments) empowers the U.S. Trade Representative to investigate and retaliate against foreign countries engaging in unfair or discriminatory trade practices that burden U.S. commerce. The Act also created Trade Adjustment Assistance (TAA) programs to help workers and firms displaced by import competition. Trade Promotion Authority (fast-track authority) traces its origins to this statute.',
    keyProvisions: [
      'Section 201: escape clause authorizes temporary import relief when domestic industry is seriously injured',
      'Section 301: USTR may investigate and retaliate against unfair foreign trade practices, including IP theft',
      'Section 203: Presidential action on ITC injury findings (tariffs, quotas, trade adjustment)',
      'Trade Adjustment Assistance (TAA): worker and firm assistance programs for import-displaced employees',
      'Grants the President Trade Promotion Authority (fast-track) for negotiating reciprocal trade agreements',
      'Foundation for U.S. negotiations that led to GATT Tokyo Round and later WTO agreements',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/19/2101',
    relatedLitigation: ['international-trade'],
  },
  {
    name: 'Federal Tort Claims Act',
    shortName: 'FTCA',
    citation: '28 U.S.C. §§ 1346(b), 2671–2680',
    category: 'Torts',
    jurisdiction: 'Federal Statute',
    enactedYear: 1946,
    summary:
      'The FTCA waives the federal government\'s sovereign immunity from tort suits and allows private individuals to recover damages for injuries caused by negligent or wrongful acts of federal employees acting within the scope of their employment. Before filing suit, claimants must first present their claim administratively to the relevant federal agency, which has six months to accept or deny the claim. The FTCA imposes several important limitations: it does not apply to intentional torts committed by most federal employees (with exceptions for law enforcement), discretionary functions are immune from suit, and foreign claims are excluded. Damages are determined without a jury; the United States substitutes for the individual federal employee as defendant.',
    keyProvisions: [
      'Waives federal sovereign immunity for money-damages claims arising from negligence of federal employees acting within scope of employment',
      'Requires administrative exhaustion: claimant must file a Form SF-95 with the agency before suit',
      'Discretionary function exception (§ 2680(a)): no liability for acts involving judgment or choice at the policy level',
      'Intentional tort exception: most intentional torts (assault, battery, false arrest, etc.) are excluded, except for federal law enforcement officers',
      'Foreign country exception: no FTCA liability for acts occurring in a foreign country',
      'Damages are determined by the court sitting without a jury; attorney fees are capped at 25% of judgment',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/28/2671',
    relatedLitigation: ['tort', 'mass-tort', 'government-contracts'],
  },
  {
    name: 'Federal Rules of Civil Procedure',
    shortName: 'FRCP',
    citation: 'Fed. R. Civ. P. 1–86',
    category: 'Civil Procedure',
    jurisdiction: 'Federal Rule',
    enactedYear: 1938,
    summary:
      'The Federal Rules of Civil Procedure govern the process of litigating civil cases in U.S. federal district courts, from commencement of suit through judgment and appeal. Promulgated by the Supreme Court under the Rules Enabling Act, they aim to secure the "just, speedy, and inexpensive determination of every action." Rule 8 requires only a short and plain statement of the claim (notice pleading), though Rule 12(b)(6) motions test whether the complaint plausibly states a claim. Discovery is governed by Rules 26–37, including mandatory initial disclosures, depositions, interrogatories, and document requests. Rule 23 governs class actions and requires certification based on numerosity, commonality, typicality, and adequacy, plus a showing that the case fits one of three class types (damages, injunctive, or hybrid).',
    keyProvisions: [
      'Rule 8: short and plain statement of the claim; plausibility pleading standard per Twombly/Iqbal',
      'Rule 12: pre-answer motions, including 12(b)(6) failure to state a claim',
      'Rules 26–37: broad discovery framework including mandatory initial disclosures and e-discovery',
      'Rule 23: class action certification requirements (numerosity, commonality, typicality, adequacy) and class types (23(b)(1), (b)(2), (b)(3))',
      'Rule 56: summary judgment standard—no genuine dispute of material fact, movant entitled to judgment as a matter of law',
      'Rule 65: standards for temporary restraining orders and preliminary injunctions',
    ],
    officialUrl: 'https://www.law.cornell.edu/rules/frcp',
    relatedLitigation: ['class-action', 'mass-tort', 'tort', 'government-contracts', 'construction'],
  },
  {
    name: 'Federal Rules of Evidence',
    shortName: 'FRE',
    citation: 'Fed. R. Evid. 101–1103',
    category: 'Evidence',
    jurisdiction: 'Federal Rule',
    enactedYear: 1975,
    summary:
      'The Federal Rules of Evidence govern what evidence may be admitted in federal court proceedings, balancing probative value against prejudice, confusion, and waste of time. Rule 401 defines relevance broadly; Rule 403 gives courts discretion to exclude relevant evidence if its probative value is substantially outweighed by the danger of unfair prejudice. The hearsay rule (Rule 802) excludes out-of-court statements offered for the truth of the matter asserted, subject to numerous exceptions in Rules 803, 804, and 807. Expert testimony is governed by Rule 702 (the Daubert standard), requiring that expert opinions rest on sufficient facts, reliable methodology, and a reliable application of that methodology to the facts. Privilege rules are governed by common law as developed by federal courts.',
    keyProvisions: [
      'Rule 401–403: relevance threshold and court\'s power to exclude unduly prejudicial evidence',
      'Rule 404: character evidence generally inadmissible to prove conduct; Rule 404(b) allows prior bad acts for limited purposes',
      'Rule 702: expert testimony must be based on sufficient facts, reliable methods, and reliable application (Daubert standard)',
      'Rules 801–807: definition of hearsay and its many exceptions (present sense impression, excited utterance, business records, etc.)',
      'Rules 901–902: authentication requirements and self-authenticating documents',
      'Rules 501–502: federal common law privileges; Rule 502 limits subject-matter waiver of attorney-client privilege',
    ],
    officialUrl: 'https://www.law.cornell.edu/rules/fre',
    relatedLitigation: ['criminal-defense', 'white-collar-crime', 'class-action', 'tort'],
  },
  {
    name: 'Class Action Fairness Act',
    shortName: 'CAFA',
    citation: '28 U.S.C. §§ 1332(d), 1453, 1711–1715',
    category: 'Civil Procedure',
    jurisdiction: 'Federal Statute',
    enactedYear: 2005,
    summary:
      'CAFA dramatically expanded federal court jurisdiction over class actions and mass actions by lowering the threshold for removal to federal court. It grants federal district courts original (and removal) jurisdiction over class actions in which any class member is diverse from any defendant, the proposed class has at least 100 members, and the aggregate amount in controversy exceeds $5 million. The statute was designed to address concerns that plaintiffs were filing large, multi-state class actions in plaintiff-friendly state courts to avoid federal procedural requirements. CAFA also regulates class action settlements, requiring notice to appropriate federal and state officials and prohibiting coupon settlements that benefit only attorneys. Several exceptions apply for certain local or consumer-protection cases.',
    keyProvisions: [
      'Grants federal jurisdiction over class actions with 100+ members, $5M+ aggregate controversy, and minimal diversity',
      'Allows any defendant to remove a qualifying class action to federal court without consent of all defendants',
      'Home-state and local controversy exceptions can remand cases with predominantly local class members',
      'Requires class counsel to provide notice of proposed settlements to federal and state attorneys general (§ 1715)',
      'Restricts coupon settlements: attorney fees must be based on value of coupons actually redeemed',
      'Applies to "mass actions" (100+ plaintiffs with $5M+ aggregate claims proposed to be tried jointly)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/28/1332',
    relatedLitigation: ['class-action', 'mass-tort'],
  },
  {
    name: 'Miller Act',
    citation: '40 U.S.C. §§ 3131–3134',
    category: 'Construction',
    jurisdiction: 'Federal Statute',
    enactedYear: 1935,
    summary:
      'The Miller Act requires that contractors on federal construction contracts exceeding $150,000 provide two types of surety bonds: a performance bond protecting the government against contractor default, and a payment bond protecting subcontractors and suppliers who cannot file mechanic\'s liens against federal property. Because federal property is immune from mechanic\'s liens, the payment bond is the primary remedy for unpaid subcontractors and material suppliers on federal projects. Claimants must give timely written notice to the prime contractor and file suit within one year. The Miller Act creates a federal cause of action, and suits are filed in the federal district court where the contract was performed.',
    keyProvisions: [
      'Requires performance and payment bonds on federal construction contracts over $150,000',
      'Performance bond protects the government if the prime contractor fails to complete the work',
      'Payment bond protects first- and second-tier subcontractors and suppliers for labor and materials',
      'First-tier claimants need not give notice; second-tier claimants must give written notice within 90 days of last furnishing',
      'Suit on the payment bond must be filed within one year of last furnishing labor or materials',
      'Federal district court (where contract performed) has exclusive jurisdiction over Miller Act claims',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/40/3131',
    relatedLitigation: ['construction', 'government-contracts'],
  },
  {
    name: 'Contract Disputes Act',
    shortName: 'CDA',
    citation: '41 U.S.C. §§ 7101–7109',
    category: 'Government Contracts',
    jurisdiction: 'Federal Statute',
    enactedYear: 1978,
    summary:
      'The Contract Disputes Act establishes the mandatory administrative and judicial process for resolving disputes arising from contracts with federal executive agencies. Before seeking judicial relief, a contractor must submit a written claim to the contracting officer, who must issue a final decision within 60 days (for claims ≤ $100,000) or within a reasonable time (for larger claims). Contractors may then appeal to the cognizant Board of Contract Appeals (e.g., ASBCA, CBCA) or directly to the U.S. Court of Federal Claims. The CDA requires contractors to certify the accuracy of claims exceeding $100,000. Interest accrues on contractor claims from the date of submission; the government is not entitled to interest on its claims.',
    keyProvisions: [
      'Requires contractors to submit a written claim to the contracting officer before seeking relief',
      'Contracting officer must issue a final decision (CO Final Decision / COFD) within 60 days for claims ≤ $100,000',
      'Contractor may appeal CO Final Decision to an agency Board of Contract Appeals within 90 days, or to the Court of Federal Claims within 12 months',
      'Claims exceeding $100,000 must be certified by a senior company official under penalty of False Claims Act',
      'Interest accrues on contractor claims from date of submission at the Treasury rate',
      'Applies to contracts with executive agencies; excludes certain grants, cooperative agreements, and procurement in foreign countries',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/41/7101',
    relatedLitigation: ['government-contracts', 'construction'],
  },
  {
    name: 'Federal Rules of Criminal Procedure',
    shortName: 'FRCrP',
    citation: 'Fed. R. Crim. P. 1–60',
    category: 'Criminal',
    jurisdiction: 'Federal Rule',
    enactedYear: 1946,
    summary:
      'The Federal Rules of Criminal Procedure govern the process of federal criminal prosecutions from initial appearance through sentencing and post-conviction proceedings. They protect defendants\' constitutional rights while providing courts and parties with uniform procedures. Rule 6 governs grand jury proceedings, including the secrecy of grand jury materials. Rule 11 governs plea agreements and requires the court to personally address the defendant in open court to ensure a knowing, voluntary, and intelligent plea. Rule 16 governs pretrial discovery in criminal cases, providing more limited discovery than the civil rules. Rule 29 allows courts to enter a judgment of acquittal if the evidence is insufficient to sustain a conviction, protecting defendants from double jeopardy.',
    keyProvisions: [
      'Rule 5: initial appearance requirements, including prompt presentment before a magistrate judge',
      'Rule 6: grand jury secrecy; government must present probable cause to indict; Rule 6(e) governs disclosure',
      'Rule 11: plea procedures requiring voluntary, knowing, and intelligent waiver of trial rights; plea agreement types',
      'Rule 16: criminal discovery—defendant\'s statements, criminal record, documents the government intends to use at trial, and expert disclosures',
      'Rule 29: motion for judgment of acquittal for insufficiency of evidence (protects against double jeopardy)',
      'Rule 33: new trial motions based on newly discovered evidence or interest of justice',
    ],
    officialUrl: 'https://www.law.cornell.edu/rules/frcrmp',
    relatedLitigation: ['criminal-defense', 'white-collar-crime', 'immigration'],
  },
];

export default statutes;
