import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'Title VII of the Civil Rights Act of 1964',
    shortName: 'Title VII',
    citation: '42 U.S.C. § 2000e et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1964,
    summary:
      'Title VII prohibits employers from discriminating against employees or job applicants on the basis of race, color, religion, sex, or national origin. It applies to employers with 15 or more employees, as well as labor unions and employment agencies. The law created the Equal Employment Opportunity Commission (EEOC) to investigate and enforce complaints. Employees must generally file a charge with the EEOC before suing in federal court. Title VII has been interpreted to cover sexual harassment and, after the Supreme Court\'s 2020 Bostock decision, discrimination based on sexual orientation and gender identity.',
    keyProvisions: [
      'Prohibits discrimination in hiring, firing, pay, job assignments, promotions, and training based on race, color, religion, sex, or national origin',
      'Established the Equal Employment Opportunity Commission (EEOC) to receive, investigate, and conciliate discrimination charges',
      'Covers employers with 15 or more employees, labor organizations, and employment agencies',
      'Requires employees to exhaust administrative remedies by filing an EEOC charge before pursuing a federal lawsuit',
      'Prohibits retaliation against employees who oppose discriminatory practices or participate in EEOC proceedings',
      'Allows courts to order reinstatement, back pay, compensatory and punitive damages, and attorney\'s fees',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/2000e',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Age Discrimination in Employment Act',
    shortName: 'ADEA',
    citation: '29 U.S.C. § 621 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1967,
    summary:
      'The ADEA protects workers who are 40 years of age or older from employment discrimination based on age. It applies to employers with 20 or more employees and covers all aspects of employment, including hiring, firing, pay, benefits, and job assignments. Plaintiffs must show that age was the "but-for" cause of the adverse employment action, a standard confirmed by the Supreme Court in Gross v. FBL Financial Services (2009). The ADEA is enforced by the EEOC, and employees must file an administrative charge before suing.',
    keyProvisions: [
      'Prohibits discrimination against employees and applicants aged 40 and older in all terms and conditions of employment',
      'Applies to employers with 20 or more employees, labor organizations, and employment agencies',
      'Prohibits mandatory retirement for most workers (with narrow exceptions such as certain executives)',
      'Requires plaintiffs to prove age was the "but-for" cause of the adverse action, not merely a motivating factor',
      'Prohibits retaliation against employees who file charges or participate in ADEA proceedings',
      'Provides for back pay, liquidated (double) damages for willful violations, and attorney\'s fees',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/621',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Americans with Disabilities Act — Employment (Title I)',
    shortName: 'ADA Title I',
    citation: '42 U.S.C. § 12101 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1990,
    summary:
      'Title I of the ADA prohibits covered employers from discriminating against qualified individuals with disabilities in any aspect of employment. A "disability" is a physical or mental impairment that substantially limits a major life activity, a record of such an impairment, or being regarded as having one. Employers must provide reasonable accommodations unless doing so would impose an undue hardship on the business. The ADA Amendments Act of 2008 (ADAAA) broadened the definition of disability after courts had interpreted it too narrowly.',
    keyProvisions: [
      'Prohibits discrimination against qualified individuals with disabilities in hiring, promotion, discharge, pay, and training',
      'Defines "disability" broadly to include physical or mental impairments substantially limiting a major life activity, a record of such impairment, or being regarded as disabled',
      'Requires employers to provide reasonable accommodations (e.g., modified schedules, assistive equipment) unless they impose undue hardship',
      'Restricts pre-employment medical examinations and disability-related inquiries',
      'Applies to employers with 15 or more employees',
      'Enforced by the EEOC; remedies include reinstatement, back pay, compensatory and punitive damages',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/12101',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Fair Labor Standards Act',
    shortName: 'FLSA',
    citation: '29 U.S.C. § 201 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1938,
    summary:
      'The FLSA establishes the federal minimum wage, requires overtime pay at 1.5 times the regular rate for hours worked over 40 per week, and sets child-labor restrictions. It applies to employees engaged in interstate commerce or employed by an enterprise engaged in interstate commerce. Certain "white-collar" employees (executive, administrative, professional) are exempt from overtime if they earn above a salary threshold and meet duties tests. The Department of Labor (DOL) Wage and Hour Division enforces the FLSA, and employees may also bring private lawsuits.',
    keyProvisions: [
      'Establishes the federal minimum wage (currently $7.25/hour) for covered, non-exempt employees',
      'Requires overtime pay of at least 1.5× the regular rate for hours worked beyond 40 in a workweek',
      'Sets child-labor standards limiting the hours and types of work that minors may perform',
      'Exempts executive, administrative, and professional employees who meet salary and duties tests from overtime requirements',
      'Prohibits retaliation against employees who file complaints or participate in FLSA proceedings',
      'Allows employees to recover unpaid wages, an equal amount in liquidated damages, and attorney\'s fees',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/201',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Family and Medical Leave Act',
    shortName: 'FMLA',
    citation: '29 U.S.C. § 2601 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1993,
    summary:
      'The FMLA entitles eligible employees of covered employers to take up to 12 weeks of unpaid, job-protected leave per year for specified family and medical reasons. Qualifying reasons include the birth or adoption of a child, caring for a seriously ill family member, or the employee\'s own serious health condition. Employees must have worked for the employer for at least 12 months and at least 1,250 hours in the past year, and the employer must have 50 or more employees. Upon return, the employee is entitled to the same or an equivalent position. The DOL Wage and Hour Division enforces the FMLA.',
    keyProvisions: [
      'Provides eligible employees up to 12 weeks of unpaid, job-protected leave per year for qualifying family or medical events',
      'Provides up to 26 weeks of leave to care for a covered servicemember with a serious injury or illness',
      'Requires employers to maintain group health benefits during FMLA leave under the same terms as if the employee continued working',
      'Guarantees restoration to the same or an equivalent position upon return from leave',
      'Applies to employers with 50 or more employees within 75 miles of the worksite',
      'Prohibits interference with FMLA rights and retaliation against employees who exercise those rights',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/2601',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Equal Pay Act',
    shortName: 'EPA',
    citation: '29 U.S.C. § 206(d)',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1963,
    summary:
      'The Equal Pay Act, enacted as an amendment to the FLSA, requires that men and women in the same workplace receive equal pay for substantially equal work. Jobs need not be identical, but must require substantially equal skill, effort, and responsibility performed under similar working conditions. Employers may justify pay differences only through a seniority system, a merit system, a system measuring earnings by quantity or quality of production, or any factor other than sex. Unlike Title VII claims, EPA plaintiffs do not need to file an EEOC charge before filing suit in court.',
    keyProvisions: [
      'Prohibits wage differentials between male and female employees performing substantially equal work in the same establishment',
      'Defines equal work by skill, effort, and responsibility performed under similar working conditions',
      'Permits pay differences based on seniority, merit, production-based pay systems, or any factor other than sex',
      'Covers virtually all employers engaged in interstate commerce, regardless of size',
      'Does not require filing an EEOC charge — plaintiffs may sue directly in federal court',
      'Provides remedies of back pay, liquidated damages for willful violations, and attorney\'s fees',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/206',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Pregnancy Discrimination Act',
    shortName: 'PDA',
    citation: '42 U.S.C. § 2000e(k)',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1978,
    summary:
      'The Pregnancy Discrimination Act amended Title VII to clarify that discrimination based on pregnancy, childbirth, or related medical conditions constitutes unlawful sex discrimination. Employers must treat pregnant employees the same as other employees who are similar in their ability or inability to work. The law was passed in response to the Supreme Court\'s 1976 decision in General Electric Co. v. Gilbert, which had held that pregnancy discrimination was not sex discrimination under Title VII. The PDA does not guarantee paid leave, but requires equal treatment in benefit programs. In 2023, Congress enacted the Pregnant Workers Fairness Act (PWFA) to add a separate reasonable accommodation requirement.',
    keyProvisions: [
      'Amends Title VII to define "sex" as including pregnancy, childbirth, and related medical conditions',
      'Requires employers to treat pregnant employees the same as non-pregnant employees with similar work limitations',
      'Prohibits discrimination in hiring, firing, job assignments, promotions, and fringe benefits on the basis of pregnancy',
      'Requires that health insurance plans cover pregnancy-related conditions on the same basis as other medical conditions',
      'Applies to employers with 15 or more employees (same threshold as Title VII)',
      'Enforced through the EEOC with the same procedures and remedies as Title VII',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/2000e',
    relatedLitigation: ['employment'],
  },
  {
    name: 'National Labor Relations Act',
    shortName: 'NLRA',
    citation: '29 U.S.C. § 151 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1935,
    summary:
      'The NLRA, also known as the Wagner Act, is the cornerstone of U.S. labor law. It guarantees private-sector employees the right to organize, form, join, or assist labor unions, to bargain collectively with their employer, and to engage in concerted activities for mutual aid or protection. The NLRA established the National Labor Relations Board (NLRB) to conduct union elections and investigate and remedy unfair labor practices. The law does not cover government employees, agricultural workers, or independent contractors.',
    keyProvisions: [
      'Guarantees employees the right to self-organization, to form or join unions, and to bargain collectively',
      'Prohibits employer unfair labor practices, including interfering with union organizing, dominating a labor organization, or discriminating against union members',
      'Established the National Labor Relations Board (NLRB) to supervise union elections and adjudicate unfair labor practice charges',
      'Requires employers and certified unions to bargain in good faith over wages, hours, and other terms and conditions of employment',
      'Protects concerted activity by non-union employees (e.g., group complaints about working conditions)',
      'Excludes federal and state government employees, agricultural workers, domestic workers, supervisors, and independent contractors',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/151',
    relatedLitigation: ['employment', 'labor-union'],
  },
  {
    name: 'Labor Management Relations Act',
    shortName: 'Taft-Hartley Act',
    citation: '29 U.S.C. § 141 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1947,
    summary:
      'The Labor Management Relations Act, commonly called the Taft-Hartley Act, significantly amended the NLRA to address perceived abuses by labor unions after World War II. It added a list of union unfair labor practices to mirror the existing list of employer unfair labor practices. The Act prohibited certain strike tactics (e.g., secondary boycotts, jurisdictional strikes), allowed states to pass right-to-work laws banning union security agreements, and authorized the President to seek injunctions against strikes threatening national health or safety. It also required union officials to file affidavits disavowing Communist Party membership.',
    keyProvisions: [
      'Established union unfair labor practices, including coercing employees, refusing to bargain in good faith, and engaging in secondary boycotts',
      'Prohibited closed shops (requiring union membership as a condition of hiring) while permitting union shops subject to state right-to-work laws',
      'Authorized states to enact right-to-work laws banning mandatory union membership or dues as a condition of employment',
      'Empowered the President to seek federal injunctions ("cooling-off" periods) against strikes posing a national emergency',
      'Required unions and employers to provide 60 days\' notice before terminating or modifying a collective bargaining agreement',
      'Prohibited unions from making direct contributions to federal political campaigns',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/141',
    relatedLitigation: ['labor-union'],
  },
  {
    name: 'Occupational Safety and Health Act',
    shortName: 'OSH Act / OSHA',
    citation: '29 U.S.C. § 651 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1970,
    summary:
      'The OSH Act was enacted to ensure safe and healthful working conditions for American workers by authorizing enforcement of safety and health standards, assisting states in their occupational safety and health efforts, and providing for research, information, education, and training in the field of occupational safety and health. It created the Occupational Safety and Health Administration (OSHA) within the Department of Labor to develop and enforce workplace safety standards, and the National Institute for Occupational Safety and Health (NIOSH) to conduct research. Employers have a "general duty" to provide a workplace free from recognized hazards likely to cause death or serious physical harm.',
    keyProvisions: [
      'Imposes a general duty on employers to provide a workplace free from recognized, serious hazards',
      'Authorizes OSHA to develop and enforce specific safety and health standards for particular industries and hazards',
      'Requires employers to keep records of work-related injuries and illnesses and to report fatalities and serious hospitalizations',
      'Grants employees the right to request OSHA inspections, participate in inspections, and receive information about workplace hazards',
      'Prohibits retaliation against employees who report safety hazards or exercise their OSHA rights',
      'Authorizes civil and criminal penalties for willful or serious violations of safety standards',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/651',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Employee Retirement Income Security Act',
    shortName: 'ERISA',
    citation: '29 U.S.C. § 1001 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1974,
    summary:
      'ERISA sets minimum standards for most voluntarily established retirement and health plans in private industry to provide protection for individuals in those plans. It requires plan administrators to provide participants with plan information, establishes fiduciary responsibilities for plan managers, and provides plan participants with remedies for breaches of fiduciary duty. ERISA broadly preempts state laws that relate to employee benefit plans, creating a uniform federal regime. It does not require employers to establish plans, but regulates them once they do.',
    keyProvisions: [
      'Requires plan administrators to furnish participants with a Summary Plan Description (SPD) and annual financial reports',
      'Establishes minimum vesting schedules for employer contributions to pension plans',
      'Imposes fiduciary duties of prudence and loyalty on plan managers, prohibiting self-dealing and conflicts of interest',
      'Provides plan participants with the right to sue for benefits, breaches of fiduciary duty, and violations of the plan',
      'Preempts most state laws that relate to employee benefit plans, creating uniform federal standards',
      'Created the Pension Benefit Guaranty Corporation (PBGC) to insure participants in defined-benefit pension plans against plan failure',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/1001',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Worker Adjustment and Retraining Notification Act',
    shortName: 'WARN Act',
    citation: '29 U.S.C. § 2101 et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 1988,
    summary:
      'The WARN Act requires covered employers to provide 60 calendar days\' advance written notice before plant closings or mass layoffs affecting a significant number of workers. The purpose is to give workers and their families time to seek other employment or retraining before they lose their jobs. Covered employers are those with 100 or more full-time employees. The notice must be given to affected workers, their union representatives, and state and local government officials. Employers who violate WARN are liable to each affected employee for up to 60 days of back pay and benefits.',
    keyProvisions: [
      'Requires 60 days\' advance written notice of plant closings affecting 50 or more employees at a single site',
      'Requires 60 days\' notice of mass layoffs affecting 500 or more employees, or 50–499 employees if they constitute at least 33% of the workforce',
      'Applies to employers with 100 or more full-time employees',
      'Notice must be provided to affected workers or their union, and to state and local rapid-response agencies',
      'Recognizes limited exceptions for unforeseeable business circumstances, natural disasters, and "faltering company" situations, with reduced notice obligations',
      'Imposes liability of up to 60 days\' back pay and benefits per employee, plus civil penalties, for violations',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/29/2101',
    relatedLitigation: ['employment'],
  },
  {
    name: 'Genetic Information Nondiscrimination Act',
    shortName: 'GINA',
    citation: '42 U.S.C. § 2000ff et seq.',
    category: 'Employment & Labor',
    jurisdiction: 'Federal Statute',
    enactedYear: 2008,
    summary:
      'GINA prohibits discrimination by health insurers and employers based on genetic information. Title II of GINA, the employment title, bars employers from using an individual\'s genetic information in hiring, firing, pay, job assignments, promotions, or any other terms, conditions, or privileges of employment. Genetic information includes information about an individual\'s genetic tests, the genetic tests of family members, and the manifestation of a disease or disorder in family members. Employers are also prohibited from requesting, requiring, or purchasing genetic information about employees or their family members, with narrow exceptions.',
    keyProvisions: [
      'Prohibits employers from discriminating against employees or applicants based on genetic information',
      'Broadly defines "genetic information" to include results of genetic tests for the individual and family members, and family medical history',
      'Prohibits employers from requesting, requiring, or purchasing genetic information about employees or their family members, with narrow exceptions (e.g., voluntary wellness programs)',
      'Requires employers who inadvertently receive genetic information to treat it as confidential medical information',
      'Applies to employers with 15 or more employees; enforced by the EEOC under procedures similar to Title VII',
      'Prohibits retaliation against employees who oppose GINA violations or participate in EEOC proceedings',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/2000ff',
    relatedLitigation: ['employment'],
  },
];

export default statutes;
