import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'Clean Air Act',
    shortName: 'CAA',
    citation: '42 U.S.C. § 7401 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1963,
    summary:
      'The Clean Air Act is the primary federal law governing air pollution in the United States, comprehensively restructured in 1970 and significantly amended in 1977 and 1990. It authorizes the EPA to establish National Ambient Air Quality Standards (NAAQS) for pollutants considered harmful to public health and the environment. The Act divides regulatory responsibility between the federal government and the states, requiring each state to develop a State Implementation Plan (SIP) to achieve and maintain the NAAQS. It also regulates emissions from stationary sources (like factories and power plants) and mobile sources (like cars and trucks). Violations can result in substantial civil penalties, criminal prosecution, and citizen suits.',
    keyProvisions: [
      'National Ambient Air Quality Standards (NAAQS) for six "criteria" pollutants: particulate matter, ozone, carbon monoxide, lead, sulfur dioxide, and nitrogen dioxide',
      'State Implementation Plans (SIPs) requiring states to demonstrate how they will meet NAAQS',
      'New Source Review (NSR) permitting for major new or modified stationary sources',
      'Title IV Acid Rain Program establishing a cap-and-trade system for sulfur dioxide and nitrogen oxides',
      'Title V operating permit program for major sources',
      'Mobile source emission standards for cars, trucks, and other vehicles',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/chapter-85',
    relatedLitigation: ['environmental', 'environmental-justice', 'administrative-law'],
  },
  {
    name: 'Clean Water Act',
    shortName: 'CWA',
    citation: '33 U.S.C. § 1251 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1972,
    summary:
      'The Clean Water Act establishes the basic structure for regulating discharges of pollutants into the waters of the United States and regulating quality standards for surface waters. Originally enacted as the Federal Water Pollution Control Act in 1948, it was comprehensively amended in 1972 to establish its modern framework. The Act makes it unlawful to discharge any pollutant from a point source into navigable waters without a permit issued under the National Pollutant Discharge Elimination System (NPDES). It also established the goal of eliminating pollutant discharges into navigable waters by 1985 and achieving fishable/swimmable water quality standards by 1983. The Act funds construction of sewage treatment plants and provides authority to regulate dredge-and-fill activities in wetlands.',
    keyProvisions: [
      'National Pollutant Discharge Elimination System (NPDES) permit program for point-source discharges',
      'Section 404 wetlands permitting program administered by the Army Corps of Engineers',
      'Water quality standards requiring states to designate uses for waters and set criteria to protect those uses',
      'Total Maximum Daily Load (TMDL) requirements for impaired water bodies',
      'Oil Spill Prevention, Control, and Countermeasure (SPCC) regulations',
      'Citizen suit provision allowing private parties to sue polluters and the EPA',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/33/chapter-26',
    relatedLitigation: ['environmental', 'environmental-justice', 'administrative-law'],
  },
  {
    name: 'Comprehensive Environmental Response, Compensation, and Liability Act',
    shortName: 'CERCLA (Superfund)',
    citation: '42 U.S.C. § 9601 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1980,
    summary:
      'CERCLA, commonly known as Superfund, was enacted in 1980 in response to the growing problem of hazardous waste sites that threatened public health and the environment. It created a federal "superfund" to clean up uncontrolled or abandoned hazardous waste sites and authorized the EPA to compel responsible parties to perform cleanups or to reimburse the government for EPA-led cleanups. The law imposes strict, joint and several, and retroactive liability on a broad class of potentially responsible parties (PRPs), including current and past owners and operators of contaminated sites, generators of hazardous waste, and transporters who selected disposal sites. CERCLA also established the National Priorities List (NPL) of the most seriously contaminated sites. It was amended by the Superfund Amendments and Reauthorization Act (SARA) in 1986.',
    keyProvisions: [
      'Strict, joint and several, and retroactive liability for four categories of potentially responsible parties (PRPs)',
      'National Priorities List (NPL) identifying sites eligible for federal cleanup funding',
      'Remedial Investigation/Feasibility Study (RI/FS) process to evaluate contamination and cleanup options',
      'Natural Resource Damages (NRD) claims for harm to public natural resources',
      'Innocent Landowner Defense and Bona Fide Prospective Purchaser protections for certain property buyers',
      'Contribution rights allowing PRPs who have paid more than their fair share to seek reimbursement from other PRPs',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/chapter-103',
    relatedLitigation: ['environmental', 'environmental-justice'],
  },
  {
    name: 'National Environmental Policy Act',
    shortName: 'NEPA',
    citation: '42 U.S.C. § 4321 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1969,
    summary:
      'NEPA is often called the "environmental Magna Carta" and was one of the first comprehensive environmental laws in the United States. It requires federal agencies to assess the environmental effects of their proposed major actions before making decisions. The centerpiece of NEPA is the Environmental Impact Statement (EIS), a detailed document that must be prepared for major federal actions significantly affecting the quality of the human environment. NEPA established the Council on Environmental Quality (CEQ) to oversee its implementation and coordinate federal environmental efforts. While NEPA is primarily a procedural statute requiring analysis and public disclosure, it has been a powerful tool for public participation and litigation challenging federal projects.',
    keyProvisions: [
      'Environmental Impact Statement (EIS) requirement for major federal actions significantly affecting the environment',
      'Environmental Assessment (EA) as a shorter review used to determine whether a full EIS is required',
      'Finding of No Significant Impact (FONSI) issued when an EA concludes no EIS is needed',
      'Public comment and participation requirements throughout the review process',
      'Categorical Exclusions for actions with no significant environmental effects',
      'Council on Environmental Quality (CEQ) established to implement NEPA and issue binding regulations',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/chapter-55',
    relatedLitigation: ['environmental', 'administrative-law', 'energy-natural-resources'],
  },
  {
    name: 'Resource Conservation and Recovery Act',
    shortName: 'RCRA',
    citation: '42 U.S.C. § 6901 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1976,
    summary:
      'RCRA gives the EPA the authority to control hazardous waste from the point of generation through disposal — a concept known as "cradle-to-grave" management. Enacted in 1976 as an amendment to the Solid Waste Disposal Act of 1965, RCRA also sets standards for non-hazardous solid waste management and underground storage tanks. Subtitle C establishes the hazardous waste management program, requiring generators, transporters, and treatment/storage/disposal facilities to comply with strict standards and obtain permits. Subtitle D addresses non-hazardous solid waste, including municipal landfills. Unlike CERCLA, which addresses past contamination, RCRA primarily regulates ongoing waste management practices to prevent future contamination.',
    keyProvisions: [
      'Cradle-to-grave hazardous waste tracking through the manifest system',
      'Hazardous waste generator standards for storage, labeling, and recordkeeping',
      'Treatment, Storage, and Disposal Facility (TSDF) permitting under Subtitle C',
      'Underground Storage Tank (UST) regulations to prevent leaks and spills',
      'Corrective Action program requiring cleanup of releases from RCRA-permitted facilities',
      'Citizen suit provision and imminent and substantial endangerment authority',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/chapter-82',
    relatedLitigation: ['environmental', 'administrative-law'],
  },
  {
    name: 'Endangered Species Act',
    shortName: 'ESA',
    citation: '16 U.S.C. § 1531 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1973,
    summary:
      'The Endangered Species Act is one of the most comprehensive wildlife conservation laws in the world, aimed at protecting imperiled species from extinction and recovering them to the point where such protection is no longer necessary. It requires the U.S. Fish & Wildlife Service and the National Marine Fisheries Service to list species as "threatened" or "endangered" and to designate "critical habitat" essential to their survival. Section 7 requires all federal agencies to consult with the wildlife agencies to ensure their actions do not jeopardize listed species or adversely modify critical habitat. Section 9 prohibits any person from "taking" a listed species, a term broadly interpreted to include harming or harassing the species. The ESA has been the subject of extensive litigation and political controversy, particularly when species protections conflict with economic development.',
    keyProvisions: [
      'Listing of species as "threatened" or "endangered" based on the best available science',
      'Designation of "critical habitat" necessary for species conservation',
      'Section 7 consultation requirement for federal agency actions that may affect listed species',
      'Section 9 prohibition on "take" (harm, harassment, killing) of listed species by any person',
      'Incidental Take Permits (ITPs) allowing private parties to "take" species if they adopt a Habitat Conservation Plan (HCP)',
      'Recovery plans developed to guide actions needed to recover listed species',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/16/chapter-35',
    relatedLitigation: ['environmental', 'environmental-justice', 'administrative-law'],
  },
  {
    name: 'Toxic Substances Control Act',
    shortName: 'TSCA',
    citation: '15 U.S.C. § 2601 et seq.',
    category: 'Environmental',
    jurisdiction: 'Federal Statute',
    enactedYear: 1976,
    summary:
      'TSCA gives the EPA authority to require reporting, record-keeping, testing, and restrictions on chemical substances and mixtures, including new chemicals before they enter commerce. Originally enacted in 1976, TSCA was significantly overhauled by the Frank R. Lautenberg Chemical Safety for the 21st Century Act in 2016, which strengthened EPA\'s ability to evaluate and regulate existing chemicals. The law requires the EPA to evaluate chemicals for "unreasonable risk" to human health or the environment and to take risk management action when such risk is found. TSCA also contains specific provisions addressing asbestos, lead-based paint, polychlorinated biphenyls (PCBs), and radon. Companies must notify the EPA before manufacturing or importing new chemical substances.',
    keyProvisions: [
      'Chemical inventory requiring manufacturers to report existing and new chemical substances',
      'Pre-manufacture notice (PMN) requirement before introducing new chemicals into commerce',
      'Risk evaluation process for existing chemicals to determine unreasonable risk',
      'Risk management rules (including bans or restrictions) when unreasonable risk is found',
      'Specific rules for asbestos, lead-based paint, and polychlorinated biphenyls (PCBs)',
      'Confidential Business Information (CBI) provisions balancing transparency with trade secret protection',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/chapter-53',
    relatedLitigation: ['environmental', 'environmental-justice', 'administrative-law'],
  },
  {
    name: 'Administrative Procedure Act',
    shortName: 'APA',
    citation: '5 U.S.C. § 551 et seq.',
    category: 'Administrative Law',
    jurisdiction: 'Federal Statute',
    enactedYear: 1946,
    summary:
      'The Administrative Procedure Act is the foundational statute governing how federal administrative agencies propose and establish regulations and how courts review agency action. Enacted in 1946 as a compromise between those who wanted to rein in the growth of the New Deal regulatory state and those who supported it, the APA establishes procedures for notice-and-comment rulemaking, formal adjudication, and informal agency action. It also establishes standards for judicial review of agency action, including the "arbitrary and capricious" standard and the requirement that courts set aside rules that are "not in accordance with law." The APA is implicated in virtually every area of federal regulatory law and is the primary vehicle for challenging agency rules and decisions in federal court.',
    keyProvisions: [
      'Notice-and-comment (informal) rulemaking under Section 553, requiring agencies to publish proposed rules, solicit public comments, and issue a final rule with a reasoned explanation',
      'Formal rulemaking and adjudication procedures for on-the-record agency proceedings',
      'Right to judicial review of final agency action under Section 702',
      '"Arbitrary and capricious" standard of review requiring agencies to engage in reasoned decision-making',
      'Hearing rights and due process protections in formal adjudications',
      'Freedom of Information Act (FOIA) provisions requiring agencies to make records available to the public',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/5/part-I/chapter-5',
    relatedLitigation: ['administrative-law', 'environmental', 'healthcare', 'government-contracts'],
  },
  {
    name: 'Affordable Care Act',
    shortName: 'ACA',
    citation: 'Pub. L. 111-148, 42 U.S.C. § 18001 et seq.',
    category: 'Healthcare',
    jurisdiction: 'Federal Statute',
    enactedYear: 2010,
    summary:
      'The Affordable Care Act, also known as "Obamacare," is the most significant overhaul of the U.S. healthcare system since the creation of Medicare and Medicaid in 1965. The ACA expanded access to health insurance through a combination of insurance market reforms, the creation of health insurance marketplaces ("exchanges"), the expansion of Medicaid eligibility, and mandates on individuals and employers. It prohibits insurance companies from denying coverage based on pre-existing conditions, allows young adults to remain on their parents\' plans until age 26, and eliminates annual and lifetime coverage limits. The law has been the subject of numerous major Supreme Court challenges, including NFIB v. Sebelius (2012) and California v. Texas (2021). Its implementation involved extensive rulemaking by HHS, the IRS, and other agencies.',
    keyProvisions: [
      'Individual mandate (upheld as a tax by the Supreme Court) and employer mandate to offer qualifying coverage',
      'Health insurance marketplaces (exchanges) for individuals and small businesses to purchase coverage',
      'Medicaid expansion to cover adults with incomes up to 138% of the federal poverty level',
      'Prohibition on denying coverage or charging higher premiums based on pre-existing conditions',
      'Essential Health Benefits requirement for plans to cover ten categories of care',
      'Premium tax credits to make marketplace coverage affordable for low- and middle-income individuals',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/chapter-157',
    relatedLitigation: ['healthcare', 'administrative-law'],
  },
  {
    name: 'Emergency Medical Treatment and Labor Act',
    shortName: 'EMTALA',
    citation: '42 U.S.C. § 1395dd',
    category: 'Healthcare',
    jurisdiction: 'Federal Statute',
    enactedYear: 1986,
    summary:
      'EMTALA, sometimes called the "anti-patient dumping" law, requires hospital emergency departments that accept Medicare payments to provide a medical screening examination to anyone who comes seeking care, regardless of their ability to pay. If the examination reveals an emergency medical condition, the hospital must provide stabilizing treatment or arrange an appropriate transfer. EMTALA was enacted in 1986 in response to evidence that hospitals were turning away or prematurely transferring indigent patients with serious medical conditions. The law applies to virtually every hospital in the country because nearly all participate in Medicare. Violations can result in civil monetary penalties and exclusion from Medicare and Medicaid, and private individuals have a right of action against violating hospitals.',
    keyProvisions: [
      'Mandatory medical screening examination for all individuals presenting to the emergency department',
      'Obligation to stabilize any emergency medical condition detected before discharge or transfer',
      'Strict transfer requirements, including patient consent, physician certification, and accepting facility agreement',
      'On-call physician obligations requiring hospitals to maintain coverage for the ER',
      'Prohibition on delay of screening or stabilizing treatment to inquire about insurance or payment',
      'Civil monetary penalties and exclusion from Medicare/Medicaid for violations; private right of action for patients',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/1395dd',
    relatedLitigation: ['healthcare'],
  },
  {
    name: 'Anti-Kickback Statute',
    shortName: 'AKS',
    citation: '42 U.S.C. § 1320a-7b(b)',
    category: 'Healthcare',
    jurisdiction: 'Federal Statute',
    enactedYear: 1972,
    summary:
      'The Anti-Kickback Statute is a federal criminal law that prohibits offering, paying, soliciting, or receiving anything of value to induce or reward referrals of items or services covered by federal healthcare programs such as Medicare and Medicaid. Congress enacted the AKS because financial incentives to refer patients can corrupt medical decision-making, cause over-utilization of services, and increase program costs. The law has been interpreted very broadly — even if a legitimate business purpose exists, a payment can violate the AKS if one purpose is to induce referrals. Congress created a number of regulatory "safe harbors" for certain payment arrangements that do not trigger the statute. Violations are felonies and can also result in exclusion from federal healthcare programs and civil liability under the False Claims Act.',
    keyProvisions: [
      'Prohibition on knowingly and willfully offering, paying, soliciting, or receiving remuneration to induce or reward healthcare referrals',
      'Felony criminal penalties of up to 10 years imprisonment and $100,000 fines per violation',
      'Regulatory safe harbors for certain arrangements (e.g., personal services, space rental, employment relationships)',
      'Advisory opinion process allowing parties to seek OIG guidance on proposed arrangements',
      'Exclusion from Medicare and Medicaid as an additional sanction',
      'Linkage to the False Claims Act — AKS violations can serve as the basis for False Claims Act liability',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/42/1320a-7b',
    relatedLitigation: ['healthcare', 'government-contracts'],
  },
  {
    name: 'False Claims Act',
    shortName: 'FCA',
    citation: '31 U.S.C. § 3729 et seq.',
    category: 'Healthcare',
    jurisdiction: 'Federal Statute',
    enactedYear: 1863,
    summary:
      'The False Claims Act, originally enacted during the Civil War to combat fraud by military contractors, is today the federal government\'s primary tool for combating fraud against the government, including in the Medicare and Medicaid programs. It imposes civil liability on any person who knowingly submits or causes the submission of a false or fraudulent claim for payment to the federal government. A particularly powerful feature of the FCA is the qui tam provision, which allows private individuals (called "relators" or "whistleblowers") to file lawsuits on behalf of the government and receive a share of any recovery. Damages are trebled, and each false claim carries additional per-claim penalties. The FCA has become the government\'s most important civil fraud enforcement tool, recovering billions of dollars each year.',
    keyProvisions: [
      'Civil liability for knowingly presenting false or fraudulent claims to the federal government',
      'Treble damages (three times the government\'s actual loss) plus per-claim civil penalties',
      'Qui tam provision allowing private whistleblowers to file suits on the government\'s behalf and receive 15-30% of recoveries',
      'Government intervention right: the DOJ may take over a qui tam case or decline to intervene',
      'Anti-retaliation provisions protecting whistleblowers from termination, harassment, or discrimination',
      'Reverse false claims liability for concealing or avoiding an obligation to pay money to the government',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/31/3729',
    relatedLitigation: ['healthcare', 'government-contracts', 'administrative-law'],
  },
  {
    name: 'Federal Power Act',
    shortName: 'FPA',
    citation: '16 U.S.C. § 791a et seq.',
    category: 'Energy & Natural Resources',
    jurisdiction: 'Federal Statute',
    enactedYear: 1920,
    summary:
      'The Federal Power Act grants the Federal Energy Regulatory Commission (FERC) authority over the interstate transmission and wholesale sale of electricity in the United States. Originally enacted as Part II of the Federal Water Power Act in 1920 and significantly expanded in 1935, the FPA gives FERC jurisdiction to ensure that rates for wholesale electricity sales and transmission services are "just and reasonable" and not unduly discriminatory. The Act also requires FERC to license hydroelectric projects on navigable waters and to protect fish, wildlife, and other environmental and recreational interests in the licensing process. The FPA divides regulatory authority between FERC (wholesale/interstate) and state public utility commissions (retail/intrastate), a division that has been a source of ongoing jurisdictional disputes.',
    keyProvisions: [
      'FERC jurisdiction over wholesale electric sales and interstate transmission rates',
      '"Just and reasonable" rate standard and prohibition on undue discrimination',
      'Hydroelectric project licensing authority including environmental conditions',
      'Open access transmission requirements to prevent anti-competitive behavior',
      'Market-based rate authority for sellers with no market power',
      'Division of authority between FERC (wholesale) and state regulators (retail)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/16/chapter-12',
    relatedLitigation: ['energy-natural-resources', 'administrative-law'],
  },
  {
    name: 'Natural Gas Act',
    shortName: 'NGA',
    citation: '15 U.S.C. § 717 et seq.',
    category: 'Energy & Natural Resources',
    jurisdiction: 'Federal Statute',
    enactedYear: 1938,
    summary:
      'The Natural Gas Act grants the Federal Energy Regulatory Commission (FERC) authority over the interstate transportation and wholesale sale of natural gas in the United States. Enacted in 1938 in response to the monopoly power of interstate pipeline companies, the NGA requires that rates for the interstate transportation and sale of natural gas be "just and reasonable." It also requires FERC to approve the siting and construction of new interstate natural gas pipelines, which includes an assessment of need, environmental impacts, and the use of eminent domain. Like the Federal Power Act, the NGA divides authority between FERC and the states, with states retaining authority over intrastate gas transportation and local distribution. The NGA has been a central statute in disputes over pipeline siting, LNG terminals, and natural gas exports.',
    keyProvisions: [
      'FERC jurisdiction over interstate natural gas transportation and wholesale sales',
      '"Just and reasonable" rate standard for interstate gas pipelines',
      'Certificate of Public Convenience and Necessity required for new pipeline construction and LNG terminals',
      'Eminent domain authority for pipeline companies to acquire rights-of-way',
      'Abandonment restrictions preventing companies from discontinuing service without FERC approval',
      'Division of authority between FERC (interstate) and state commissions (intrastate/distribution)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/chapter-15B',
    relatedLitigation: ['energy-natural-resources', 'administrative-law', 'environmental'],
  },
  {
    name: 'Energy Policy Act',
    shortName: 'EPAct 2005',
    citation: 'Pub. L. 109-58, 42 U.S.C. § 15801 et seq.',
    category: 'Energy & Natural Resources',
    jurisdiction: 'Federal Statute',
    enactedYear: 2005,
    summary:
      'The Energy Policy Act of 2005 is a comprehensive federal energy law that addresses energy production in the United States across multiple sectors, including oil and gas, nuclear, coal, electricity, and renewable energy. The Act provided extensive tax incentives to encourage domestic energy production and the development of alternative fuels and energy efficiency. It expanded FERC\'s authority over electric grid reliability by establishing mandatory reliability standards, and it authorized the "fast-track" approval of liquefied natural gas (LNG) terminals. The Act also created new loan guarantee programs for innovative energy technologies and addressed concerns about electricity market manipulation following the California energy crisis. Among its most controversial provisions were incentives for hydraulic fracturing (fracking) and provisions addressing the "Halliburton loophole" in environmental regulation.',
    keyProvisions: [
      'Tax incentives for oil and gas production, nuclear power, clean coal, renewable energy, and energy efficiency',
      'Mandatory electric grid reliability standards enforced by FERC through NERC',
      'Loan guarantee program for innovative energy technologies',
      'FERC primacy over LNG terminal siting, superseding state authority',
      'Renewable Fuel Standard (RFS) requiring blending of biofuels into transportation fuel',
      'Hydraulic fracturing exemptions from Safe Drinking Water Act underground injection control requirements',
    ],
    officialUrl: 'https://en.wikipedia.org/wiki/Energy_Policy_Act_of_2005',
    relatedLitigation: ['energy-natural-resources', 'environmental', 'administrative-law'],
  },
];

export default statutes;
