import { StatuteSeed } from './types';

const statutes: StatuteSeed[] = [
  {
    name: 'Patent Act',
    shortName: 'Patent Act',
    citation: '35 U.S.C. §§ 1 et seq.',
    category: 'Intellectual Property',
    jurisdiction: 'Federal Statute',
    enactedYear: 1952,
    summary:
      'The Patent Act establishes the framework for obtaining and enforcing patents in the United States. It defines what types of inventions are patentable—processes, machines, manufactures, and compositions of matter—and sets out the conditions for patentability, including novelty, non-obviousness, and usefulness. The U.S. Patent and Trademark Office (USPTO) administers the patent system under this Act. Patent holders are granted the exclusive right to make, use, sell, and import their invention for up to 20 years from the filing date. Infringers may face injunctions and monetary damages, including reasonable royalties.',
    keyProvisions: [
      'Defines patentable subject matter: processes, machines, manufactures, and compositions of matter (§ 101)',
      'Requires novelty (§ 102), non-obviousness (§ 103), and written description/enablement (§ 112)',
      'Grants a 20-year patent term from the earliest effective filing date',
      'Provides civil remedies including injunctions and damages no less than a reasonable royalty (§ 284)',
      'Allows enhanced damages up to three times for willful infringement (§ 284)',
      'Establishes inter partes review (IPR) for challenging patent validity before the Patent Trial and Appeal Board (PTAB)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/35',
    relatedLitigation: ['intellectual-property'],
  },
  {
    name: 'Lanham Act',
    shortName: 'Lanham Act',
    citation: '15 U.S.C. §§ 1051 et seq.',
    category: 'Intellectual Property',
    jurisdiction: 'Federal Statute',
    enactedYear: 1946,
    summary:
      'The Lanham Act is the primary federal trademark statute, governing the registration, use, and protection of trademarks and service marks in U.S. commerce. It established the federal trademark registration system administered by the USPTO. Trademark owners can sue for infringement when another party uses a mark that is likely to cause consumer confusion. The Act also prohibits false advertising and trade dress infringement. Remedies include injunctions, disgorgement of profits, actual damages, and attorneys\' fees in exceptional cases.',
    keyProvisions: [
      'Establishes federal registration of trademarks and service marks through the USPTO (§ 1051)',
      'Prohibits trademark infringement based on a likelihood of consumer confusion (§ 1114)',
      'Bars false designation of origin and false advertising (§ 1125(a))',
      'Protects famous marks against dilution by blurring or tarnishment (§ 1125(c))',
      'Provides remedies including injunctions, profits, damages, and attorney fees (§ 1117)',
      'Creates incontestability for marks registered and in continuous use for five years (§ 1065)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/1051',
    relatedLitigation: ['intellectual-property'],
  },
  {
    name: 'Copyright Act of 1976',
    shortName: 'Copyright Act',
    citation: '17 U.S.C. §§ 101 et seq.',
    category: 'Intellectual Property',
    jurisdiction: 'Federal Statute',
    enactedYear: 1976,
    summary:
      'The Copyright Act of 1976 is the cornerstone of U.S. copyright law, protecting original works of authorship fixed in a tangible medium of expression. It grants authors exclusive rights to reproduce, distribute, perform, display, and create derivative works. Copyright protection generally lasts for the life of the author plus 70 years. The Act includes the fair use doctrine, which allows limited use of copyrighted material without permission for purposes such as criticism, comment, news reporting, teaching, scholarship, and research. Registration with the Copyright Office is not required but provides procedural benefits, including the ability to seek statutory damages.',
    keyProvisions: [
      'Protects original works of authorship fixed in any tangible medium (§ 102)',
      'Grants six exclusive rights: reproduction, distribution, adaptation, public performance, public display, and digital audio transmission (§ 106)',
      'Establishes a fair use defense based on four factors including purpose and market effect (§ 107)',
      'Sets copyright duration at life of the author plus 70 years (§ 302)',
      'Allows statutory damages of $750–$30,000 per work ($150,000 for willful infringement) upon registration (§ 504)',
      'Provides work-for-hire doctrine under which employers own employee-created works (§ 101, § 201)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/17',
    relatedLitigation: ['intellectual-property'],
  },
  {
    name: 'Digital Millennium Copyright Act',
    shortName: 'DMCA',
    citation: 'Pub. L. 105-304, 17 U.S.C. §§ 512, 1201 et seq.',
    category: 'Intellectual Property',
    jurisdiction: 'Federal Statute',
    enactedYear: 1998,
    summary:
      'The DMCA updated U.S. copyright law for the digital age, implementing two World Intellectual Property Organization (WIPO) treaties. Its most significant provisions prohibit circumventing technological protection measures (TPMs) on copyrighted works and provide a safe harbor for online service providers (OSPs) from copyright liability when they host user-generated content. The safe harbor requires OSPs to have a notice-and-takedown system and to expeditiously remove infringing content upon notification. The DMCA also criminalizes circumvention of digital rights management (DRM) systems. These provisions have shaped the modern internet ecosystem, enabling platforms like YouTube and Facebook to operate.',
    keyProvisions: [
      'Prohibits circumvention of technological protection measures (TPMs/DRM) used to protect copyrighted works (§ 1201)',
      'Provides safe harbor from copyright liability for ISPs and online platforms that host user content, subject to notice-and-takedown compliance (§ 512)',
      'Requires service providers to have a designated agent for DMCA takedown notices registered with the Copyright Office (§ 512(c))',
      'Mandates "repeat infringer" policies: providers must terminate accounts of repeat copyright infringers (§ 512(i))',
      'Prohibits removal or alteration of copyright management information (CMI) (§ 1202)',
      'Implements WIPO Copyright Treaty and WIPO Performances and Phonograms Treaty obligations',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/17/512',
    relatedLitigation: ['intellectual-property'],
  },
  {
    name: 'Defend Trade Secrets Act',
    shortName: 'DTSA',
    citation: '18 U.S.C. §§ 1836–1839',
    category: 'Intellectual Property',
    jurisdiction: 'Federal Statute',
    enactedYear: 2016,
    summary:
      'The Defend Trade Secrets Act created the first federal civil cause of action for trade secret misappropriation, allowing companies to sue in federal court without needing to show diversity of citizenship. Prior to the DTSA, trade secret disputes were governed exclusively by state law, usually the Uniform Trade Secrets Act. The DTSA protects trade secrets related to products or services used in, or intended for use in, interstate or foreign commerce. It provides powerful remedies including injunctions, damages, and in extraordinary cases, ex parte seizure orders to prevent the dissemination of a misappropriated trade secret. Criminal penalties are also available for willful misappropriation.',
    keyProvisions: [
      'Creates a federal civil cause of action for misappropriation of trade secrets (§ 1836(b))',
      'Defines "trade secret" broadly to include formulas, patterns, compilations, programs, devices, methods, techniques, or processes (§ 1839(3))',
      'Allows ex parte seizure orders in extraordinary circumstances to preserve evidence (§ 1836(b)(2))',
      'Provides remedies including injunctive relief, actual damages, unjust enrichment, and exemplary damages up to two times the actual damages for willful misappropriation (§ 1836(b)(3))',
      'Requires whistleblower immunity notice in employment and contractor agreements (§ 1833(b))',
      'Applies a three-year statute of limitations from discovery of misappropriation',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/1836',
    relatedLitigation: ['intellectual-property'],
  },
  {
    name: 'Computer Fraud and Abuse Act',
    shortName: 'CFAA',
    citation: '18 U.S.C. § 1030',
    category: 'Cybercrime',
    jurisdiction: 'Federal Statute',
    enactedYear: 1986,
    summary:
      'The Computer Fraud and Abuse Act is the primary U.S. federal anti-hacking law, prohibiting unauthorized access to, and unauthorized use of, computer systems. Originally enacted to combat computer espionage, it was expanded to cover a wide range of computer-related offenses. The CFAA applies to any "protected computer," which includes virtually any computer connected to the internet. It is used to prosecute hackers, malware authors, and in some cases, employees who exceed their authorized access. The Act provides both criminal penalties and civil remedies, allowing victims to sue for damages.',
    keyProvisions: [
      'Prohibits unauthorized access to, or exceeding authorized access of, a protected computer to obtain information (§ 1030(a)(2))',
      'Criminalizes intentional transmission of malicious code (e.g., malware, ransomware) that causes damage (§ 1030(a)(5))',
      'Prohibits computer fraud: accessing a protected computer to commit fraud and obtain anything of value (§ 1030(a)(4))',
      'Bars trafficking in passwords or similar information to gain unauthorized computer access (§ 1030(a)(6))',
      'Provides civil cause of action for victims who suffer damage or loss exceeding $5,000 (§ 1030(g))',
      'Enhanced penalties for offenses causing serious bodily harm or affecting critical infrastructure (§ 1030(c))',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/1030',
    relatedLitigation: ['cybercrime'],
  },
  {
    name: 'Electronic Communications Privacy Act',
    shortName: 'ECPA',
    citation: '18 U.S.C. §§ 2510–2523',
    category: 'Privacy & Data',
    jurisdiction: 'Federal Statute',
    enactedYear: 1986,
    summary:
      'The Electronic Communications Privacy Act extended federal wiretapping protections to electronic data transmissions and stored electronic communications. Enacted to modernize the outdated Federal Wiretap Act, ECPA covers three areas: Title I (the Wiretap Act) prohibits real-time interception of communications; Title II (the Stored Communications Act) governs access to stored electronic data; and Title III (the Pen Register Act) regulates tracking of telephone numbers and email addresses. Government agencies must generally obtain a warrant to intercept real-time communications, though standards for stored data have been more permissive. ECPA has been criticized as outdated given modern cloud storage practices.',
    keyProvisions: [
      'Title I: prohibits the intentional interception of wire, oral, or electronic communications without consent or a court order (§ 2511)',
      'Title II (Stored Communications Act): restricts government and private access to stored electronic communications and subscriber records (§§ 2701–2713)',
      'Title III (Pen Register Act): requires a court order for installation of pen registers or trap-and-trace devices (§§ 3121–3127)',
      'Provides a good-faith exception allowing service providers to disclose communications to law enforcement under specific legal processes',
      'Creates civil and criminal liability for unlawful interceptions or disclosures',
      'Applies to both government actors and private parties who intercept communications',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/2510',
    relatedLitigation: ['privacy-data', 'cybercrime'],
  },
  {
    name: 'Stored Communications Act',
    shortName: 'SCA',
    citation: '18 U.S.C. §§ 2701–2713',
    category: 'Privacy & Data',
    jurisdiction: 'Federal Statute',
    enactedYear: 1986,
    summary:
      'The Stored Communications Act (Title II of ECPA) protects the privacy of stored electronic communications held by third-party service providers, such as emails, texts, and social media messages. It restricts when the government can compel service providers to disclose user data and prohibits unauthorized private access to stored communications. The SCA distinguishes between content (full emails, messages) and non-content metadata (subscriber information, login records), applying different legal standards to each. Courts have struggled to apply the SCA to modern cloud storage, and Congress amended it via the CLOUD Act in 2018 to address cross-border data requests.',
    keyProvisions: [
      'Prohibits intentional unauthorized access to stored wire or electronic communications held by service providers (§ 2701)',
      'Requires a warrant for government access to communications in electronic storage for 180 days or less (§ 2703(a))',
      'Allows government to obtain older stored communications with a subpoena or court order, subject to notice requirements (§ 2703(b)–(d))',
      'Permits service providers to voluntarily disclose non-content data (e.g., subscriber records) to law enforcement in certain circumstances (§ 2702)',
      'Creates civil liability for service providers or government actors who violate its provisions (§ 2707)',
      'The CLOUD Act (2018) clarified that U.S. providers must comply with legal process for data stored abroad',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/18/2701',
    relatedLitigation: ['privacy-data', 'cybercrime'],
  },
  {
    name: 'Communications Decency Act Section 230',
    shortName: 'Section 230',
    citation: '47 U.S.C. § 230',
    category: 'Media & Defamation',
    jurisdiction: 'Federal Statute',
    enactedYear: 1996,
    summary:
      'Section 230 of the Communications Decency Act is often called "the twenty-six words that created the internet." It provides that online platforms and interactive computer services cannot be treated as the publisher or speaker of third-party content posted by users. This immunity shields platforms from liability for user-generated defamatory, offensive, or harmful content, enabling the modern internet ecosystem. The law also provides immunity when platforms moderate or remove content in good faith, even if they remove legal content. Section 230 has faced growing criticism and calls for reform, with arguments that platforms should bear more responsibility for harmful content they host or amplify.',
    keyProvisions: [
      'Shields interactive computer service providers from liability as the publisher of third-party user content (§ 230(c)(1))',
      'Provides immunity for good-faith moderation: providers are not liable for restricting or blocking objectionable content (§ 230(c)(2))',
      'Applies broadly to any interactive computer service, including social media platforms, websites, and apps',
      'Does not immunize providers for federal criminal law violations, intellectual property claims, or federal sex trafficking laws (§ 230(e))',
      'Has been interpreted expansively by courts to cover even algorithmic amplification and curation of third-party content',
      'Requires platforms that receive federal sex trafficking content notice to take action under FOSTA-SESTA (2018 amendment)',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/47/230',
    relatedLitigation: ['defamation-media'],
  },
  {
    name: 'Health Insurance Portability and Accountability Act',
    shortName: 'HIPAA',
    citation: 'Pub. L. 104-191; 45 C.F.R. Parts 160, 162, 164',
    category: 'Privacy & Data',
    jurisdiction: 'Federal Statute',
    enactedYear: 1996,
    summary:
      'HIPAA established national standards for the protection of individuals\' medical records and other protected health information (PHI). The Privacy Rule restricts how covered entities—including health plans, health care clearinghouses, and most health care providers—may use and disclose PHI. The Security Rule sets standards for safeguarding electronically stored PHI (ePHI). The Breach Notification Rule requires covered entities and their business associates to notify affected individuals, HHS, and sometimes the media when unsecured PHI is improperly disclosed. HIPAA is enforced by the Department of Health and Human Services (HHS) Office for Civil Rights (OCR), which may impose civil monetary penalties.',
    keyProvisions: [
      'Privacy Rule: restricts use and disclosure of PHI without patient authorization, with limited exceptions such as treatment, payment, and operations (45 C.F.R. § 164.502)',
      'Security Rule: requires administrative, physical, and technical safeguards to protect ePHI (45 C.F.R. §§ 164.302–318)',
      'Breach Notification Rule: mandates notice to affected individuals within 60 days of discovery of a PHI breach (45 C.F.R. §§ 164.400–414)',
      'Business Associate Agreements (BAAs): covered entities must obtain BAAs from vendors who handle PHI on their behalf',
      'Grants patients rights to access, amend, and request accounting of disclosures of their PHI',
      'Civil penalties range from $100 to $50,000+ per violation category, with annual caps up to $1.9 million',
    ],
    officialUrl: 'https://www.law.cornell.edu/cfr/text/45/164.502',
    relatedLitigation: ['privacy-data', 'healthcare'],
  },
  {
    name: 'California Consumer Privacy Act',
    shortName: 'CCPA/CPRA',
    citation: 'Cal. Civ. Code §§ 1798.100 et seq.',
    category: 'Privacy & Data',
    jurisdiction: 'State/Uniform',
    enactedYear: 2018,
    summary:
      'The California Consumer Privacy Act (CCPA), strengthened by the California Privacy Rights Act (CPRA) effective January 2023, is the most comprehensive U.S. state privacy law. It grants California residents significant rights over their personal information collected by businesses, including the right to know, delete, correct, and opt out of the sale or sharing of personal data. The CPRA also restricts the use of sensitive personal information and created the California Privacy Protection Agency (CPPA) to enforce the law. Businesses subject to the law must provide privacy notices, honor consumer rights requests, and implement reasonable security measures. The law applies to for-profit businesses that meet certain revenue or data-processing thresholds and operate in California.',
    keyProvisions: [
      'Grants consumers the right to know what personal information is collected, used, shared, or sold (§ 1798.110)',
      'Provides the right to delete personal information collected by the business (§ 1798.105)',
      'Creates opt-out rights for sale or sharing of personal information, including a "Do Not Sell or Share My Personal Information" link requirement (§ 1798.120)',
      'CPRA adds the right to correct inaccurate personal information and limits use of sensitive personal information (§ 1798.121)',
      'Provides a private right of action for data breaches resulting from failure to implement reasonable security (§ 1798.150)',
      'Creates the California Privacy Protection Agency (CPPA) with rulemaking and enforcement authority',
    ],
    officialUrl: 'https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=1798.100.&lawCode=CIV',
    relatedLitigation: ['privacy-data'],
  },
  {
    name: "Children's Online Privacy Protection Act",
    shortName: 'COPPA',
    citation: '15 U.S.C. §§ 6501–6506',
    category: 'Privacy & Data',
    jurisdiction: 'Federal Statute',
    enactedYear: 1998,
    summary:
      "COPPA protects the privacy of children under 13 online by restricting what information websites and online services can collect from them. Operators of websites or online services directed to children, or who have actual knowledge they are collecting personal information from children under 13, must obtain verifiable parental consent before collecting, using, or disclosing the child's personal information. The FTC enforces COPPA and has levied some of the largest privacy fines in U.S. history against companies that violated it. The law was updated in 2013 to cover mobile apps and to expand the definition of personal information to include persistent identifiers like device IDs and IP addresses. The FTC began a rulemaking to further update COPPA in 2022.",
    keyProvisions: [
      'Requires verifiable parental consent before collecting, using, or disclosing personal information from children under 13 (§ 6502)',
      'Mandates a clear, prominent privacy notice disclosing data collection practices directed at children',
      'Grants parents the right to review, delete, and refuse further collection of their child\'s personal information',
      'Prohibits conditioning a child\'s participation in an online activity on providing more personal information than is reasonably necessary',
      'Applies to websites and online services directed to children or with actual knowledge they are collecting information from children under 13',
      'FTC may seek civil penalties up to tens of thousands of dollars per violation per day',
    ],
    officialUrl: 'https://www.law.cornell.edu/uscode/text/15/6501',
    relatedLitigation: ['privacy-data'],
  },
  {
    name: 'General Data Protection Regulation',
    shortName: 'GDPR',
    citation: 'Regulation (EU) 2016/679',
    category: 'Privacy & Data',
    jurisdiction: 'International',
    enactedYear: 2016,
    summary:
      'The GDPR is the European Union\'s landmark data protection law, which took effect in May 2018 and applies to organizations worldwide that process the personal data of EU residents. It imposes strict requirements on how personal data is collected, processed, stored, and transferred, and grants individuals expansive rights over their data. The GDPR requires a lawful basis for all data processing, such as consent or legitimate interest, and mandates data minimization, purpose limitation, and accuracy. It established the role of Data Protection Officers (DPOs) and requires Data Protection Impact Assessments (DPIAs) for high-risk processing. Non-compliance can result in fines up to 4% of global annual turnover or €20 million, whichever is higher.',
    keyProvisions: [
      'Requires a lawful basis for processing personal data (consent, contract, legal obligation, vital interest, public task, or legitimate interest) (Art. 6)',
      'Grants data subjects rights to access, rectification, erasure ("right to be forgotten"), restriction, portability, and objection (Arts. 15–21)',
      'Mandates data breach notification to supervisory authorities within 72 hours and to affected individuals without undue delay (Art. 33–34)',
      'Requires Data Protection by Design and by Default, and Data Protection Impact Assessments (DPIAs) for high-risk processing (Arts. 25, 35)',
      'Restricts transfers of personal data to countries outside the EU/EEA without adequate protection mechanisms (Arts. 44–49)',
      'Imposes fines of up to €20 million or 4% of global annual turnover for serious violations (Art. 83)',
    ],
    officialUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016R0679',
    relatedLitigation: ['privacy-data'],
  },
];

export default statutes;
