import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'commercial',
    name: 'Hadley v. Baxendale',
    citation: '9 Exch. 341, 156 Eng. Rep. 145 (1854)',
    jurisdiction: 'England and Wales',
    court: 'Court of Exchequer',
    year: 1854,
    facts: 'The plaintiffs, Joseph and Jonah Hadley, operated a flour mill in Gloucester that was forced to shut down when its crankshaft broke. They contracted with defendant Joseph Baxendale, a carrier operating under the firm Pickford & Co., to transport the broken crankshaft to the manufacturer in Greenwich so that a replacement could be made. Baxendale negligently delayed delivery of the crankshaft by several days beyond the agreed time, causing the mill to remain idle longer than anticipated. The Hadleys brought suit claiming lost profits for the entire period the mill was shut down due to Baxendale\'s delay. Baxendale argued he had no knowledge at the time of contracting that the mill would be entirely idle without the crankshaft, and that the lost profits were therefore too remote a consequence of his breach.',
    keyLegalIssues: [
      'What is the proper measure of damages for breach of contract?',
      'Whether consequential damages must be foreseeable at the time of contracting to be recoverable',
      'The distinction between general damages and special or consequential damages',
      'What facts must a party communicate to make consequential losses recoverable',
    ],
    plaintiffArguments: 'The Hadleys argued that Baxendale\'s delay in delivering the crankshaft directly caused their mill to remain idle and that they were therefore entitled to recover all lost profits flowing from that breach. They contended that any carrier should understand that a broken mill component being shipped for repair is urgently needed and that delay would cause commercial harm. The plaintiffs maintained that the full measure of their loss, including all profits foregone during the extended shutdown, should be compensable because it was the direct result of Baxendale\'s failure to perform on time.',
    defendantArguments: 'Baxendale contended that he was never informed that the mill would be entirely at a standstill during the period of delay, and that such special circumstances were not communicated to him at the time the contract of carriage was formed. He argued that lost profits of this magnitude were not a natural or foreseeable consequence of a mere delay in delivery and therefore could not be recovered as damages. Baxendale maintained that to hold carriers liable for all downstream commercial losses caused by delay would expose them to ruinous and unlimited liability that they could not have anticipated or priced into the contract.',
    proceduralHistory: 'The case was originally tried at the Gloucester Assizes, where the jury awarded the plaintiffs damages of £50 for lost profits, a sum which Baxendale challenged as excessive. The matter was appealed to the Court of Exchequer, which considered the proper legal standard for the recoverability of consequential damages in contract cases. The Court of Exchequer issued a new trial on the question of damages, articulating for the first time the two-branch rule governing remoteness of damage.',
    finalDecision: 'The Court of Exchequer held that damages for breach of contract should be limited to those that either arise naturally from the breach in the usual course of things, or those that were reasonably contemplated by both parties at the time of contracting as the probable result of a breach. Because Baxendale had no knowledge that the mill would be wholly stopped during the delay, the lost profits were too remote and could not be recovered. A new trial was ordered to assess damages on the correct basis.',
    judicialReasoning: 'Baron Alderson, writing for the court, articulated what became known as the two-limb test for remoteness of damages in contract. The first limb allows recovery for damages that arise naturally, according to the usual course of things, from the breach of contract itself. The second limb allows recovery for damages that, although not arising naturally, were reasonably contemplated by both parties at the time of contracting as the probable result of breach given any special circumstances communicated. The court reasoned that because the Hadleys never told Baxendale that the mill would be idle pending the return of the crankshaft, Baxendale could not have foreseen lost profits as a probable result of delay. The rule was designed to protect contracting parties from liability for consequences they could not have anticipated and did not implicitly agree to bear, thereby encouraging efficient commercial dealings and fair allocation of risk.',
    legalStandards: [
      'Hadley v. Baxendale two-limb test for remoteness of damages',
      'Foreseeability at the time of contracting as the measure of recoverable loss',
      'The natural and direct consequences rule for general damages',
      'Special circumstances must be communicated for consequential losses to be recoverable',
    ],
    keyPrecedents: [
      'Robinson v. Harman (1848) — expectation damages as the general principle',
      'Victoria Laundry (Windsor) Ltd v. Newman Industries Ltd [1949] — elaboration of the Hadley rule',
      'Koufos v. C. Czarnikow Ltd (The Heron II) [1969] — House of Lords refining the foreseeability standard',
    ],
    evidenceAnalysis: 'The critical evidentiary question was what information Baxendale had received at the time of contracting. The clerk who arranged the carriage gave no indication to Baxendale that the mill was idle and awaiting the crankshaft\'s return, and the only instruction given was to deliver it as soon as possible. This informational gap was decisive in the court\'s conclusion that Baxendale could not have contemplated lost profits as a probable consequence of delay.',
    alternativeOutcomes: 'Had the Hadleys communicated that the mill was entirely shut down pending return of the crankshaft, Baxendale would have had the special knowledge required to make lost profits foreseeable under the second limb, and full recovery would likely have been available. Alternatively, if the court had adopted a broader consequentialism, carriers and service providers throughout England would have faced dramatically expanded liability for delay, potentially chilling commercial transport services.',
    lessonsLearned: [
      'Parties should communicate special circumstances to the other contracting party to preserve recovery of consequential damages',
      'Carriers and service providers should inquire about the commercial urgency of shipments to price risk appropriately',
      'Consequential damages clauses in commercial contracts should explicitly define the scope of recoverable losses',
      'Contracting parties bear responsibility for ensuring the other side is aware of facts that would affect their liability exposure',
    ],
    bestPractices: [
      'Include consequential damages provisions in commercial contracts that expressly define recoverable losses',
      'Communicate all special circumstances to the counterparty at contract formation',
      'Service providers should consider standard contract terms that cap consequential liability',
      'Document all communications at the time of contracting regarding the commercial importance of timely performance',
    ],
    significance: 'Hadley v. Baxendale is the foundational case of Anglo-American contract law on the recoverability of consequential damages, and its two-limb test has been applied in virtually every common-law jurisdiction for over 170 years. The decision established a principle of limited liability in contract that encourages commercial certainty and allows parties to price and allocate risk at the time of contracting. It has been adopted, refined, and followed by courts in England, the United States, Canada, Australia, and beyond, and is considered the starting point for any analysis of contract damages. The case introduced the concept that contract law should promote efficient exchange by tying liability to what the parties actually contemplated, rather than all losses however remote. Its influence extends into modern commercial drafting practice, where consequential damages waivers and limitation-of-liability clauses trace their intellectual lineage directly to this decision.',
    outcome: 'Defendant Victory (new trial on damages)',
    isFeatured: true,
    parties: [
      {
        name: 'Joseph Hadley and Jonah Hadley',
        role: 'PLAINTIFF',
        description: 'Operators of a flour mill in Gloucester whose crankshaft required shipping for repair',
      },
      {
        name: 'Joseph Baxendale (Pickford & Co.)',
        role: 'DEFENDANT',
        description: 'Carrier who contracted to transport the broken crankshaft and delayed delivery',
      },
    ],
  },
  {
    litigationSlug: 'commercial',
    name: 'Lucy v. Zehmer',
    citation: '196 Va. 493, 84 S.E.2d 516 (1954)',
    jurisdiction: 'Virginia, United States',
    court: 'Supreme Court of Appeals of Virginia',
    year: 1954,
    facts: 'W.O. Lucy had long sought to purchase Zehmer\'s farm in Dinwiddie County, Virginia, known as the Ferguson Farm, and on the evening of December 20, 1952, approached A.H. Zehmer at a restaurant. Over the course of the evening, during which both men consumed whiskey, Lucy again raised the possibility of purchasing the farm for $50,000. Zehmer, on a restaurant check, wrote out an agreement to sell the farm for $50,000 and had both himself and his wife Ida sign it. Zehmer later claimed that the entire negotiation was a joke and that he had no actual intention to sell, believing Lucy was also treating it as a jest. Lucy took the agreement seriously, paid $5 as part performance, and the following day arranged financing and attempted to proceed with the sale, at which point Zehmer refused to honor the contract.',
    keyLegalIssues: [
      'Whether a contract is formed based on the objective manifestation of intent or the subjective secret intent of the parties',
      'The objective theory of contract formation under Virginia law',
      'Whether intoxication negates contractual capacity when a party appears to understand the transaction',
      'Whether a purported joke can negate the formation of an otherwise outwardly serious contract',
    ],
    plaintiffArguments: 'Lucy argued that the written agreement signed by both Zehmers constituted a binding contract because he reasonably and in good faith understood the transaction to be serious and genuine. He maintained that Zehmer\'s outward conduct throughout the evening — including rewriting the agreement, having his wife sign it, and discussing terms — manifested an unmistakable intent to be bound. Lucy contended that he had relied on the agreement to his detriment by arranging financing and taking other steps to close the transaction, making it inequitable for Zehmer to escape performance on the basis of an undisclosed subjective intent to joke.',
    defendantArguments: 'Zehmer argued that he never subjectively intended to sell the farm and that the entire episode was conducted in a spirit of humor and jest, with both parties understanding it as such. He contended that his intoxication further undermined the formation of a genuine agreement, as his judgment and intent were impaired throughout the evening. Zehmer also argued that no reasonable person would sell a farm worth more than $50,000 to a neighbor over drinks at a restaurant, and that the circumstances surrounding the agreement demonstrated its lack of seriousness.',
    proceduralHistory: 'Lucy brought an action for specific performance of the contract in the Circuit Court of Dinwiddie County, Virginia. The trial court ruled in favor of the Zehmers, finding that the agreement was made in jest and that no binding contract had been formed. Lucy appealed to the Supreme Court of Appeals of Virginia, which reversed the lower court\'s decision and ordered specific performance of the contract.',
    finalDecision: 'The Supreme Court of Appeals of Virginia reversed the trial court and ordered specific performance of the contract of sale. The court held that the law applies an objective test to contract formation and that Zehmer\'s outward conduct manifested a genuine offer to sell, which Lucy accepted in good faith. Because the agreement was written, signed by both parties, and treated seriously by Lucy, the contract was enforceable regardless of Zehmer\'s secret subjective intent.',
    judicialReasoning: 'Justice Buchanan, writing for the court, applied the objective theory of contract formation, which holds that a party\'s intent is judged not by what he secretly meant but by what his words and conduct would reasonably communicate to the other party. The court found that Zehmer\'s actions throughout the evening — discussing the farm, rewriting the agreement to be clearer, and having his wife co-sign — were entirely consistent with a genuine offer to sell and inconsistent with any outward manifestation of a joke. The court rejected the intoxication defense, finding that Zehmer appeared to know what he was doing throughout and that his conduct was not so impaired as to negate contractual capacity. The court emphasized that if the secret intent of a party could defeat a contract, the entire foundation of commercial certainty would be undermined because no one could safely rely on a counterparty\'s apparent assent. The holding firmly anchored Virginia contract law in the objective theory and underscored that parties are bound by the reasonable meaning of their words and acts.',
    legalStandards: [
      'Objective theory of contract formation — intent judged by outward manifestation',
      'Specific performance as a remedy for breach of a contract for the sale of unique real property',
      'Contractual capacity — intoxication must be severe enough to negate understanding',
      'Reasonable reliance by the offeree on the apparent seriousness of an offer',
    ],
    keyPrecedents: [
      'Embry v. Hargadine-McKittrick Dry Goods Co. (1907) — objective theory applied in employment context',
      'Hotchkiss v. National City Bank (1911) — Holmes articulating the objective theory of contracts',
      'Restatement (Second) of Contracts § 17 — requirement of manifestation of mutual assent',
    ],
    evidenceAnalysis: 'The physical evidence of the written agreement on the restaurant check, signed by both Zehmer and his wife, was central to the court\'s analysis. The court also credited testimony that Zehmer rewrote the agreement to make it more specific and that Lucy observed no outward indication of humor or jest during the negotiation. Zehmer\'s own acknowledgment that he understood he was writing out an agreement to sell, even if he claims he thought Lucy was also joking, supported the conclusion that his conduct objectively manifested contractual intent.',
    alternativeOutcomes: 'Had the court adopted the subjective theory of contract formation, Zehmer\'s hidden intent would have been determinative and no contract would have been found, leaving Lucy without recourse despite his reasonable reliance. If the level of intoxication had been more severe and the evidence supported a genuine impairment of capacity, the outcome might have been a voidable rather than enforceable contract, allowing Zehmer to rescind upon a showing of incapacity.',
    lessonsLearned: [
      'Parties are bound by the reasonable meaning of their outward conduct, regardless of secret subjective intent',
      'Written agreements, even those created informally, carry significant legal weight',
      'Commercial negotiations conducted in social settings can result in enforceable contracts',
      'Intoxication will not excuse contractual obligations unless it reaches the level of total incapacity',
    ],
    bestPractices: [
      'Avoid signing any written agreement unless you intend to be bound, regardless of the social context',
      'Include clear language in any preliminary writing indicating it is non-binding if that is the intent',
      'Do not rely on an undisclosed subjective belief that a transaction is a joke to escape performance',
      'Negotiate commercial transactions in formal settings with legal counsel present to avoid ambiguity',
    ],
    significance: 'Lucy v. Zehmer is the canonical American law school case for teaching the objective theory of contract formation, illustrating that courts evaluate intent by outward conduct rather than private mental state. The decision reinforced the principle that commercial certainty depends on parties being able to rely on what the other party objectively manifested, rather than being surprised by a claim of secret non-intent. The case is regularly cited for the proposition that a written, signed agreement creates a strong presumption of intent to be bound that is not easily overcome by after-the-fact claims of jest or intoxication. It also stands for the rule that specific performance is an appropriate remedy when the subject matter is unique real property and money damages would be inadequate. The case remains a fixture in first-year contracts courses throughout the United States as a vivid demonstration of why the law must use an objective measure of assent.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'W.O. Lucy',
        role: 'PLAINTIFF',
        description: 'Purchaser who sought specific performance of the agreement to buy the Ferguson Farm',
      },
      {
        name: 'A.H. Zehmer and Ida Zehmer',
        role: 'DEFENDANT',
        description: 'Owners of the Ferguson Farm who claimed the agreement was made in jest',
      },
    ],
  },
  {
    litigationSlug: 'commercial',
    name: 'Hawkins v. McGee',
    citation: '84 N.H. 114, 146 A. 641 (1929)',
    jurisdiction: 'New Hampshire, United States',
    court: 'Supreme Court of New Hampshire',
    year: 1929,
    facts: 'George Hawkins, a young man from Grafton County, New Hampshire, had a scarred hand resulting from a childhood accident involving an electrical wire. Dr. Edward McGee, a surgeon who wished to experiment with skin grafting techniques, repeatedly solicited Hawkins and his father, offering to restore the hand to a perfect condition. McGee assured the Hawkins family that he would make the hand "one hundred percent perfect" and that the surgery would take only a few days with a short hospital stay. Relying on these assurances, Hawkins consented to the surgery, during which McGee grafted skin taken from Hawkins\'s chest onto his palm. The result was disastrous: rather than being improved, Hawkins\'s hand became worse, covered in thick, hairy skin from the chest graft and functioning less well than before the operation. Hawkins brought suit against McGee for breach of contract, arguing that McGee\'s promises amounted to a contractual guarantee of a specific result.',
    keyLegalIssues: [
      'Whether a physician\'s pre-operative assurances can constitute a binding contractual guarantee of a specific outcome',
      'The proper measure of expectation damages in a contract for services',
      'Distinction between contract damages and tort damages in medical malpractice context',
      'Whether "pain and suffering" is a proper element of contract damages',
    ],
    plaintiffArguments: 'Hawkins argued that Dr. McGee\'s repeated and emphatic assurances that the surgery would produce a "one hundred percent perfect" hand amounted to an enforceable contractual promise to achieve a specific result, not merely a promise to exercise professional care. He contended that he had relied on this guarantee in consenting to the surgery and was entitled to the benefit of the bargain he struck, meaning the difference in value between the promised perfect hand and the damaged hand he was left with after surgery. Hawkins further argued that he was entitled to damages representing not merely the cost of the operation but the full extent of his loss measured against what was promised.',
    defendantArguments: 'McGee argued that his pre-operative statements were no more than the ordinary optimistic assurances a physician gives to encourage a patient to undergo a beneficial procedure, and that they could not be construed as a contractual guarantee of a perfect result. He maintained that the appropriate standard for a surgeon is one of reasonable care and skill, not a warranty of outcome, and that the relationship was governed by tort law principles rather than contract. McGee also disputed the proper measure of damages, contending that the jury instruction allowing recovery for pain and suffering and other losses went beyond what contract law permits.',
    proceduralHistory: 'Hawkins brought suit in the superior court of Grafton County, New Hampshire, pleading both contract and tort theories. The jury returned a verdict for Hawkins but on a damages measure that included elements the court found improper. The case was appealed to the Supreme Court of New Hampshire, which affirmed liability but ordered a new trial on damages to apply the correct contractual measure of recovery — expectation damages calculated as the difference between the value of a perfect hand and the value of the hand as it existed after surgery.',
    finalDecision: 'The Supreme Court of New Hampshire affirmed that Dr. McGee\'s assurances constituted an enforceable contract to produce a specific result and that Hawkins was entitled to the benefit of the bargain. The court held that the correct measure of damages was the difference between the value of a perfect hand as promised and the value of the hand in its post-operative condition, plus any expenditures reasonably made in reliance on the contract. The court ordered a new trial solely on the issue of damages, rejecting the inclusion of pain and suffering as a contract damages element.',
    judicialReasoning: 'Chief Justice Peaslee\'s opinion drew a sharp distinction between the measure of damages in tort — which aims to restore the plaintiff to the position before the wrong — and the measure of damages in contract — which aims to give the plaintiff the benefit of the bargain that was promised. Because McGee had promised a perfect hand, Hawkins\'s expectation interest was measured as the difference between that promised condition and the actual post-operative state of his hand, not merely the pre-operative state. The court held that pain and suffering experienced during and after surgery is not a proper element of contract damages, as contract law does not ordinarily compensate for emotional or physical distress unless it was within the contemplation of the parties at the time of contracting. The opinion established New Hampshire as a state clearly endorsing the expectation interest as the appropriate goal of contract damages. The case is also significant for recognizing that a physician can, by sufficiently definite and unequivocal language, undertake a contractual obligation to achieve a particular result, going beyond the ordinary duty of care in negligence.',
    legalStandards: [
      'Expectation damages as the proper measure of recovery for breach of contract',
      'Benefit-of-the-bargain measure: difference between promised value and actual value received',
      'Physician warranties of result as enforceable contractual commitments',
      'Pain and suffering generally not recoverable as contract damages absent special circumstances',
    ],
    keyPrecedents: [
      'Sullivan v. O\'Connor (1973) — Massachusetts applying similar expectation/reliance analysis in medical contracts',
      'Restatement (Second) of Contracts § 344 — purposes of contract remedies',
      'Fuller & Perdue, The Reliance Interest in Contract Damages (1936) — foundational academic framework',
    ],
    evidenceAnalysis: 'The testimony of Hawkins and his father regarding the frequency and definiteness of McGee\'s pre-operative assurances was the critical evidence establishing the existence of a contractual guarantee. Expert medical testimony was introduced to establish the condition of the hand before surgery, the condition after surgery, and the value of a perfect hand for the purposes of computing expectation damages. The hairy, thick skin resulting from the chest graft was itself vivid physical evidence of the extent to which the promised result was not achieved.',
    alternativeOutcomes: 'Had the court found McGee\'s statements to be mere puffery or ordinary medical optimism rather than a guarantee, Hawkins would have been limited to a negligence theory requiring proof of a deviation from the standard of care, which might have been more difficult to establish. If the court had applied a reliance rather than expectation measure of damages, Hawkins would have recovered only his expenditures in connection with the surgery and not the full difference between the promised and actual condition of his hand.',
    lessonsLearned: [
      'Physicians and other professionals must be careful that pre-engagement assurances are not so definite as to constitute contractual warranties of result',
      'Contract damages are measured by the benefit of the bargain, not the restoration of the plaintiff to the pre-contract position',
      'Pain and suffering is generally not compensable under contract law, distinguishing it from tort remedies',
      'Written professional service agreements should clearly disclaim any guarantee of outcome to avoid warranty liability',
    ],
    bestPractices: [
      'Professionals should use written engagement letters that clearly state the scope of services and disclaim guarantees of specific results',
      'Oral assurances made during sales or solicitation of business should be carefully worded to avoid creating warranty obligations',
      'Contracts for services should specify the standard of performance (reasonable care) rather than a particular outcome',
      'Damages provisions in service contracts should expressly limit recoverable losses to defined categories',
    ],
    significance: 'Hawkins v. McGee is the archetypal American contracts case for teaching the expectation interest in damages, and it is famous in legal education for the concept of the "hairy hand" and the "perfect hand" as illustrations of the benefit-of-the-bargain principle. The case demonstrates with unusual clarity the difference between the contract goal of putting the plaintiff in the position promised and the tort goal of restoring the plaintiff to the pre-wrong position. It also stands as a cautionary tale for professionals about the legal consequences of definitive pre-service assurances, establishing that sufficiently emphatic guarantees of result can be enforced as contracts regardless of professional norms. The decision has been widely followed for the proposition that expectation damages, not reliance damages, are the default measure of contract recovery. Its influence endures in first-year contracts curricula and in the drafting of professional services agreements throughout the United States.',
    outcome: 'Plaintiff Victory (new trial on damages)',
    parties: [
      {
        name: 'George Hawkins',
        role: 'PLAINTIFF',
        description: 'Patient who underwent a skin-graft operation based on the surgeon\'s guarantee of a perfect result',
      },
      {
        name: 'Dr. Edward McGee',
        role: 'DEFENDANT',
        description: 'Surgeon who repeatedly assured Hawkins that the skin-graft operation would produce a perfect hand',
      },
    ],
  },
  {
    litigationSlug: 'commercial',
    name: 'ProCD, Inc. v. Zeidenberg',
    citation: '86 F.3d 1447 (7th Cir. 1996)',
    jurisdiction: 'Federal — Seventh Circuit, United States',
    court: 'United States Court of Appeals for the Seventh Circuit',
    year: 1996,
    facts: 'ProCD, Inc. compiled a massive database of telephone listings from more than 3,000 telephone directories and sold it on CD-ROM under the brand name SelectPhone. The software was sold in shrink-wrapped packages that contained a notice that use was governed by license terms printed inside the box and displayed on the screen during installation. Matthew Zeidenberg purchased a consumer version of SelectPhone and, despite being presented with the license agreement that restricted the data to personal, non-commercial use, proceeded to extract the data and make it available to the public through a website for a fee. ProCD brought suit against Zeidenberg for breach of the shrink-wrap license agreement and sought injunctive relief. The central legal question was whether a license agreement that the buyer does not see before purchase — the terms appearing only inside the box and on the computer screen after opening — could be enforceable as a binding contract.',
    keyLegalIssues: [
      'Whether shrink-wrap license agreements are enforceable as binding contracts despite the buyer not reading terms before purchase',
      'Whether terms inside a product package that appear after purchase can become part of the contract',
      'Preemption of state contract law by the Copyright Act with respect to database licensing',
      'Whether UCC Article 2 permits contract terms to be disclosed after the initial transaction',
    ],
    plaintiffArguments: 'ProCD argued that shrink-wrap licenses are a widely accepted and commercially necessary form of contract in the software and information industries, and that buyers are put on notice that the product is subject to license terms by language on the outside of the package. It contended that because Zeidenberg had the opportunity to read the license on screen during installation and return the product if he disagreed with the terms, his decision to proceed with installation constituted acceptance of the full license. ProCD maintained that enforcing the shrink-wrap license was essential to the economic viability of the information-product market, as the company had invested millions of dollars compiling the database and needed licensing restrictions to price-discriminate between consumer and commercial markets.',
    defendantArguments: 'Zeidenberg argued that a contract is formed at the moment of purchase and that terms appearing only after the sale are mere post-contract documents that cannot bind a buyer who had no opportunity to review them before agreeing to pay. He contended that the Copyright Act preempted any state contract claim over a database of uncopyrightable facts, because to enforce such a license would give the licensor copyright-like control over public domain information. Zeidenberg also argued that UCC Article 2 required all material terms to be part of the agreement at the time of contracting and that terms disclosed only after purchase failed that requirement.',
    proceduralHistory: 'ProCD brought suit in the United States District Court for the Western District of Wisconsin, which ruled in favor of Zeidenberg, holding that the shrink-wrap license was not enforceable because the terms were not available to the buyer before purchase. ProCD appealed, and the Seventh Circuit Court of Appeals reversed the district court\'s decision in a widely influential opinion by Judge Frank Easterbrook.',
    finalDecision: 'The Seventh Circuit reversed the district court and held that the shrink-wrap license was an enforceable contract. Judge Easterbrook reasoned that the sale of software packaged with a license is an offer to contract on the stated terms, and that the buyer accepts by using the software after having had the opportunity to read and reject the terms. The court further held that the Copyright Act did not preempt the license because contract rights are qualitatively different from copyright rights and impose obligations only on the contracting party rather than the world at large.',
    judicialReasoning: 'Judge Easterbrook\'s opinion analogized the shrink-wrap license transaction to other common commercial arrangements in which buyers receive full contract terms only after an initial payment, such as insurance policies delivered after premium payment or airline tickets with conditions printed on the back. He reasoned that enforcing licenses with deferred disclosure is commercially necessary and that the legal system routinely gives effect to such arrangements when the buyer has a meaningful opportunity to review and reject the terms. The court applied UCC Article 2 and found that it permits contracts to be formed in stages, with terms filling in over time as long as the overall arrangement reflects a genuine agreement. On preemption, Easterbrook held that a contract right — which binds only the parties — is not "equivalent" to a copyright right — which binds the world — and therefore state contract law enforcement of the license was not displaced by federal copyright law. The opinion is a landmark in information commerce law, recognizing that digital-age transactions often require deferred disclosure of terms and that courts should facilitate rather than frustrate such commercially reasonable arrangements.',
    legalStandards: [
      'Shrink-wrap and click-wrap license enforceability under UCC Article 2',
      'Offer and acceptance in rolling or layered contracts',
      'Copyright Act Section 301 preemption of state law contract claims',
      'Extra element test distinguishing contract rights from copyright-equivalent rights',
    ],
    keyPrecedents: [
      'Step-Saver Data Systems, Inc. v. Wyse Technology (3d Cir. 1991) — earlier skepticism of shrink-wrap licenses',
      'Hill v. Gateway 2000, Inc. (7th Cir. 1997) — Easterbrook extending ProCD to arbitration clauses in product boxes',
      'Specht v. Netscape Communications Corp. (2d Cir. 2002) — limits on online contract enforceability when notice is inadequate',
    ],
    evidenceAnalysis: 'The record established that ProCD\'s package prominently stated that use was subject to a license agreement and that the license terms were fully displayed on screen during the installation process, giving Zeidenberg actual notice of the restriction before he completed installation. Evidence also showed that ProCD sold different versions of SelectPhone at different price points for consumer and commercial users, demonstrating the economic rationale for the licensing restrictions. The court found no evidence that Zeidenberg had been unable to read or understand the license before choosing to proceed with installation and commercial exploitation of the data.',
    alternativeOutcomes: 'Had the Seventh Circuit affirmed the district court, shrink-wrap and click-wrap licenses throughout the software and information industries would have been rendered unenforceable, potentially destroying the economic basis for distributing commercial databases and software. If the Copyright Act preemption argument had succeeded, companies could not have used contract law to restrict the use of uncopyrightable factual compilations, significantly undermining the information-product market.',
    lessonsLearned: [
      'License terms disclosed after purchase can be enforceable if the buyer has a reasonable opportunity to review and reject them',
      'Contract rights are not preempted by federal copyright law because they bind only the parties, not the world',
      'Commercial necessity is a relevant consideration in the enforceability of standard-form license agreements',
      'Software and information-product companies can use license agreements to segment consumer and commercial markets',
    ],
    bestPractices: [
      'Provide clear notice on product packaging that use is subject to a license agreement',
      'Give buyers a genuine opportunity to review license terms and return the product if they disagree',
      'Use click-through acceptance mechanisms to create a clear record of the buyer\'s assent to license terms',
      'Distinguish between consumer and commercial licenses in product documentation and pricing',
    ],
    significance: 'ProCD v. Zeidenberg is one of the most influential commercial law decisions of the digital age, providing the legal foundation for shrink-wrap and click-wrap licensing that is now ubiquitous in the software and internet industries. The decision resolved significant uncertainty about whether licenses disclosed after purchase could be enforced, and its affirmative answer enabled the modern model of software and digital content distribution. Judge Easterbrook\'s opinion is also a landmark in the law of copyright preemption, providing a clear analytical framework — the "extra element" test — for distinguishing enforceable contract claims from copyright-equivalent rights. The case has been followed, distinguished, and debated in dozens of subsequent decisions involving online terms of service, software licenses, and e-commerce agreements. It remains essential reading for anyone involved in the drafting or enforcement of standard-form digital agreements.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'ProCD, Inc.',
        role: 'PLAINTIFF',
        counsel: 'Represented by counsel in the Western District of Wisconsin and Seventh Circuit',
        description: 'Compiler and licensor of the SelectPhone telephone directory database on CD-ROM',
      },
      {
        name: 'Matthew Zeidenberg',
        role: 'DEFENDANT',
        description: 'Consumer who extracted database contents and made them commercially available in violation of the shrink-wrap license',
      },
    ],
  },
  {
    litigationSlug: 'commercial',
    name: 'Carlill v. Carbolic Smoke Ball Co.',
    citation: '[1893] 1 QB 256 (CA)',
    jurisdiction: 'England and Wales',
    court: 'Court of Appeal',
    year: 1893,
    facts: 'The Carbolic Smoke Ball Company placed an advertisement in the Pall Mall Gazette offering to pay £100 to any person who used its product — the Carbolic Smoke Ball — three times daily for two weeks according to the printed directions and thereafter contracted influenza, colds, or any diseases caused by taking cold. The advertisement stated that the company had deposited £1,000 with the Alliance Bank to show its sincerity. Louisa Carlill, a London resident, purchased a Carbolic Smoke Ball, used it as directed for the prescribed period, and nevertheless contracted influenza. She claimed the £100 reward, which the Carbolic Smoke Ball Company refused to pay, arguing that the advertisement was not a legally binding offer capable of acceptance and that, even if it were, Carlill had not given any consideration or communicated her acceptance to the company. Mrs. Carlill brought suit to recover the promised £100.',
    keyLegalIssues: [
      'Whether an advertisement addressed to the world at large can constitute a binding offer capable of acceptance',
      'Whether performance of the advertised conditions constitutes valid acceptance of an offer',
      'Whether the performance of act-as-acceptance requires prior notification to the offeror',
      'Whether the promise of a reward constitutes sufficient consideration to support a contract',
    ],
    plaintiffArguments: 'Carlill argued that the advertisement was a clear and unambiguous offer made to the general public, and that she had accepted it by purchasing the product and using it precisely as directed — thereby performing exactly the conditions the company had stipulated. She maintained that the deposit of £1,000 at the Alliance Bank, as stated in the advertisement, demonstrated that the company intended to be legally bound and was not merely making an unenforceable promise. Carlill contended that notification of acceptance was unnecessary for an offer of this kind because the very nature of the offer contemplated acceptance by performance rather than by communication, and that requiring prior notification would defeat the commercial purpose of the advertisement.',
    defendantArguments: 'The Carbolic Smoke Ball Company argued that the advertisement was a mere puff or sales promotion, not a genuine offer capable of giving rise to a binding contract, because no reasonable business could have intended to bind itself to the world at large. The company also argued that Carlill had not communicated her acceptance to the offeror before performing the conditions, as required by the general rule of contract law that acceptance must be communicated to be effective. The company further contended that there was no consideration for the promise because Carlill\'s purchase of the Smoke Ball was a transaction with the retailer, not with the company itself, and that her use of the product was not a detriment she incurred at the company\'s request.',
    proceduralHistory: 'Carlill brought an action in the Queen\'s Bench Division, where she obtained judgment in her favor for the £100 promised in the advertisement. The Carbolic Smoke Ball Company appealed the decision to the Court of Appeal, which heard arguments on the issues of offer, acceptance, consideration, and certainty of terms. The Court of Appeal unanimously dismissed the appeal and affirmed the judgment for Mrs. Carlill.',
    finalDecision: 'The Court of Appeal unanimously held that the advertisement was a binding offer to the world at large, that Mrs. Carlill had accepted it by performing the stipulated conditions, and that there was good consideration for the company\'s promise in Carlill\'s purchase and use of the product as directed. The court dismissed the appeal and affirmed the judgment awarding Carlill £100. The company\'s various technical defenses — including lack of communication of acceptance, vagueness of the promise, and absence of consideration — were each rejected.',
    judicialReasoning: 'Lord Justice Lindley held that an offer made to the world, in contrast to an offer to a specific individual, can be accepted by any member of the public who performs the stipulated conditions, and that the offeror in such cases dispenses with the need for communication of acceptance by the very terms of the offer. Lord Justice Bowen famously held that the deposit of money at the Alliance Bank was inconsistent with the advertisement being a mere puff: a company does not put £1,000 in a bank merely to advertise, and the language of the advertisement was specific, definite, and not vague. All three judges agreed that consideration was present because Carlill had incurred the trouble and inconvenience of using the product as directed, and had exposed herself to discomfort in reliance on the company\'s promise, which constituted a detriment sufficient to support a contract. The court also addressed the argument about certainty, finding that although the conditions referred to "influenza" and kindred illnesses, the terms were sufficiently clear to be enforceable. The decision established the foundational principle that unilateral contracts — offers accepted by performance — are binding in English law.',
    legalStandards: [
      'Unilateral contract formation — offer accepted by performance rather than promise',
      'Offers to the world at large (offers to all and sundry)',
      'Communication of acceptance may be dispensed with where the offer contemplates acceptance by act',
      'Consideration in the form of inconvenience or detriment incurred in reliance on an offer',
      'Puffery versus binding contractual promise — intent to be legally bound',
    ],
    keyPrecedents: [
      'Williams v. Carwardine (1833) — earlier English authority on reward offers and acceptance by performance',
      'R v. Clarke (1927) — High Court of Australia on knowledge of offer as requirement for acceptance',
      'Lefkowitz v. Great Minneapolis Surplus Store (1957) — American analog on advertisement-as-offer',
    ],
    evidenceAnalysis: 'The text of the advertisement was the central piece of evidence, and the courts analyzed it closely to determine whether it bore the hallmarks of a genuine offer or a mere sales puff. The reference to a deposit of £1,000 at the Alliance Bank was treated as compelling evidence of genuine intent to be bound, as a company would not incur that expense unless it intended the promise seriously. Evidence of Carlill\'s purchase of the product and her use of it for the prescribed period according to directions was uncontested and provided the factual basis for finding that she had performed the conditions required for acceptance.',
    alternativeOutcomes: 'Had the court found the advertisement to be a mere puff, the entire category of reward-by-performance contracts would have been left without legal protection, undermining the enforceability of prize offers, satisfaction guarantees, and similar commercial promises that are commonplace in trade. If the court had required prior communication of acceptance, the practical effect would have been to make offers to the general public nearly impossible to enforce, as individual notification by each potential acceptor would be commercially unworkable.',
    lessonsLearned: [
      'Advertisements containing specific, measurable conditions and a promise of reward can be binding offers to the world at large',
      'In unilateral contracts, acceptance is accomplished by performance and notification to the offeror is generally not required',
      'Language in an advertisement indicating that money has been deposited or that the company is "sincere" can be treated as evidence of intent to be legally bound',
      'Businesses should treat advertising copy as potentially creating legal obligations and review it for unintended contractual commitments',
    ],
    bestPractices: [
      'Review all advertising and promotional materials for language that could be construed as a binding offer or warranty',
      'Include clear disclaimers or terms and conditions in promotional campaigns to define the scope of any promise',
      'Reward-based promotions should specify all eligibility conditions, caps on claims, and duration in clear, unambiguous language',
      'Deposit or escrow arrangements referenced in promotional material can be treated as evidence of intent to be bound and should be used deliberately',
    ],
    significance: 'Carlill v. Carbolic Smoke Ball Co. is one of the most celebrated and frequently cited cases in the common law of contracts, establishing the doctrine of the unilateral contract as a binding legal form and resolving fundamental questions about offer and acceptance that remain authoritative more than 130 years later. The case is the leading authority for the proposition that an offer to the world at large can be accepted by performance, without any need to communicate acceptance to the offeror, and that the offeror implicitly waives this requirement by the terms of a public offer. It also settled the law on consideration in unilateral contracts, confirming that the inconvenience or detriment suffered by the offeree in performing the conditions is sufficient to support the contract. The decision has profound implications for modern commercial practices including warranty disclaimers, consumer promotions, loyalty programs, and satisfaction guarantees, all of which trace their legal analysis to this Victorian authority. Carlill v. Carbolic Smoke Ball Co. is studied in every common-law jurisdiction and stands as a monument to the principle that courts will hold commercial actors to their public promises.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Louisa Carlill',
        role: 'PLAINTIFF',
        description: 'Consumer who purchased and used the Carbolic Smoke Ball as directed and subsequently contracted influenza',
      },
      {
        name: 'Carbolic Smoke Ball Company',
        role: 'DEFENDANT',
        description: 'Manufacturer and advertiser of the Carbolic Smoke Ball who refused to pay the promised £100 reward',
      },
    ],
  },
];

export default cases;
