import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'criminal-defense',
    name: 'Gideon v. Wainwright',
    citation: '372 U.S. 335 (1963)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1963,
    isFeatured: true,
    facts: 'Clarence Earl Gideon was charged in Florida state court with felony breaking and entering of a poolroom in 1961. At trial, Gideon appeared without counsel and requested that the court appoint an attorney for him because he could not afford one. The trial judge denied the request, stating that under Florida law counsel could only be appointed in capital cases. Gideon represented himself, was convicted, and sentenced to five years in prison. From his cell, Gideon filed a handwritten habeas corpus petition with the Supreme Court, arguing that the denial of counsel violated the Sixth and Fourteenth Amendments.',
    keyLegalIssues: [
      'Whether the Sixth Amendment right to counsel applies to state criminal proceedings through the Fourteenth Amendment',
      'Whether Betts v. Brady (1942) should be overruled',
      'Whether an indigent felony defendant has a constitutional right to appointed counsel',
      'Whether the denial of appointed counsel constitutes a fundamentally unfair trial',
    ],
    plaintiffArguments: 'Gideon argued that the Sixth Amendment guarantee of the right to counsel is a fundamental right essential to a fair trial, and that the Due Process Clause of the Fourteenth Amendment makes this right obligatory on the states. He contended that without counsel, an untrained layperson cannot adequately navigate complex legal procedures, cross-examine witnesses, or present a proper defense. He also argued that the Court\'s prior ruling in Betts v. Brady was incorrect and should be reconsidered.',
    defendantArguments: 'Florida argued that under Betts v. Brady, states were not required to furnish counsel in all felony cases unless special circumstances were present. The state maintained that appointment of counsel should be left to state discretion based on specific circumstances, and that the federal government should not impose a blanket requirement on state criminal procedures. Florida contended that Gideon\'s case presented no special circumstances warranting appointed counsel.',
    proceduralHistory: 'Gideon was tried and convicted in the Circuit Court of Bay County, Florida in 1961. He appealed to the Florida Supreme Court, which denied relief citing Betts v. Brady. Gideon then filed a petition for certiorari with the U.S. Supreme Court, which granted the petition and appointed Abe Fortas, later a Supreme Court Justice, to argue on Gideon\'s behalf.',
    finalDecision: 'The Supreme Court unanimously reversed Gideon\'s conviction in a 9-0 decision authored by Justice Hugo Black. The Court held that the Sixth Amendment right to counsel is a fundamental right incorporated against the states via the Fourteenth Amendment, and that Betts v. Brady was overruled. Gideon was retried with appointed counsel and acquitted.',
    judicialReasoning: 'Justice Black, writing for the Court, emphasized that the right to counsel is fundamental and essential to a fair trial in an adversarial system of justice. The Court reasoned that lawyers are not luxuries but necessities in a system that prosecutes individuals for serious crimes. Black noted the inconsistency that governments spend vast resources to prosecute defendants, yet defendants without means had no comparable assistance. The Court observed that every state and the federal government already provided counsel in at least some circumstances, reflecting a broad consensus that counsel is indispensable. The decision recognized that an untrained defendant, however intelligent, lacks the skills to contest complex legal proceedings. By incorporating the Sixth Amendment right through the Fourteenth, the Court established a floor of constitutional protection applicable in all state felony proceedings.',
    legalStandards: [
      'Sixth Amendment right to counsel',
      'Fourteenth Amendment Due Process Clause incorporation',
      'Fundamental fairness standard',
      'Selective incorporation doctrine',
    ],
    keyPrecedents: [
      'Betts v. Brady, 316 U.S. 455 (1942) — overruled',
      'Powell v. Alabama, 287 U.S. 45 (1932)',
      'Johnson v. Zerbst, 304 U.S. 458 (1938)',
      'Palko v. Connecticut, 302 U.S. 319 (1937)',
    ],
    evidenceAnalysis: 'The evidentiary record focused on the circumstances of Gideon\'s trial without counsel, demonstrating that he was unable to conduct proper cross-examination and lacked the legal knowledge to raise substantive defenses. At his retrial with counsel, Gideon\'s attorney effectively cross-examined the prosecution\'s key witness and introduced evidence of the witness\'s own motive to lie, resulting in acquittal — illustrating precisely how the absence of counsel had undermined the original verdict.',
    alternativeOutcomes: 'Had the Court upheld Betts v. Brady, states would have retained discretion to deny appointed counsel in non-capital cases without special circumstances, leaving millions of indigent defendants to navigate serious criminal proceedings without legal representation. A narrower ruling might have found special circumstances in Gideon\'s specific case without creating a categorical right, which would have provided him relief while leaving the broader question unresolved.',
    lessonsLearned: [
      'Effective assistance of counsel is the cornerstone of the adversarial criminal justice system',
      'Constitutional rights guaranteed by the Bill of Rights apply to state proceedings through the Fourteenth Amendment',
      'The quality of legal representation directly affects trial outcomes and the reliability of verdicts',
      'Systemic access to counsel is essential to justice, not merely a benefit for those who can afford it',
    ],
    bestPractices: [
      'Public defender offices must be adequately funded to provide meaningful representation',
      'Defense counsel should conduct thorough pre-trial investigation and witness preparation',
      'Courts must ensure prompt appointment of counsel at the earliest stage of proceedings',
      'Attorneys representing indigent clients must provide the same diligence as private counsel',
      'Defense teams should scrutinize witness credibility and motives as part of standard preparation',
    ],
    significance: 'Gideon v. Wainwright is one of the most consequential criminal procedure decisions in American history, fundamentally transforming the relationship between the state and accused individuals. The ruling prompted every state to establish or dramatically expand public defender systems and appointed counsel programs. It established that the right to counsel is not a privilege of wealth but a constitutional guarantee in all felony proceedings. The case spawned a network of public defender offices across the country and directly contributed to subsequent decisions extending the right to earlier stages of proceedings. The decision remains the foundational precedent for the Sixth Amendment right to counsel in state courts and is widely taught as an illustration of the Bill of Rights\' incorporation against the states.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Clarence Earl Gideon',
        role: 'PLAINTIFF',
        counsel: 'Abe Fortas (before Supreme Court)',
        description: 'Indigent defendant convicted of felony breaking and entering who petitioned pro se for certiorari',
      },
      {
        name: 'Louie L. Wainwright',
        role: 'DEFENDANT',
        counsel: 'Bruce R. Jacob (Florida Assistant Attorney General)',
        description: 'Director of the Florida Division of Corrections, representing the state\'s position against mandatory appointment of counsel',
      },
    ],
  },

  {
    litigationSlug: 'criminal-defense',
    name: 'Miranda v. Arizona',
    citation: '384 U.S. 436 (1966)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1966,
    facts: 'Ernesto Miranda was arrested in Phoenix, Arizona in 1963 and taken to a police interrogation room, where he was questioned for two hours without being informed of his right to an attorney or his right against self-incrimination. Miranda signed a written confession that included a pre-printed statement claiming the confession was made voluntarily and with full knowledge of his legal rights. Miranda was convicted of kidnapping and rape based substantially on the confession. The case was consolidated with three others presenting similar issues of custodial interrogation without prior warnings.',
    keyLegalIssues: [
      'Whether statements obtained during custodial interrogation without prior warnings are admissible under the Fifth Amendment privilege against self-incrimination',
      'Whether the inherently coercive nature of custodial interrogation requires prophylactic safeguards',
      'What procedural warnings law enforcement must give suspects before interrogation',
      'Whether the Sixth Amendment right to counsel attaches during pre-indictment interrogation',
    ],
    plaintiffArguments: 'Miranda argued that his confession was obtained in violation of the Fifth Amendment privilege against self-incrimination because he was not informed of his rights before interrogation. He contended that the inherently coercive atmosphere of custodial interrogation psychologically compels suspects to speak, making truly voluntary confessions impossible without prior warnings. Miranda\'s counsel argued that the right to counsel must attach at the moment of custodial interrogation, not merely at formal adversarial proceedings.',
    defendantArguments: 'Arizona argued that Miranda\'s confession was voluntary and that existing totality-of-the-circumstances analysis was sufficient to protect defendants\' rights. The state contended that mandatory warnings would unduly hamper law enforcement\'s ability to solve crimes and that Congress and state legislatures, not courts, should set interrogation rules. Arizona also argued that police interrogation manuals did not demonstrate systematic coercion sufficient to require categorical warnings.',
    proceduralHistory: 'Miranda was convicted in the Maricopa County Superior Court in 1963 and sentenced to twenty to thirty years on each count. The Arizona Supreme Court affirmed, finding the confession voluntary under the totality of circumstances. The U.S. Supreme Court granted certiorari and consolidated Miranda with Vignera v. New York, Westover v. United States, and California v. Stewart to address the custodial interrogation issue comprehensively.',
    finalDecision: 'Chief Justice Warren, writing for a 5-4 majority, held that the prosecution may not use statements from custodial interrogation unless it demonstrates the use of procedural safeguards to secure the Fifth Amendment privilege. The Court established that prior to interrogation, suspects must be informed of their right to remain silent, that statements may be used against them, their right to an attorney, and their right to appointed counsel if indigent. Miranda\'s conviction was reversed.',
    judicialReasoning: 'Chief Justice Warren analyzed police interrogation manuals to demonstrate the inherently compelling pressures of custodial interrogation, designed to overcome a suspect\'s will to resist. The Court concluded that without adequate safeguards, the process of in-custody interrogation contains inherently compelling pressures that undermine an individual\'s will to invoke the Fifth Amendment privilege. Warren reasoned that the right to counsel during interrogation reinforces the privilege against self-incrimination by enabling suspects to make informed choices. The majority emphasized that the warnings required were not novel, as the FBI already employed similar practices. The decision established a bright-line rule to provide certainty for law enforcement while protecting constitutional rights. Justices Harlan, Stewart, and White dissented vigorously, arguing the majority was imposing excessive restrictions on law enforcement based on speculative harms.',
    legalStandards: [
      'Fifth Amendment privilege against self-incrimination',
      'Sixth Amendment right to counsel during interrogation',
      'Custodial interrogation standard',
      'Waiver of Miranda rights — knowing, intelligent, and voluntary',
      'Prophylactic rule doctrine',
    ],
    keyPrecedents: [
      'Massiah v. United States, 377 U.S. 201 (1964)',
      'Escobedo v. Illinois, 378 U.S. 478 (1964)',
      'Bram v. United States, 168 U.S. 532 (1897)',
      'Dickerson v. United States, 530 U.S. 428 (2000) — reaffirming Miranda',
    ],
    evidenceAnalysis: 'The Court examined the written confession signed by Miranda and the record of the two-hour interrogation to assess voluntariness. The confession form stated it was given with full knowledge of legal rights, yet Miranda had not been informed of those rights. The Court also examined police interrogation manuals, including those published by law enforcement professional organizations, to document systematic techniques designed to psychologically overcome resistance, lending empirical support to the conclusion that custodial interrogation is inherently coercive.',
    alternativeOutcomes: 'A ruling upholding Miranda\'s conviction would have left the totality-of-circumstances test as the sole safeguard, resulting in continued uncertainty for both law enforcement and suspects. The Court could have adopted a narrower rule requiring counsel only after formal charges, avoiding the interrogation context entirely. Some commentators argued for a statutory framework rather than a constitutional mandate, which would have permitted legislative modification but lacked the constitutional floor that Miranda established.',
    lessonsLearned: [
      'Suspects must be clearly and promptly advised of their rights before any custodial interrogation begins',
      'A valid waiver of Miranda rights must be knowing, intelligent, and voluntary — not merely the absence of an assertion of rights',
      'Invocation of the right to remain silent or to counsel must be scrupulously honored',
      'Statements obtained in violation of Miranda are generally inadmissible in the prosecution\'s case-in-chief',
    ],
    bestPractices: [
      'Defense attorneys should move to suppress any statements obtained without proper Miranda warnings',
      'Investigators should administer complete and accurate warnings before all custodial interrogation',
      'Defense counsel should examine whether the client\'s waiver was truly knowing and voluntary given individual circumstances',
      'Attorneys should assess whether invocation of rights was equivocal and how police responded',
      'Records of interrogation, including audio and video, should be reviewed for compliance with Miranda requirements',
    ],
    significance: 'Miranda v. Arizona fundamentally reshaped American law enforcement practice by requiring police to advise suspects of their constitutional rights before interrogation. The "Miranda warnings" have become one of the most recognizable legal phrases in American culture, routinely depicted in news and entertainment. The decision generated extensive subsequent litigation refining when warnings are required, what constitutes custody, and what constitutes valid waiver. Though critics predicted it would cripple law enforcement, empirical studies found minimal impact on confession rates. The case remains central to criminal procedure doctrine and the relationship between the state\'s investigative power and individual constitutional rights.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Ernesto Arturo Miranda',
        role: 'PLAINTIFF',
        counsel: 'John J. Flynn',
        description: 'Defendant convicted of kidnapping and rape following a two-hour custodial interrogation without advisement of rights',
      },
      {
        name: 'State of Arizona',
        role: 'DEFENDANT',
        counsel: 'Gary K. Nelson (Arizona Attorney General\'s Office)',
        description: 'Prosecuting authority defending Miranda\'s conviction and the constitutionality of existing interrogation practices',
      },
    ],
  },

  {
    litigationSlug: 'criminal-defense',
    name: 'Mapp v. Ohio',
    citation: '367 U.S. 643 (1961)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1961,
    facts: 'On May 23, 1957, Cleveland police officers arrived at Dollree Mapp\'s home seeking a bombing suspect and allegedly looking for policy paraphernalia related to illegal gambling. When Mapp refused to admit officers without a warrant, they forcibly entered her home approximately three hours later. Officers showed Mapp a paper they claimed was a warrant, but no valid warrant was ever produced at trial. During the search, officers discovered obscene materials, and Mapp was prosecuted for possession of obscene materials under Ohio law. She was convicted despite the lack of a valid warrant and sentenced to an indefinite term at the Ohio Reformatory for Women.',
    keyLegalIssues: [
      'Whether evidence obtained through an unreasonable search and seizure in violation of the Fourth Amendment is admissible in state criminal proceedings',
      'Whether the exclusionary rule applies to the states through the Fourteenth Amendment',
      'Whether the Court\'s ruling in Wolf v. Colorado (1949) should be reconsidered with respect to the remedy for Fourth Amendment violations',
      'Whether state courts must exclude illegally seized evidence to enforce the constitutional guarantee against unreasonable searches',
    ],
    plaintiffArguments: 'Mapp argued that the search of her home was conducted without a valid warrant and violated her Fourth Amendment rights. Although the case was briefed primarily on First Amendment obscenity grounds, the American Civil Liberties Union\'s amicus brief argued forcefully for application of the exclusionary rule to the states. Defense counsel contended that Wolf v. Colorado had been undermined by subsequent decisions and that without the exclusionary rule, the Fourth Amendment protection against unreasonable searches was illusory in state proceedings.',
    defendantArguments: 'Ohio argued that Wolf v. Colorado permitted states to choose their own remedies for Fourth Amendment violations other than exclusion of evidence. The state maintained that civil remedies against officers, criminal prosecution of offending officers, and other state-law mechanisms were adequate alternatives to the exclusionary rule. Ohio contended that imposing the federal exclusionary rule on states would unduly impair effective law enforcement and was not constitutionally required.',
    proceduralHistory: 'Mapp was convicted in the Cuyahoga County Court of Common Pleas in 1958. The Ohio Supreme Court affirmed the conviction, acknowledging the search was unlawful but holding that the exclusionary rule did not apply to the states under Wolf. The U.S. Supreme Court granted certiorari primarily to consider First Amendment issues, but ultimately decided the case on Fourth and Fourteenth Amendment grounds.',
    finalDecision: 'Justice Clark, writing for a 6-3 majority, overruled Wolf v. Colorado in part and held that the exclusionary rule is constitutionally required and applicable to the states through the Fourteenth Amendment. The Court vacated Mapp\'s conviction and remanded. The decision established that evidence obtained in violation of the Fourth Amendment cannot be used in state criminal proceedings.',
    judicialReasoning: 'Justice Clark reasoned that the Fourth Amendment\'s right of privacy would be without meaning if it could be violated with impunity, and that the only effective deterrent against unconstitutional police searches is exclusion of the fruits of those searches. The majority concluded that without the exclusionary rule, the Fourth Amendment would be a form of words, valueless and undeserving of mention in a perpetual charter of inestimable human liberties. The Court rejected the premise of Wolf that alternative remedies were sufficient, noting that those remedies had proven ineffective over the twelve years since Wolf was decided. Clark emphasized the imperative of judicial integrity — courts must not become accomplices in willful disobedience of the Constitution by admitting illegally seized evidence. The decision also sought to create uniformity between federal and state standards, avoiding the anomaly that federal officers are bound by the exclusionary rule while state officers dealing with similar conduct are not.',
    legalStandards: [
      'Fourth Amendment prohibition on unreasonable searches and seizures',
      'Exclusionary rule as constitutional mandate',
      'Fourteenth Amendment incorporation of Fourth Amendment rights',
      'Fruit of the poisonous tree doctrine',
      'Good faith exception analysis (subsequent development)',
    ],
    keyPrecedents: [
      'Weeks v. United States, 232 U.S. 383 (1914) — establishing federal exclusionary rule',
      'Wolf v. Colorado, 338 U.S. 25 (1949) — overruled in part',
      'Elkins v. United States, 364 U.S. 206 (1960)',
      'United States v. Leon, 468 U.S. 897 (1984) — good faith exception',
    ],
    evidenceAnalysis: 'The evidentiary record was notable for the absence of a valid warrant — officers displayed a paper to Mapp but never produced a warrant in court, and the trial court found no valid warrant existed. The obscene materials seized were the sole basis for conviction, making the admissibility question dispositive. The Court examined the record from Wolf-era states to assess whether alternative remedies had effectively deterred Fourth Amendment violations, finding the empirical evidence weighed heavily in favor of the exclusionary rule.',
    alternativeOutcomes: 'Affirming on Wolf grounds would have left state defendants without the exclusionary remedy, producing continued disparity between federal and state courts and effectively allowing state officers to engage in unconstitutional searches without meaningful sanction. A narrower ruling on First Amendment grounds — the original basis for certiorari — would have avoided the Fourth Amendment question entirely. The Court could also have ruled more narrowly that the particular severity of this warrantless intrusion required exclusion without broadly overruling Wolf.',
    lessonsLearned: [
      'The exclusionary rule is the primary mechanism for enforcing the Fourth Amendment\'s guarantee against unreasonable searches and seizures',
      'Defense counsel must identify and timely file motions to suppress evidence obtained through illegal searches',
      'The absence of a valid warrant presumptively renders a search unconstitutional, placing the burden on the government to justify the intrusion',
      'The good faith exception limits but does not eliminate the exclusionary rule\'s reach',
    ],
    bestPractices: [
      'Defense attorneys should review all search warrants for facial validity, particularity, and probable cause',
      'Suppression motions must identify every item of evidence seized and the specific Fourth Amendment violation',
      'Counsel should investigate the manner in which searches were conducted, including whether any consent was truly voluntary',
      'Defense teams should examine the chain of custody of seized evidence for additional grounds to challenge admissibility',
      'Attorneys should consider whether the inevitable discovery or independent source doctrines may limit suppression arguments',
    ],
    significance: 'Mapp v. Ohio represents one of the Warren Court\'s most consequential criminal procedure decisions, applying the exclusionary rule uniformly to all American courts. The decision effectively nationalized Fourth Amendment enforcement by denying governments the benefit of evidence obtained through unconstitutional searches. It prompted substantial changes in police training and supervision to avoid suppression of evidence. The ruling generated decades of refinement through exceptions — good faith, inevitable discovery, independent source, attenuation — but the core holding remains intact. Mapp is consistently cited as a landmark in the incorporation of the Bill of Rights against the states and in the development of modern criminal defense practice.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Dollree Mapp',
        role: 'PLAINTIFF',
        counsel: 'A.L. Kearns; Walter L. Greene',
        description: 'Cleveland resident convicted of possessing obscene materials discovered during a warrantless police search of her home',
      },
      {
        name: 'State of Ohio',
        role: 'DEFENDANT',
        counsel: 'Gertrude Bauer Mahon (Cuyahoga County Prosecutor\'s Office)',
        description: 'Prosecuting authority defending both Mapp\'s conviction and the state\'s authority to admit evidence seized without a valid warrant',
      },
    ],
  },

  {
    litigationSlug: 'criminal-defense',
    name: 'Brady v. Maryland',
    citation: '373 U.S. 83 (1963)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1963,
    facts: 'John Brady and a companion, Donald Boblit, were convicted separately for the murder of William Brooks in Maryland in 1958. Brady admitted his participation in the crime but claimed that Boblit had actually committed the killing, seeking to avoid the death penalty. Prior to trial, Brady\'s attorney requested that the prosecution allow him to examine all of Boblit\'s extrajudicial statements. The prosecution complied with the request except that it withheld one statement in which Boblit admitted he had actually committed the killing. Brady was convicted and sentenced to death. The suppressed statement was discovered only after trial.',
    keyLegalIssues: [
      'Whether the suppression of material evidence favorable to the defendant by the prosecution violates due process',
      'Whether due process requires disclosure of exculpatory evidence even when the prosecution acts in good faith',
      'What standard of materiality applies to suppressed evidence for purposes of determining whether a new trial is required',
      'Whether the Brady rule applies regardless of prosecutorial intent to suppress',
    ],
    plaintiffArguments: 'Brady argued that the prosecution\'s suppression of Boblit\'s confession admitting to the actual killing constituted a violation of due process that rendered his trial fundamentally unfair. His counsel contended that evidence directly bearing on which participant committed the killing was clearly material to both guilt and, more importantly, to the appropriate punishment — specifically whether Brady should receive the death penalty. Brady maintained that the withheld statement would have supported his claim that he was not the triggerman.',
    defendantArguments: 'Maryland argued that Brady had admitted his participation in the crime and that the withheld statement related primarily to punishment rather than guilt, making it less than fully exculpatory. The state contended that the omission, while improper, did not rise to the level of a constitutional due process violation requiring a new trial on guilt. Maryland also argued that Brady\'s counsel had been given access to a substantial portion of Boblit\'s statements and that the single omission did not fundamentally alter the fairness of the proceedings.',
    proceduralHistory: 'Brady was tried and convicted of first-degree murder in the Circuit Court for Anne Arundel County, Maryland in 1958, and sentenced to death. The Maryland Court of Appeals affirmed the conviction but ordered a new trial on the issue of punishment only, finding that the suppressed evidence was material to sentencing. Both Brady and the state filed petitions for certiorari, and the Supreme Court granted review to address the constitutional due process question.',
    finalDecision: 'Justice Douglas, writing for the Court, held in an 8-1 decision that the suppression by the prosecution of evidence favorable to an accused upon request violates due process where the evidence is material either to guilt or to punishment. The Court affirmed the Maryland Court of Appeals\' order granting a new trial on sentencing only, agreeing that the withheld statement was material to punishment but not to the guilt phase given Brady\'s own admission of participation.',
    judicialReasoning: 'Justice Douglas grounded the Brady rule in the principle that society wins not only when the guilty are convicted but when criminal trials are fair. The Court reasoned that the prosecutor is the representative not of an ordinary party but of a sovereignty whose obligation is to govern impartially and whose interest in a criminal prosecution is not that it shall win a case but that justice shall be done. The majority found that suppression of material favorable evidence deprives the defendant of a fair trial without regard to whether the prosecutor acted in bad faith, because the harm to the defendant is the same in either case. The Court drew on Mooney v. Holohan and Pyle v. Kansas to establish that due process prohibits the state from using false evidence and from suppressing evidence that undermines the prosecution\'s case. The requirement that suppressed evidence be "material" introduced a limiting principle to avoid requiring disclosure of every potentially favorable item.',
    legalStandards: [
      'Brady disclosure obligation — evidence material to guilt or punishment',
      'Due Process Clause of the Fourteenth Amendment',
      'Materiality standard — reasonable probability of different result',
      'Giglio rule for impeachment evidence (extension of Brady)',
      'Prosecution\'s duty to learn of favorable evidence in possession of police',
    ],
    keyPrecedents: [
      'Mooney v. Holohan, 294 U.S. 103 (1935)',
      'Pyle v. Kansas, 317 U.S. 213 (1942)',
      'Napue v. Illinois, 360 U.S. 264 (1959)',
      'United States v. Bagley, 473 U.S. 667 (1985) — materiality standard',
      'Giglio v. United States, 405 U.S. 150 (1972)',
    ],
    evidenceAnalysis: 'The dispositive piece of evidence was Boblit\'s written statement confessing to the actual killing of William Brooks. Brady\'s own admissions made the withheld statement minimally material to guilt, since Brady had conceded participation. However, the statement was highly material to punishment, as it directly supported Brady\'s claim that he was not the triggerman — a fact potentially decisive to a jury deliberating between life imprisonment and death. The Court\'s evidentiary analysis thus distinguished between the materiality of the evidence for guilt-phase and penalty-phase purposes.',
    alternativeOutcomes: 'A ruling in Maryland\'s favor would have left defendants without a constitutional remedy for prosecutorial suppression of favorable evidence unless actual bad faith could be proven, making Brady violations effectively unreviewable in most cases. A broader ruling could have ordered a new trial on both guilt and punishment rather than punishment only, recognizing the theoretical possibility that a jury aware of who actually committed the killing might have treated Brady\'s role differently. The Court could also have established a broader rule requiring automatic disclosure of all potentially favorable materials without requiring a defense request.',
    lessonsLearned: [
      'Prosecutors have an affirmative constitutional duty to disclose material exculpatory and impeachment evidence to the defense',
      'Brady violations occur regardless of prosecutorial good faith; the test is materiality, not intent',
      'Evidence is material if there is a reasonable probability that its disclosure would have produced a different result',
      'The Brady obligation extends to evidence within the possession of the police, not merely the prosecutor personally',
    ],
    bestPractices: [
      'Defense counsel should file comprehensive, specific Brady requests early in the proceedings',
      'Prosecutors must implement office-wide systems to identify and disclose favorable evidence, including evidence in law enforcement files',
      'Defense attorneys should renew Brady requests throughout the case as new evidence develops',
      'Counsel should scrutinize all government witness agreements, prior criminal records, and potential motive to fabricate as Giglio material',
      'Courts should enforce Brady obligations through sanctions including dismissal in cases of willful suppression',
    ],
    significance: 'Brady v. Maryland established one of the most important doctrinal pillars of modern criminal defense law, imposing a constitutional duty on prosecutors to disclose material exculpatory and impeachment evidence. The decision has generated an extensive body of case law defining what constitutes material evidence and the scope of the prosecutorial disclosure obligation. Brady violations have been identified as a significant cause of wrongful convictions, making the rule particularly critical in capital and other serious cases. Subsequent cases including Giglio v. United States, United States v. Bagley, and Kyles v. Whitley have expanded and refined Brady\'s scope. The decision fundamentally reshaped the ethics and practice of prosecution by establishing that the government\'s obligation in criminal cases is justice, not merely conviction.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'John Leo Brady',
        role: 'PLAINTIFF',
        counsel: 'E. Clinton Bamberger Jr.',
        description: 'Death-row defendant convicted of murder who sought a new trial based on the prosecution\'s suppression of his co-defendant\'s confession to committing the killing',
      },
      {
        name: 'State of Maryland',
        role: 'DEFENDANT',
        counsel: 'Thomas W. Jamison III (Maryland Attorney General\'s Office)',
        description: 'Prosecution defending Brady\'s conviction and sentence and the constitutionality of non-disclosure of Boblit\'s statement',
      },
      {
        name: 'Donald Boblit',
        role: 'THIRD_PARTY',
        description: 'Co-defendant who had separately confessed to committing the actual killing; his suppressed statement was the subject of the Brady claim',
      },
    ],
  },

  {
    litigationSlug: 'criminal-defense',
    name: 'Strickland v. Washington',
    citation: '466 U.S. 668 (1984)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1984,
    facts: 'David Leroy Washington was charged in Florida with three counts of capital murder arising from a ten-day crime spree in 1976 during which he committed murder, kidnapping, robbery, and other crimes. Against his counsel\'s advice, Washington pleaded guilty to all three capital murder charges. At the sentencing hearing, Washington\'s court-appointed attorney made several decisions that Washington later challenged as constitutionally deficient: he did not request a psychiatric examination, did not seek character witnesses, and did not obtain records from a clergyman who had known Washington. The attorney conducted only a minimal investigation and relied on the trial judge\'s sympathy in mitigation. Washington was sentenced to death on each count.',
    keyLegalIssues: [
      'What standard governs claims that counsel\'s assistance was so defective as to require reversal of a conviction or death sentence',
      'Whether a defendant claiming ineffective assistance of counsel must show both deficient performance and resulting prejudice',
      'How courts should measure whether counsel\'s performance fell below an objective standard of reasonableness',
      'What level of prejudice a defendant must demonstrate to obtain relief for counsel\'s deficient performance',
    ],
    plaintiffArguments: 'Washington argued that his counsel\'s failure to conduct an adequate mitigation investigation — including failure to seek psychiatric evaluation, gather character evidence, and obtain records from a known clergyman — constituted constitutionally deficient performance. He contended that a competent attorney representing a capital defendant facing sentencing would have undertaken thorough investigation of mitigating factors, and that counsel\'s deficiencies undermined the adversarial process that the Sixth Amendment guarantees. Washington argued that the prejudice standard should be relatively lenient given the stakes in capital sentencing.',
    defendantArguments: 'Florida argued that Washington\'s attorney had made reasonable strategic decisions under the circumstances, including the judgment that emphasizing mitigating factors might draw attention to aggravating ones. The state contended that courts should not second-guess reasonable tactical choices made by competent counsel under the pressures of actual litigation. Florida maintained that any workable standard must give substantial deference to counsel\'s professional judgment, and that Washington had failed to demonstrate that different conduct would have changed the outcome.',
    proceduralHistory: 'Washington was sentenced to death in Florida state court in 1976. After exhausting state remedies, he brought a federal habeas corpus petition in the Southern District of Florida, which rejected the claim. The Eleventh Circuit Court of Appeals reversed in part, applying a more categorical approach to ineffective assistance claims in capital cases. The Supreme Court granted certiorari to resolve conflicting circuit approaches to the ineffective assistance standard.',
    finalDecision: 'Justice O\'Connor, writing for an 8-1 majority, established a two-pronged test for evaluating claims of ineffective assistance of counsel. To succeed, a defendant must show: (1) that counsel\'s performance was deficient — meaning it fell below an objective standard of reasonableness as measured by prevailing professional norms; and (2) that the deficiency prejudiced the defense — meaning there is a reasonable probability that, but for counsel\'s errors, the result would have been different. The Court affirmed Washington\'s death sentences, finding that his counsel\'s performance did not fall below constitutional standards.',
    judicialReasoning: 'Justice O\'Connor reasoned that the Sixth Amendment\'s guarantee of counsel is the right to the effective assistance of counsel, meaning assistance that is reasonably competent, not perfect. The majority established that judicial scrutiny of counsel\'s performance must be highly deferential, avoiding the distorting effects of hindsight and recognizing the wide range of reasonable professional assistance. Courts must indulge a strong presumption that counsel\'s conduct falls within the wide range of reasonable professional assistance. The prejudice prong was calibrated to require a substantial probability of different outcome, not merely a conceivable effect — a standard reflecting that only errors of constitutional magnitude should void an otherwise valid conviction. O\'Connor rejected per se rules requiring specific conduct, preferring an open-ended standard adaptable to varying circumstances. Justice Marshall dissented, arguing the majority\'s standard was so deferential as to be unworkable and would rarely provide relief to defendants whose counsel had genuinely failed them.',
    legalStandards: [
      'Strickland two-pronged test: deficient performance and prejudice',
      'Objective reasonableness standard under prevailing professional norms',
      'Reasonable probability of different result — prejudice prong',
      'Strong presumption of counsel competence',
      'Deference to reasonable tactical decisions of trial counsel',
    ],
    keyPrecedents: [
      'McMann v. Richardson, 397 U.S. 759 (1970)',
      'United States v. Cronic, 466 U.S. 648 (1984) — decided same day, addressing presumed prejudice',
      'Wiggins v. Smith, 539 U.S. 510 (2003) — applying Strickland to mitigation investigation',
      'Rompilla v. Beard, 545 U.S. 374 (2005)',
      'Padilla v. Kentucky, 559 U.S. 356 (2010)',
    ],
    evidenceAnalysis: 'The sentencing record documented Washington\'s counsel\'s minimal mitigation investigation and the strategic choices made in the guilt and sentencing phases. The Court examined the aggravating and mitigating circumstances actually presented and found three strong aggravating factors against a background of only limited mitigating evidence. The majority concluded that even had counsel conducted the additional investigation Washington claimed was required, there was no reasonable probability of a different sentencing outcome given the strength of the aggravating circumstances and the limited additional mitigating evidence that could plausibly have been uncovered.',
    alternativeOutcomes: 'A more defendant-favorable standard — such as the per se rules proposed by some circuits — would have required reversal in a broader range of cases without requiring specific prejudice analysis, making relief more accessible but potentially creating windfalls for defendants whose outcomes were not actually affected by counsel\'s errors. A ruling adopting the Eleventh Circuit\'s categorical approach in capital cases would have established heightened protections specifically for death-penalty defendants without altering the standard in non-capital contexts.',
    lessonsLearned: [
      'Defense counsel must conduct a thorough and diligent investigation proportionate to the stakes of the case, especially in capital proceedings',
      'Strategic choices receive deference only when they are based on adequate investigation — not when they result from failure to investigate',
      'Both prongs of Strickland must be satisfied; a deficient performance claim that cannot demonstrate prejudice will not result in relief',
      'Courts applying Strickland must consider the totality of counsel\'s performance, not isolated errors',
    ],
    bestPractices: [
      'Capital defense counsel must conduct comprehensive mitigation investigations covering childhood, mental health, substance abuse, and family history',
      'Defense attorneys should document the reasoning behind strategic decisions to demonstrate reasonableness if later challenged',
      'Counsel must consult with all reasonably available witnesses and experts before making decisions about which to call',
      'Post-conviction counsel should obtain and review the trial file and counsel\'s notes to identify failure-to-investigate claims',
      'Defense teams should utilize investigators and mitigation specialists as standard practice in serious felony cases',
    ],
    significance: 'Strickland v. Washington established the constitutional framework for ineffective assistance of counsel claims that remains controlling law throughout the United States. The two-pronged test — deficient performance and prejudice — has been applied in thousands of habeas corpus petitions and direct appeals since 1984, generating an enormous body of case law on counsel\'s obligations in investigation, plea bargaining, sentencing, and trial. Critics argue that the standard\'s deferential approach has made it extremely difficult for defendants to prevail even in egregious cases. The decision has prompted substantial scholarship and reform efforts in capital defense, leading to the American Bar Association\'s Guidelines for the Appointment and Performance of Defense Counsel in Death Penalty Cases. Strickland\'s framework has been extended to guilty pleas, sentencing, and plea negotiation advice, making it the foundational precedent for the quality dimension of the Sixth Amendment right to counsel.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'David Leroy Washington',
        role: 'PLAINTIFF',
        counsel: 'Richard E. Shapiro (habeas counsel)',
        description: 'Capital defendant convicted of three counts of murder who challenged the constitutional adequacy of his trial counsel\'s performance at sentencing',
      },
      {
        name: 'State of Florida',
        role: 'DEFENDANT',
        counsel: 'Joy B. Shearer (Florida Attorney General\'s Office)',
        description: 'Respondent defending the constitutionality of the capital sentences and the legal standard applied to ineffective assistance claims',
      },
    ],
  },
];

export default cases;
