import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'elder-estate',
    name: 'In re Quinlan',
    citation: '70 N.J. 10, 355 A.2d 647 (1976)',
    jurisdiction: 'New Jersey',
    court: 'New Jersey Supreme Court',
    year: 1976,
    facts: 'Karen Ann Quinlan, a 21-year-old woman, lapsed into a persistent vegetative state in April 1975 after ingesting a combination of alcohol and tranquilizers at a party. She was placed on a mechanical respirator at Saint Clare\'s Hospital in Denville, New Jersey, and physicians determined she had no reasonable possibility of returning to a cognitive, sapient life. Her father, Joseph Quinlan, sought appointment as her guardian with the express authority to discontinue life-sustaining treatment, believing it was consistent with Karen\'s previously expressed wishes and her Catholic faith. The hospital and her attending physicians refused to withdraw the respirator, fearing criminal liability for homicide. The case raised profound questions about the right to die, the role of the family and medical community in end-of-life decisions, and the constitutional limits of state intervention in deeply personal medical choices.',
    keyLegalIssues: [
      'Whether a person in a persistent vegetative state has a constitutional right to refuse life-sustaining treatment',
      'Whether a guardian may exercise that right on behalf of an incompetent patient',
      'Whether withdrawal of life support constitutes homicide under New Jersey law',
      'The proper standard for surrogate medical decision-making for incompetent adults',
    ],
    plaintiffArguments: 'Joseph Quinlan argued that Karen possessed a constitutional right to privacy under the Fourteenth Amendment that encompassed the right to refuse extraordinary medical treatment, and that as her father and guardian he could exercise that right on her behalf. He contended that continued mechanical ventilation violated Karen\'s personal dignity and her own previously expressed wishes that she would not want to be kept alive by artificial means. Quinlan further argued that the state\'s interest in preserving life diminishes as the prognosis for meaningful recovery becomes more remote, and that neither physicians nor hospitals should be the final arbiters of such profoundly personal decisions.',
    defendantArguments: 'The hospital and attending physicians argued that withdrawing the respirator would constitute active homicide and expose medical personnel to criminal prosecution under New Jersey law. They maintained that the standard of care required continuation of treatment so long as the patient showed any signs of life, and that medical professionals rather than family members were best positioned to make clinical judgments. The State of New Jersey intervened to argue a compelling interest in preserving human life that outweighed any claimed privacy right, particularly given Karen\'s inability to personally express a current wish to die.',
    proceduralHistory: 'Joseph Quinlan filed in the Superior Court of New Jersey in November 1975 seeking appointment as Karen\'s guardian with authority to authorize removal of the respirator. The trial court denied the request, finding no constitutional basis for the relief sought and deferring to medical judgment. Quinlan appealed directly to the New Jersey Supreme Court, which certified the case for immediate consideration given its importance.',
    finalDecision: 'The New Jersey Supreme Court reversed the trial court, holding that Karen\'s right of privacy included the right to have the respirator withdrawn, and that her father as guardian could exercise that right on her behalf. The court established that an ethics committee concurrence would provide immunity for medical personnel who participated in withdrawal of treatment.',
    judicialReasoning: 'Chief Justice Richard Hughes, writing for a unanimous court, grounded the decision in the constitutional right of privacy first recognized in Griswold v. Connecticut, finding that the right was broad enough to encompass a patient\'s decision to decline medical treatment even if that decision might hasten death. The court reasoned that Karen\'s right did not evaporate simply because she was incompetent; rather, it could be asserted on her behalf by a close family member acting as a surrogate. The justices acknowledged the genuine tension between individual autonomy and the state\'s interest in preserving life but concluded that interest weakens proportionally as the possibility of meaningful recovery diminishes. The court also drew on the principle of substituted judgment, directing the guardian to make the decision Karen herself would have made. To protect physicians from criminal liability, the court created the hospital ethics committee mechanism as a procedural safeguard. The opinion explicitly distinguished between allowing a patient to die naturally and active euthanasia, framing removal of the respirator as the former.',
    legalStandards: [
      'Constitutional right of privacy as applied to medical decision-making',
      'Substituted judgment standard for surrogate decision-makers',
      'Balancing of state interest in life against individual autonomy',
      'Ethics committee review as a procedural safeguard for withdrawal of treatment',
    ],
    keyPrecedents: [
      'Griswold v. Connecticut, 381 U.S. 479 (1965) — constitutional right of privacy',
      'Superintendent of Belchertown State School v. Saikewicz, 373 Mass. 728 (1977) — surrogate decision-making for incompetents',
      'Cruzan v. Director, Missouri Dept. of Health, 497 U.S. 261 (1990) — U.S. Supreme Court affirmance of right to refuse treatment',
    ],
    evidenceAnalysis: 'Medical testimony established with near certainty that Karen had no neocortical function and no reasonable prospect of regaining sapient existence. Expert witnesses differentiated between her brain-stem-mediated vegetative functions, which persisted, and higher cognitive activity, which was irreversibly absent. The court credited the testimony of Karen\'s family and a priest regarding her prior statements expressing her wish not to be kept alive artificially, treating those statements as probative evidence of her substituted judgment even though they were informal and had not been memorialized in any written advance directive.',
    alternativeOutcomes: 'Had the court sided with the hospital, Karen would have remained on the respirator indefinitely and the judiciary would have effectively foreclosed family-based surrogate decision-making. A narrower ruling limited to Karen\'s specific facts rather than a broad privacy right would have left the law uncertain and required case-by-case litigation for every similar dispute. The court also could have required legislative rather than judicial resolution, deferring to the New Jersey legislature to craft a right-to-die framework.',
    lessonsLearned: [
      'Families and physicians need clear, legally recognized frameworks for end-of-life decision-making',
      'Advance directives and living wills are essential tools to express wishes before incapacity',
      'Ethics committees serve a vital role as an internal check on withdrawal-of-treatment decisions',
      'The state\'s interest in preserving life is not absolute and must be weighed against patient autonomy',
    ],
    bestPractices: [
      'Execute a durable power of attorney for health care and living will while competent',
      'Discuss end-of-life wishes explicitly with family members and record those conversations',
      'Hospitals should establish ethics committees to review withdrawal-of-treatment requests',
      'Physicians should document prognosis and treatment goals clearly in the medical record',
    ],
    significance: 'In re Quinlan is the foundational American right-to-die case and one of the most consequential judicial decisions of the twentieth century. It established for the first time that an incompetent patient\'s constitutional privacy right could be exercised by a surrogate and that withdrawal of life-sustaining treatment does not constitute homicide. The decision directly spurred the living-will and advance-directive legislative movement: within a decade virtually every state had enacted some form of natural-death statute. It established the hospital ethics committee as a standard feature of American healthcare institutions. The case influenced the U.S. Supreme Court\'s later analysis in Cruzan and shaped the conceptual framework that would be applied in the Terri Schiavo controversy nearly three decades later. Quinlan remains required reading in every medical ethics, bioethics, and elder-law curriculum in the United States.',
    outcome: 'Plaintiff Victory',
    isFeatured: true,
    parties: [
      {
        name: 'Joseph Quinlan',
        role: 'PLAINTIFF',
        counsel: 'Paul W. Armstrong',
        description: 'Father of Karen Ann Quinlan; sought guardianship with authority to withdraw life support',
      },
      {
        name: 'Saint Clare\'s Hospital',
        role: 'DEFENDANT',
        counsel: 'Theodore Einhorn',
        description: 'Hospital that refused to remove the respirator without a court order',
      },
      {
        name: 'State of New Jersey',
        role: 'INTERVENOR',
        description: 'Intervened to assert the state\'s interest in preserving human life',
      },
    ],
  },

  {
    litigationSlug: 'elder-estate',
    name: 'Marshall v. Marshall (Anna Nicole Smith)',
    citation: '547 U.S. 293 (2006)',
    jurisdiction: 'Federal / Texas',
    court: 'United States Supreme Court',
    year: 2006,
    facts: 'Vickie Lynn Marshall, known publicly as Anna Nicole Smith, married J. Howard Marshall II, a Texas oil billionaire, in June 1994 when she was 26 and he was 89. J. Howard Marshall died in August 1995 without leaving Vickie any portion of his roughly $1.6 billion estate; his son E. Pierce Marshall received the bulk of the assets under a trust that had been established years earlier. Vickie filed a claim in J. Howard\'s Texas probate proceeding, alleging that Pierce had tortiously interfered with a gift she was promised by her husband. While the Texas probate case was pending, Vickie also filed for bankruptcy in California, where Pierce filed a proof of claim alleging she had defamed him. The California bankruptcy court ruled in Vickie\'s favor on her tortious-interference counterclaim and awarded her $474 million; the Texas probate court subsequently ruled for Pierce. The competing judgments set up a clash over federal court jurisdiction and the so-called probate exception to federal jurisdiction.',
    keyLegalIssues: [
      'Whether the federal probate exception to jurisdiction strips federal courts of power over related tort claims',
      'Scope of the probate exception under 28 U.S.C. § 1334 and general federal diversity jurisdiction',
      'Whether a bankruptcy court\'s adjudication of a tortious-interference counterclaim was within its subject-matter jurisdiction',
      'Preclusive effect of competing state probate and federal bankruptcy judgments',
    ],
    plaintiffArguments: 'Vickie Marshall argued that her tortious-interference claim was an independent tort action arising from Pierce\'s conduct in manipulating the decedent and had nothing to do with the actual probate of the will or administration of the estate, meaning it fell outside the narrow probate exception and was properly before the federal bankruptcy court. She contended that federal courts are not required to yield to state probate courts on every dispute tangentially related to an estate, and that the circuit court had improperly expanded the probate exception beyond its historical limits. Vickie further argued that the California bankruptcy court\'s judgment was entitled to full faith and credit and should have been given preclusive effect in the Texas proceedings.',
    defendantArguments: 'Pierce Marshall argued that the probate exception to federal jurisdiction is broad and encompasses any claim that, if successful, would effectively distribute estate assets, regardless of how the claim is styled. He maintained that Vickie\'s tortious-interference claim was at its core an attempt to obtain a share of J. Howard\'s estate and therefore should be litigated exclusively in the Texas probate court. Pierce also argued that the Texas state court judgment in his favor was rendered first and should be given preclusive effect over the subsequent California bankruptcy ruling.',
    proceduralHistory: 'Vickie filed for Chapter 11 bankruptcy in the Central District of California in 1996. Pierce filed a proof of claim alleging defamation; Vickie counterclaimed for tortious interference. The bankruptcy court ruled for Vickie in 2000 and awarded $474 million, later reduced by the district court. The Ninth Circuit reversed, holding the probate exception barred federal jurisdiction. The U.S. Supreme Court granted certiorari to resolve a circuit split on the scope of the probate exception.',
    finalDecision: 'The Supreme Court unanimously reversed the Ninth Circuit, holding that the probate exception does not bar federal courts from adjudicating Vickie\'s tortious-interference claim. Justice Ginsburg\'s opinion clarified that the probate exception is narrow: it covers only cases that would require a federal court to probate a will, administer an estate, or disturb state court orders pertaining to property in the custody of a state probate court.',
    judicialReasoning: 'Justice Ginsburg traced the probate exception to its English equity-court origins and found that American courts had improperly expanded it far beyond its historical scope. The Court held that the exception covers only two situations: cases requiring a federal court to probate a will or administer an estate, and cases requiring the court to assume control of property already in the custody of a state probate court. A tort claim for interference with an expected inheritance is neither. The majority emphasized that federal courts have a virtually unflagging obligation to exercise jurisdiction conferred by Congress and that exceptions must be construed narrowly. The Court also addressed the meaning of the Ankenbrandt precedent on the domestic-relations exception, analogizing the two doctrines. Because Vickie\'s claim rested on Pierce\'s alleged tortious conduct rather than on a will or trust instrument, it was a standard common-law tort well within federal subject-matter jurisdiction.',
    legalStandards: [
      'Federal probate exception to subject-matter jurisdiction — narrow construction',
      '28 U.S.C. § 1334 bankruptcy court subject-matter jurisdiction',
      'Virtually unflagging obligation of federal courts to exercise conferred jurisdiction',
      'Tortious interference with an expected inheritance as an independent common-law tort',
    ],
    keyPrecedents: [
      'Markham v. Allen, 326 U.S. 490 (1946) — early articulation of probate exception',
      'Ankenbrandt v. Richards, 504 U.S. 689 (1992) — narrow construction of domestic-relations exception by analogy',
      'Granfinanciera, S.A. v. Nordberg, 492 U.S. 33 (1989) — bankruptcy court adjudicatory power',
    ],
    evidenceAnalysis: 'The record included deposition testimony and documentary evidence that J. Howard Marshall had repeatedly promised Vickie a substantial inter-vivos gift and that Pierce had allegedly interfered with his father\'s ability to execute documents reflecting that gift. The bankruptcy court credited Vickie\'s witnesses over Pierce\'s, finding Pierce\'s conduct tortious. The Supreme Court did not re-examine the factual record, focusing instead on the jurisdictional question, but the factual findings of the bankruptcy court formed the predicate for the legal analysis of whether the claim was estate-related or independently tortious in nature.',
    alternativeOutcomes: 'Had the Supreme Court affirmed the Ninth Circuit, the probate exception would have become a broad shield allowing wealthy estates to avoid federal court scrutiny by routing assets through state probate proceedings. Vickie would have been left with only the adverse Texas probate judgment and no federal forum. A ruling that the Texas judgment had preclusive effect would have ended the litigation in Pierce\'s favor without any Supreme Court analysis of the jurisdictional question.',
    lessonsLearned: [
      'The probate exception to federal jurisdiction is narrow and does not bar independent tort claims merely because they relate to an estate',
      'Testators should document inter-vivos gift intentions clearly to prevent later tortious-interference claims',
      'Surviving spouses should be considered in estate plans to avoid contentious post-death litigation',
      'Concurrent state and federal proceedings over the same underlying dispute create complex preclusion problems',
    ],
    bestPractices: [
      'Married individuals should execute comprehensive estate plans including trusts that expressly address the surviving spouse\'s interests',
      'Attorneys should advise clients on the risk of tortious-interference claims when excluding close family members from estate plans',
      'Document all inter-vivos gift commitments in writing to reduce litigation risk',
      'Counsel should monitor parallel state and federal proceedings to manage preclusion and inconsistent judgment risks',
    ],
    significance: 'Marshall v. Marshall is a landmark federal-jurisdiction case with far-reaching consequences for estate litigation strategy. By narrowing the probate exception, the Supreme Court confirmed that federal courts remain available to adjudicate tort and contract claims arising around an estate even when the estate is being administered in state probate court. The decision resolved a deep circuit split and clarified the relationship between federal bankruptcy courts and state probate courts. It also brought enormous public attention to the vulnerability of elderly individuals\' estate plans to undue influence and to the importance of careful pre-death planning. The tortious-interference-with-inheritance tort gained renewed prominence as a litigation tool for disinherited family members, and the case is now a standard teaching vehicle for federal courts and estate-planning courses alike.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Vickie Lynn Marshall (Anna Nicole Smith)',
        role: 'PLAINTIFF',
        counsel: 'Kent Richland; Howard K. Stern',
        description: 'Widow of J. Howard Marshall II; sought share of estate through tortious-interference claim',
      },
      {
        name: 'E. Pierce Marshall',
        role: 'DEFENDANT',
        counsel: 'G. Eric Brunstad Jr.',
        description: 'Son of J. Howard Marshall II and principal beneficiary of the estate',
      },
    ],
  },

  {
    litigationSlug: 'elder-estate',
    name: 'Schiavo ex rel. Schindler v. Schiavo',
    citation: '403 F.3d 1223 (11th Cir. 2005)',
    jurisdiction: 'Federal / Florida',
    court: 'United States Court of Appeals, Eleventh Circuit',
    year: 2005,
    facts: 'Theresa Marie Schiavo suffered severe brain damage in February 1990 following a cardiac arrest that deprived her brain of oxygen for several minutes, leaving her in what Florida courts repeatedly found to be a persistent vegetative state with no hope of recovery. Her husband, Michael Schiavo, was appointed her legal guardian and after several years sought court authorization to remove her feeding tube, asserting that Terri had expressed wishes not to be kept alive artificially. Terri\'s parents, Robert and Mary Schindler, bitterly contested Michael\'s account, disputed the vegetative-state diagnosis, and sought to have the feeding tube maintained. The dispute became one of the most contentious right-to-die cases in American history, involving years of state court litigation, two acts of the Florida legislature, a special act of the United States Congress, and intervention by President George W. Bush. The feeding tube was removed and reinserted multiple times before being permanently removed on March 18, 2005, and Terri Schiavo died on March 31, 2005.',
    keyLegalIssues: [
      'Whether federal courts had jurisdiction to review Florida state court findings under the emergency federal legislation (Pub. L. 109-3)',
      'Whether the withdrawal of a feeding tube from a person in a persistent vegetative state violates the Due Process or Equal Protection Clauses',
      'The constitutional limits of congressional power to grant federal courts jurisdiction over specific state-court judgments',
      'Standard of clear and convincing evidence for an incompetent patient\'s wishes regarding end-of-life treatment in the absence of a written advance directive',
    ],
    plaintiffArguments: 'The Schindlers argued that Terri was not in a true persistent vegetative state and that there was a reasonable possibility of rehabilitation with appropriate therapy. They contended that Michael Schiavo had a conflict of interest as guardian because he had entered into a new relationship and would benefit financially from Terri\'s death. The Schindlers further argued that removing the feeding tube constituted murder and violated Terri\'s federal constitutional rights under the Due Process and Equal Protection Clauses, and that the emergency congressional legislation required federal courts to conduct a fresh, de novo review of all constitutional claims rather than deferring to the extensive Florida court record.',
    defendantArguments: 'Michael Schiavo, represented by the court-appointed guardian ad litem and supported by Florida courts, argued that fifteen years of state court proceedings including multiple evidentiary hearings had conclusively established both that Terri was in a persistent vegetative state and that she had clearly expressed a wish not to be maintained by artificial nutrition. He contended that the emergency federal legislation did not entitle the Schindlers to a new factual trial in federal court but only to a federal review of whether constitutional rights had been violated, and that the state courts had fully and fairly adjudicated all such claims. Michael argued that the state courts\' findings were entitled to deference and that the federal intervention was an unprecedented and unconstitutional interference with both state court judgments and individual rights.',
    proceduralHistory: 'Florida state courts conducted extensive litigation from 1998 through 2005, with the Second District Court of Appeal affirming the trial court\'s findings in multiple opinions. The Florida Supreme Court struck down "Terri\'s Law," a 2003 act that had temporarily allowed the governor to order reinsertion of the feeding tube. Congress enacted Pub. L. 109-3 in March 2005, granting the federal district court jurisdiction to hear the Schindlers\' claims. The Middle District of Florida denied an emergency injunction; the Eleventh Circuit affirmed; and the Supreme Court denied certiorari.',
    finalDecision: 'The Eleventh Circuit, in a 2-1 decision, affirmed the denial of an emergency injunction and declined to order reinsertion of the feeding tube. The court held that the Schindlers had not demonstrated a substantial likelihood of success on any of their federal constitutional claims and that the balance of harms weighed against injunctive relief. The feeding tube was not reinserted.',
    judicialReasoning: 'The Eleventh Circuit majority held that the emergency federal legislation, while granting jurisdiction, did not require de novo factual review of the extensive state court record; rather, it allowed the federal court to examine whether the state proceedings comported with constitutional requirements. Having reviewed the Florida courts\' thorough findings, the majority concluded there was no viable constitutional claim. The court applied the clear-and-convincing evidence standard used by Florida and affirmed that Michael Schiavo as guardian had legal authority to make the decision. The majority emphasized that the federal judiciary cannot and should not substitute its judgment for that of a guardian acting within a constitutionally adequate state process merely because others disagree with the outcome. Judge Wilson dissented on procedural grounds relating to the scope of the congressional grant of jurisdiction.',
    legalStandards: [
      'Clear and convincing evidence standard for proof of an incompetent\'s end-of-life wishes',
      'Substituted judgment standard for guardian decision-making',
      'Federal court jurisdiction under emergency special legislation',
      'Preliminary injunction standard: likelihood of success on the merits and balance of harms',
      'Constitutional adequacy of state court proceedings as a limit on federal review',
    ],
    keyPrecedents: [
      'In re Quinlan, 70 N.J. 10 (1976) — foundational right-to-die case',
      'Cruzan v. Director, Missouri Dept. of Health, 497 U.S. 261 (1990) — clear-and-convincing evidence standard',
      'In re Guardianship of Schiavo, 780 So. 2d 176 (Fla. 2d DCA 2001) — Florida appellate history',
    ],
    evidenceAnalysis: 'Florida courts heard extensive medical testimony from numerous neurologists, neuroradiologists, and rehabilitation specialists over several years. The majority of court-appointed and examined experts concluded that Terri\'s cerebral cortex had been largely replaced by cerebrospinal fluid and that her responses were reflexive rather than purposeful. The trial court and multiple appellate panels found Michael Schiavo\'s account of Terri\'s expressed wishes credible; his testimony was corroborated by two of his siblings. The Schindlers\' experts, several of whom had not examined Terri in person, were given less weight. The court\'s evidence analysis highlighted the challenge of proving an incompetent person\'s wishes through oral testimony alone, underscoring the need for advance directives.',
    alternativeOutcomes: 'If the Eleventh Circuit had ordered reinsertion, Terri would have remained on life support indefinitely with no clear mechanism for resolution given the family impasse. A finding that congressional intervention was itself unconstitutional would have raised serious separation-of-powers concerns but might have foreclosed future similar legislation. Had Florida courts applied a lower evidentiary standard for proving Terri\'s wishes, removal might have occurred years earlier, avoiding a decade of litigation.',
    lessonsLearned: [
      'The absence of a written advance directive can lead to years of devastating family conflict and public litigation',
      'Guardianship disputes between spouses and parents of incapacitated adults require careful judicial management',
      'Legislative intervention in individual court cases raises profound constitutional concerns',
      'Medical consensus on vegetative-state diagnosis, while strong, can still be a flashpoint for public controversy',
    ],
    bestPractices: [
      'Every adult should execute a health care surrogate designation and living will that clearly addresses artificial nutrition and hydration',
      'Guardians should maintain detailed records of the ward\'s prior expressed wishes regarding end-of-life care',
      'Courts appointing guardians in contested cases should consider independent guardian ad litem review',
      'Healthcare providers should initiate ethics consultation early in chronic vegetative-state cases to facilitate family communication',
    ],
    significance: 'Schiavo is the most high-profile right-to-die case since Quinlan and had a transformative effect on American law and public policy. The case demonstrated with devastating clarity the consequences of failing to execute an advance directive and catalyzed a nationwide surge in living-will preparation. It raised profound questions about the constitutional limits of legislative power to intervene in individual court cases and about the respective roles of courts, legislatures, and the executive in end-of-life decisions. The episode prompted numerous states to revise and clarify their advance-directive statutes and guardian-ship laws. It also re-energized debates about the adequacy of safeguards for incapacitated persons and the proper evidentiary standard for proving an incompetent patient\'s wishes. The Schiavo litigation remains a central case study in bioethics, constitutional law, and elder law courses throughout the United States.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Robert and Mary Schindler',
        role: 'PLAINTIFF',
        counsel: 'David Gibbs III; Randall Terry (advocacy)',
        description: 'Parents of Theresa Marie Schiavo; sought to prevent removal of feeding tube',
      },
      {
        name: 'Michael Schiavo',
        role: 'DEFENDANT',
        counsel: 'George Felos',
        description: 'Husband and court-appointed guardian of Theresa Marie Schiavo',
      },
    ],
  },

  {
    litigationSlug: 'elder-estate',
    name: 'Shapira v. Union National Bank',
    citation: '39 Ohio Misc. 28, 315 N.E.2d 825 (Ohio C.P. 1974)',
    jurisdiction: 'Ohio',
    court: 'Court of Common Pleas, Mahoning County, Ohio',
    year: 1974,
    facts: 'Dr. David Shapira died testate and his will conditioned a bequest to his son Daniel upon Daniel marrying a Jewish woman who was born of two Jewish parents within seven years of the testator\'s death. If Daniel failed to meet this condition, the share was to pass to the State of Israel. Daniel Shapira was unmarried at the time of his father\'s death, and he challenged the condition as an unconstitutional restriction on his right to marry and as contrary to public policy. The case presented the question whether a private testamentary condition restricting a beneficiary\'s choice of spouse is enforceable in probate or whether such a condition impermissibly infringes on fundamental constitutional rights. The dispute required the court to balance the long-established principle of testamentary freedom against constitutional protections for personal liberty and marriage choice.',
    keyLegalIssues: [
      'Whether a testamentary condition requiring marriage to a person of a specific religion and ethnicity is enforceable',
      'Whether such a condition violates the First Amendment, the Equal Protection Clause, or public policy',
      'The scope of testamentary freedom as a property right versus constitutional rights of the beneficiary',
      'Whether the state-action doctrine applies to enforcement of a private will\'s conditions through the probate court',
    ],
    plaintiffArguments: 'Daniel Shapira argued that the testamentary condition was void because it violated his constitutional right to marry whomever he chose, a right protected under the Due Process and Equal Protection Clauses as articulated in Loving v. Virginia. He contended that when a court enforces a marriage-restrictive will condition, the state becomes complicit in the discrimination and thus state action exists, rendering the First and Fourteenth Amendment protections applicable. Daniel also argued that the condition violated public policy because it tended to coerce marriage decisions based on impermissible factors rather than free choice, and that such coercive inducements undermined the state\'s interest in healthy and freely entered marriages.',
    defendantArguments: 'The bank as executor argued that the condition was a valid exercise of testamentary freedom, a foundational principle of American property law. It maintained that there is no constitutional right to receive a testamentary gift and that a testator may attach any reasonable condition to a bequest, including conditions related to religion or marriage, as long as the condition does not constitute state action. The bank relied on the well-established line of cases holding that partial restraints on marriage are permissible if they are reasonable and do not completely prohibit marriage, noting that Daniel remained free to marry any Jewish woman and thus was not entirely prevented from inheriting.',
    proceduralHistory: 'Daniel Shapira filed a complaint in the Mahoning County Court of Common Pleas seeking a declaration that the testamentary condition was unconstitutional and unenforceable. The case was submitted to the court on stipulated facts and cross-motions for judgment. The court of common pleas rendered a comprehensive written opinion examining both the constitutional and common-law public-policy challenges to the condition.',
    finalDecision: 'The court upheld the testamentary condition as valid and enforceable. It found no state action sufficient to trigger constitutional scrutiny and concluded that the condition was a reasonable partial restraint on marriage rather than a complete prohibition, and thus did not violate public policy under Ohio law or the common law.',
    judicialReasoning: 'Judge Henderson reasoned that enforcement of a private testamentary condition through the probate court does not constitute state action for constitutional purposes, drawing on the distinction between state enforcement of discriminatory private contracts and the mere fulfillment of a testator\'s private wishes in probate. The court found that Loving v. Virginia applied to state prohibitions on marriage, not to private bequest conditions. On the public-policy question, the court distinguished between conditions that completely prohibit marriage, which are void, and conditions that merely limit the class of eligible spouses, which are treated as partial restraints enforceable if reasonable. The court found the condition reasonable because it reflected the testator\'s genuine and sincere religious and cultural values and did not prevent Daniel from marrying; it only conditioned a bequest on a particular choice. The court also noted that Jewish endogamy has long been recognized as a legitimate religious practice.',
    legalStandards: [
      'Testamentary freedom as a fundamental principle of property law',
      'Partial versus total restraint on marriage doctrine',
      'State-action requirement for application of constitutional protections to private conduct',
      'Public policy as a limit on enforcement of testamentary conditions',
    ],
    keyPrecedents: [
      'Loving v. Virginia, 388 U.S. 1 (1967) — constitutional right to marry distinguished from private bequest conditions',
      'Gordon v. Gordon — partial restraint on marriage by religious condition generally enforceable',
      'Restatement (Second) of Property (Donative Transfers) § 6.2 — restraint on marriage analysis',
    ],
    evidenceAnalysis: 'The case was decided on stipulated facts, so there was no live testimonial evidence. The record established that Dr. Shapira had clearly and unambiguously expressed his intent in the will, that Daniel was unmarried at the time of death, and that the residual gift to Israel provided a valid alternative disposition. The court examined the historical and sociological context of Jewish religious practice regarding endogamy and credited the sincerity of the testator\'s religious motivations as relevant to the reasonableness inquiry.',
    alternativeOutcomes: 'If the court had found state action, the condition would likely have been struck down under Equal Protection principles, potentially opening a wide range of religious or ethnic testamentary conditions to constitutional attack. A finding that the condition was an unreasonable total restraint on marriage would have voided it and passed the bequest to Daniel unconditionally. The alternative-beneficiary gift to Israel provided a judicial safety valve that may have influenced the court\'s willingness to uphold the condition, since doing so did not result in an intestate windfall to the challenging party.',
    lessonsLearned: [
      'Testamentary freedom is broad but not unlimited; conditions must be reasonable partial restraints rather than absolute prohibitions on marriage',
      'Religious and cultural conditions in wills occupy a legally protected space as long as state action cannot be established',
      'Beneficiaries challenging will conditions face a high burden when the condition leaves open a class of eligible candidates',
      'Estate planners should advise clients on the litigation risk associated with unusual testamentary conditions',
    ],
    bestPractices: [
      'Testators who wish to encourage certain marriage choices should consult an attorney to frame conditions as incentives rather than absolute prohibitions',
      'Include a clear alternative disposition to avoid intestacy challenges if a challenged condition is struck down',
      'Document the testator\'s genuine personal, religious, or cultural motivations in the will or a contemporaneous memorandum',
      'Advise potential beneficiaries of conditional bequests well before the testator\'s death to allow informed life planning',
    ],
    significance: 'Shapira v. Union National Bank is the leading American case on religious and ethnic conditions in testamentary gifts and is widely taught in property and estate law courses as a vehicle for exploring the tension between testamentary freedom and constitutional rights. The decision established the prevailing rule that enforcement of private will conditions does not constitute state action, placing such conditions largely beyond constitutional attack. It also clarified the partial-restraint-on-marriage doctrine as applied to religion-based conditions, finding them enforceable when they leave a reasonable pool of potential spouses. The case continues to generate scholarly debate about whether the state-action analysis is correct given the courts\' active role in probate administration, and it has been cited in subsequent cases involving conditions based on religion, race, and sexual orientation.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Daniel Shapira',
        role: 'PLAINTIFF',
        description: 'Son of decedent Dr. David Shapira; challenged testamentary condition requiring marriage to a Jewish woman',
      },
      {
        name: 'Union National Bank',
        role: 'DEFENDANT',
        description: 'Executor of the estate of Dr. David Shapira; defended the will\'s validity',
      },
    ],
  },

  {
    litigationSlug: 'elder-estate',
    name: 'In re Totten',
    citation: '179 N.Y. 112, 71 N.E. 748 (1904)',
    jurisdiction: 'New York',
    court: 'New York Court of Appeals',
    year: 1904,
    facts: 'Tillie Totten deposited funds in a savings bank in her own name as trustee for a named beneficiary, her brother, under a passbook account that she retained and over which she exercised complete control during her lifetime. Upon her death, a dispute arose as to whether the account passed to her estate or directly to the named beneficiary, and whether the arrangement constituted a revocable or irrevocable inter-vivos trust that was valid despite not satisfying the Statute of Wills. Savings bank trust accounts of this form were extremely common in the late nineteenth century but their legal status was uncertain. The Court of Appeals faced the question of whether such an informal deposit arrangement could constitute a valid testamentary substitute, effectively passing assets outside the probate estate.',
    keyLegalIssues: [
      'Whether a savings bank account opened in the depositor\'s name as trustee for a named beneficiary creates a valid trust',
      'Whether such an arrangement constitutes an attempted testamentary transfer invalid for failure to comply with the Statute of Wills',
      'Whether a revocable trust over which the settlor retains complete control and beneficial enjoyment during life can be a valid inter-vivos trust',
      'The legal status of tentative or Totten trust accounts as probate-avoidance devices',
    ],
    plaintiffArguments: 'The estate administrator and other claimants argued that the bank account arrangement was in substance a testamentary transfer because it was designed to take effect only upon the depositor\'s death, when she no longer had control over the funds. They contended that allowing such an arrangement to pass assets outside the estate would circumvent the Statute of Wills and its protective safeguards requiring witnesses and formalities designed to prevent fraud and undue influence. The challengers maintained that a trust requires delivery of the res and some present beneficial interest in the beneficiary, neither of which existed here since Tillie retained full control and the beneficiary had no right to demand the funds during her lifetime.',
    defendantArguments: 'The beneficiary argued that a valid inter-vivos trust was created at the moment of deposit, subject only to revocation by the depositor during her lifetime. He contended that the law has long recognized tentative or revocable trusts as valid legal arrangements and that the depositor\'s retention of control during life is a feature of revocability, not a defect that negates trust formation. The beneficiary also argued that enforcing such accounts was essential to honoring the intentions of countless depositors who used this common banking practice as a straightforward estate-planning tool.',
    proceduralHistory: 'Following Tillie Totten\'s death, competing claims to the savings account balance arose between the named beneficiary and the estate. The Surrogate\'s Court ruled on the disposition of the account, and the matter was appealed through the New York intermediate appellate courts before reaching the Court of Appeals, which issued the opinion establishing the Totten trust doctrine.',
    finalDecision: 'The Court of Appeals held that a deposit in the form of a trust for a named beneficiary creates a valid tentative trust, revocable at will by the depositor during life, that vests in the beneficiary upon the depositor\'s death if it has not been previously revoked. The account was awarded to the named beneficiary rather than the estate.',
    judicialReasoning: 'Chief Judge Cullen acknowledged the doctrinal difficulty presented by a "trust" in which the supposed settlor retains all beneficial enjoyment and complete power of revocation, which in other contexts would be deemed illusory. However, the court chose to treat the arrangement as a tentative trust — one that is in effect during the depositor\'s life but becomes absolute on her death if not revoked. The court reasoned that the practical necessity of validating these exceedingly common banking arrangements outweighed strict doctrinal concerns, and that denying their validity would frustrate the clear intentions of millions of depositors and disrupt the reliance interests of beneficiaries. The court distinguished the arrangement from an outright testamentary transfer by characterizing it as a trust that exists from the moment of deposit, even if it is subject to complete defeasance. The court also noted that the arrangement does not require the formalities of a will because it is not technically a will — it is an inter-vivos trust, even if revocable.',
    legalStandards: [
      'Requirements for creation of a valid inter-vivos trust: intent, res, and ascertainable beneficiary',
      'Revocable versus irrevocable trust doctrine and the illusory trust concept',
      'Statute of Wills requirements and the inter-vivos trust exception',
      'Tentative trust doctrine as established in Totten',
    ],
    keyPrecedents: [
      'Statute of Wills — formal requirements for testamentary transfers distinguished from inter-vivos trusts',
      'Martin v. Funk, 75 N.Y. 134 (1878) — prior New York savings account trust authority',
      'Uniform Probate Code § 6-212 — later codification of the Totten trust concept',
    ],
    evidenceAnalysis: 'The court\'s analysis focused primarily on the legal documents — the bank passbook and account records — rather than on testimonial evidence. The passbook established that the account was opened in the form "Tillie Totten, trustee for [beneficiary]" and that Tillie retained the passbook and made all deposits and withdrawals. The court treated these facts as sufficient to establish the tentative trust relationship without requiring additional evidence of intent, relying on the objective form of the account as the basis for the legal conclusion.',
    alternativeOutcomes: 'Had the court invalidated Totten trusts as attempted wills not complying with Statute of Wills formalities, the practice of using pay-on-death bank accounts as estate-planning tools would have been foreclosed in New York, forcing depositors to rely on formal testamentary instruments. The ruling could have cast doubt on the validity of millions of existing accounts, creating chaos for banks and beneficiaries alike. A narrower ruling validating only completed and delivered trusts would have required depositors to relinquish control to create valid arrangements, eliminating the flexibility that made the Totten trust so useful.',
    lessonsLearned: [
      'Courts will sometimes validate widely-used practical arrangements even when they create doctrinal tension with established legal principles',
      'Pay-on-death and Totten trust accounts are powerful and accessible probate-avoidance tools available to people of modest means',
      'The form of a bank account title creates legally significant consequences that depositors should understand',
      'Estate planners should counsel clients on the interaction between Totten trust accounts and overall estate plans, including creditor rights and Medicaid implications',
    ],
    bestPractices: [
      'Depositors should designate beneficiaries on all bank accounts and periodically review and update those designations',
      'Elder law attorneys should advise clients on how Totten trust accounts affect Medicaid eligibility and estate recovery',
      'Ensure Totten trust beneficiary designations are consistent with overall testamentary planning to avoid unintended disinheritance',
      'Maintain records of all pay-on-death account designations alongside other estate planning documents',
    ],
    significance: 'In re Totten is one of the most practically consequential estate-law decisions in American history, having given its name to an entire category of probate-avoidance account — the "Totten trust" or pay-on-death account — used by tens of millions of Americans. The decision recognized a flexible, accessible means for people of ordinary means to pass bank accounts directly to named beneficiaries outside the probate process without the cost or complexity of a formal trust instrument. The Totten trust concept was subsequently adopted by the Uniform Probate Code and the Restatement (Third) of Trusts, and has been codified by statute in virtually every American jurisdiction. Modern pay-on-death account statutes, beneficiary designations on retirement accounts and life insurance, and transfer-on-death securities registrations all trace their doctrinal lineage to the Totten decision. The case profoundly democratized estate planning by placing effective probate-avoidance tools within reach of all depositors, not just those wealthy enough to create formal trusts.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Named Beneficiary (brother of Tillie Totten)',
        role: 'PLAINTIFF',
        description: 'Named beneficiary of the savings bank trust account; claimed funds passed outside the estate',
      },
      {
        name: 'Estate of Tillie Totten',
        role: 'DEFENDANT',
        description: 'Estate administrator asserting the account funds were part of the probate estate',
      },
    ],
  },
];

export default cases;
