import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'energy-natural-resources',
    name: 'Federal Power Commission v. Hope Natural Gas Co.',
    citation: '320 U.S. 591 (1944)',
    jurisdiction: 'Federal',
    court: 'United States Supreme Court',
    year: 1944,
    facts: 'Hope Natural Gas Company was a West Virginia natural gas producer and distributor regulated under the Natural Gas Act of 1938. The Federal Power Commission (FPC) issued an order reducing Hope\'s wholesale rates, applying a cost-of-service methodology that set the rate base at original cost (historical cost of plant) rather than reproduction cost or fair value as Hope preferred. Hope challenged the FPC\'s rate order, arguing that the resulting rates were confiscatory because they did not provide a constitutionally adequate return on the fair market value of its property. The company contended that the commission\'s original-cost methodology failed to allow sufficient earnings to maintain its financial integrity and attract capital. The dispute centered on the proper constitutional standard for determining a fair rate of return for regulated utilities under the Fifth Amendment\'s Takings Clause.',
    keyLegalIssues: [
      'Whether the FPC\'s use of an original-cost rate base rather than fair market value violated the Due Process or Takings Clauses of the Constitution',
      'What constitutes a constitutionally adequate standard for utility rate regulation under the Natural Gas Act',
      'Whether the "end result" of a rate order, rather than the specific methodology employed, is the proper constitutional test',
      'The scope of federal agency discretion in setting natural gas wholesale rates',
    ],
    plaintiffArguments: 'The FPC argued that the Natural Gas Act granted it broad discretion to choose the rate-making methodology it deemed most appropriate, and that original cost was a rational, administratively workable basis for setting rates. The Commission contended that the constitutional requirement was satisfied so long as the resulting rates allowed the utility to operate successfully, maintain its financial integrity, attract capital, and compensate investors for risks assumed. The FPC maintained that rigid adherence to any single valuation formula was not constitutionally compelled.',
    defendantArguments: 'Hope Natural Gas argued that the Smyth v. Ames (1898) fair value standard required the FPC to consider reproduction cost and market value of property when setting rates, and that failure to do so was constitutionally defective. Hope contended the rates set were confiscatory because they yielded an insufficient return on the true value of its invested property. The company maintained that regulatory agencies could not arbitrarily ignore established constitutional standards by simply substituting original cost for fair market value.',
    proceduralHistory: 'The FPC issued an order setting Hope\'s rates based on original cost. Hope challenged the order in the Fourth Circuit Court of Appeals, which vacated the FPC\'s order and held that the fair value standard of Smyth v. Ames required consideration of reproduction cost. The Supreme Court granted certiorari to resolve the conflict over the proper constitutional standard for utility rate regulation.',
    finalDecision: 'The Supreme Court reversed the Fourth Circuit and upheld the FPC\'s rate order. The Court held that the "end result" test governs constitutional adequacy of utility rates — if the resulting rate allows the utility to operate successfully, maintain financial integrity, attract capital, and compensate investors for risks, it is constitutionally permissible regardless of the methodology used to reach it.',
    judicialReasoning: 'Justice Douglas, writing for the majority, rejected the rigid Smyth v. Ames fair-value formula and replaced it with an "end result" test. The Court reasoned that regulatory agencies must be given flexibility in rate-making because no single formula works equitably in all circumstances. The majority emphasized that the constitution does not demand any particular methodology; what matters is whether the utility can maintain financial integrity and attract capital at the rates set. The Court noted that rate-making is a legislative, not judicial, function and that courts should defer to agency expertise in this technical domain. The decision effectively overruled the Smyth v. Ames fair-value requirement, freeing regulators from having to use market-value-based rate bases.',
    legalStandards: [
      'End-result test for constitutional adequacy of utility rates',
      'FPC authority under the Natural Gas Act of 1938 to set just and reasonable rates',
      'Fifth Amendment Takings Clause limits on rate regulation',
      'Original-cost rate base methodology',
    ],
    keyPrecedents: [
      'Smyth v. Ames, 169 U.S. 466 (1898) — overruled as mandatory formula',
      'Bluefield Water Works & Improvement Co. v. PSC of West Virginia, 262 U.S. 679 (1923)',
      'Natural Gas Act of 1938, 15 U.S.C. § 717 et seq.',
    ],
    evidenceAnalysis: 'The FPC compiled detailed cost-of-service data, depreciation schedules, and original plant investment records to support its rate order. Hope submitted expert testimony on reproduction cost and market valuations, which the FPC weighed but declined to make determinative. The Court reviewed the commission\'s evidentiary record and found adequate factual support for the rates imposed. The sufficiency of return on original cost was demonstrated through capital market comparisons and financial integrity metrics.',
    alternativeOutcomes: 'Had the Court affirmed the Fourth Circuit, regulators would have been constitutionally required to use fair-value (reproduction-cost) rate bases, dramatically increasing rates paid by consumers during wartime and thereafter. Alternatively, a ruling requiring a hybrid methodology could have created continuing litigation over the proper weighting of reproduction cost versus original cost, burdening both agencies and courts.',
    lessonsLearned: [
      'Regulatory agencies have broad methodological discretion in rate-making so long as the end result is constitutionally adequate',
      'Courts should defer to agency expertise in technical utility rate proceedings',
      'The constitution permits original-cost rate bases, which tend to produce lower rates than fair-value approaches',
      'Utility investors bear the risk that regulation may limit returns to less than full market-value recovery',
    ],
    bestPractices: [
      'Regulators should document the financial integrity and capital-attraction adequacy of rates, not merely the methodology chosen',
      'Utilities challenging rate orders must demonstrate that the overall result is confiscatory, not merely that the methodology differs from their preference',
      'Rate proceedings should include comparable-earnings evidence to show adequacy of return',
      'Agencies should build a thorough record supporting the end-result adequacy of any rate order',
    ],
    significance: 'Hope Natural Gas is the foundational precedent for modern utility rate regulation in the United States. By replacing the Smyth v. Ames fair-value formula with the flexible end-result test, the Court liberated regulatory agencies from judicially imposed accounting constraints and permitted original cost to become the dominant rate-base methodology. The decision enabled regulators to hold consumer rates lower than they would have been under fair-value accounting, fundamentally shaping the economics of regulated industries for decades. It also established the principle of judicial deference to agency expertise in rate proceedings, influencing administrative law broadly. The case remains the bedrock constitutional standard for rate regulation across gas, electric, telephone, and other utility sectors.',
    outcome: 'Plaintiff Victory',
    isFeatured: true,
    parties: [
      {
        name: 'Federal Power Commission',
        role: 'PLAINTIFF',
        description: 'Federal regulatory agency responsible for setting wholesale natural gas rates under the Natural Gas Act of 1938',
      },
      {
        name: 'Hope Natural Gas Company',
        role: 'DEFENDANT',
        description: 'West Virginia natural gas producer and distributor challenging the FPC\'s rate order as constitutionally confiscatory',
      },
    ],
  },
  {
    litigationSlug: 'energy-natural-resources',
    name: 'Phillips Petroleum Co. v. Wisconsin',
    citation: '347 U.S. 672 (1954)',
    jurisdiction: 'Federal',
    court: 'United States Supreme Court',
    year: 1954,
    facts: 'Phillips Petroleum Company was a major independent producer of natural gas that sold gas at the wellhead to interstate pipeline companies for resale in interstate commerce. The State of Wisconsin, along with other state public utility commissions and municipalities, petitioned the Federal Power Commission to assert jurisdiction over Phillips\'s wellhead sales, arguing that such prices directly affected the rates ultimately charged to consumers in interstate commerce. Phillips contended that the Natural Gas Act of 1938 did not grant the FPC jurisdiction over production and gathering activities, placing its wellhead sales beyond federal regulatory reach. The FPC initially declined jurisdiction, reasoning that Congress had excluded production and gathering from its authority. The dispute had enormous practical consequences because extending FPC jurisdiction to wellhead prices would subject thousands of independent producers to federal rate regulation.',
    keyLegalIssues: [
      'Whether the FPC had jurisdiction under the Natural Gas Act to regulate the wellhead sales price of natural gas by independent producers to interstate pipeline companies',
      'Whether the Natural Gas Act\'s exclusion of "production or gathering" from FPC jurisdiction covered wellhead sales or only the physical acts of production',
      'The scope of "sale in interstate commerce for resale" under Section 1(b) of the Natural Gas Act',
      'Whether economic policy considerations could inform the Court\'s statutory interpretation of regulatory jurisdiction',
    ],
    plaintiffArguments: 'Wisconsin and the other state petitioners argued that the Natural Gas Act\'s grant of FPC jurisdiction over "sales of natural gas in interstate commerce for resale" plainly encompassed Phillips\'s wellhead sales to interstate pipelines, since those sales were the first link in the chain of interstate commerce. They contended that without wellhead price regulation, pipeline companies would pass through high field prices to consumers, undermining the entire regulatory scheme Congress had established. The states maintained that the production-and-gathering exclusion addressed only the physical acts of extraction, not commercial sales.',
    defendantArguments: 'Phillips argued that the Natural Gas Act\'s explicit exclusion of "the production or gathering of natural gas" from FPC jurisdiction immunized its wellhead sales from federal regulation because such sales were an integral part of the production and gathering function. The company contended that regulating thousands of independent producers would be administratively unworkable and that Congress did not intend such an expansive regulatory regime. Phillips also argued that the legislative history of the Act demonstrated congressional intent to leave producer markets to state regulation and free-market forces.',
    proceduralHistory: 'Wisconsin and others petitioned the FPC to assert jurisdiction over Phillips\'s rates. The FPC dismissed the petition, concluding it lacked jurisdiction over independent producer sales. The Court of Appeals for the District of Columbia Circuit reversed, holding the FPC did have jurisdiction. The Supreme Court granted certiorari to resolve the critical jurisdictional question.',
    finalDecision: 'The Supreme Court affirmed the D.C. Circuit and held that the FPC had jurisdiction under the Natural Gas Act over Phillips\'s wellhead sales of natural gas to interstate pipeline companies. The Court ruled that the production-and-gathering exclusion did not exempt sales made at the wellhead from the Act\'s coverage of interstate sales for resale.',
    judicialReasoning: 'Justice Clark, writing for the majority, concluded that the statutory text covering "sales of natural gas in interstate commerce for resale" unambiguously included Phillips\'s transactions. The Court reasoned that excluding wellhead sales would create a regulatory gap that would undermine the congressional purpose of protecting consumers from excessive gas prices throughout the interstate chain. The majority distinguished between the physical activities of production and gathering, which the Act exempted, and commercial sales transactions, which it covered. The Court acknowledged the administrative burden of regulating thousands of producers but concluded that the statutory language compelled the result. The decision effectively required the FPC to embark on the enormous task of setting just-and-reasonable rates for all independent producer wellhead sales.',
    legalStandards: [
      'Natural Gas Act of 1938, Section 1(b) jurisdictional scope',
      'Exclusion of "production or gathering" from FPC authority',
      '"Sales in interstate commerce for resale" statutory coverage',
      'Purposivist statutory interpretation to prevent regulatory gaps',
    ],
    keyPrecedents: [
      'Interstate Natural Gas Co. v. FPC, 331 U.S. 682 (1947)',
      'Colorado Interstate Gas Co. v. FPC, 324 U.S. 581 (1945)',
      'Federal Power Commission v. Hope Natural Gas Co., 320 U.S. 591 (1944)',
    ],
    evidenceAnalysis: 'The Court examined the legislative history of the Natural Gas Act, including committee reports and floor debates, to determine congressional intent regarding producer regulation. Evidence showed that Congress was aware of the gap argument but the statutory text\'s plain meaning carried the day. FPC records demonstrated the cascading effect of unregulated wellhead prices on downstream interstate pipeline and consumer rates. Economic analyses submitted by Wisconsin showed significant consumer price impacts from unregulated producer sales.',
    alternativeOutcomes: 'Had the Court ruled for Phillips, wellhead gas prices would have been entirely unregulated at the federal level, likely resulting in significantly higher consumer natural gas prices during the post-war era. The absence of producer rate regulation could have accelerated depletion of domestic reserves through rapid, high-price development. Conversely, keeping producer sales unregulated might have avoided the severe natural gas shortages of the 1970s that many economists attributed to artificially low FPC-mandated wellhead prices discouraging production.',
    lessonsLearned: [
      'Statutory grants of regulatory jurisdiction will be construed broadly when necessary to effectuate the consumer-protection purposes of the legislation',
      'Regulatory gaps in multi-tiered industries can frustrate the entire statutory scheme if upstream transactions are left unregulated',
      'Administrative workability is not a sufficient reason to read jurisdiction out of an otherwise plain statutory grant',
      'Wellhead price controls can produce long-term supply distortions, as the subsequent natural gas shortage of the 1970s demonstrated',
    ],
    bestPractices: [
      'Industry participants should seek explicit statutory exemptions rather than relying on implied exclusions from regulatory jurisdiction',
      'Regulators must develop scalable methodologies when extending jurisdiction to large numbers of small market participants',
      'Policymakers should anticipate long-run supply effects when imposing price ceilings on natural resource markets',
      'States should monitor whether federal regulatory gaps at the production level undermine state consumer-protection goals',
    ],
    significance: 'Phillips Petroleum v. Wisconsin is one of the most consequential energy law decisions of the twentieth century. By extending FPC jurisdiction to wellhead natural gas prices, the Court set in motion decades of federal producer price regulation that shaped the entire structure of the U.S. natural gas industry. The resulting price controls contributed to the natural gas shortages and curtailments of the 1970s, ultimately leading Congress to enact the Natural Gas Policy Act of 1978 and the Natural Gas Wellhead Decontrol Act of 1989. The case illustrates how a single jurisdictional ruling by the Supreme Court can reshape an entire industry for generations. It also remains a landmark in the interpretation of regulatory statutes and the tension between administrative workability and consumer protection.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'State of Wisconsin (and other state commissions)',
        role: 'PLAINTIFF',
        description: 'State public utility commissions and municipalities seeking FPC regulation of independent producer wellhead gas prices',
      },
      {
        name: 'Phillips Petroleum Company',
        role: 'DEFENDANT',
        description: 'Major independent natural gas producer contesting FPC jurisdiction over its wellhead sales to interstate pipelines',
      },
    ],
  },
  {
    litigationSlug: 'energy-natural-resources',
    name: 'Pacific Gas & Electric Co. v. State Energy Resources Conservation & Development Commission',
    citation: '461 U.S. 190 (1983)',
    jurisdiction: 'Federal',
    court: 'United States Supreme Court',
    year: 1983,
    facts: 'California enacted Section 25524.2 of its Public Resources Code, which imposed a moratorium on the certification of new nuclear power plants until the State Energy Resources Conservation and Development Commission found that there was an adequate demonstrated technology or means for the disposal of high-level nuclear waste. Pacific Gas and Electric Company (PG&E) and other California utilities challenged the statute, arguing that it was preempted by the federal Atomic Energy Act (AEA) because Congress had delegated nuclear safety regulation exclusively to the Nuclear Regulatory Commission (NRC). California defended the statute as a legitimate exercise of its authority over the economic and land-use dimensions of power plant siting, asserting that its concern was the economic risk of operating plants that lacked a waste-disposal solution rather than radiological safety. The case arose against the backdrop of the Three Mile Island accident in 1979 and widespread public concern about nuclear waste.',
    keyLegalIssues: [
      'Whether the Atomic Energy Act preempted California\'s moratorium on new nuclear plant certification pending a waste-disposal solution',
      'Whether Congress intended to occupy the field of nuclear safety regulation to the exclusion of state action',
      'Whether California\'s stated economic rationale for the moratorium was pretextual or a legitimate non-safety state interest',
      'The boundary between federal nuclear safety jurisdiction and state authority over power plant economics and siting',
    ],
    plaintiffArguments: 'PG&E and the utilities argued that California\'s statute was a thinly veiled attempt to regulate nuclear safety — specifically the safety of nuclear waste storage — in a field exclusively occupied by federal law under the AEA. They contended that the NRC had plenary authority over radiological hazards and that states could not impose conditions on new nuclear plants that were predicated on unresolved safety concerns. The utilities also argued that the moratorium unconstitutionally burdened interstate commerce and frustrated federal energy policy favoring nuclear power development.',
    defendantArguments: 'California argued that its statute was rooted in economic and land-use policy, not safety regulation: the state was exercising its traditional authority over the economics of power generation by refusing to certify plants that posed unacceptable financial risks to ratepayers because of unresolved waste-disposal costs. The Commission maintained that the federal government had not preempted state authority over the economic dimensions of power plant siting, and that a state could legitimately decide it did not want the economic burden of plants whose fuel cycle was incomplete. California emphasized that its decision-making standard was economic feasibility of waste disposal, not radiological risk.',
    proceduralHistory: 'PG&E filed suit in federal district court challenging the California statute on federal preemption and Commerce Clause grounds. The district court held the statute preempted. The Ninth Circuit Court of Appeals reversed, upholding the state law. The Supreme Court granted certiorari given the importance of the question to national energy policy.',
    finalDecision: 'The Supreme Court affirmed the Ninth Circuit and upheld the California moratorium. The Court held that the Atomic Energy Act preempted state regulation of nuclear safety but did not preempt California\'s statute because it rested on economic rather than safety grounds, a distinction the Court accepted on the face of the legislation.',
    judicialReasoning: 'Justice White, writing for a unanimous Court, confirmed that the AEA and NRC regulations occupied the field of nuclear safety, preempting state laws directed at radiological hazards. However, the Court accepted California\'s stated rationale that the moratorium addressed the economic risk of nuclear power without an assured waste-disposal solution rather than safety risks per se. The Court refused to invalidate the statute on the ground that its economic rationale was pretextual, finding insufficient basis to second-guess the state legislature\'s declared purpose. The majority drew a distinction between states regulating nuclear safety (preempted) and states making economic and land-use judgments about the desirability of nuclear power (reserved to the states). The Court noted that states retain authority over the need for and economic feasibility of new generating capacity under the traditional state role in regulating electrical utilities.',
    legalStandards: [
      'Field preemption under the Supremacy Clause in the area of nuclear safety',
      'Atomic Energy Act of 1954 and NRC\'s exclusive authority over radiological hazards',
      'State police power over economic and land-use aspects of power plant siting',
      'Conflict preemption analysis in dual-purpose regulatory statutes',
    ],
    keyPrecedents: [
      'Northern States Power Co. v. Minnesota, 447 F.2d 1143 (8th Cir. 1971), aff\'d mem., 405 U.S. 1035 (1972)',
      'Silkwood v. Kerr-McGee Corp., 464 U.S. 238 (1984)',
      'Hines v. Davidowitz, 312 U.S. 52 (1941) — preemption doctrine',
    ],
    evidenceAnalysis: 'The Court examined the text and legislative history of the Atomic Energy Act to determine the scope of federal preemption. California\'s legislative record was scrutinized to determine whether the economic rationale was genuine or a pretext for safety regulation. Expert testimony and commission reports demonstrated the real economic uncertainty surrounding nuclear waste disposal costs and long-term liability. The NRC\'s own findings that the waste problem had not been solved lent credence to California\'s economic concern.',
    alternativeOutcomes: 'Had the Court held the statute preempted, states would have lost significant leverage to shape their electricity generation mix and ratepayer risk exposure in the nuclear arena. California\'s ability to protect ratepayers from potentially stranded nuclear investments would have been curtailed. Conversely, a ruling that expressly allowed states to regulate nuclear waste on safety grounds could have created a patchwork of fifty different nuclear safety regimes, fragmenting federal regulatory authority.',
    lessonsLearned: [
      'The framing and legislative history of a state statute is critical to surviving preemption analysis — a law addressing economic concerns can survive even if it incidentally affects federally regulated activity',
      'States retain meaningful authority over the economics and land-use dimensions of energy facility siting notwithstanding broad federal regulatory occupation of the safety field',
      'Federal preemption does not automatically extend to every state decision that touches on a federally regulated industry',
      'Nuclear waste policy uncertainty creates real and legally cognizable economic risks that states may legitimately weigh in energy planning',
    ],
    bestPractices: [
      'State legislatures should carefully articulate non-safety economic rationales for nuclear energy restrictions to survive preemption challenge',
      'Utilities should engage state regulators early in the plant-certification process to surface preemption issues before litigation',
      'Federal energy policy should provide regulatory certainty on waste disposal to reduce state-level uncertainty and potential state restrictions',
      'Legal challenges to state energy statutes should develop a complete record of legislative purpose rather than relying solely on facial preemption arguments',
    ],
    significance: 'Pacific Gas & Electric v. State Energy Commission is the leading Supreme Court precedent on the boundary between federal nuclear safety preemption and state authority over the economics of electricity generation. The decision preserved state power to shape their energy mixes on economic grounds, influencing subsequent state renewable portfolio standards, nuclear moratoriums, and integrated resource planning. It has been cited in dozens of cases involving the intersection of federal energy law and state utility regulation. The ruling contributed to the practical slowing of nuclear plant construction in the United States during the 1980s by confirming states\' legal ability to impose economically based barriers. The case remains essential reading for energy lawyers navigating federal-state jurisdictional boundaries in electricity and nuclear matters.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Pacific Gas and Electric Company',
        role: 'PLAINTIFF',
        description: 'California electric utility challenging the state nuclear moratorium as federally preempted',
        counsel: 'Argued by Jerome B. Falk Jr.',
      },
      {
        name: 'State Energy Resources Conservation and Development Commission',
        role: 'DEFENDANT',
        description: 'California state commission defending the nuclear plant certification moratorium as an economic regulation within state authority',
        counsel: 'Argued by Laurence H. Tribe',
      },
    ],
  },
  {
    litigationSlug: 'energy-natural-resources',
    name: 'FPC v. Florida Power & Light Co.',
    citation: '404 U.S. 453 (1972)',
    jurisdiction: 'Federal',
    court: 'United States Supreme Court',
    year: 1972,
    facts: 'Florida Power & Light Company (FPL) operated an interconnected electric system that was physically connected, through transmission ties, with the systems of other utilities in the southeastern United States. The Federal Power Commission (FPC) sought to assert jurisdiction over FPL under the Federal Power Act (FPA), which granted the agency authority over the transmission of electric energy in interstate commerce and over the sale of electric energy at wholesale in interstate commerce. FPL\'s electricity did not physically cross state lines — all of its generation, transmission, and distribution facilities were located within Florida — but electrons from FPL\'s system did commingle with electrons from other states through the interconnection. The FPC argued that this physical commingling made FPL\'s transmissions part of interstate commerce, giving the commission jurisdiction.',
    keyLegalIssues: [
      'Whether the Federal Power Act grants the FPC jurisdiction over an electric utility that operates entirely within one state but is interconnected with out-of-state systems',
      'Whether the commingling of electrons through interstate interconnections subjects intrastate utilities to federal jurisdiction under the FPA',
      'The definition of "interstate commerce" as applied to electric energy transmission through interconnected grids',
      'The scope of the FPC\'s jurisdiction over local distribution and transmission facilities',
    ],
    plaintiffArguments: 'The FPC argued that because FPL\'s system was physically interconnected with out-of-state utilities and electrons flowing into FPL\'s system could be traced to out-of-state generation (even if electrons themselves are fungible and indistinguishable), FPL\'s transmissions were part of a stream of interstate commerce subject to federal regulation. The commission contended that a broad construction of FPA jurisdiction was necessary to ensure reliable, coordinated management of the interconnected national grid. The FPC also emphasized that the practical effect of FPL\'s operations on interstate electric markets justified federal oversight.',
    defendantArguments: 'Florida Power & Light argued that it was a purely intrastate utility — all its facilities, customers, and operations were within Florida — and that the FPA\'s jurisdictional grant did not reach utilities merely because electrons physically commingle at interconnection points. FPL maintained that the commingling of fungible electrons did not transform its intrastate operations into interstate commerce. The company contended that Congress had preserved state regulatory authority over local electric utilities and that extending federal jurisdiction on the basis of physical interconnection would swallow the intrastate exception in the FPA.',
    proceduralHistory: 'The FPC initiated proceedings to assert jurisdiction over FPL\'s facilities. FPL contested jurisdiction, and the matter was litigated before the Commission. On review, the Fifth Circuit Court of Appeals held that the FPC lacked jurisdiction over FPL because its operations were intrastate in character. The Supreme Court granted certiorari to resolve the jurisdictional question.',
    finalDecision: 'The Supreme Court reversed the Fifth Circuit and held that the FPC had jurisdiction over FPL\'s transmission facilities because FPL\'s system was interconnected with out-of-state utilities and electrons from out-of-state generators commingled with those on FPL\'s system, making the transmissions part of interstate commerce within the meaning of the Federal Power Act.',
    judicialReasoning: 'Justice Douglas, writing for the majority, reasoned that the commingling of electrons from out-of-state generators on FPL\'s lines was sufficient to constitute interstate transmission of electric energy, even though FPL\'s physical facilities were entirely in Florida and no individual electron\'s origin could be traced. The Court applied a functional analysis rather than a tracing approach, noting that electricity markets are operated as interconnected systems where state boundaries are physically irrelevant to electron flow. The majority concluded that Congress, in enacting the FPA, intended federal jurisdiction to track the physical realities of electricity transmission on interconnected grids. The decision significantly expanded the FPC\'s jurisdictional reach over investor-owned utilities operating within interconnected grid regions.',
    legalStandards: [
      'Federal Power Act Section 201 jurisdictional scope over interstate transmission and wholesale sales',
      'Commerce Clause application to electricity as a physical commodity',
      'Commingling doctrine for interstate commerce jurisdiction over electric utilities',
      'Intrastate utility exception under the FPA',
    ],
    keyPrecedents: [
      'Connecticut Light & Power Co. v. FPC, 324 U.S. 515 (1945)',
      'Panhandle Eastern Pipe Line Co. v. Public Serv. Comm\'n, 332 U.S. 507 (1947)',
      'United States v. Wrightwood Dairy Co., 315 U.S. 110 (1942)',
    ],
    evidenceAnalysis: 'Engineering evidence established the physical interconnection between FPL\'s system and out-of-state utility systems, and demonstrated that electrons from out-of-state generating plants flowed onto FPL\'s transmission lines under normal operating conditions. FPC experts testified about the nature of alternating-current grids and the impossibility of segregating electrons by geographic origin. FPL\'s own operating data confirmed that system imports and exports occurred continuously across the interstate ties. The technical record was central to the Court\'s commingling analysis.',
    alternativeOutcomes: 'Had the Court upheld the Fifth Circuit, the FPC\'s jurisdiction would have been confined to utilities that explicitly sold power across state lines or owned transmission lines crossing state borders, excluding most southeastern utilities from federal oversight. This would have created a significant gap in federal regulation of the emerging interconnected national grid. Alternatively, Congress might have been prompted to amend the FPA to more explicitly extend jurisdiction to interconnected systems, potentially resolving the question legislatively.',
    lessonsLearned: [
      'Physical interconnection with interstate systems subjects an otherwise intrastate utility to federal jurisdiction under the Federal Power Act',
      'The fungible nature of electricity means that origin-tracing approaches to jurisdiction are unworkable — courts will apply functional grid-level analyses',
      'Utilities operating in interconnected regions should assume federal jurisdiction will apply to their transmission and wholesale activities',
      'The commingling doctrine established in FPC v. Florida Power & Light continues to govern jurisdictional disputes over integrated grid operators',
    ],
    bestPractices: [
      'Electric utilities should assess their interconnection arrangements when evaluating the scope of applicable federal versus state regulation',
      'Regulatory counsel should analyze transmission system topology when advising on FPA jurisdiction in borderline cases',
      'State regulators should be aware that interconnected utilities may be subject to concurrent federal jurisdiction over wholesale and transmission activities',
      'Utilities challenging federal jurisdiction should build a complete factual record regarding the nature and extent of their interstate interconnections',
    ],
    significance: 'FPC v. Florida Power & Light established the commingling doctrine as the basis for FPC — now FERC — jurisdiction over electric utilities interconnected with interstate grids, fundamentally defining the reach of federal regulation over the U.S. electric power system. The decision enabled the FPC and its successor FERC to regulate the interconnected bulk power system as a national grid rather than as a collection of state-by-state systems. This jurisdictional foundation underpinned subsequent FERC orders opening transmission access and eventually restructuring wholesale electricity markets across the country. The case remains a touchstone in electric utility regulation and is regularly cited in FERC proceedings and federal court litigation over the agency\'s jurisdictional boundaries.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Federal Power Commission',
        role: 'PLAINTIFF',
        description: 'Federal agency asserting jurisdiction over FPL\'s transmission system based on interstate interconnection',
      },
      {
        name: 'Florida Power & Light Company',
        role: 'DEFENDANT',
        description: 'Florida electric utility challenging FPC jurisdiction over its intrastate electric operations',
      },
    ],
  },
  {
    litigationSlug: 'energy-natural-resources',
    name: 'FERC v. Electric Power Supply Association',
    citation: '577 U.S. 260 (2016)',
    jurisdiction: 'Federal',
    court: 'United States Supreme Court',
    year: 2016,
    facts: 'The Federal Energy Regulatory Commission (FERC) issued Order 745 in 2011, requiring wholesale electricity market operators to compensate demand response providers — entities that agree to reduce electricity consumption during peak demand periods — at the same "locational marginal price" (LMP) paid to electricity generators. Demand response is the practice of paying consumers to curtail electricity use rather than bringing additional generation online, and FERC found it significantly reduced wholesale market prices and improved grid reliability. The Electric Power Supply Association (EPSA), representing electricity generators who viewed demand response compensation as competitively threatening to their revenues, challenged FERC\'s authority to regulate demand response in wholesale markets. EPSA argued that demand response involves retail customers and retail electricity consumption, which falls outside FERC\'s wholesale market jurisdiction under the Federal Power Act and is reserved to state regulators.',
    keyLegalIssues: [
      'Whether FERC has authority under the Federal Power Act to regulate demand response in wholesale electricity markets',
      'Whether demand response compensation rules directly regulate retail electricity consumption in violation of the FPA\'s reservation of retail jurisdiction to states',
      'Whether FERC\'s Order 745 compensation rule (LMP minus G) was arbitrary and capricious under the Administrative Procedure Act',
      'The boundary between FERC wholesale market jurisdiction and state retail electricity jurisdiction under the FPA',
    ],
    plaintiffArguments: 'EPSA argued that FERC\'s Order 745 improperly extended the agency\'s jurisdiction into the retail electricity market, which Section 201(b) of the FPA expressly reserves to state regulation. The association contended that demand response programs directly regulate how much electricity retail customers consume — an inherently retail function — and that FERC could not circumvent this jurisdictional limit simply by operating through wholesale market mechanisms. EPSA also argued that Order 745\'s compensation formula was arbitrary because it did not account for the fact that demand response providers save money by not purchasing retail electricity while simultaneously receiving LMP payments.',
    defendantArguments: 'FERC argued that it had explicit authority under FPA Section 206 to correct unjust and unreasonable practices in wholesale electricity markets, and that demand response directly and substantially affects wholesale market prices and outcomes. The commission contended that Order 745 regulated the terms and conditions of wholesale market participation rather than retail consumption per se, and that its rules operated only through wholesale markets. FERC maintained that the rule\'s effect on retail customer behavior was incidental to its direct regulation of wholesale market transactions, preserving the jurisdictional distinction. The commission also defended the LMP-minus-G compensation formula as a reasoned policy choice within its ratemaking discretion.',
    proceduralHistory: 'FERC issued Order 745 in 2011 after notice-and-comment rulemaking. EPSA petitioned for review in the D.C. Circuit Court of Appeals. The D.C. Circuit vacated Order 745, holding that FERC had exceeded its jurisdiction by regulating retail customer behavior and that the compensation rule was arbitrary. The Supreme Court granted certiorari given the significant implications for wholesale electricity market regulation.',
    finalDecision: 'The Supreme Court reversed the D.C. Circuit in a 6-2 decision and upheld FERC\'s Order 745. The Court held that FERC had jurisdiction to regulate demand response in wholesale markets because such regulation directly affects wholesale rates, and that the FPA\'s reservation of retail jurisdiction to states does not bar FERC from regulating wholesale market rules that incidentally involve retail customers.',
    judicialReasoning: 'Justice Kagan, writing for the majority, analyzed the jurisdictional boundary between FERC\'s wholesale authority and state retail authority. The Court concluded that FERC\'s Order 745 regulated wholesale market transactions — the terms on which demand response providers participate in wholesale markets — rather than retail consumption directly. The majority applied Chevron deference to FERC\'s interpretation of its own jurisdictional limits, finding the agency\'s reading reasonable. The Court reasoned that the FPA\'s jurisdictional line tracks the nature of the transaction being regulated, not the identity of the market participant, and that demand response participation in wholesale markets is a wholesale transaction. The majority also upheld FERC\'s LMP-minus-G compensation formula as a permissible policy choice supported by the record, rejecting the D.C. Circuit\'s arbitrariness ruling. Justice Scalia dissented, joined by Justice Thomas, arguing that Order 745 effectively compelled retail conduct and exceeded FERC\'s statutory authority.',
    legalStandards: [
      'Federal Power Act Section 201(b) retail jurisdiction reservation to states',
      'FERC\'s Section 206 authority to remedy unjust and unreasonable wholesale rate practices',
      'Chevron deference to agency interpretation of jurisdictional scope',
      'Arbitrary and capricious review of agency ratemaking formulas under the APA',
    ],
    keyPrecedents: [
      'New England Power Co. v. New Hampshire, 455 U.S. 331 (1982)',
      'Chevron U.S.A. Inc. v. Natural Resources Defense Council, 467 U.S. 837 (1984)',
      'Morgan Stanley Capital Group Inc. v. Public Util. Dist. No. 1, 554 U.S. 527 (2008)',
      'Mississippi Power & Light Co. v. Mississippi ex rel. Moore, 487 U.S. 354 (1988)',
    ],
    evidenceAnalysis: 'FERC\'s rulemaking record included substantial evidence from wholesale market operators demonstrating that demand response resources significantly reduced wholesale electricity prices and enhanced grid reliability during peak demand periods. Market data showed demand response prevented price spikes and reduced the need for costly peaker generation. EPSA submitted economic analyses arguing that the LMP compensation formula overcompensated demand response providers by failing to net out the retail electricity costs they avoided. FERC\'s expert analysis supported the LMP-minus-G formula as appropriately reflecting the net benefit demand response provides to wholesale markets.',
    alternativeOutcomes: 'Had the Court affirmed the D.C. Circuit, FERC would have been barred from encouraging demand response in wholesale markets, potentially leaving wholesale markets less efficient and more vulnerable to price spikes and reliability emergencies. State regulators would have retained exclusive authority over demand response, resulting in a fragmented patchwork of programs with varying compensation structures. Alternatively, a narrow ruling on the compensation formula alone could have preserved demand response jurisdiction while requiring FERC to redesign the payment methodology.',
    lessonsLearned: [
      'FERC has broad authority to regulate demand response and other demand-side resources when their participation materially affects wholesale electricity markets',
      'The FPA\'s jurisdictional line turns on the nature of the transaction regulated, not the identity of the market participant',
      'Chevron deference applies to FERC\'s interpretations of the scope of its own FPA jurisdiction in cases of genuine statutory ambiguity',
      'Demand response is a legitimate and legally protected tool for wholesale market operators to manage grid reliability and control electricity costs',
    ],
    bestPractices: [
      'Wholesale market participants offering demand response should structure their programs to operate through wholesale market mechanisms to preserve FERC jurisdictional protection',
      'Challengers to FERC orders should develop both jurisdictional and arbitrary-and-capricious arguments in parallel before the D.C. Circuit',
      'State regulators and FERC should coordinate on demand response programs to avoid conflicts between wholesale and retail market rules',
      'Electricity generators facing demand response competition should engage in rulemaking proceedings rather than relying solely on judicial challenge',
    ],
    significance: 'FERC v. Electric Power Supply Association is the most important electricity regulation decision of the early twenty-first century, confirming FERC\'s authority to integrate demand-side resources into wholesale electricity markets and spurring the widespread deployment of demand response across RTOs and ISOs nationwide. The decision enabled FERC to pursue a market design vision that treats reduced consumption as a functional equivalent of new generation, profoundly shaping the economics of the bulk power system. It also provided an important reaffirmation of Chevron deference to FERC\'s interpretations of its own jurisdictional boundaries at a time when such deference was under doctrinal pressure. The case has been central to subsequent litigation over FERC\'s authority to regulate distributed energy resources, energy storage, and other new technologies whose retail and wholesale dimensions overlap.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Federal Energy Regulatory Commission',
        role: 'PLAINTIFF',
        description: 'Federal agency defending Order 745 requiring wholesale market compensation for demand response at the locational marginal price',
        counsel: 'Solicitor General Donald B. Verrilli Jr.',
      },
      {
        name: 'Electric Power Supply Association',
        role: 'DEFENDANT',
        description: 'Trade association of electricity generators challenging FERC\'s authority to regulate demand response in wholesale markets',
        counsel: 'Argued by Paul D. Clement',
      },
    ],
  },
];

export default cases;
