import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'family-law',
    name: 'Loving v. Virginia',
    citation: '388 U.S. 1 (1967)',
    jurisdiction: 'Federal – United States',
    court: 'Supreme Court of the United States',
    year: 1967,
    isFeatured: true,
    facts: 'Richard Loving, a white man, and Mildred Jeter, a Black and Native American woman, were residents of Caroline County, Virginia, who traveled to Washington, D.C. in June 1958 to marry because Virginia law prohibited interracial marriage. Upon returning to Virginia, they were indicted under the state Racial Integrity Act of 1924 for cohabiting as man and wife against the peace and dignity of the Commonwealth. The trial court sentenced each to one year in jail, suspending the sentence on the condition that they leave Virginia and not return together for 25 years. The Lovings lived in Washington, D.C. for several years before initiating legal proceedings to challenge the conviction, filing a motion in 1963 to vacate the judgment on constitutional grounds. The case ultimately reached the Supreme Court, which agreed to hear it as a definitive challenge to anti-miscegenation statutes still in force across sixteen states.',
    keyLegalIssues: [
      'Whether Virginia\'s anti-miscegenation statutes violated the Equal Protection Clause of the Fourteenth Amendment',
      'Whether the statutes violated the Due Process Clause of the Fourteenth Amendment by infringing on the fundamental right to marry',
      'Whether a state may restrict marriage solely on the basis of racial classifications',
      'Whether the equal application of a statute to both races immunizes it from Fourteenth Amendment scrutiny',
    ],
    plaintiffArguments: 'The Lovings argued that Virginia\'s Racial Integrity Act rested entirely on invidious racial distinctions condemned by the Equal Protection Clause, serving no legitimate government purpose apart from maintaining white supremacy. They contended that marriage is a fundamental civil right of free citizens and that restricting it on racial grounds violated substantive due process. Their counsel Bernard Cohen and Philip Hirschkop further argued that the "equal application" theory—that the statute punished both races equally—was a logical fallacy that had already been rejected by the Court in other racial classification cases.',
    defendantArguments: 'Virginia defended the statute as a legitimate exercise of the state\'s traditional police power over domestic relations, arguing that regulation of marriage had historically been reserved to the states. The Commonwealth invoked the "equal application" theory, contending that because the statute punished members of all races equally for interracial marriage it did not discriminate on the basis of race. Virginia also cited a 1955 state court decision upholding similar legislation and argued that the Fourteenth Amendment was never intended to reach anti-miscegenation laws enacted by the same Congress that ratified it.',
    proceduralHistory: 'The Lovings were convicted in Caroline County Circuit Court in 1959 under Virginia Code Section 20-58. The Virginia Supreme Court of Appeals upheld the conviction in 1966, relying on the equal-application rationale and the state\'s authority over marriage. The United States Supreme Court granted certiorari and heard oral argument on April 10, 1967, issuing its unanimous opinion on June 12, 1967.',
    finalDecision: 'The Supreme Court unanimously reversed the convictions, holding that Virginia\'s anti-miscegenation statutes violated both the Equal Protection and Due Process Clauses of the Fourteenth Amendment. Chief Justice Warren\'s opinion declared that "the freedom to marry has long been recognized as one of the vital personal rights essential to the orderly pursuit of happiness by free men."',
    judicialReasoning: 'Chief Justice Warren, writing for a unanimous Court, applied strict scrutiny to Virginia\'s racial classification, finding that the state offered no legitimate overriding purpose independent of invidious racial discrimination. The Court rejected the equal-application theory, reasoning that the mere fact that a statute applies equally to members of different races does not exempt it from Fourteenth Amendment review when its very purpose is to maintain racial segregation. The opinion grounded the right to marry in substantive due process, holding that restricting the freedom to marry solely because of racial classifications "directly subverts the principle of equality at the heart of the Fourteenth Amendment." The Court also declined to defer to state authority over domestic relations when that authority was exercised in violation of federal constitutional guarantees.',
    legalStandards: [
      'Strict scrutiny for racial classifications under the Equal Protection Clause',
      'Fundamental right to marry protected by the Due Process Clause of the Fourteenth Amendment',
      'Rejection of the "equal application" theory as a shield against Fourteenth Amendment challenge',
      'State police power over marriage subordinated to federal constitutional requirements',
    ],
    keyPrecedents: [
      'McLaughlin v. Florida, 379 U.S. 184 (1964) – racial classifications in criminal statutes require strict scrutiny',
      'Skinner v. Oklahoma, 316 U.S. 535 (1942) – marriage and procreation as fundamental civil rights',
      'Pace v. Alabama, 106 U.S. 583 (1883) – overruled insofar as it validated equal-application theory for racial statutes',
    ],
    evidenceAnalysis: 'The factual record was straightforward: the Lovings\' marriage certificate from Washington, D.C. and their Virginia domicile established the prima facie violation. The constitutional challenge rested entirely on legal argument rather than disputed facts, with the Court examining the legislative history and stated purposes of Virginia\'s Racial Integrity Act to confirm that racial superiority was its sole rationale.',
    alternativeOutcomes: 'Had the Court applied rational basis review and upheld the statute, anti-miscegenation laws in sixteen states would have remained enforceable, delaying recognition of interracial marriage rights by an indeterminate period. Alternatively, a ruling narrowly striking down only criminal penalties—without addressing the right to marry—would have left civil prohibition of interracial marriage intact and required further litigation.',
    lessonsLearned: [
      'Racial classifications in family law statutes receive strict scrutiny regardless of equal application across races',
      'The right to marry is a fundamental liberty that states cannot restrict without compelling justification',
      'Longstanding legislative tradition and widespread state practice do not immunize a law from constitutional challenge',
      'Framing litigation around both Equal Protection and Due Process creates overlapping grounds for relief',
    ],
    bestPractices: [
      'Challenge family law statutes grounded in suspect classifications under both Equal Protection and substantive Due Process',
      'Identify and document the discriminatory legislative purpose behind facially neutral or equally applied statutes',
      'Coordinate with civil-rights organizations to develop comprehensive amicus support for landmark constitutional challenges',
      'Present sympathetic plaintiffs whose personal circumstances humanize the constitutional violation for the Court',
    ],
    significance: 'Loving v. Virginia is the foundational precedent establishing marriage as a fundamental constitutional right and prohibiting state-imposed racial restrictions on that right. The decision invalidated anti-miscegenation laws in sixteen states overnight and ended one of the most pervasive forms of legally sanctioned racial discrimination in American family law. Its doctrinal framework—strict scrutiny for racial classifications and substantive due process protection for the right to marry—was later extended in cases addressing sex-based distinctions in family law and, ultimately, the right of same-sex couples to marry in Obergefell v. Hodges (2015). The case remains the clearest illustration of the Supreme Court\'s role in striking down majoritarian legislation that violates fundamental rights guaranteed to a minority.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Richard Perry Loving',
        role: 'PLAINTIFF',
        counsel: 'Bernard S. Cohen; Philip J. Hirschkop',
        description: 'White Virginia resident who married Mildred Jeter in Washington, D.C. and was convicted under Virginia\'s Racial Integrity Act',
      },
      {
        name: 'Mildred Delores Jeter Loving',
        role: 'PLAINTIFF',
        counsel: 'Bernard S. Cohen; Philip J. Hirschkop',
        description: 'Black and Native American Virginia resident who married Richard Loving and co-defendant in the criminal prosecution',
      },
      {
        name: 'Commonwealth of Virginia',
        role: 'DEFENDANT',
        counsel: 'R. D. McIlwaine III, Assistant Attorney General of Virginia',
        description: 'State that prosecuted the Lovings under the Racial Integrity Act of 1924 and defended the statute on appeal',
      },
    ],
  },

  {
    litigationSlug: 'family-law',
    name: 'Troxel v. Granville',
    citation: '530 U.S. 57 (2000)',
    jurisdiction: 'Federal – United States',
    court: 'Supreme Court of the United States',
    year: 2000,
    facts: 'Jenifer and Gary Troxel were the paternal grandparents of Isabelle and Natalie Troxel, daughters of Tommie Granville and the Troxels\' deceased son Brad. After Brad\'s suicide in 1993, Tommie Granville limited the grandparents\' visitation to one short visit per month. The Troxels filed a petition under Washington Revised Code Section 26.10.160(3), a broad statute allowing "any person" to petition for visitation rights at "any time" when such visitation might serve the best interests of the child. The Washington trial court ordered significantly more visitation than Granville had offered, finding it in the children\'s best interests. Granville challenged the order as an unconstitutional infringement on her right as a fit parent to make decisions about her children\'s associations.',
    keyLegalIssues: [
      'Whether the Washington third-party visitation statute unconstitutionally infringed on parents\' Fourteenth Amendment liberty interest in directing their children\'s upbringing',
      'What standard of deference courts must give to fit parents\' decisions regarding third-party visitation',
      'Whether a state may grant visitation to any person over a fit parent\'s objection based solely on a best-interests-of-the-child finding',
      'How to balance parental constitutional rights against state interests in child welfare',
    ],
    plaintiffArguments: 'The Troxels argued that Washington\'s visitation statute served the compelling state interest in maintaining children\'s relationships with extended family members, particularly after the death of a parent, and that courts were well equipped to determine what visitation arrangement served the children\'s best interests. They contended that Granville\'s preference for limited visitation was unreasonable and not grounded in the children\'s welfare. The grandparents also argued that the state had a legitimate interest in protecting the children from the potential harm of severing significant family relationships.',
    defendantArguments: 'Granville argued that the Washington statute was facially unconstitutional as applied to fit parents because it permitted a court to override parental judgment based on nothing more than a best-interests finding, with no threshold showing of harm or parental unfitness. She contended that the Due Process Clause has long protected the fundamental right of parents to make decisions regarding the care, custody, and control of their children, and that this right required courts to give at least some special weight to a fit parent\'s determination before ordering third-party visitation.',
    proceduralHistory: 'The Washington Superior Court granted the Troxels\' petition and ordered expanded visitation in 1995. The Washington Court of Appeals reversed, holding the statute unconstitutional as applied. The Washington Supreme Court affirmed the reversal on broader grounds, striking the statute as facially unconstitutional. The United States Supreme Court granted certiorari and issued a plurality opinion in 2000.',
    finalDecision: 'A plurality of the Supreme Court affirmed the Washington Supreme Court\'s judgment, holding that the visitation order violated Granville\'s due process rights as applied. The plurality, authored by Justice O\'Connor, declined to rule on the statute\'s facial validity but held that the lower court had given insufficient weight to Granville\'s judgment as a fit parent.',
    judicialReasoning: 'Justice O\'Connor\'s plurality opinion reaffirmed that the Due Process Clause protects the fundamental right of parents to make decisions concerning the care, custody, and control of their children, tracing this liberty interest through Meyer v. Nebraska and Pierce v. Society of Sisters. The plurality found that Washington\'s statute, as applied, was constitutionally infirm because the trial court had accorded no special weight to the fit mother\'s already-generous offer of visitation and had simply imposed its own best-interests judgment. The opinion established that fit parents are presumed to act in their children\'s best interests, and a court must give that presumption some weight before overriding a parental decision. The fractured Court could not agree on a single rationale, leaving the precise constitutional standard unclear.',
    legalStandards: [
      'Fundamental parental liberty interest in the care, custody, and control of children under the Due Process Clause',
      'Presumption that fit parents act in the best interests of their children',
      'Requirement that courts give "special weight" to fit parents\' visitation decisions before ordering third-party access',
      'Best-interests standard alone is insufficient to override fit parental judgment on third-party visitation',
    ],
    keyPrecedents: [
      'Meyer v. Nebraska, 262 U.S. 390 (1923) – liberty interest in directing children\'s upbringing',
      'Pierce v. Society of Sisters, 268 U.S. 510 (1925) – parental right to direct education and upbringing',
      'Stanley v. Illinois, 405 U.S. 645 (1972) – parents\' interest in children requires procedural protection',
      'Parham v. J.R., 442 U.S. 584 (1979) – presumption of parental fitness',
    ],
    evidenceAnalysis: 'The trial record showed that Granville had allowed some grandparent visitation before the petition and had offered one short visit per month—evidence the plurality found significant as demonstrating her willingness to maintain the relationship on her own terms. The absence of any finding of harm from limiting visitation, or any finding of parental unfitness, was central to the constitutional defect identified by the plurality.',
    alternativeOutcomes: 'A majority opinion finding the Washington statute facially unconstitutional would have provided clearer guidance to state legislatures on permissible third-party visitation laws. Conversely, a ruling deferring entirely to the best-interests standard would have substantially eroded parental constitutional rights and potentially opened the door to broad judicial supervision of fit parents\' child-rearing decisions.',
    lessonsLearned: [
      'State third-party visitation statutes must provide procedural protection for fit parents\' decisions, not merely a best-interests balancing test',
      'A fit parent\'s demonstrated willingness to allow some contact weighs against judicial override of the parent\'s chosen terms',
      'Fractured Supreme Court opinions leave lower courts without a clear controlling standard, generating continued circuit splits',
      'Grandparent visitation petitions are more likely to succeed when accompanied by evidence of parental unfitness or demonstrable harm to the child',
    ],
    bestPractices: [
      'When representing grandparents, gather evidence of the existing relationship and document the child\'s attachment to the third party',
      'When representing a parent, emphasize parental fitness and any prior willingness to allow voluntary visitation',
      'Analyze state statutes for facial overbreadth that fails to require a threshold showing of harm or parental unfitness',
      'Account for the plurality\'s lack of a clear majority rule when predicting how a given state court will balance parental rights against third-party visitation claims',
    ],
    significance: 'Troxel v. Granville is the leading Supreme Court precedent on grandparent and third-party visitation rights, establishing that the Due Process Clause imposes meaningful limits on state courts\' ability to override fit parents\' judgments about their children\'s associations. Although the plurality\'s fragmented reasoning left the precise constitutional test uncertain, the decision prompted widespread legislative reform of third-party visitation statutes across the states and reaffirmed that parenthood carries constitutional weight that cannot be displaced by a mere judicial preference for a different outcome. The case continues to govern the outer limits of state visitation law and informs family law practitioners\' strategy in grandparent visitation disputes.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Gary Troxel and Jenifer Troxel',
        role: 'PLAINTIFF',
        counsel: 'Mark D. Olson',
        description: 'Paternal grandparents of the minor children who petitioned for court-ordered visitation after their son\'s death',
      },
      {
        name: 'Tommie Granville',
        role: 'DEFENDANT',
        counsel: 'Catherine Shaffer',
        description: 'Biological mother of the minor children who challenged the visitation order as an infringement on her parental rights',
      },
    ],
  },

  {
    litigationSlug: 'family-law',
    name: 'Santosky v. Kramer',
    citation: '455 U.S. 745 (1982)',
    jurisdiction: 'Federal – United States',
    court: 'Supreme Court of the United States',
    year: 1982,
    facts: 'John Santosky II and Annie Santosky were the biological parents of three children—Tina, John III, and Jed—who were removed from the family home by Ulster County, New York child protective services between 1973 and 1976 due to findings of neglect. The county Department of Social Services filed a petition to terminate the Santoskys\' parental rights permanently under New York Social Services Law Section 384-b. At the termination hearing, New York law required proof of permanent neglect only by a "fair preponderance of the evidence"—the lowest civil standard of proof. The parents argued that due process required a higher standard given the gravity and permanence of termination of parental rights. The family court terminated parental rights using the preponderance standard, and the Appellate Division affirmed.',
    keyLegalIssues: [
      'Whether the Due Process Clause of the Fourteenth Amendment requires a higher standard of proof than preponderance of the evidence in a state proceeding to terminate parental rights',
      'What standard of proof—clear and convincing evidence or proof beyond a reasonable doubt—is constitutionally required for permanent termination of parental rights',
      'How to weigh parents\' fundamental liberty interest against the state\'s parens patriae interest in child welfare',
      'Whether the risk of an erroneous deprivation of parental rights under a preponderance standard is constitutionally tolerable',
    ],
    plaintiffArguments: 'The Santoskys argued that the termination of parental rights—an irrevocable, permanent extinguishment of one of the most fundamental human relationships—was so severe a deprivation that due process required the state to prove its case by clear and convincing evidence at a minimum. They contended that New York\'s preponderance standard created an unacceptably high risk of erroneous termination and failed to account for the gross power imbalance between the state, with its professional legal apparatus, and impoverished parents with limited resources. They also argued that until the state proved permanent neglect by the higher standard, it could not constitutionally consider what disposition served the child\'s best interests.',
    defendantArguments: 'The Commissioner of Ulster County Social Services argued that the preponderance standard struck an appropriate balance between the state\'s parens patriae interest in protecting children from neglect and parents\' interests, noting that the children had already been adjudicated neglected and placed in foster care before the termination proceeding. The state contended that increasing the burden of proof would make it harder to protect children from abusive or neglectful parents and would leave children in legal limbo in foster care for longer periods. New York also argued that the best-interests-of-the-child calculus provided sufficient protection against erroneous termination.',
    proceduralHistory: 'The Ulster County Family Court terminated parental rights in 1978 under the preponderance standard. The New York Appellate Division, Third Department, affirmed. The New York Court of Appeals affirmed by a 4-3 vote, upholding the constitutionality of the preponderance standard. The U.S. Supreme Court granted certiorari to resolve the due process question.',
    finalDecision: 'The Supreme Court reversed 5-4, holding that the Due Process Clause requires clear and convincing evidence before a state may sever the rights of parents in their natural children. Justice Blackmun\'s majority opinion applied the Mathews v. Eldridge balancing test and concluded that the preponderance standard was constitutionally insufficient.',
    judicialReasoning: 'Justice Blackmun applied the three-factor Mathews v. Eldridge balancing test: the private interest affected, the risk of erroneous deprivation under existing procedures and the value of additional safeguards, and the government\'s interest. The majority found the parents\' liberty interest in the relationship with their children to be "far more precious than any property right" and the termination proceeding to be fundamentally one-sided, with the state employing trained lawyers and social workers against frequently unrepresented or underrepresented parents. The risk of an erroneous deprivation under the preponderance standard was deemed unacceptably high given the severity and permanence of termination. Although the state had a legitimate interest in protecting children, that interest aligned with the parents\' insofar as both required an accurate finding of permanent neglect—accuracy was better served by clear and convincing evidence. The Court expressly reserved the question whether proof beyond a reasonable doubt might also be required.',
    legalStandards: [
      'Mathews v. Eldridge three-factor procedural due process balancing test',
      'Clear and convincing evidence as the constitutionally mandated minimum standard of proof in parental rights termination proceedings',
      'Fundamental liberty interest of parents in the care and companionship of their children',
      'Due process requires procedures calibrated to the gravity and permanence of the deprivation at stake',
    ],
    keyPrecedents: [
      'Mathews v. Eldridge, 424 U.S. 319 (1976) – procedural due process balancing test',
      'Stanley v. Illinois, 405 U.S. 645 (1972) – parental rights require due process protection',
      'Lassiter v. Department of Social Services, 452 U.S. 18 (1981) – right to counsel in parental termination proceedings',
      'Addington v. Texas, 441 U.S. 418 (1979) – clear and convincing standard required for civil commitment',
    ],
    evidenceAnalysis: 'The evidentiary record showed years of documented neglect findings against the Santoskys and substantial state intervention; however, the constitutional question turned not on the sufficiency of the evidence actually presented but on whether the procedural standard used to evaluate that evidence was constitutionally adequate. The majority\'s point was that under a preponderance standard, a court could terminate parental rights even when the evidence was only marginally in the state\'s favor, creating an unacceptable risk of permanent error.',
    alternativeOutcomes: 'Had the Court upheld the preponderance standard, states would have retained broad latitude to terminate parental rights on relatively weak evidence, likely accelerating termination proceedings at the cost of accuracy. A ruling requiring proof beyond a reasonable doubt would have made termination proceedings resemble criminal trials and might have left more children in long-term foster care without permanency.',
    lessonsLearned: [
      'The standard of proof in civil proceedings must be calibrated to the severity and permanence of the potential deprivation',
      'Courts apply heightened procedural scrutiny to government action that permanently severs fundamental family relationships',
      'The Mathews balancing test is the governing framework for analyzing procedural due process claims in family law proceedings',
      'Effective advocacy for parents in termination proceedings must address both the substantive evidence of neglect and the procedural fairness of the hearing itself',
    ],
    bestPractices: [
      'Challenge state termination statutes that apply the preponderance standard; Santosky mandates at least clear and convincing evidence',
      'Preserve procedural due process objections at every level to ensure they are not waived on appeal',
      'Document the resource and expertise disparity between state agencies and parents when arguing for additional procedural protections',
      'Argue for appointment of counsel for parents at termination hearings to mitigate the structural imbalance identified in Santosky',
    ],
    significance: 'Santosky v. Kramer is the definitive precedent requiring clear and convincing evidence before a state may permanently terminate parental rights, establishing a constitutional floor that all fifty states must meet. The decision reshaped termination of parental rights (TPR) proceedings nationwide, forcing legislative revisions to state statutory standards of proof and generating significant reform in how child protective agencies build and present their cases. It anchored the principle that the constitutional magnitude of a deprivation—not merely its civil or criminal label—determines what procedural protections due process demands, and it remains the central authority cited by parents\' counsel in TPR proceedings across the country.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'John Santosky II and Annie Santosky',
        role: 'PLAINTIFF',
        counsel: 'Ranne Miller',
        description: 'Biological parents whose parental rights were terminated by New York under a preponderance-of-the-evidence standard',
      },
      {
        name: 'Ernest L. Kramer, Commissioner of Ulster County Department of Social Services',
        role: 'DEFENDANT',
        counsel: 'Iris A. Steel, Assistant County Attorney of Ulster County',
        description: 'County social services commissioner who initiated the termination proceeding and defended the preponderance standard',
      },
    ],
  },

  {
    litigationSlug: 'family-law',
    name: 'Orr v. Orr',
    citation: '440 U.S. 268 (1979)',
    jurisdiction: 'Federal – United States',
    court: 'Supreme Court of the United States',
    year: 1979,
    facts: 'William Herbert Orr and Lillian Orr were divorced in Alabama in 1974 pursuant to a separation agreement under which William was obligated to pay alimony to Lillian. William fell into arrears on the alimony payments and Lillian initiated contempt proceedings against him in Alabama state court. In response, William challenged the constitutionality of Alabama\'s alimony statutes, which imposed alimony obligations exclusively on husbands and categorically exempted wives from any obligation to pay alimony to a spouse. The Alabama statutes reflected the common-law assumption that husbands were the breadwinners and wives were financially dependent. William argued that imposing alimony obligations solely on the basis of sex violated the Equal Protection Clause of the Fourteenth Amendment.',
    keyLegalIssues: [
      'Whether Alabama statutes imposing alimony obligations exclusively on husbands and exempting wives violated the Equal Protection Clause',
      'Whether sex is a permissible basis for assigning alimony burdens in family law without individualized inquiry into financial need',
      'What level of scrutiny applies to sex-based classifications under the Equal Protection Clause in family law contexts',
      'Whether William Orr had standing to raise the equal protection challenge in proceedings initiated to enforce his alimony obligation',
    ],
    plaintiffArguments: 'Lillian Orr argued that Alabama\'s alimony statutes reflected realistic differences in the economic positions of men and women resulting from the traditional division of marital roles and that the legislative distinction therefore bore a substantial relationship to an important governmental objective. She contended that the statutes served the legitimate purpose of compensating women for economic disadvantages suffered during marriage and that the legislature could reasonably conclude that wives were more likely than husbands to need post-divorce financial support. She also challenged William\'s standing, arguing that because he had agreed to pay alimony in the separation agreement he could not benefit from a ruling invalidating the statute.',
    defendantArguments: 'William Orr argued that Alabama\'s categorical exclusion of wives from any alimony obligation constituted sex discrimination that could not survive the intermediate scrutiny applied to sex-based classifications under Craig v. Boren. He contended that if the legislature\'s true aim was to help needy spouses, the statute was poorly tailored to that end because it aided all wives regardless of need and burdened all husbands regardless of relative financial position. He argued that individualized hearings to determine need and ability to pay were already required in alimony proceedings, making the sex classification redundant and constitutionally superfluous.',
    proceduralHistory: 'The Alabama Circuit Court held William in contempt for non-payment of alimony and rejected his constitutional challenge. The Alabama Court of Civil Appeals affirmed. The Alabama Supreme Court denied certiorari. The United States Supreme Court granted certiorari and reversed, remanding for further proceedings on the standing question and the merits of the equal protection claim.',
    finalDecision: 'The Supreme Court held 6-3 that Alabama\'s sex-based alimony statutes violated the Equal Protection Clause. Justice Brennan\'s majority opinion applied intermediate scrutiny and found that the statutes were not substantially related to any important governmental interest because a sex-neutral individualized inquiry would achieve the same lawful goals without relying on gender stereotypes.',
    judicialReasoning: 'Justice Brennan applied intermediate scrutiny, the standard the Court had established for sex-based classifications in Craig v. Boren, requiring that such classifications serve important governmental objectives and be substantially related to the achievement of those objectives. The majority accepted that providing for needy spouses and compensating for marital discrimination were important objectives but concluded that the sex-based classification was not substantially related to either because: (1) Alabama already required individualized hearings in alimony proceedings where need and resources could be assessed without reference to sex; and (2) the statute operated on the basis of the very gender stereotype—the dependent wife and breadwinner husband—that it was supposedly designed to remedy. The Court declined to strike down the Alabama contempt proceedings against William; instead it remanded to allow Alabama to reconfigure the remedy in a sex-neutral fashion or to permit William to raise his individual circumstances in a new hearing.',
    legalStandards: [
      'Intermediate scrutiny for sex-based classifications: important governmental objective substantially related to the classification',
      'Sex may not serve as a proxy for need or financial capacity when individualized determination is already required',
      'Sex-based classifications that perpetuate gender stereotypes about marital roles fail equal protection review',
      'Standing doctrine applied in context of enforcement proceedings against the challenging party',
    ],
    keyPrecedents: [
      'Craig v. Boren, 429 U.S. 190 (1976) – intermediate scrutiny for sex-based classifications',
      'Weinberger v. Wiesenfeld, 420 U.S. 636 (1975) – sex-based Social Security distinctions invalidated',
      'Frontiero v. Richardson, 411 U.S. 677 (1973) – sex discrimination in military benefits struck down',
      'Reed v. Reed, 404 U.S. 71 (1971) – first Supreme Court decision striking sex classification under Equal Protection',
    ],
    evidenceAnalysis: 'The statistical record presented by Alabama showing that wives were more likely than husbands to be financially disadvantaged upon divorce was relevant to the government\'s objective but could not justify a categorical sex-based rule because the same statistical disparity could be addressed—more precisely and without constitutional defect—through individualized hearings that Alabama\'s own procedure already required. The Court emphasized that a sex-neutral standard would capture all genuinely needy spouses, including husbands, without the constitutional cost of relying on gender stereotypes.',
    alternativeOutcomes: 'Had the Court deferred to the traditional legislative judgment about marital roles, sex-segregated alimony obligations would have persisted as constitutionally permissible throughout the states, reinforcing the economic dependency model of marriage. Alternatively, a ruling applying only rational basis review might have reached the same result but would have set a lower constitutional bar for future sex-based family law classifications.',
    lessonsLearned: [
      'Sex-based categorical rules in family law cannot survive intermediate scrutiny when individualized inquiry is both feasible and already required',
      'Statutes that rest on gender role stereotypes—however historically widespread—are especially vulnerable to equal protection challenge',
      'Challengers to facially discriminatory statutes may have standing even when the immediate proceeding is brought to enforce the challenged obligation against them',
      'Equal protection principles apply symmetrically: men may challenge sex classifications that disadvantage them just as women may',
    ],
    bestPractices: [
      'When challenging sex-based family law statutes, demonstrate that a sex-neutral alternative would achieve the legislature\'s legitimate objectives equally well or better',
      'Identify individualized hearing procedures already present in the statutory scheme that make the sex classification constitutionally redundant',
      'Document the gender stereotype underlying the challenged statute to invoke the Court\'s heightened skepticism of role-based classifications',
      'Address standing proactively when the challenger is the party against whom a sex-discriminatory obligation is being enforced',
    ],
    significance: 'Orr v. Orr is the landmark precedent requiring sex-neutral standards in alimony and spousal support law, holding that states may not impose support obligations exclusively on husbands or exclusively on wives. The decision accelerated the transformation of divorce law from a status-based framework premised on gender roles into a needs-and-capacity framework applied without regard to sex. Its application of intermediate scrutiny to sex-based classifications in the family law context has been extended to a wide range of domestic relations statutes governing inheritance, property division, and child support, making it a foundational case in the equality-of-the-sexes strand of constitutional family law.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Lillian Orr',
        role: 'PLAINTIFF',
        counsel: 'Sybil Vogel',
        description: 'Former wife who obtained the alimony order and initiated contempt proceedings against William Orr for non-payment',
      },
      {
        name: 'William Herbert Orr',
        role: 'DEFENDANT',
        counsel: 'Jerome A. Cooper',
        description: 'Former husband who challenged the constitutionality of Alabama\'s sex-based alimony statutes in the contempt proceeding',
      },
    ],
  },

  {
    litigationSlug: 'family-law',
    name: 'Michael H. v. Gerald D.',
    citation: '491 U.S. 110 (1989)',
    jurisdiction: 'Federal – United States',
    court: 'Supreme Court of the United States',
    year: 1989,
    facts: 'Carole D. was married to Gerald D., a French citizen residing in California, when she had an adulterous relationship with Michael H., a neighbor. Carole gave birth to Victoria D. in 1981, and blood tests later established a 98.07% probability that Michael, not Gerald, was Victoria\'s biological father. Carole moved back and forth between Michael and Gerald during the years following Victoria\'s birth, and Michael developed a close relationship with Victoria, who was baptized with him listed as her father and spent periods living with him. California\'s Evidence Code Section 621 created a conclusive presumption that a child born to a married woman living with her husband is the legitimate child of the husband, which could be rebutted only by the husband or wife, not by a third party. Michael sought a declaration of paternity and visitation rights, and Victoria\'s court-appointed guardian ad litem also sought standing for Victoria to assert her own rights to maintain the relationship.',
    keyLegalIssues: [
      'Whether a biological father\'s constitutionally protected liberty interest in his relationship with his child could be extinguished by a state conclusive presumption of marital legitimacy',
      'Whether California\'s Evidence Code Section 621 violated the Due Process Clause as applied to an established relationship between a biological father and his child',
      'Whether a minor child has a constitutional liberty interest in maintaining a relationship with her biological father against the wishes of her mother and legal father',
      'How to identify protected liberty interests under substantive due process when tradition and history point in different directions',
    ],
    plaintiffArguments: 'Michael H. argued that his actual, established, and loving relationship with Victoria—a relationship confirmed by biology and nurtured over years of cohabitation and parental involvement—constituted a fundamental liberty interest under the Due Process Clause that California could not extinguish through a conclusive fiction. He contended that the Constitution protects the liberty of parents who have established a parental relationship, not merely the liberty of those who fit into a particular legal status, and that the undisputed probability of his biological paternity combined with his parental conduct created a protected interest. Michael also argued that Victoria had an independent liberty interest in maintaining her relationship with her biological father.',
    defendantArguments: 'Gerald D. argued that California\'s conclusive legitimacy presumption reflected a deeply rooted and historically supported state interest in protecting the integrity of the marital family unit from disruption by third parties claiming competing paternity. He contended that the tradition of protecting marital families from outside interference with paternity was the relevant tradition for purposes of substantive due process analysis, and that no constitutional liberty interest was recognized at the level of specificity required by the Court\'s methodology for a biological father who was an adulterous interloper into an ongoing marriage. Carole, who had returned to Gerald, joined his position.',
    proceduralHistory: 'The California Superior Court granted Gerald\'s and Carole\'s motions for summary judgment, holding that Michael lacked standing to assert parental rights under Section 621. The California Court of Appeal affirmed. The California Supreme Court denied review. The United States Supreme Court granted certiorari and affirmed in a fragmented plurality opinion.',
    finalDecision: 'The Supreme Court affirmed 5-4 the California Court of Appeal\'s judgment upholding the constitutionality of the conclusive presumption as applied to Michael and Victoria. Justice Scalia\'s plurality opinion held that neither Michael nor Victoria had a constitutionally protected liberty interest sufficient to override the state\'s interest in protecting the marital family.',
    judicialReasoning: 'Justice Scalia\'s plurality (joined by Chief Justice Rehnquist and, in relevant parts, by Justices O\'Connor and Kennedy) held that substantive due process protects only those fundamental rights and liberties that are objectively rooted in the nation\'s history and traditions, and that the applicable tradition must be identified at the most specific level of abstraction available. At that level of specificity—the rights of an adulterous natural father against the wishes of both the mother and her husband—no such tradition existed. Justice Scalia also held that Victoria had no independent liberty interest in maintaining two fathers because such a liberty interest had no historical basis. Justice O\'Connor, joined by Justice Kennedy, concurred in the judgment but wrote separately to reject the plurality\'s methodology of requiring courts always to identify the most specific applicable tradition, arguing that such a rigid approach could foreclose legitimate future recognition of fundamental rights. The four dissenters argued that the established parent-child relationship between Michael and Victoria was itself the constitutionally relevant interest, and that California\'s conclusive presumption extinguished that relationship without adequate process.',
    legalStandards: [
      'Substantive due process protects only fundamental rights rooted in the nation\'s history and traditions at the relevant level of specificity',
      'Plurality methodology: liberty interests identified at the most specific applicable level of historical tradition',
      'State conclusive presumptions of marital legitimacy withstand due process challenge where no competing historical tradition protects the challenger',
      'Minor children\'s liberty interests in parental relationships are assessed independently and also require historical grounding',
    ],
    keyPrecedents: [
      'Moore v. City of East Cleveland, 431 U.S. 494 (1977) – family relationships receive substantive due process protection',
      'Stanley v. Illinois, 405 U.S. 645 (1972) – unwed fathers with established parental relationships have due process rights',
      'Lehr v. Robertson, 463 U.S. 248 (1983) – biological connection alone without parental relationship insufficient for constitutional protection',
      'Quilloin v. Walcott, 434 U.S. 246 (1978) – unwed father who never established custodial relationship lacks veto over adoption',
    ],
    evidenceAnalysis: 'The blood test establishing a 98.07% probability of biological paternity was the central factual predicate of Michael\'s claim, but the plurality held it insufficient on its own to establish a constitutionally protected interest. Evidence of the actual parental relationship—periods of cohabitation, baptism records listing Michael as father, and testimony about the father-daughter bond—was presented but ultimately trumped by the plurality\'s focus on the marital family as the historically protected unit. The guardian ad litem\'s evidence of Victoria\'s attachment to Michael was relevant to Victoria\'s independent claim but was equally unavailing under the plurality\'s framework.',
    alternativeOutcomes: 'Had the Court adopted the dissent\'s approach and recognized the established father-child relationship as the constitutionally relevant liberty interest regardless of marital status, California would have been required to provide Michael an opportunity to demonstrate why visitation or paternity recognition served Victoria\'s best interests. A ruling in Michael\'s favor would also have significantly narrowed states\' ability to use marital presumptions to exclude biological fathers from any role in their children\'s lives.',
    lessonsLearned: [
      'The level of abstraction at which a claimed liberty interest is defined is often outcome-determinative in substantive due process litigation',
      'Biological paternity alone, without an established ongoing parental relationship, receives weaker constitutional protection',
      'Conclusive statutory presumptions can be constitutionally adequate when they protect a competing, historically grounded family unit',
      'Concurrent claims by both a biological parent and a minor child may receive different constitutional treatment despite arising from the same factual relationship',
    ],
    bestPractices: [
      'Counsel for biological fathers should establish and document the parental relationship as early as possible to strengthen the liberty interest claim',
      'When challenging conclusive legitimacy presumptions, argue at the broadest level of abstraction—the right to maintain an established parent-child relationship—rather than at the specific fact pattern level',
      'Assess state statutes for alternative rebuttal mechanisms that may provide an avenue to adjudication without reaching constitutional challenge',
      'Coordinate the biological father\'s claim with a guardian ad litem representing the child\'s independent interest in preserving the relationship',
    ],
    significance: 'Michael H. v. Gerald D. is the leading case on the constitutional rights of unwed biological fathers and the permissibility of state marital presumptions that extinguish those rights. The decision\'s plurality methodology—requiring that claimed liberty interests be grounded in history and tradition at the most specific applicable level—became a major point of doctrinal debate and was specifically contested in later substantive due process cases including Lawrence v. Texas and Obergefell v. Hodges, where the majority declined to follow Scalia\'s specificity requirement. The case also crystallized the tension between biological paternity, psychological parenthood, and legal parentage as competing frameworks for organizing constitutional family law, tensions that continue to generate litigation in the contexts of assisted reproduction, surrogacy, and same-sex parenting.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Michael H.',
        role: 'PLAINTIFF',
        counsel: 'John L. Dodd',
        description: 'Biological father who sought a declaration of paternity and visitation rights despite California\'s conclusive marital presumption',
      },
      {
        name: 'Gerald D.',
        role: 'DEFENDANT',
        counsel: 'Vincent J. Bartolotta Jr.',
        description: 'Legal husband of Carole D. who invoked the California marital presumption to exclude Michael from any parental role',
      },
      {
        name: 'Victoria D.',
        role: 'THIRD_PARTY',
        counsel: 'Harold La Flamme (guardian ad litem)',
        description: 'Minor child whose independent constitutional right to maintain a relationship with her biological father was also at issue',
      },
      {
        name: 'Carole D.',
        role: 'THIRD_PARTY',
        description: 'Mother of Victoria who returned to Gerald and joined his position opposing Michael\'s paternity claim',
      },
    ],
  },
];

export default cases;
