import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'healthcare',
    name: 'National Federation of Independent Business v. Sebelius',
    citation: '567 U.S. 519 (2012)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2012,
    facts: 'The Affordable Care Act (ACA), enacted in 2010, included an individual mandate requiring most Americans to purchase health insurance or pay a financial penalty. The National Federation of Independent Business (NFIB) and 26 state attorneys general challenged the constitutionality of the mandate. Plaintiffs argued Congress lacked authority under the Commerce Clause to compel individuals to enter commerce by purchasing a product. The ACA also expanded Medicaid eligibility and threatened states with loss of all existing Medicaid funding if they refused to participate in the expansion. The litigation consolidated multiple challenges from across the country and was expedited to the Supreme Court given the law\'s sweeping national importance.',
    keyLegalIssues: [
      'Whether the individual mandate was constitutional under the Commerce Clause',
      'Whether the individual mandate could be sustained as a valid exercise of Congress\'s taxing power',
      'Whether the Medicaid expansion unconstitutionally coerced states by threatening to withdraw existing funding',
      'Whether the Anti-Injunction Act barred pre-enforcement challenges to the mandate penalty',
    ],
    plaintiffArguments: 'The NFIB and state plaintiffs argued that the Commerce Clause does not permit Congress to regulate inactivity — the failure to purchase insurance — because commerce requires a pre-existing commercial activity. They contended that upholding the mandate would grant Congress unlimited power to compel any purchase. They further argued the Medicaid expansion was unconstitutionally coercive because states had no meaningful choice but to accept it given the financial stakes.',
    defendantArguments: 'The federal government defended the mandate as a valid Commerce Clause regulation of the interstate health insurance market, noting that virtually everyone eventually consumes health care. Alternatively, the government argued the penalty was a permissible tax. On Medicaid, the government argued that Congress\'s broad spending power permits conditions on federal funds and that states voluntarily participate in Medicaid.',
    proceduralHistory: 'The district court for the Northern District of Florida struck down the entire ACA. The Eleventh Circuit Court of Appeals upheld most of the law but invalidated the individual mandate. The Supreme Court granted certiorari and heard argument over three days in March 2012, an unusually extended schedule reflecting the case\'s significance.',
    finalDecision: 'Chief Justice Roberts, writing for a five-Justice majority on the taxing power question, upheld the individual mandate as a valid exercise of Congress\'s power to lay and collect taxes, even though it could not be sustained under the Commerce Clause. Seven Justices agreed the Medicaid expansion was unconstitutionally coercive, and the Court remedied it by holding states could not lose existing Medicaid funding for declining to expand.',
    judicialReasoning: 'Chief Justice Roberts reasoned that the Commerce Clause permits regulation of existing commercial activity but does not authorize Congress to create commerce by mandating purchase. However, because the mandate\'s consequence is a monetary payment to the Treasury collected by the IRS, it operates as a tax and is therefore constitutional under the Taxing and Spending Clause. On Medicaid, the Court applied its unconstitutional conditions doctrine, holding that conditioning a state\'s entire existing Medicaid grant on accepting the expansion was a "gun to the head" that crossed the constitutional line. The Court severed the coercive condition rather than invalidating the expansion outright, allowing states to opt out of the expansion without losing prior funding. Justices Ginsburg, Breyer, Sotomayor, and Kagan concurred in upholding the mandate but would have done so under the Commerce Clause as well.',
    legalStandards: [
      'Commerce Clause activity/inactivity distinction',
      'Taxing and Spending Clause — tax vs. penalty analysis',
      'Unconstitutional conditions doctrine as applied to Spending Clause programs',
      'Severability analysis for partially unconstitutional statutes',
    ],
    keyPrecedents: [
      'Gibbons v. Ogden, 22 U.S. 1 (1824) — breadth of Commerce Clause power',
      'United States v. Lopez, 514 U.S. 549 (1995) — limits of Commerce Clause',
      'South Dakota v. Dole, 483 U.S. 203 (1987) — conditions on federal spending',
      'Steward Machine Co. v. Davis, 301 U.S. 548 (1937) — taxing power and social programs',
    ],
    evidenceAnalysis: 'The Court examined congressional findings that the uninsured cost the economy hundreds of billions annually through cost-shifting in emergency care. The legislative record showed Congress treated the mandate as integral to the ACA\'s broader insurance market reforms, including guaranteed issue and community rating provisions. Statistical data demonstrated that virtually all Americans will consume health care at some point, supporting the government\'s market-participation framing.',
    alternativeOutcomes: 'Had the Court struck down the mandate without severability, the ACA\'s guaranteed issue and community rating provisions might have been invalidated as well, potentially unraveling the entire regulatory framework. Had the Court accepted the Commerce Clause argument, it would have dramatically expanded federal regulatory power. A ruling invalidating the Medicaid expansion without a severability remedy could have ended the expansion entirely rather than making it optional for states.',
    lessonsLearned: [
      'Creative statutory interpretation — framing a mandate penalty as a tax — can save legislation from constitutional invalidity',
      'Conditions on federal spending have outer constitutional limits even under the broad Spending Clause',
      'Severability analysis allows courts to preserve beneficial statutory provisions when discrete parts are unconstitutional',
      'Political and institutional considerations can influence doctrinal choices in landmark constitutional cases',
    ],
    bestPractices: [
      'Draft revenue-raising provisions so they can stand independently as taxes if penalty framing is challenged',
      'Build multiple independent constitutional bases into major legislation to provide fallback authority',
      'Include explicit severability clauses in complex statutes to guide courts if portions are struck',
      'Anticipate coercion challenges when conditioning existing federal grants on acceptance of major new program expansions',
    ],
    significance: 'NFIB v. Sebelius is the most consequential healthcare decision of the twenty-first century, preserving the ACA and ensuring coverage for tens of millions of Americans. The Commerce Clause holding established an "activity/inactivity" distinction that constrains future federal regulatory power. The Medicaid coercion ruling created a new doctrinal limit on Spending Clause conditions that states have successfully invoked in subsequent litigation. Chief Justice Roberts\'s pivot to the taxing power has been both celebrated as judicial statesmanship and criticized as results-oriented. The decision shapes all future debates over the constitutional limits of comprehensive federal healthcare reform.',
    outcome: 'Plaintiff Partial Victory',
    isFeatured: true,
    parties: [
      {
        name: 'National Federation of Independent Business',
        role: 'PLAINTIFF',
        counsel: 'Paul D. Clement',
        description: 'Business advocacy organization challenging the individual mandate on behalf of small business owners',
      },
      {
        name: 'Twenty-Six State Attorneys General',
        role: 'PLAINTIFF',
        counsel: 'Paul D. Clement',
        description: 'Coalition of state governments challenging both the individual mandate and the Medicaid expansion',
      },
      {
        name: 'Kathleen Sebelius, Secretary of Health and Human Services',
        role: 'DEFENDANT',
        counsel: 'Donald B. Verrilli Jr., Solicitor General of the United States',
        description: 'Federal government defendant defending the constitutionality of the Affordable Care Act',
      },
    ],
  },
  {
    litigationSlug: 'healthcare',
    name: 'King v. Burwell',
    citation: '576 U.S. 473 (2015)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2015,
    facts: 'The Affordable Care Act authorized tax credits to help low- and moderate-income Americans purchase health insurance through exchanges "established by the State." The federal government interpreted this language to permit tax credits in both state-established and federally-established exchanges under 26 U.S.C. § 36B. Several plaintiffs who were Virginia residents — a state that used the federally-facilitated exchange — challenged this interpretation, arguing the statute\'s plain text limited credits to state exchanges only. If credits were unavailable on federal exchanges, millions of Americans in the 34 states using federal exchanges would lose subsidies, likely destabilizing insurance markets across the country. The case presented a question of statutory interpretation with enormous practical consequences for the ACA\'s operation.',
    keyLegalIssues: [
      'Whether the phrase "established by the State" in 26 U.S.C. § 36B limited tax credits to state-run exchanges only',
      'Whether Chevron deference applied to IRS interpretation of an ambiguous tax provision in a major healthcare statute',
      'Whether statutory context and legislative purpose could resolve apparent textual ambiguity',
      'Whether plaintiffs had standing to challenge the tax credit rule',
    ],
    plaintiffArguments: 'Plaintiffs argued that the ACA\'s text unambiguously limited premium tax credits to exchanges "established by the State," which by its plain meaning excludes federally established exchanges. They contended the IRS rule exceeded statutory authority and that applying Chevron deference was inappropriate when the agency was interpreting a provision that defined the limits of its own authority.',
    defendantArguments: 'The government argued the statutory phrase was ambiguous when read in the context of the full ACA, which in multiple provisions treated federal and state exchanges as equivalent. The government contended the IRS\'s interpretation was a permissible construction entitled to Chevron deference, and that denying credits on federal exchanges would undermine the ACA\'s core structure by creating adverse selection death spirals in those markets.',
    proceduralHistory: 'The IRS promulgated a rule in 2012 permitting tax credits on federally facilitated exchanges. The Eastern District of Virginia granted summary judgment for the government. The Fourth Circuit affirmed, applying Chevron deference. The D.C. Circuit, in a different case raising the same issue decided the same day, reached the opposite conclusion. The Supreme Court granted certiorari to resolve the circuit split.',
    finalDecision: 'Chief Justice Roberts, writing for a 6-3 majority, held that the ACA\'s tax credit provision was ambiguous, and that context and structure of the statute supported the IRS interpretation allowing credits on all exchanges, including federally established ones. The Court declined to apply Chevron deference, reasoning that an agency interpretation of a question of deep economic and political significance belonged to the courts rather than the agency.',
    judicialReasoning: 'Chief Justice Roberts applied the "whole statute" canon of construction, examining the ACA as an integrated scheme rather than focusing on the isolated phrase. He reasoned that interpreting "established by the State" to exclude federal exchanges would destroy the ACA\'s three-part regulatory framework — guaranteed issue, community rating, and subsidies — in two-thirds of the states. The Court invoked the major questions doctrine to withhold Chevron deference, finding that Congress could not have intended to delegate to the IRS a decision with such vast economic and political consequences. Justice Scalia\'s dissent, joined by Thomas and Alito, criticized the majority for disregarding plain text and accused the Court of giving the statute a "SCOTUScare" reading to protect the law from political consequences.',
    legalStandards: [
      'Whole-statute canon of statutory construction',
      'Major questions doctrine limiting Chevron deference',
      'Plain meaning vs. contextual interpretation of ambiguous statutory text',
      'Chevron two-step framework and its limitations in cases of major political significance',
    ],
    keyPrecedents: [
      'Chevron U.S.A. Inc. v. Natural Resources Defense Council, 467 U.S. 837 (1984) — deference to agency statutory interpretation',
      'FDA v. Brown & Williamson Tobacco Corp., 529 U.S. 120 (2000) — major questions doctrine precursor',
      'National Federation of Independent Business v. Sebelius, 567 U.S. 519 (2012) — ACA constitutional architecture',
    ],
    evidenceAnalysis: 'The Court examined the ACA\'s full text, including provisions requiring every exchange to operate under the rules applicable to "an Exchange established by the State." Economic modeling showing market destabilization in federal exchange states informed the Court\'s reading of congressional intent. The legislative history, though sparse on this precise point, reflected no congressional intent to create a penalty on states that failed to establish their own exchanges.',
    alternativeOutcomes: 'A ruling for the plaintiffs would have stripped subsidies from approximately 6.4 million enrollees in 34 states, likely causing adverse selection spirals that would have destabilized insurance markets in those states. Congress would have faced intense pressure to act but would have been sharply divided. Some states might have rushed to establish their own exchanges; others might have allowed markets to collapse, potentially exposing tens of millions to loss of affordable coverage.',
    lessonsLearned: [
      'Statutory drafting in complex legislation must anticipate textual ambiguities that adversaries will exploit in litigation',
      'Courts will look beyond isolated statutory phrases to the overall structure and purpose of comprehensive regulatory schemes',
      'The major questions doctrine limits agency interpretive authority over economically and politically significant questions',
      'A credible threat of market-destabilizing consequences can influence judicial construction of ambiguous statutory text',
    ],
    bestPractices: [
      'Define key operational terms explicitly and consistently throughout complex regulatory statutes',
      'Include clear statements of congressional intent regarding program applicability when state and federal actors share implementation responsibilities',
      'Anticipate litigation over program eligibility rules and draft implementing regulations with robust legal support',
      'Use explicit cross-reference provisions to ensure parallel treatment of equivalent federal and state entities',
    ],
    significance: 'King v. Burwell preserved the ACA a second time before the Supreme Court and resolved a circuit split that threatened to destabilize insurance markets across 34 states. The decision significantly advanced the major questions doctrine, which the Court later expanded in West Virginia v. EPA (2022) into a major constraint on agency rulemaking authority. The case also demonstrated the Court\'s willingness to read statutory text purposively rather than literally when literal reading would produce results plainly at odds with the legislative scheme. It remains the leading authority on the limits of Chevron deference in economically significant regulatory contexts.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'David King and Other Virginia Plaintiffs',
        role: 'PLAINTIFF',
        counsel: 'Michael A. Carvin',
        description: 'Virginia residents who objected to being required to purchase health insurance they argued was made artificially affordable by unlawful federal subsidies',
      },
      {
        name: 'Sylvia Mathews Burwell, Secretary of Health and Human Services',
        role: 'DEFENDANT',
        counsel: 'Donald B. Verrilli Jr., Solicitor General of the United States',
        description: 'Federal government defendant defending the IRS rule permitting tax credits on all ACA exchanges',
      },
    ],
  },
  {
    litigationSlug: 'healthcare',
    name: 'Gonzales v. Oregon',
    citation: '546 U.S. 243 (2006)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2006,
    facts: 'Oregon enacted the Death with Dignity Act in 1997, the first state law authorizing physician-assisted suicide for terminally ill patients meeting specified criteria. Physicians who complied with Oregon\'s law prescribed controlled substances — typically secobarbital — to qualifying patients for self-administration. Attorney General John Ashcroft issued an Interpretive Rule in 2001 declaring that prescribing controlled substances for assisted suicide served no "legitimate medical purpose" under the Controlled Substances Act (CSA) and that physicians who did so faced revocation of their DEA registration. Oregon and a physician, pharmacist, and several terminally ill patients immediately challenged the Interpretive Rule in federal court. The case presented a fundamental question about federal authority to override state medical practice law through the CSA.',
    keyLegalIssues: [
      'Whether the Attorney General had authority under the Controlled Substances Act to prohibit physicians from prescribing federally controlled substances for physician-assisted suicide authorized by state law',
      'Whether the Interpretive Rule was entitled to Chevron or Skidmore deference',
      'Whether the CSA\'s "legitimate medical purpose" standard was meant to federalize medical ethics and preempt state medical practice standards',
      'Whether the rule exceeded the scope of the CSA\'s anti-drug trafficking purpose',
    ],
    plaintiffArguments: 'Oregon and its co-plaintiffs argued that the CSA was designed to combat drug trafficking and abuse, not to define substantive standards of medical practice, which have historically been left to the states. They contended that the Attorney General\'s Interpretive Rule exceeded his statutory authority because the CSA grants the executive authority to prevent diversion of drugs to illicit purposes, not to override state determinations of legitimate medical practice. They further argued the rule was not entitled to Chevron deference because it was not promulgated through notice-and-comment rulemaking.',
    defendantArguments: 'The federal government argued that the CSA gives the Attorney General broad authority to determine what constitutes a "legitimate medical purpose" for prescribing controlled substances, and that assisted suicide — condemned by Congress as contrary to medical ethics — cannot be a legitimate medical purpose. The government contended that this authority was essential to the uniform national regulation of controlled substances and that allowing states to authorize prescriptions for assisted suicide would undermine the CSA\'s comprehensive regulatory scheme.',
    proceduralHistory: 'The District Court for the District of Oregon permanently enjoined enforcement of the Interpretive Rule. The Ninth Circuit affirmed, holding the rule exceeded the Attorney General\'s statutory authority. Attorney General Ashcroft\'s successor, Alberto Gonzales, pursued the appeal. The Supreme Court granted certiorari to resolve whether the CSA preempted Oregon\'s Death with Dignity Act.',
    finalDecision: 'Justice Kennedy, writing for a 6-3 majority, affirmed the Ninth Circuit and held that the Attorney General\'s Interpretive Rule was not authorized by the CSA. The Court ruled that the statute\'s delegation of authority to the Attorney General to prevent drug abuse and trafficking did not encompass the power to define — and thus effectively regulate — legitimate medical practice. Because the rule lacked statutory authority, it was invalid regardless of what deference standard applied.',
    judicialReasoning: 'Justice Kennedy reasoned that the CSA\'s text, structure, and history demonstrated that Congress intended it as a drug trafficking statute, not a vehicle for federal supervision of medical ethics. The phrase "legitimate medical purpose" in the CSA was meant to separate lawful medical prescribing from diversion to recreational use, not to give the federal executive branch authority to settle contested questions of medical ethics like physician-assisted suicide. The Court applied Skidmore deference because the Interpretive Rule was not a formal regulation, but found the rule unpersuasive on the merits. Justice Scalia\'s dissent, joined by Chief Justice Roberts and Justice Thomas, argued the majority improperly second-guessed the Attorney General\'s reasonable statutory construction.',
    legalStandards: [
      'Skidmore deference for informal agency interpretive rules',
      'Limits of Chevron deference when agency lacks substantive authority over the regulated domain',
      'Anti-commandeering and traditional state prerogatives in regulating medical practice',
      'Statutory interpretation of dual-purpose federal statutes with state-law interface',
    ],
    keyPrecedents: [
      'Chevron U.S.A. Inc. v. Natural Resources Defense Council, 467 U.S. 837 (1984)',
      'Skidmore v. Swift & Co., 323 U.S. 134 (1944) — persuasiveness standard for informal agency guidance',
      'United States v. Oakland Cannabis Buyers\' Cooperative, 532 U.S. 483 (2001) — scope of CSA',
      'Washington v. Glucksberg, 521 U.S. 702 (1997) — constitutionality of assisted suicide bans',
    ],
    evidenceAnalysis: 'The Court examined the text and legislative history of the CSA and found no evidence Congress intended to grant the executive branch authority to define medical ethics. Agency correspondence and the Interpretive Rule\'s own language revealed that the decision to classify assisted suicide as illegitimate was a policy choice by the Attorney General rather than an exercise of pharmacological or medical expertise. Oregon\'s experience administering the Death with Dignity Act showed no evidence of abuse or diversion of controlled substances to illicit purposes, undermining the federal government\'s drug-trafficking rationale.',
    alternativeOutcomes: 'Had the Court upheld the Interpretive Rule, Oregon\'s Death with Dignity Act would have been effectively nullified because any participating physician would have risked losing their DEA registration. Other states considering similar legislation would have been deterred. The ruling would also have dramatically expanded the federal executive\'s power to override state medical practice standards on contested ethical questions through informal agency guidance rather than statute.',
    lessonsLearned: [
      'Federal statutes aimed at drug trafficking do not automatically preempt state laws regulating legitimate medical practice',
      'Agency interpretive rules that reach beyond the statute\'s core purpose lack the deference given to formal regulations',
      'States retain primary authority over medical practice standards absent a clear congressional statement of preemptive intent',
      'The form and process of agency action affects the degree of judicial deference it receives',
    ],
    bestPractices: [
      'Attorneys challenging agency overreach should focus on the structural limits of the statute granting agency authority',
      'State governments seeking to protect innovative medical practice laws should build comprehensive administrative records documenting absence of abuse',
      'Federal agencies seeking to regulate in traditionally state-controlled domains should use notice-and-comment rulemaking rather than informal interpretive rules',
      'Legislative advocates for medical practice laws should include explicit findings that distinguish their purposes from any overlapping federal regulatory scheme',
    ],
    significance: 'Gonzales v. Oregon preserved Oregon\'s pioneering Death with Dignity Act and has since enabled other states — now numbering more than ten — to enact similar statutes without federal interference. The decision established an important limit on the CSA\'s reach and reaffirmed that states hold primary authority over the definition of legitimate medical practice. The case also contributed to the doctrinal development of Skidmore deference as a meaningful alternative to Chevron in cases where agencies act informally. It remains a landmark in the intersection of federal drug law, medical ethics, and state regulatory authority.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'State of Oregon',
        role: 'PLAINTIFF',
        counsel: 'Robert M. Atkinson, Oregon Department of Justice',
        description: 'State defending its Death with Dignity Act against federal executive preemption',
      },
      {
        name: 'Peter Rasmussen, M.D.',
        role: 'PLAINTIFF',
        description: 'Oregon physician who prescribed medications under the Death with Dignity Act and faced loss of DEA registration under the Interpretive Rule',
      },
      {
        name: 'Alberto Gonzales, Attorney General of the United States',
        role: 'DEFENDANT',
        counsel: 'Paul D. Clement, Acting Solicitor General',
        description: 'Federal defendant defending the Interpretive Rule prohibiting prescriptions for assisted suicide under the CSA',
      },
    ],
  },
  {
    litigationSlug: 'healthcare',
    name: 'Canterbury v. Spence',
    citation: '464 F.2d 772 (D.C. Cir. 1972)',
    jurisdiction: 'Federal',
    court: 'United States Court of Appeals for the District of Columbia Circuit',
    year: 1972,
    facts: 'Jerry Canterbury, a 19-year-old clerk, suffered severe back pain and sought treatment from neurosurgeon Dr. William Spence at the George Washington University Hospital. Dr. Spence recommended a laminectomy — surgical removal of part of a vertebra to relieve spinal cord pressure. Before the procedure, Canterbury asked whether the surgery was dangerous; Spence told him it was not particularly serious. Canterbury was not informed that laminectomy carries approximately a one-percent risk of paralysis. Canterbury consented to the surgery. During the post-operative period, Canterbury fell from his hospital bed while attempting to void without assistance, and shortly thereafter suffered paralysis of his lower body. Following a second surgery that achieved only partial improvement, Canterbury was left with bladder problems and partial paralysis. Canterbury sued Dr. Spence and the hospital for negligence, including failure to disclose the risk of paralysis before obtaining informed consent.',
    keyLegalIssues: [
      'Whether a physician\'s duty to disclose risks before obtaining informed consent is measured by the professional custom of disclosure or by what a reasonable patient would want to know',
      'Whether the one-percent risk of paralysis from laminectomy was material and should have been disclosed',
      'Whether non-disclosure of a material risk without therapeutic privilege justification constituted actionable negligence',
      'What causal standard applies when a plaintiff claims they would not have consented had they been properly informed',
    ],
    plaintiffArguments: 'Canterbury argued that Dr. Spence had a legal duty to disclose all material risks of the surgery, including the risk of paralysis, so that Canterbury could make a genuinely informed decision about whether to consent to the procedure. He contended that the standard for disclosure should be what a reasonable patient would want to know, not merely what other physicians customarily disclosed. Canterbury further argued that had he been informed of the paralysis risk, he would not have consented to the elective surgery.',
    defendantArguments: 'Dr. Spence argued that the standard for disclosure was professional custom — whether other physicians in similar circumstances would have disclosed the same information — and that the one-percent risk of paralysis was not customarily disclosed. The defense also argued that therapeutic privilege applied because informing Canterbury of the paralysis risk might have caused him to forgo a medically necessary procedure, and that any failure to disclose was not the proximate cause of Canterbury\'s injuries, which resulted from his fall rather than the surgery itself.',
    proceduralHistory: 'The District Court directed a verdict for the defendants, holding that Canterbury had failed to introduce expert medical testimony establishing that the customary standard of disclosure required informing patients of the paralysis risk. Canterbury appealed, arguing the professional custom standard was the wrong legal test for informed consent disclosure. The D.C. Circuit reversed and remanded for a new trial.',
    finalDecision: 'Judge Spottswood Robinson III, writing for the D.C. Circuit, reversed the directed verdict and established a patient-centered standard of informed consent disclosure. The court held that the duty to disclose is measured by what a reasonable patient would want to know in order to make an intelligent decision, not by professional custom. The court also established that non-disclosure is excused only by genuine therapeutic privilege or the patient\'s own expressed wish not to be informed.',
    judicialReasoning: 'Judge Robinson grounded the duty of informed consent in the constitutional and common law right of self-determination, reasoning that every human being of adult years and sound mind has a right to determine what shall be done with their own body. The professional custom standard was rejected because it allowed physicians to define the scope of their own duty — effectively permitting the medical community to control the information patients receive rather than respecting patient autonomy. The court articulated a "materiality" standard: a risk is material if a reasonable person in the patient\'s position would likely attach significance to it in deciding whether to consent. On causation, the court adopted an objective standard, asking whether a reasonable patient — not the particular plaintiff — would have withheld consent had the risk been disclosed, to prevent hindsight bias. The court noted that the one-percent risk of permanent paralysis was plainly material under this standard.',
    legalStandards: [
      'Reasonable patient standard (patient-centered) for informed consent disclosure, replacing professional custom standard',
      'Materiality test: whether a reasonable patient would consider the risk significant in making a treatment decision',
      'Therapeutic privilege exception permitting non-disclosure only when disclosure itself would harm the patient',
      'Objective causation standard for informed consent claims to prevent hindsight bias',
    ],
    keyPrecedents: [
      'Schloendorff v. Society of New York Hospital, 211 N.Y. 125 (1914) — foundational right of self-determination in medical treatment',
      'Salgo v. Leland Stanford Jr. University Board of Trustees, 154 Cal. App. 2d 560 (1957) — early articulation of informed consent duty',
      'Natanson v. Kline, 186 Kan. 393 (1960) — physician duty to disclose risks and alternatives',
    ],
    evidenceAnalysis: 'The appellate record included evidence that Dr. Spence had not disclosed the one-percent paralysis risk and had downplayed the seriousness of the surgery when directly asked. Hospital nursing records and physician testimony established that Canterbury\'s post-operative fall occurred because he was left unattended and unrestrained while hospital staff called Dr. Spence. Medical literature established that the paralysis risk from laminectomy was a known and statistically significant complication. The court found that no expert testimony was needed to establish materiality when the risk involved — permanent paralysis — was severe and the decision was elective.',
    alternativeOutcomes: 'If the professional custom standard had been upheld, patients across the United States would have remained subject to physician-controlled information about medical procedures, with the medical profession effectively policing its own disclosure obligations. The entire subsequent development of patient-centered bioethics, shared decision-making, and statutory informed consent requirements might have evolved differently or more slowly. Canterbury himself would have received no recovery despite suffering permanent partial paralysis from a procedure whose risks were not disclosed.',
    lessonsLearned: [
      'Patient autonomy and the right of self-determination are fundamental values that the law of informed consent must protect',
      'Disclosure standards should be patient-centered rather than determined by the medical profession\'s own customs',
      'Any risk that is material — meaning a reasonable patient would consider it significant — must be disclosed regardless of statistical probability',
      'Therapeutic privilege is a narrow exception that cannot be invoked merely because disclosure might cause a patient to decline a recommended procedure',
    ],
    bestPractices: [
      'Physicians should disclose all material risks, including low-probability but high-severity outcomes such as paralysis or death',
      'Informed consent discussions should be documented contemporaneously with specificity about risks disclosed and questions answered',
      'Hospitals should develop systematic informed consent protocols that are not delegated solely to the treating physician\'s judgment',
      'Healthcare attorneys should advise clients on jurisdiction-specific informed consent standards, which in many states codify the Canterbury reasonable-patient test',
    ],
    significance: 'Canterbury v. Spence is the most influential American appellate decision in the development of informed consent law. The reasonable-patient standard it articulated has been adopted by a majority of states and has reshaped medical practice, hospital policy, and the bioethics field. The decision catalyzed a shift from physician paternalism toward patient autonomy as the organizing principle of medical ethics. It is consistently cited in medical school ethics curricula, state informed consent statutes, and subsequent cases addressing the scope of physician disclosure obligations. The case fundamentally altered the doctor-patient relationship by establishing that patients, not physicians, define what information is necessary for meaningful consent.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Jerry W. Canterbury',
        role: 'PLAINTIFF',
        counsel: 'Norman A. Greenspan',
        description: '19-year-old patient who suffered partial paralysis following laminectomy surgery for which risks were not disclosed',
      },
      {
        name: 'Dr. William T. Spence',
        role: 'DEFENDANT',
        description: 'Neurosurgeon who performed the laminectomy and failed to disclose the risk of paralysis before obtaining consent',
      },
      {
        name: 'The Washington Hospital Center',
        role: 'DEFENDANT',
        description: 'Hospital defendant whose nursing staff allegedly left Canterbury unattended during the post-operative fall',
      },
    ],
  },
  {
    litigationSlug: 'healthcare',
    name: 'Pegram v. Herdrich',
    citation: '530 U.S. 211 (2000)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2000,
    facts: 'Cynthia Herdrich was a patient enrolled in Carle Clinic Association\'s HMO health plan, which was an ERISA-covered employee benefit plan. Dr. Lori Pegram, an HMO physician-employee, examined Herdrich and discovered an inflamed mass in her abdomen. Rather than ordering an immediate ultrasound at a local facility, Dr. Pegram required Herdrich to wait eight days for the ultrasound at a Carle facility 50 miles away, allegedly to reduce costs because Carle physicians received year-end bonuses tied to the difference between plan revenues and costs. During the wait, Herdrich\'s appendix ruptured, causing peritonitis and requiring emergency surgery. Herdrich sued under ERISA, alleging that Carle\'s physician-incentive structure constituted a breach of fiduciary duty to plan beneficiaries because it rewarded physicians for withholding medically necessary care.',
    keyLegalIssues: [
      'Whether an HMO\'s decision to withhold or delay treatment, made through a plan physician with a financial incentive to reduce costs, constitutes a breach of ERISA fiduciary duty',
      'Whether mixed eligibility/treatment decisions made by physician-employees of an HMO are subject to ERISA fiduciary duty claims',
      'Whether physician-incentive compensation structures that reward cost savings are inherently inconsistent with ERISA fiduciary obligations',
      'Whether the plaintiff\'s claims were preempted by ERISA from state tort law remedies',
    ],
    plaintiffArguments: 'Herdrich argued that Carle\'s physician-incentive structure — rewarding doctors with year-end bonuses for keeping costs below a target — constituted a breach of ERISA fiduciary duty because it created an impermissible financial conflict of interest that caused plan physicians to make coverage decisions for personal financial gain rather than in the interest of plan beneficiaries. She contended that the decision to delay her ultrasound was a plan administration decision, not a purely medical one, and therefore fell within the scope of ERISA fiduciary obligations.',
    defendantArguments: 'Carle and Dr. Pegram argued that treatment decisions made by plan physicians are medical, not fiduciary, determinations even when made within the context of an HMO plan. They contended that holding HMO physician-incentive structures to be ERISA fiduciary breaches would effectively prohibit managed care, which Congress had not intended in enacting ERISA. They further argued that Herdrich\'s proper remedy, if any, was through state medical malpractice law, not a federal ERISA fiduciary breach claim.',
    proceduralHistory: 'The district court dismissed Herdrich\'s ERISA claims, holding that the challenged decisions were medical treatment decisions outside ERISA\'s fiduciary duty framework. The Seventh Circuit reversed, holding that Carle acted as an ERISA fiduciary when making coverage decisions and that a blanket policy of self-interested cost-minimization could constitute a fiduciary breach. The Supreme Court granted certiorari to resolve the scope of ERISA fiduciary duty in HMO managed care settings.',
    finalDecision: 'Justice Souter, writing for a unanimous Court, reversed the Seventh Circuit and held that the mixed eligibility/treatment decisions made by HMO physician-employees do not constitute a breach of ERISA fiduciary duty. The Court ruled that physician-incentive structures of the kind Carle used were not categorically impermissible under ERISA and that treating such structures as ERISA fiduciary breaches would effectively prohibit all forms of managed care.',
    judicialReasoning: 'Justice Souter reasoned that ERISA\'s fiduciary duty provisions were designed to protect beneficiaries from plan administrators acting in self-interest when making purely administrative decisions, not to regulate the content of medical treatment decisions. The Court recognized that HMO cost-containment inherently involves financial incentives that influence treatment decisions, and that Congress had implicitly blessed HMO structures by enacting the HMO Act of 1973 without addressing such conflicts as fiduciary breaches. Souter acknowledged the real tension between financial incentives and patient welfare but held that this was a policy question for Congress rather than a judicial rewriting of ERISA. The Court noted that plaintiffs were not without remedy — state medical malpractice claims remained available for negligent treatment decisions by plan physicians. The decision deliberately avoided deciding whether ERISA preempted such state law claims, leaving that question to future litigation.',
    legalStandards: [
      'ERISA fiduciary duty standards under 29 U.S.C. § 1104 — loyalty and prudence obligations of plan fiduciaries',
      'Distinction between plan administration (fiduciary function) and medical treatment decisions (non-fiduciary function)',
      'Mixed eligibility/treatment decision doctrine in managed care settings',
      'ERISA preemption analysis as applied to state tort claims against HMOs',
    ],
    keyPrecedents: [
      'Firestone Tire & Rubber Co. v. Bruch, 489 U.S. 101 (1989) — ERISA fiduciary standards and deference to plan administrators',
      'Pilot Life Insurance Co. v. Dedeaux, 481 U.S. 41 (1987) — ERISA preemption of state law claims',
      'HMO Act of 1973, 42 U.S.C. § 300e — congressional recognition of HMO cost-containment structures',
      'Moran v. Rush Prudential HMO, Inc., 536 U.S. 355 (2002) — subsequent ERISA preemption case in HMO context',
    ],
    evidenceAnalysis: 'The record established that Carle physicians received year-end bonuses calibrated to the spread between plan revenues and plan costs, creating a direct financial incentive to reduce medical services. Dr. Pegram\'s decision to delay the ultrasound was made in her capacity as both treating physician and plan employee. Expert evidence showed that the delay materially increased the risk of the complication Herdrich suffered. The Court did not dispute these facts but held they did not give rise to an ERISA fiduciary claim, distinguishing administrative self-dealing from inherent HMO cost-management incentives.',
    alternativeOutcomes: 'Had the Seventh Circuit decision been affirmed, HMO physician-incentive compensation structures would have been exposed to widespread ERISA fiduciary duty litigation, potentially rendering capitated managed care economically unviable. Millions of patients would potentially have gained standing to challenge cost-containment decisions that affected their care. Conversely, the decision left patients largely without a federal remedy for cost-driven coverage denials, a gap Congress attempted to address through the Patients\' Bill of Rights debate of the early 2000s, which ultimately failed to pass.',
    lessonsLearned: [
      'ERISA\'s fiduciary duty framework has significant limitations as a vehicle for challenging managed care cost-containment practices',
      'Patients seeking remedies for harm caused by HMO coverage denials must look primarily to state tort law rather than federal ERISA claims',
      'Congress, not courts, is the appropriate body to address structural conflicts of interest inherent in HMO physician-incentive compensation',
      'The distinction between plan administration and medical treatment decisions is critical in determining the scope of ERISA protections',
    ],
    bestPractices: [
      'Plaintiffs counsel representing patients harmed by HMO coverage denials should plead state law malpractice and bad faith claims alongside any federal ERISA claims',
      'Healthcare plan administrators should document the independence of clinical decision-making from financial incentive structures to defend against fiduciary breach allegations',
      'Employers selecting HMO plans should evaluate physician-incentive structures and disclose conflicts of interest to plan participants',
      'Policymakers should consider explicit statutory protections for patients against cost-driven treatment denials that fall outside ERISA\'s fiduciary reach',
    ],
    significance: 'Pegram v. Herdrich is the definitive Supreme Court ruling on the limits of ERISA fiduciary duty in managed care, and it effectively foreclosed a promising avenue of federal litigation for patients harmed by HMO cost-containment decisions. The decision exposed a major gap in the legal protection of managed care enrollees and fueled the early 2000s legislative push for a federal Patients\' Bill of Rights. It remains foundational in understanding the interplay between ERISA preemption and state tort law in healthcare litigation, and it is widely taught as a case study in the structural tensions between cost containment and patient welfare in American health law.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Dr. Lori Pegram',
        role: 'DEFENDANT',
        description: 'Carle Clinic physician-employee who delayed ordering an ultrasound for Herdrich, allegedly to reduce HMO costs',
      },
      {
        name: 'Carle Clinic Association',
        role: 'DEFENDANT',
        counsel: 'James D. Holzhauer',
        description: 'HMO operating both as a health plan and medical practice, whose physician-incentive compensation structure was challenged as an ERISA fiduciary breach',
      },
      {
        name: 'Cynthia Herdrich',
        role: 'PLAINTIFF',
        counsel: 'John G. Langhenry Jr.',
        description: 'Plan beneficiary who suffered a ruptured appendix and peritonitis allegedly caused by cost-driven delay in diagnostic care',
      },
    ],
  },
];

export default cases;
