import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'intellectual-property',
    name: 'Apple Inc. v. Samsung Electronics Co.',
    citation: '695 F.3d 1370 (Fed. Cir. 2012); 137 S. Ct. 429 (2016)',
    jurisdiction: 'Federal',
    court: 'U.S. District Court, N.D. California; U.S. Court of Appeals for the Federal Circuit; U.S. Supreme Court',
    year: 2012,
    isFeatured: true,
    facts: 'Apple filed suit in April 2011 alleging that Samsung smartphones and tablets infringed Apple patents covering the iPhone and iPad design and utility patents, including the distinctive rounded-rectangle front face, colorful icon grid, and the "bounce-back" scrolling feature. Samsung, a major hardware supplier to Apple, denied infringement and countersued alleging infringement of its own wireless-technology patents. The litigation sprawled across multiple continents and involved billions of dollars in alleged damages. A California jury returned a verdict of over $1 billion for Apple in August 2012, the largest patent damages award in U.S. history at the time. The case ultimately reached the U.S. Supreme Court on the narrow question of how design-patent damages are apportioned against a multi-component product.',
    keyLegalIssues: [
      'Infringement of utility patents covering smartphone user-interface features (bounce-back scrolling, tap-to-zoom)',
      'Infringement of design patents covering the ornamental appearance of the iPhone',
      'Calculation of design-patent damages under 35 U.S.C. § 289 (entire article of manufacture)',
      'Scope of trade-dress protection for product appearance',
      'Validity and enforceability of software and design patents',
    ],
    plaintiffArguments: 'Apple argued that Samsung deliberately copied the iPhone and iPad after internal documents revealed Samsung executives instructed engineers to study the iPhone and replicate its user experience. Apple contended that the design patents covered the entire smartphone as the relevant "article of manufacture," entitling Apple to Samsung\'s total profits from infringing devices under 35 U.S.C. § 289. Apple further argued that the utility patents covering bounce-back scrolling and tap-to-zoom were valid, non-obvious innovations that Samsung incorporated verbatim into Android products shipped to millions of consumers.',
    defendantArguments: 'Samsung argued that its products independently incorporated design choices driven by functional and aesthetic considerations common to the smartphone industry and that Apple\'s patents were invalid for obviousness given prior art including earlier touchscreen devices. Samsung contended that even if design patents were infringed, damages must be limited to the profits attributable to the infringing design component—the screen bezel or icon grid—rather than the entire phone. Samsung also raised FRAND defenses, arguing that certain wireless patents Apple sought to enforce were subject to fair-licensing obligations.',
    proceduralHistory: 'Apple filed the initial complaint in the Northern District of California in April 2011. The district court (Judge Lucy Koh) issued a preliminary injunction against certain Samsung products, which the Federal Circuit partially reversed. A jury awarded Apple $1.049 billion in August 2012; post-trial proceedings reduced that figure to $930 million. The Federal Circuit affirmed liability but remanded damages. The Supreme Court granted certiorari on the design-patent damages question and issued its opinion in December 2016, unanimously reversing the Federal Circuit\'s interpretation of "article of manufacture."',
    finalDecision: 'The Supreme Court held unanimously (8-0) that the "article of manufacture" for purposes of § 289 design-patent damages need not be the entire commercial product sold to consumers; it may be a component of that product. The Court remanded to the Federal Circuit to develop a test for identifying the relevant article of manufacture. On remand and in subsequent settlement discussions, the parties ultimately settled in 2018 for an undisclosed amount reported to be approximately $539 million.',
    judicialReasoning: 'Justice Sotomayor, writing for the Court, relied on the plain text of § 289 and its legislative history, noting that Congress enacted the provision in 1887 to overrule a court decision that had limited design-patent damages to profits on the specific component incorporating the protected design. The Court reasoned that an "article of manufacture" is simply "a thing made by hand or machine" and encompasses both entire products and their components. The Court declined to announce a definitive multi-factor test for identifying the relevant article, leaving that development to the Federal Circuit and district courts. The decision acknowledged the commercial reality that modern products contain thousands of patented components and that attributing total profits to any single design element could produce disproportionate windfalls.',
    legalStandards: [
      '35 U.S.C. § 271 — patent infringement (utility patents)',
      '35 U.S.C. § 289 — design-patent damages (total profit on article of manufacture)',
      'Egyptian Goddess, Inc. v. Swisa, Inc., 543 F.3d 665 (Fed. Cir. 2008) — ordinary observer test for design-patent infringement',
      'Graham v. John Deere Co., 383 U.S. 1 (1966) — obviousness standard',
    ],
    keyPrecedents: [
      'Egyptian Goddess, Inc. v. Swisa, Inc. (Fed. Cir. 2008) — ordinary observer infringement test for design patents',
      'Graham v. John Deere Co. (1966) — four-factor obviousness framework',
      'Gorham Co. v. White (1871) — foundational design-patent infringement standard',
    ],
    evidenceAnalysis: 'Internal Samsung documents—including a 132-page report instructing engineers to study the iPhone and a "crisis of design" memo from Samsung\'s CEO—were admitted as highly probative evidence of deliberate copying and willfulness. Apple presented consumer surveys and conjoint analysis studies purporting to quantify the value consumers placed on the patented features. Samsung countered with its own survey evidence and expert testimony arguing that consumers bought Samsung phones for carrier relationships and Android functionality, not specific design elements. The jury credited Apple\'s evidence of copying and consumer demand, forming the basis for the substantial damages award.',
    alternativeOutcomes: 'Had the Supreme Court affirmed the Federal Circuit\'s entire-profits rule, Samsung and other multi-component product manufacturers would have faced catastrophic design-patent exposure disproportionate to the contribution of any single design element, potentially chilling competition and innovation across the consumer electronics industry. Conversely, a stricter utility-patent obviousness ruling by the Federal Circuit could have invalidated Apple\'s bounce-back and tap-to-zoom patents and eliminated that portion of the damages award entirely, which would have undermined Apple\'s negotiating leverage.',
    lessonsLearned: [
      'Design patents are powerful offensive tools in consumer-electronics litigation but their damages must now be apportioned to the relevant article of manufacture after Samsung Electronics.',
      'Internal corporate documents comparing products to a competitor\'s offering can be devastating evidence of willful infringement.',
      'Global patent litigation strategy requires coordinating parallel proceedings across multiple jurisdictions simultaneously.',
      'Conjoint analysis and consumer survey evidence have become central battlegrounds in patent damages disputes.',
    ],
    bestPractices: [
      'Conduct thorough freedom-to-operate analyses before launching products in markets where a competitor holds both utility and design patents.',
      'Train engineering teams on proper competitive analysis practices that do not create documentary evidence of copying.',
      'Develop comprehensive patent portfolios covering both functional innovations and ornamental designs to enable cross-licensing leverage.',
      'Retain damages experts early to model multiple theories of recovery and apportion damages to specific patent claims.',
    ],
    significance: 'Apple v. Samsung reshaped the landscape of design-patent litigation worldwide and put design protection at the center of smartphone competition. The Supreme Court\'s 2016 ruling introduced the "article of manufacture" apportionment framework that fundamentally changed how design-patent damages are calculated for multi-component products, preventing windfalls while still incentivizing design innovation. The case also spurred broad industry attention to the strategic value of design patents as litigation weapons and prompted patent offices globally to tighten design-patent examination. Beyond legal doctrine, the decade-long dispute illustrated how intellectual-property litigation can serve as a proxy for market competition and corporate strategy at the highest levels of the global technology industry.',
    outcome: 'Mixed — Apple won liability; damages reduced and settled',
    parties: [
      {
        name: 'Apple Inc.',
        role: 'PLAINTIFF',
        counsel: 'Harold McElhinny, Michael Jacobs (Morrison & Foerster LLP); William F. Lee (Wilmer Cutler Pickering Hale and Dorr LLP)',
        description: 'iPhone and iPad manufacturer asserting utility and design patent infringement',
      },
      {
        name: 'Samsung Electronics Co., Ltd.',
        role: 'DEFENDANT',
        counsel: 'John Quinn, Charles Verhoeven (Quinn Emanuel Urquhart & Sullivan LLP)',
        description: 'Global consumer-electronics manufacturer accused of copying iPhone and iPad designs',
      },
    ],
  },

  {
    litigationSlug: 'intellectual-property',
    name: 'Sony Corp. of America v. Universal City Studios, Inc.',
    citation: '464 U.S. 417 (1984)',
    jurisdiction: 'Federal',
    court: 'U.S. District Court, C.D. California; U.S. Court of Appeals for the Ninth Circuit; U.S. Supreme Court',
    year: 1984,
    facts: 'Universal City Studios and Walt Disney Productions filed suit in 1976 against Sony Corporation of America, the manufacturer of the Betamax home video cassette recorder. The studios alleged that Sony was liable for contributory copyright infringement because consumers used the Betamax to record copyrighted television programs off the air without authorization. At the time of filing, the VCR market was nascent and the legal question of home taping for personal use had no direct precedent. The district court found for Sony, but the Ninth Circuit reversed, holding Sony secondarily liable. The case reached the Supreme Court on the question whether the sale of a general-purpose copying device—used substantially for non-infringing purposes—could itself constitute copyright infringement.',
    keyLegalIssues: [
      'Whether the sale of a home video recording device constitutes contributory copyright infringement',
      'Whether home "time-shifting" of free over-the-air television broadcasts constitutes fair use',
      'The extent of vicarious and contributory liability for manufacturers of dual-use technologies',
      'The scope of the copyright owner\'s exclusive right to control reproduction of broadcast content',
    ],
    plaintiffArguments: 'Universal and Disney argued that copyright owners hold the exclusive right to reproduce their works and that Sony, by selling a device whose primary purpose was to capture copyrighted broadcasts, was materially contributing to mass infringement. The studios contended that time-shifting was not fair use because it facilitated free viewing of content the studios licensed to broadcasters under agreements that contemplated single live broadcasts. They further argued that the Betamax created a market for unauthorized home libraries of copyrighted films and television programs, undermining potential licensing revenues.',
    defendantArguments: 'Sony argued that the Betamax was a general-purpose device capable of substantial non-infringing uses, including recording of public-domain material, time-shifting of programs that copyright owners authorized for home recording, and use by individuals who had a fair-use right to record for personal convenience. Sony analogized its position to that of a staple-article-of-commerce manufacturer and argued that imposing liability on device makers would stifle technological innovation. Sony also presented survey evidence showing the most common use of Betamax was time-shifting—watching a program at a more convenient time and then erasing it.',
    proceduralHistory: 'Universal filed suit in the Central District of California in November 1976. After a lengthy bench trial, Judge Warren Ferguson ruled in favor of Sony in October 1979, finding that home time-shifting was fair use and that Sony lacked the requisite knowledge to be liable as a contributory infringer. The Ninth Circuit reversed in October 1981, holding that time-shifting was not fair use and Sony was liable. The Supreme Court granted certiorari and heard oral argument twice before issuing its 5-4 decision in January 1984.',
    finalDecision: 'The Supreme Court reversed the Ninth Circuit and held for Sony. The Court held that the sale of the Betamax did not constitute contributory copyright infringement because the device was "capable of substantial noninfringing uses." The Court further held that private, non-commercial home time-shifting of free over-the-air broadcasts was a fair use, applying all four statutory factors from 17 U.S.C. § 107.',
    judicialReasoning: 'Justice Stevens, writing for the five-Justice majority, borrowed the staple-article-of-commerce doctrine from patent law, holding that a manufacturer of a product is not liable for contributory infringement if the product is widely used for legitimate, non-infringing purposes. The majority conducted a fair-use analysis of home time-shifting, finding that it was non-commercial, did not harm the market for broadcast programming (since those programs were broadcast free), and was actually endorsed by some copyright owners. The majority emphasized that Congress, not courts, was the appropriate body to expand copyright liability to new technologies. Justice Blackmun\'s dissent argued that the staple-article doctrine was inapplicable to copyright, that time-shifting created a market substitution, and that the majority gave insufficient weight to copyright holders\' exclusive rights.',
    legalStandards: [
      '17 U.S.C. § 107 — fair use (four-factor test)',
      'Contributory copyright infringement — knowledge plus material contribution standard',
      'Staple-article-of-commerce doctrine imported from patent law (35 U.S.C. § 271(c))',
    ],
    keyPrecedents: [
      'Fortnightly Corp. v. United Artists Television, Inc., 392 U.S. 390 (1968) — cable retransmission not a "performance" for copyright purposes',
      'Teleprompter Corp. v. Columbia Broadcasting System, Inc., 415 U.S. 394 (1974) — further defining cable copyright liability',
      'MGM Studios Inc. v. Grokster, Ltd., 545 U.S. 913 (2005) — later distinguishing Sony by adopting an inducement theory for peer-to-peer file-sharing services',
    ],
    evidenceAnalysis: 'Sony introduced consumer survey data compiled by Dr. Judith Langer showing that the predominant use of the Betamax was time-shifting of broadcast programming for later personal viewing, with users typically erasing recordings afterward. Universal countered with evidence of consumers who assembled libraries of recorded films. The district court credited Sony\'s time-shifting evidence heavily. The Supreme Court relied on survey findings to conclude that the primary use was non-commercial time-shifting, which weighed in favor of fair use under the first factor of § 107.',
    alternativeOutcomes: 'Had the Supreme Court affirmed the Ninth Circuit, Sony and other VCR manufacturers could have faced massive damages liability and potentially been enjoined from selling recording devices in the United States, effectively ending the home-video industry before it fully emerged. The ruling\'s defeat would also have chilled development of subsequent consumer technologies including DVRs, digital audio recorders, and cloud-based storage services that depend on the same "capable of substantial noninfringing uses" safe harbor. A ruling against Sony would have forced Congress to legislate explicitly on home taping, likely producing a compulsory licensing regime rather than a bright-line fair-use defense.',
    lessonsLearned: [
      'The "capable of substantial noninfringing uses" standard is a cornerstone safe harbor for manufacturers of dual-use technologies and must be considered when designing and marketing new products.',
      'Fair-use analysis is highly fact-specific, and the non-commercial, time-shifting nature of a use can weigh heavily in the user\'s favor.',
      'Courts look to Congressional intent when asked to extend copyright liability to new technological contexts, counseling humility in judicial expansion of rights.',
      'Consumer survey evidence can be decisive in establishing the predominant use of a technology and thus its characterization for fair-use and contributory-liability purposes.',
    ],
    bestPractices: [
      'Design products with non-infringing use cases prominently supported and documented to establish that the product is capable of substantial noninfringing uses.',
      'Proactively engage with copyright owners before product launch to identify licensing opportunities and reduce litigation risk.',
      'Preserve contemporaneous evidence of the range of uses for which a product is marketed and actually employed by consumers.',
      'Monitor legislative developments, as Congress may respond to landmark decisions with statutory adjustments that alter the legal landscape.',
    ],
    significance: 'The Betamax decision is one of the most consequential copyright rulings of the twentieth century. By establishing the "capable of substantial noninfringing uses" safe harbor, the Court enabled the home-video industry, which generated billions in revenues for studios that had tried to suppress it. The decision\'s logic anchored subsequent analyses of CD burners, DVRs, MP3 players, and peer-to-peer networks, serving as the foundational precedent every dual-use technology company invokes when facing copyright claims. The case also established the principle that courts should be cautious about extending copyright liability to new technologies without clear congressional authorization, shaping judicial restraint in intellectual-property cases for decades.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Sony Corp. of America',
        role: 'DEFENDANT',
        counsel: 'Dean Dunlavey; later Supreme Court argument by Dean Dunlavey and Lloyd Cutler',
        description: 'Japanese consumer-electronics manufacturer and U.S. distributor of the Betamax VCR',
      },
      {
        name: 'Universal City Studios, Inc.',
        role: 'PLAINTIFF',
        counsel: 'Carey Ramos; Supreme Court argument by Laurence Tribe',
        description: 'Major film studio seeking to hold Sony liable for consumer recording of its copyrighted broadcasts',
      },
      {
        name: 'Walt Disney Productions',
        role: 'PLAINTIFF',
        description: 'Co-plaintiff film studio with significant library of copyrighted television content',
      },
    ],
  },

  {
    litigationSlug: 'intellectual-property',
    name: 'Diamond v. Chakrabarty',
    citation: '447 U.S. 303 (1980)',
    jurisdiction: 'Federal',
    court: 'U.S. Patent and Trademark Office Board of Appeals; U.S. Court of Customs and Patent Appeals; U.S. Supreme Court',
    year: 1980,
    facts: 'Ananda Mohan Chakrabarty, a microbiologist employed by General Electric Company, developed a bacterium of the genus Pseudomonas that had the ability to break down crude oil, making it potentially useful for treating oil spills. Chakrabarty filed a patent application in 1972 claiming the genetically engineered bacterium itself, a method of producing it, and an inoculum comprising the bacterium mixed with a carrier. The Patent and Trademark Office (PTO) examiner allowed the method and inoculum claims but rejected the claim to the bacterium itself, concluding that living organisms were not patentable subject matter under 35 U.S.C. § 101. The Board of Patent Appeals affirmed the rejection, but the Court of Customs and Patent Appeals reversed, holding that the fact that the invention was alive was without legal significance for § 101 purposes.',
    keyLegalIssues: [
      'Whether a living, genetically engineered microorganism constitutes patentable subject matter under 35 U.S.C. § 101',
      'Whether the term "manufacture" or "composition of matter" in § 101 encompasses living organisms',
      'Whether the 1930 Plant Patent Act and 1970 Plant Variety Protection Act implicitly excluded other living organisms from § 101',
      'The limits of Congressional intent in defining the scope of patentable subject matter',
    ],
    plaintiffArguments: 'Chakrabarty (and GE as the real party in interest) argued that the bacterium was a product of human ingenuity and research—a non-naturally occurring manufacture or composition of matter—and therefore fell squarely within the broad language of § 101. The applicant contended that the bacterium\'s origin as a living organism was irrelevant; what mattered was that it was the result of human intervention creating something that did not exist in nature. Chakrabarty further argued that the plant-specific statutes passed by Congress addressed different subject matter and did not signal an intent to exclude other living organisms from general patent protection.',
    defendantArguments: 'The Patent Commissioner argued that Congress never intended § 101 to cover living organisms, relying on the principle that "products of nature" are not patentable. The Commissioner contended that the passage of the Plant Patent Act of 1930 and the Plant Variety Protection Act of 1970 demonstrated that Congress, when it wished to extend protection to living things, did so explicitly in targeted legislation—implying that general patent law did not cover them. The Commissioner also warned of the profound ethical and policy implications of patenting life forms and argued that such questions should be decided by Congress rather than courts.',
    proceduralHistory: 'The PTO examiner rejected the claims to the bacterium in 1973. The Board of Patent Appeals affirmed the rejection. The Court of Customs and Patent Appeals reversed in 1978, holding that the microorganism was patentable subject matter. The Commissioner of Patents petitioned the Supreme Court, which granted certiorari. The Court heard argument in March 1980 and issued its 5-4 decision in June 1980.',
    finalDecision: 'The Supreme Court affirmed the Court of Customs and Patent Appeals in a 5-4 decision. Chief Justice Burger, writing for the majority, held that Chakrabarty\'s genetically engineered bacterium was patentable subject matter under § 101 because it was a non-naturally occurring manufacture or composition of matter—the product of human ingenuity—and was therefore within the broad scope of the statute.',
    judicialReasoning: 'Chief Justice Burger emphasized Congress\'s intent in enacting § 101, citing the legislative history indicating that patent protection should extend to "anything under the sun that is made by man." The majority drew a sharp distinction between products of nature (which are not patentable) and human-made inventions that happen to be alive (which are patentable if they meet the other statutory requirements). The Court rejected the inference from the plant-specific statutes, finding that those Acts addressed different problems in extending protection to asexually and sexually reproduced plants and did not evidence a general Congressional intent to exclude living organisms from § 101. The majority explicitly declined to address broader policy concerns about genetic engineering, stating that those were for Congress and the executive branch to resolve. Justice Brennan\'s dissent argued that the plant-specific statutes demonstrated congressional awareness of the question and the choice to legislate narrowly, counseling judicial restraint.',
    legalStandards: [
      '35 U.S.C. § 101 — patentable subject matter (process, machine, manufacture, or composition of matter)',
      'Products of nature doctrine — naturally occurring phenomena not patentable',
      'Human ingenuity and research standard — non-naturally occurring manufactures patentable',
    ],
    keyPrecedents: [
      'Funk Brothers Seed Co. v. Kalo Inoculant Co., 333 U.S. 127 (1948) — mixtures of naturally occurring bacteria not patentable',
      'Association for Molecular Pathology v. Myriad Genetics, Inc., 569 U.S. 576 (2013) — later applying Chakrabarty to hold naturally occurring DNA sequences non-patentable',
      'Alice Corp. v. CLS Bank International, 573 U.S. 208 (2014) — extending subject-matter analysis to abstract ideas',
    ],
    evidenceAnalysis: 'The technical record before the Court established that Chakrabarty\'s bacterium did not occur naturally and could not result from natural processes; it was created through laboratory manipulation transferring genes from three additional Pseudomonas strains into the host bacterium. This factual finding was critical: the Court\'s holding turned entirely on the distinction between naturally occurring organisms (unpatentable) and human-engineered ones (patentable), making the technical showing of human intervention essential to the outcome.',
    alternativeOutcomes: 'Had the Court ruled for the Commissioner, living organisms would have remained categorically excluded from patent protection under § 101, fundamentally altering the biotechnology industry before it fully emerged. Without patent protection for genetically engineered organisms, investment in recombinant-DNA research—including the development of insulin, growth hormone, and other pharmaceuticals produced in engineered bacteria—might have been severely curtailed. The ruling\'s rejection would likely have forced Congress to enact specific biotechnology-patent legislation, potentially with narrower scope or additional regulatory conditions attached to patents on life forms.',
    lessonsLearned: [
      'The breadth of patentable subject matter under § 101 is determined by the distinction between human-made inventions and naturally occurring phenomena, not by whether the invention is alive.',
      'Courts interpret patent statutes in light of broad Congressional intent to encourage innovation, construing § 101 expansively absent clear signals to the contrary.',
      'Policy concerns about new technologies, while legitimate, are ordinarily for the legislature rather than courts to address when the statutory text is broad.',
      'Technical evidence demonstrating the non-natural origin of an invention is crucial when arguing patentability of biologically derived subject matter.',
    ],
    bestPractices: [
      'Document laboratory processes thoroughly to establish that engineered biological materials are the product of human intervention and do not occur naturally.',
      'Draft patent claims to emphasize the non-natural characteristics and human-engineered features of biological inventions.',
      'File claims covering both the product and the methods of making and using it to maximize protection in the event some claims are rejected.',
      'Monitor downstream Supreme Court decisions (Myriad, Alice) that refine the § 101 landscape for biological and other emerging technologies.',
    ],
    significance: 'Diamond v. Chakrabarty is the foundational decision enabling the modern biotechnology industry. By holding that human-engineered living organisms are patentable, the Court provided the legal framework that made investment in recombinant-DNA research commercially viable. The decision catalyzed the formation of companies like Genentech and Amgen, whose patent-protected biologics transformed medicine. The ruling\'s "anything under the sun made by man" standard has been cited in virtually every § 101 case since, including disputes over software patents and gene patents. Chakrabarty also launched enduring debates about the ethics of patenting life, foreshadowing controversies over genetically modified organisms and human-gene patents that continue to the present day.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Ananda Mohan Chakrabarty / General Electric Company',
        role: 'PLAINTIFF',
        counsel: 'Edward F. McKie, Jr.',
        description: 'Microbiologist and his employer seeking patent protection for a genetically engineered oil-degrading bacterium',
      },
      {
        name: 'Sidney A. Diamond, Commissioner of Patents and Trademarks',
        role: 'DEFENDANT',
        counsel: 'Brian Strum (Solicitor General\'s office)',
        description: 'Patent Commissioner defending the PTO\'s rejection of claims to living organisms as non-patentable subject matter',
      },
    ],
  },

  {
    litigationSlug: 'intellectual-property',
    name: 'Google LLC v. Oracle America, Inc.',
    citation: '593 U.S. 1 (2021)',
    jurisdiction: 'Federal',
    court: 'U.S. District Court, N.D. California; U.S. Court of Appeals for the Federal Circuit; U.S. Supreme Court',
    year: 2021,
    facts: 'When Google designed the Android mobile operating system beginning in 2005, it incorporated approximately 11,500 lines of declaring code from the Java Standard Edition application programming interface (API), which was owned by Sun Microsystems and later acquired by Oracle through its purchase of Sun in 2010. Google copied the Java API declarations verbatim—preserving the same names, structures, and organization—so that the millions of Java programmers could write Android applications using the same commands they already knew. Google wrote its own implementing code but retained the identical API structure. Oracle sued in 2010, claiming copyright infringement of the Java API code and demanding roughly $9 billion in damages. Two trials and two Federal Circuit appeals preceded a Supreme Court ruling eleven years after the lawsuit began.',
    keyLegalIssues: [
      'Whether the declaring code and organizational structure of a software API is copyrightable expression or an unprotectable method of operation or system',
      'Whether Google\'s copying of 11,500 lines of Java API declaring code constituted fair use under 17 U.S.C. § 107',
      'The scope of copyright protection available for software interfaces as distinguished from underlying implementation code',
      'Interoperability and the public interest in software compatibility as a fair-use consideration',
    ],
    plaintiffArguments: 'Oracle argued that the Java API declaring code, including the creative choices made in naming, organizing, and structuring the packages, was original creative expression fully protected by copyright. Oracle contended that Google had no right to copy exact lines of Java code without a license and that Google\'s use was plainly commercial, substituting for the Android platform in the mobile market that Oracle was independently attempting to enter. Oracle argued that the developer familiarity rationale—allowing programmers to use the same commands—did not justify free copying of copyrighted software and would eliminate incentives to develop valuable software platforms.',
    defendantArguments: 'Google argued that API declaring code is a system or method of operation—a set of commands that, by their very nature, must be written in a particular way for the interface to function—and therefore falls outside copyright protection under 17 U.S.C. § 102(b). Google alternatively argued that even if the declarations were copyrightable, its use was fair use: it took only what was necessary for interoperability, transformed the Java platform for an entirely new context (smartphones), did not harm the market for Java SE, and served the enormous public benefit of enabling a new generation of application development. Google also noted that Sun\'s CEO had publicly welcomed Android\'s use of Java.',
    proceduralHistory: 'Oracle filed suit in August 2010. After the first trial, Judge William Alsup ruled that the API declarations were not copyrightable (2012). The Federal Circuit reversed on copyrightability (2014). On remand, a jury found fair use (2016). The Federal Circuit again reversed, holding fair use could not be found as a matter of law (2018). The Supreme Court granted certiorari, heard argument in October 2020, and issued its 6-2 decision in April 2021.',
    finalDecision: 'The Supreme Court ruled 6-2 in favor of Google, holding that Google\'s copying of 11,500 lines of Java API declaring code was fair use as a matter of law. The Court assumed without deciding that the declaring code was copyrightable and resolved the case entirely on fair-use grounds, rendering the copyrightability question unanswered.',
    judicialReasoning: 'Justice Breyer, writing for the six-Justice majority, applied the four-factor fair-use test with significant attention to the nature of the copied material and the public interest in software interoperability. The Court found that the declaring code was a "creative interface" but one that functioned more like a "key" than a "novel"—it had to be written exactly as it was for the interface to work, limiting its creative expression. The majority found the use transformative because Google used the Java interface in a new and distinct computing environment (smartphones), not merely to replicate the Java platform. The Court found that Oracle had not demonstrated harm to the market for Java SE, and that the broad public benefit—enabling millions of Java programmers to develop Android apps—weighed in favor of fair use. Justices Thomas and Alito dissented, arguing that the majority\'s analysis gutted copyright protection for software and that Google\'s commercial use and verbatim copying should have defeated the fair-use claim.',
    legalStandards: [
      '17 U.S.C. § 102(b) — copyright does not extend to methods of operation, systems, or procedures',
      '17 U.S.C. § 107 — fair use (four-factor test)',
      'Transformativeness analysis under Campbell v. Acuff-Rose Music, Inc., 510 U.S. 569 (1994)',
      'Market-harm factor — fourth-factor analysis requires consideration of potential licensing markets',
    ],
    keyPrecedents: [
      'Campbell v. Acuff-Rose Music, Inc., 510 U.S. 569 (1994) — transformativeness as the central fair-use inquiry',
      'Sony Corp. of America v. Universal City Studios, Inc., 464 U.S. 417 (1984) — fair use and the public benefit consideration',
      'Lotus Development Corp. v. Borland International, Inc., 49 F.3d 807 (1st Cir. 1995) — menu command hierarchy as uncopyrightable method of operation',
    ],
    evidenceAnalysis: 'The evidentiary record included extensive expert testimony on the software industry\'s norms for API use and reuse, internal Google communications about the decision to use Java APIs for developer familiarity, and market evidence regarding Oracle\'s attempts to enter the smartphone market. Judge Alsup\'s original copyrightability finding rested in part on his own learning of Java programming during the trial. The fair-use jury verdict was supported by evidence that Android operated on a different platform (smartphones vs. desktops/servers), served a different market segment, and did not substitute for Java SE licenses. The Supreme Court treated the factual record as largely undisputed and resolved fair use as a legal question.',
    alternativeOutcomes: 'Had Oracle prevailed, every software company that had copied API declarations for interoperability purposes—a common and longstanding industry practice—would have faced retroactive copyright liability. The ruling against Google could have required companies to negotiate licenses for every API they implemented, fragmenting the software ecosystem and dramatically increasing development costs. It might also have enabled Oracle to collect royalties on the Android platform retroactively and prospectively, potentially restructuring the mobile-computing market. A ruling finding the declarations uncopyrightable (the other possible outcome) would have provided clearer guidance but left the fair-use doctrine less developed for future software disputes.',
    lessonsLearned: [
      'Fair use is a highly flexible doctrine that courts apply pragmatically to protect socially beneficial uses of copyrighted material, even commercial ones, when the use is transformative and the market harm is speculative.',
      'Assuming rather than deciding copyrightability allows courts to reach fair-use outcomes without setting broad precedent on the scope of software copyright.',
      'Developer familiarity and interoperability are recognized interests that can support fair-use findings in software-interface disputes.',
      'Decade-long intellectual-property litigation imposes enormous costs on both parties and the judicial system, underscoring the value of early licensing negotiations.',
    ],
    bestPractices: [
      'Negotiate API licensing terms proactively when incorporating third-party interface code, even when interoperability norms suggest such use is permissible.',
      'Document the purpose and context of any copied interface code to build a contemporaneous record supporting a fair-use or interoperability defense.',
      'Structure software APIs to maximize independent creative expression in naming and organization, strengthening future copyright claims if the interface is misappropriated.',
      'Assess market-harm evidence carefully: demonstrating that the copier has entered or threatens a market the copyright owner is actively pursuing is essential to defeating a fair-use defense.',
    ],
    significance: 'Google v. Oracle is one of the most consequential copyright decisions of the digital era. By ruling in Google\'s favor on fair use, the Supreme Court preserved the longstanding software-industry practice of implementing compatible APIs without licenses, protecting the open and interoperable ecosystem that underlies modern computing. The decision validated the public interest in software interoperability as a fair-use value and signaled judicial reluctance to allow copyright to be weaponized against industry-standard interfaces. The Court\'s deliberate avoidance of the copyrightability question, however, leaves unresolved whether API declarations are protected expression at all—ensuring that the legal debate over software copyright will continue in future cases involving different facts or market harms.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Google LLC',
        role: 'DEFENDANT',
        counsel: 'Daralyn Durie (Durie Tangri LLP); Thomas Goldstein (Goldstein & Russell) for Supreme Court argument',
        description: 'Search and technology company that incorporated Java API declarations into the Android operating system',
      },
      {
        name: 'Oracle America, Inc.',
        role: 'PLAINTIFF',
        counsel: 'E. Joshua Rosenkranz (Orrick, Herrington & Sutcliffe LLP); Jeffrey A. Lamken for Supreme Court argument',
        description: 'Enterprise software company that acquired Sun Microsystems and its Java platform copyrights, asserting infringement against Android',
      },
    ],
  },

  {
    litigationSlug: 'intellectual-property',
    name: 'Mattel, Inc. v. MCA Records, Inc.',
    citation: '296 F.3d 894 (9th Cir. 2002)',
    jurisdiction: 'Federal',
    court: 'U.S. District Court, C.D. California; U.S. Court of Appeals for the Ninth Circuit',
    year: 2002,
    facts: 'In 1997, the Danish pop group Aqua released the song "Barbie Girl" on MCA Records, a humorous and satirical tune narrated from the perspective of the Barbie doll character, referencing her plastic appearance, her relationship with Ken, and consumer culture generally. The song became a massive international hit, reaching number one in numerous countries. Mattel, the maker and trademark owner of the Barbie doll, sued MCA Records and the band\'s label in 1997, alleging trademark infringement, trademark dilution, and false designation of origin under the Lanham Act. Mattel argued that the song\'s use of the Barbie name would cause consumer confusion as to Mattel\'s endorsement or sponsorship of the record and diluted the Barbie brand.',
    keyLegalIssues: [
      'Whether the use of a famous trademark in an expressive artistic work constitutes trademark infringement under the Lanham Act',
      'Whether artistic use of a trademark is protected by the First Amendment from Lanham Act liability under the Rogers v. Grimaldi test',
      'Whether "Barbie Girl" constituted trademark dilution by tarnishment of the Barbie mark',
      'The balance between trademark rights and free expression in works of artistic commentary and parody',
    ],
    plaintiffArguments: 'Mattel argued that the song\'s title and lyrics prominently used the Barbie trademark to sell a commercial product—a record—and that consumers might believe Mattel had sponsored or endorsed the song, constituting actionable infringement. Mattel contended that the song\'s sexualized and parodic lyrics tarnished the wholesome Barbie image, damaging the brand\'s value among its target audience of children and their parents. Mattel further argued that trademark law did not categorically yield to the First Amendment when the mark was used in a commercially released artistic work and that MCA had alternative expressive means that did not require appropriating Mattel\'s trademark.',
    defendantArguments: 'MCA and Aqua argued that "Barbie Girl" was a lawful artistic work commenting on consumer culture and the stereotypes embodied by the Barbie doll, and that the First Amendment shielded such expressive uses of a trademark from Lanham Act liability under the Rogers v. Grimaldi test. The defendants contended that the use of "Barbie" in the title was artistically relevant—the song is literally about Barbie—and was not explicitly misleading as to the source or sponsorship of the record. MCA argued that the song was a parody protected both by fair use and by the broader principle that trademark law does not suppress commentary on cultural icons.',
    proceduralHistory: 'Mattel filed suit in the Central District of California in 1997 shortly after the song\'s release. The district court granted summary judgment for MCA, holding that the song was an expressive work and that Mattel\'s claims failed under the Rogers v. Grimaldi balancing test. Mattel appealed to the Ninth Circuit, which affirmed the district court\'s judgment in a decision authored by Judge Alex Kozinski in July 2002. Mattel petitioned for rehearing and rehearing en banc, both of which were denied. The Ninth Circuit amended the opinion to append its now-famous closing line advising both parties to "chill."',
    finalDecision: 'The Ninth Circuit affirmed summary judgment for MCA Records. The court held that "Barbie Girl" was an expressive work fully protected by the First Amendment and that it satisfied both prongs of the Rogers v. Grimaldi test: the use of the Barbie name was artistically relevant to the song\'s content, and the song was not explicitly misleading as to Mattel\'s sponsorship or endorsement. The court also rejected Mattel\'s dilution claim, finding that the song was a form of protected noncommercial use and artistic commentary.',
    judicialReasoning: 'Judge Kozinski\'s opinion applied the Rogers v. Grimaldi test, which holds that the Lanham Act should not be applied to expressive works unless the use of the mark is either (1) not artistically relevant to the work, or (2) explicitly misleads consumers as to the source or content of the work. The court found the Barbie name quintessentially relevant—the song could not communicate its satirical message about the Barbie cultural icon without referencing Barbie by name. The court also found no explicit misleading: a reasonable consumer encountering "Barbie Girl" by Aqua would not believe Mattel produced the record. On dilution, Kozinski reasoned that artistic commentary on a cultural symbol is a noncommercial use outside the dilution statute\'s reach, and that parody and critical commentary must be permitted or trademark law becomes a tool for silencing dissent about corporate brands. The opinion\'s famous conclusion—that "the parties are advised to chill"—captured the absurdity of titanic litigation over a pop song.',
    legalStandards: [
      'Rogers v. Grimaldi, 875 F.2d 994 (2d Cir. 1989) — two-part test for trademark use in expressive works (artistic relevance; no explicit misleading)',
      'Lanham Act § 43(a) (15 U.S.C. § 1125(a)) — false designation of origin and unfair competition',
      'Federal Trademark Dilution Act of 1995 — dilution by blurring or tarnishment of famous marks',
      'First Amendment protection for expressive and artistic works involving trademarked terms',
    ],
    keyPrecedents: [
      'Rogers v. Grimaldi, 875 F.2d 994 (2d Cir. 1989) — foundational test balancing trademark rights against First Amendment expression in artistic titles',
      'L.L. Bean, Inc. v. Drake Publishers, Inc., 811 F.2d 26 (1st Cir. 1987) — First Amendment limits on trademark dilution claims against parody',
      'Jack Daniel\'s Properties, Inc. v. VIP Products LLC, 599 U.S. 140 (2023) — Supreme Court later refining Rogers in context of humorous dog toys',
    ],
    evidenceAnalysis: 'The record on summary judgment contained no evidence of actual consumer confusion between Mattel and the Aqua recording—no survey evidence showed that consumers believed Mattel had sponsored or produced "Barbie Girl." The song\'s packaging, credits, and promotion uniformly identified MCA Records and Aqua as the source. Mattel\'s dilution theory rested on the song\'s lyrics describing Barbie in sexualized terms, but the court found that critical commentary on a trademark\'s cultural meaning is precisely the kind of expression the First Amendment protects, and that the absence of a commercial relationship between Mattel and Aqua defeated the tarnishment claim.',
    alternativeOutcomes: 'A ruling for Mattel would have substantially restricted artists\' ability to reference brand names and cultural icons in songs, films, and other creative works, extending trademark rights far into expressive territory and chilling commentary on consumer culture. Such a ruling might have forced artists to obtain licenses before referencing trademarked brands in lyrics, an impractical requirement that would distort creative expression and enrich trademark owners at the expense of First Amendment values. Alternatively, the court could have denied summary judgment and sent the case to trial on consumer confusion, imposing discovery and litigation costs on artists and labels without resolving the underlying legal standard.',
    lessonsLearned: [
      'The Rogers v. Grimaldi test protects expressive works that use trademarks in artistically relevant ways, provided the work does not explicitly mislead consumers about the mark owner\'s sponsorship.',
      'Trademark dilution claims face significant First Amendment barriers when directed at artistic commentary or parody of a brand, particularly in the absence of a commercial relationship between the parties.',
      'Consumer survey evidence is essential for trademark-infringement claims; the absence of survey evidence of actual confusion is highly significant on summary judgment.',
      'Aggressive trademark enforcement against cultural commentary can generate adverse publicity and reinforce the satirical point the mark owner seeks to suppress.',
    ],
    bestPractices: [
      'Conduct a First Amendment and Rogers analysis before filing Lanham Act claims against expressive works that use your trademark as subject matter rather than as a source identifier.',
      'Commission consumer-confusion surveys early in litigation to establish or rebut the likelihood-of-confusion element when trademark infringement is alleged.',
      'Consider whether enforcement action serves legitimate brand-protection interests or primarily targets criticism and commentary that the First Amendment shields.',
      'Counsel clients on reputational and business risks of high-profile intellectual-property litigation against popular cultural works before filing suit.',
    ],
    significance: 'Mattel v. MCA Records is a landmark case at the intersection of intellectual-property law and the First Amendment, establishing that the Rogers v. Grimaldi test shields artistic works from trademark liability when they use a mark in an artistically relevant, non-misleading way. The decision affirmed the right of artists, comedians, and cultural commentators to reference and critique famous brands without obtaining licenses, preserving a vital space for expressive commentary in popular culture. Judge Kozinski\'s witty opinion became one of the most-cited and widely taught decisions in intellectual-property courses and reinforced the principle that trademark law protects source identification, not brand owners\' feelings about how their products are portrayed. The Supreme Court\'s 2023 decision in Jack Daniel\'s Properties v. VIP Products later refined the Rogers framework, showing that Mattel v. MCA remains central to the ongoing development of trademark law\'s relationship with free expression.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Mattel, Inc.',
        role: 'PLAINTIFF',
        counsel: 'Skadden, Arps, Slate, Meagher & Flom LLP',
        description: 'Toy manufacturer and owner of the Barbie trademark, asserting infringement and dilution against a pop song',
      },
      {
        name: 'MCA Records, Inc.',
        role: 'DEFENDANT',
        counsel: 'O\'Melveny & Myers LLP',
        description: 'Record label that released "Barbie Girl" by Aqua, defending the song as protected First Amendment expression',
      },
      {
        name: 'Aqua (band members)',
        role: 'DEFENDANT',
        description: 'Danish pop group that recorded and performed "Barbie Girl," the song at the center of the trademark dispute',
      },
    ],
  },
];

export default cases;
