import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'privacy-data',
    name: 'Carpenter v. United States',
    citation: '585 U.S. 296 (2018)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2018,
    isFeatured: true,
    facts: 'Timothy Carpenter was suspected of coordinating a series of armed robberies of Radio Shack and T-Mobile stores in Michigan and Ohio between 2010 and 2011. Without obtaining a warrant, federal prosecutors used the Stored Communications Act to obtain 127 days of cell-site location information (CSLI) from Carpenter\'s wireless carriers, MetroPCS and Sprint. The CSLI data placed Carpenter\'s phone near four of the robbery locations at the time of the crimes. At trial, a FBI agent testified about the location data, and Carpenter was convicted on six counts of robbery and five counts of carrying a firearm during a federal crime of violence. He was sentenced to more than 116 years in prison.',
    keyLegalIssues: [
      'Whether the government\'s warrantless acquisition of historical cell-site location information violates the Fourth Amendment',
      'Whether the third-party doctrine applies to long-term CSLI data obtained from wireless carriers',
      'Whether digital-age technology requires a revision of traditional Fourth Amendment frameworks',
      'Whether an individual retains a reasonable expectation of privacy in the physical movements reflected by CSLI records',
    ],
    plaintiffArguments: 'Carpenter argued that the government\'s warrantless collection of 127 days of CSLI constituted an unreasonable search under the Fourth Amendment. He contended that cell-site data is not truly "voluntarily shared" with a third party because customers have no meaningful choice but to generate location data merely by carrying a phone. He further argued that long-term CSLI data creates a "detailed chronicle" of a person\'s movements that reveals private conduct in ways that traditional surveillance cannot, and thus requires a warrant supported by probable cause.',
    defendantArguments: 'The government argued that the third-party doctrine, established in Smith v. Maryland and Miller, foreclosed any Fourth Amendment protection because Carpenter voluntarily shared his location data with his wireless carriers. The government contended that obtaining business records from a third party — the carrier — is not a search under the Fourth Amendment. It also argued that the Stored Communications Act\'s court-order mechanism provided adequate procedural protection, and that extending Fourth Amendment protections to third-party business records would hamper law enforcement investigations.',
    proceduralHistory: 'Carpenter moved to suppress the CSLI evidence in the Eastern District of Michigan, arguing the warrantless collection violated the Fourth Amendment. The district court denied the motion and Carpenter was convicted. The Sixth Circuit Court of Appeals affirmed, holding that Carpenter lacked a reasonable expectation of privacy in CSLI under the third-party doctrine. The Supreme Court granted certiorari to resolve a circuit split on the issue.',
    finalDecision: 'The Supreme Court reversed in a 5–4 decision authored by Chief Justice Roberts, holding that the government\'s warrantless seizure of Carpenter\'s CSLI was an unreasonable search under the Fourth Amendment. The Court held that the existing third-party doctrine does not extend to the comprehensive and detailed nature of historical CSLI records.',
    judicialReasoning: 'Chief Justice Roberts reasoned that a person carries their cell phone nearly everywhere and the resulting CSLI creates a near-perfect record of that person\'s movements, effectively functioning as an ankle monitor. The majority distinguished CSLI from ordinary business records because its comprehensive nature reveals the "privacies of life" that the Founders sought to protect from general warrants. Roberts applied the "mosaic theory" from Justice Sotomayor\'s concurrence in Jones, reasoning that aggregated location data over time is qualitatively different from a single record. The Court emphasized that the digital age requires a careful application of Fourth Amendment principles to prevent near-perfect surveillance with a single subpoena. The majority explicitly declined to disturb Smith v. Maryland or Miller but held that CSLI falls outside their logic. The decision stressed that individuals do not voluntarily convey location data in any meaningful sense simply by using a mobile phone in daily life.',
    legalStandards: [
      'Fourth Amendment reasonable expectation of privacy (Katz v. United States)',
      'Third-party doctrine (Smith v. Maryland; United States v. Miller)',
      'Mosaic theory of aggregated data',
      'Probable cause and warrant requirement for digital records',
    ],
    keyPrecedents: [
      'Katz v. United States, 389 U.S. 347 (1967)',
      'Smith v. Maryland, 442 U.S. 735 (1979)',
      'United States v. Miller, 425 U.S. 435 (1976)',
      'United States v. Jones, 565 U.S. 400 (2012)',
      'Riley v. California, 573 U.S. 373 (2014)',
    ],
    evidenceAnalysis: 'The government introduced testimony from an FBI agent who analyzed 127 days of CSLI placing Carpenter\'s phone near the robbery locations at the relevant times. The records showed 12,898 location points gathered from the carriers without a warrant. The Court noted that such a voluminous record was indistinguishable from GPS surveillance and capable of revealing far more about a person\'s life than a single snapshot of location.',
    alternativeOutcomes: 'Had the Court applied the traditional third-party doctrine without modification, law enforcement would have retained the ability to obtain any volume of CSLI with a court order under the lower "specific and articulable facts" standard, fundamentally enabling mass surveillance through carrier records. Alternatively, a narrower ruling limited to cell-site records without touching the third-party doctrine would have left the broader doctrine intact while protecting CSLI specifically.',
    lessonsLearned: [
      'Long-term digital surveillance records require probable cause warrants even when collected from third parties',
      'The third-party doctrine has meaningful limits in the digital age',
      'Volume and comprehensiveness of data distinguishes modern records from traditional business documents',
      'Courts must adapt Fourth Amendment doctrine to the reality of pervasive digital tracking',
    ],
    bestPractices: [
      'Law enforcement should obtain a warrant before seeking historical CSLI from wireless carriers',
      'Prosecutors should assess whether third-party records are truly "voluntary" in the digital context before relying on the third-party doctrine',
      'Defense counsel should challenge warrantless acquisition of long-term location data under Carpenter',
      'Privacy advocates should monitor legislative efforts to codify Carpenter\'s warrant requirement',
    ],
    significance: 'Carpenter v. United States is widely regarded as the most significant Fourth Amendment decision of the digital age. By limiting the third-party doctrine for comprehensive digital records, the Supreme Court acknowledged that the government cannot exploit modern technology to conduct near-perfect surveillance without judicial oversight. The ruling established a new framework for evaluating digital privacy, focusing on the comprehensive and revealing nature of data rather than merely whether it was shared with a third party. Lower courts have since applied Carpenter to license plate reader data, real-time CSLI, and other forms of persistent digital tracking. The decision also signaled that the Court may revisit other third-party doctrine applications, such as internet browsing history and smart-device data, as technology continues to evolve. Carpenter stands as a foundational precedent for the proposition that the Fourth Amendment must keep pace with technological change.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Timothy Ivory Carpenter',
        role: 'PLAINTIFF',
        counsel: 'Nathan Wessler (ACLU)',
        description: 'Defendant in the underlying criminal case who challenged the warrantless collection of his cell-site location information',
      },
      {
        name: 'United States',
        role: 'DEFENDANT',
        counsel: 'Michael R. Dreeben (Deputy Solicitor General)',
        description: 'Federal government that obtained historical CSLI records from wireless carriers without a warrant',
      },
    ],
  },
  {
    litigationSlug: 'privacy-data',
    name: 'Riley v. California',
    citation: '573 U.S. 373 (2014)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2014,
    facts: 'David Leon Riley was stopped by San Diego police in August 2009 for driving with expired registration tags. The stop led to the discovery that Riley\'s license was suspended, and officers impounded his car. During a routine inventory search, officers found two handguns and arrested Riley. Incident to his arrest, a police officer searched Riley\'s smartphone without a warrant, discovering photos, videos, and contact information that prosecutors alleged linked him to a gang and a shooting that occurred weeks earlier. A second, more extensive search of the phone was performed by a detective who had been trained in digital forensics, revealing additional evidence. Riley was charged with assault with a semiautomatic firearm, attempted murder, and shooting at an occupied vehicle. The smartphone evidence was central to the prosecution, and Riley was convicted and sentenced to fifteen years to life.',
    keyLegalIssues: [
      'Whether the Fourth Amendment permits police to search a cell phone\'s digital contents incident to a lawful arrest without a warrant',
      'Whether the search-incident-to-arrest exception extends to the data stored on a modern smartphone',
      'Whether digital data on a cell phone presents the same safety and evidence-preservation justifications as physical items found on an arrestee',
      'How to apply traditional search-incident-to-arrest doctrine to a device containing vast amounts of personal information',
    ],
    plaintiffArguments: 'Riley argued that the warrantless search of his smartphone\'s digital contents violated the Fourth Amendment because a smartphone is categorically different from other items an arrestee might carry. He contended that the two traditional justifications for the search-incident-to-arrest exception — officer safety and prevention of evidence destruction — do not apply to digital data on a phone, since data poses no physical threat and can be remotely preserved or wiped regardless of whether the phone is in police custody. Riley asserted that a modern smartphone contains essentially the sum of a person\'s private life and therefore commands the highest Fourth Amendment protection.',
    defendantArguments: 'California argued that the search-incident-to-arrest exception, established in Chimel v. California and extended to containers in United States v. Robinson, applied straightforwardly to cell phones. The state contended that officers may search items in an arrestee\'s possession to ensure officer safety and prevent the destruction of evidence. California further argued that digital files on a phone are analogous to papers in a wallet or photographs in a purse, all of which may be searched incident to arrest, and that a categorical rule against cell-phone searches would unnecessarily hamper police investigations.',
    proceduralHistory: 'Riley moved to suppress the evidence obtained from his smartphone in San Diego Superior Court; the motion was denied. He was convicted at trial. The California Court of Appeal affirmed, applying the search-incident-to-arrest doctrine. The Supreme Court of California denied review. The Supreme Court of the United States consolidated Riley\'s case with United States v. Wurie, in which the First Circuit had reached the opposite conclusion, and granted certiorari to resolve the circuit conflict.',
    finalDecision: 'The Supreme Court reversed unanimously, holding that police must generally obtain a warrant before searching the digital contents of a cell phone seized incident to an arrest. Chief Justice Roberts authored the opinion, joined by all eight other justices.',
    judicialReasoning: 'Chief Justice Roberts wrote that cell phones are not "just another technological convenience" but are "in fact minicomputers" that contain a vast store of personal information — health records, financial records, intimate photos, and location history — that no physical object carried by an arrestee has ever contained. The Court held that neither of the two Chimel rationales applies to digital data: data cannot harm an arresting officer, and modern policing techniques including Faraday bags can address evidence-preservation concerns without warrantless searches. Roberts emphasized that the quantity and quality of digital data on a smartphone are qualitatively different from the content of a billfold or a physical container, invoking the Founders\' concerns about general warrants. The Court rejected the government\'s proposed balancing tests as unworkable and instead announced a categorical rule requiring a warrant. Justice Alito concurred in the judgment, expressing discomfort with the categorical approach but agreeing that a warrant was required pending legislative guidance.',
    legalStandards: [
      'Fourth Amendment prohibition on unreasonable searches and seizures',
      'Search-incident-to-arrest exception (Chimel v. California)',
      'Warrant requirement for searches of digital data',
      'Balancing of privacy interests against governmental need',
    ],
    keyPrecedents: [
      'Chimel v. California, 395 U.S. 752 (1969)',
      'United States v. Robinson, 414 U.S. 218 (1973)',
      'Katz v. United States, 389 U.S. 347 (1967)',
      'Arizona v. Gant, 556 U.S. 332 (2009)',
    ],
    evidenceAnalysis: 'The digital evidence from Riley\'s smartphone included photographs and videos showing him making gang signs with known gang members, evidence of gang affiliation, and content linking him to the shooting. The forensic detective\'s search of the phone\'s contents extended well beyond what was immediately visible. The Court found this breadth of warrantless digital search particularly troubling, noting that a phone\'s contents can reveal far more than any physical evidence found on a person.',
    alternativeOutcomes: 'If the Court had applied the search-incident-to-arrest exception to cell phones, police nationwide would have retained virtually unlimited authority to search the entire digital contents of any smartphone upon any custodial arrest, regardless of the crime\'s severity. A narrower ruling permitting searches of call logs but not other app data would have created difficult line-drawing problems for courts and law enforcement.',
    lessonsLearned: [
      'The search-incident-to-arrest exception has categorical limits that do not extend to digital data',
      'The quantity and sensitivity of data on modern smartphones demand warrant protection',
      'Traditional Fourth Amendment exceptions must be evaluated based on the actual justifications behind them, not automatic extension to new technology',
      'Law enforcement must obtain warrants before accessing cell phone data even when the phone is seized incident to a lawful arrest',
    ],
    bestPractices: [
      'Officers should seek a warrant before conducting any search of a seized smartphone\'s digital contents',
      'Use Faraday bags or similar signal-blocking containers to preserve phone evidence while seeking a warrant',
      'Defense counsel should file motions to suppress smartphone evidence obtained without a warrant incident to arrest',
      'Prosecutors should ensure that digital evidence obtained from phones in pre-Riley arrests is evaluated under contemporaneous law',
    ],
    significance: 'Riley v. California established that the digital contents of a cell phone are entitled to full Fourth Amendment protection and cannot be searched without a warrant incident to arrest. The decision was unanimous, which underscored the Court\'s recognition that smartphones represent a qualitatively new challenge for Fourth Amendment doctrine. Riley effectively ended a widespread law-enforcement practice of routinely searching the contents of arrested individuals\' phones. The ruling has been applied broadly to tablets and other digital devices and has become a foundational case in the digital-privacy canon alongside Carpenter v. United States. Legal scholars have cited Riley as evidence that the Roberts Court is willing to update Fourth Amendment doctrine for the digital age, departing from the categorical application of analog-era exceptions.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'David Leon Riley',
        role: 'PLAINTIFF',
        counsel: 'Patrick Pitman',
        description: 'Criminal defendant whose smartphone was searched without a warrant incident to his arrest for a traffic violation',
      },
      {
        name: 'State of California',
        role: 'DEFENDANT',
        counsel: 'Edward C. DuMont (California Solicitor General)',
        description: 'State that argued the search-incident-to-arrest exception permitted warrantless cell phone searches',
      },
    ],
  },
  {
    litigationSlug: 'privacy-data',
    name: 'Katz v. United States',
    citation: '389 U.S. 347 (1967)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1967,
    facts: 'Charles Katz was a professional gambler who used a public telephone booth in Los Angeles to transmit illegal wagering information to clients in Boston and Miami in violation of a federal statute. FBI agents, suspecting Katz of illegal gambling activity, attached a small electronic eavesdropping device to the outside of the public phone booth without obtaining a warrant. The agents recorded only Katz\'s side of the conversations, capturing his wagering calls. Katz was subsequently arrested and convicted on eight counts of transmitting wagering information by telephone. The FBI agents never obtained judicial authorization before placing or using the listening device, believing that the Fourth Amendment protected only "constitutionally protected areas" such as the interior of a home, and that a public phone booth did not qualify.',
    keyLegalIssues: [
      'Whether the Fourth Amendment protects individuals from warrantless electronic surveillance when they are in a public place',
      'Whether Fourth Amendment protection is limited to physical intrusion into constitutionally protected areas',
      'Whether a person using a public telephone booth has a reasonable expectation of privacy in conversations conducted therein',
      'What standard should govern whether government surveillance constitutes a Fourth Amendment search',
    ],
    plaintiffArguments: 'Katz argued that the FBI\'s warrantless electronic eavesdropping violated the Fourth Amendment regardless of whether he was in a public space. He contended that by entering the phone booth and closing the door, he justifiably relied on the booth\'s enclosure to protect his conversations from the outside world. Katz asserted that the Fourth Amendment protects people and their reasonable expectations, not merely places, and that government agents must obtain a warrant before intercepting private communications even when listening from outside a physical structure.',
    defendantArguments: 'The government argued that because the listening device was placed on the exterior of the phone booth — a public space — no Fourth Amendment search occurred. The government relied on the prevailing "trespass doctrine" from Olmstead v. United States and Goldman v. United States, which held that the Fourth Amendment required a physical intrusion into a constitutionally protected area. Since the agents never physically entered the booth, the government maintained that no search had taken place and no warrant was required.',
    proceduralHistory: 'Katz was convicted in the Southern District of California. The Ninth Circuit Court of Appeals affirmed, concluding that there was no Fourth Amendment violation because the agents had not physically entered the phone booth and the eavesdropping was accomplished without penetrating the booth\'s walls. The Supreme Court granted certiorari, and the case was argued on October 17, 1967.',
    finalDecision: 'The Supreme Court reversed Katz\'s conviction in a 7–1 decision authored by Justice Stewart. The Court held that the government\'s warrantless electronic surveillance of Katz\'s phone booth conversations violated the Fourth Amendment and overruled the trespass doctrine of Olmstead and Goldman.',
    judicialReasoning: 'Justice Stewart\'s majority opinion established the famous principle that "the Fourth Amendment protects people, not places," departing fundamentally from the property-based trespass doctrine. Stewart reasoned that a person who enters a phone booth, shuts the door, and pays the toll may rely upon the protection of the Fourth Amendment, even though the booth is constructed partly of glass and visible to passersby. The majority held that whatever a person "seeks to preserve as private, even in an area accessible to the public, may be constitutionally protected." The Court found that the agents\' eavesdropping, however technically skillful, was a search within the meaning of the Fourth Amendment, and that a warrant should have been obtained before the surveillance began. Justice Harlan\'s concurrence, which proved the more influential opinion, articulated the two-part "reasonable expectation of privacy" test: a person must exhibit a subjective expectation of privacy, and that expectation must be one society is prepared to recognize as reasonable. The Harlan test became the dominant framework for Fourth Amendment analysis in all subsequent cases.',
    legalStandards: [
      'Reasonable expectation of privacy test (Justice Harlan\'s concurrence)',
      'Fourth Amendment prohibition on warrantless electronic surveillance',
      'Rejection of property-based trespass doctrine for Fourth Amendment purposes',
      'Warrant requirement prior to government interception of private communications',
    ],
    keyPrecedents: [
      'Olmstead v. United States, 277 U.S. 438 (1928) (overruled)',
      'Goldman v. United States, 316 U.S. 129 (1942) (overruled)',
      'Silverman v. United States, 365 U.S. 505 (1961)',
      'Berger v. New York, 388 U.S. 41 (1967)',
    ],
    evidenceAnalysis: 'The FBI\'s recording device captured only the portion of telephone conversations spoken by Katz within the booth. Agents made selective recordings over several days to collect sufficient evidence of illegal wagering. The Court noted that the agents could have sought a warrant before conducting the surveillance and that their failure to do so — despite having probable cause — rendered the recordings inadmissible.',
    alternativeOutcomes: 'Had the Court maintained the trespass doctrine, government electronic surveillance of virtually any public communication would have been beyond Fourth Amendment scrutiny as long as agents did not physically enter a protected area. Conversely, a narrower ruling limited to phone booths without establishing the reasonable-expectation-of-privacy test would have provided less guidance for future technological developments.',
    lessonsLearned: [
      'The Fourth Amendment protects people and their reasonable expectations of privacy, not merely places',
      'Electronic surveillance without a warrant violates the Fourth Amendment even absent a physical trespass',
      'Government agents must seek judicial authorization before intercepting private communications',
      'The reasonable expectation of privacy framework must adapt as surveillance technology evolves',
    ],
    bestPractices: [
      'Law enforcement must obtain judicial authorization before conducting electronic surveillance of private communications',
      'Courts should apply the two-part Katz test to evaluate Fourth Amendment claims involving new surveillance technologies',
      'Defense counsel should challenge electronic surveillance evidence obtained without a warrant',
      'Legislators should craft wiretapping statutes consistent with Katz\'s constitutional baseline',
    ],
    significance: 'Katz v. United States is the foundational Fourth Amendment privacy case of the modern era. By replacing the trespass doctrine with the reasonable expectation of privacy test, the Supreme Court opened the door for Fourth Amendment protection to evolve alongside technological change. Justice Harlan\'s concurrence became the dominant analytical framework cited in virtually every subsequent Fourth Amendment case, including Smith v. Maryland, United States v. Jones, Riley v. California, and Carpenter v. United States. Katz also prompted Congress to enact the Omnibus Crime Control and Safe Streets Act of 1968, which created the modern federal wiretapping framework. The decision\'s enduring influence cannot be overstated: it reoriented Fourth Amendment jurisprudence from property rights to personal privacy and established the constitutional baseline against which all government surveillance is measured.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Charles Katz',
        role: 'PLAINTIFF',
        counsel: 'Harvey A. Schneider',
        description: 'Professional gambler whose telephone conversations were recorded by FBI agents using a warrantless electronic listening device',
      },
      {
        name: 'United States',
        role: 'DEFENDANT',
        counsel: 'John S. Martin Jr. (Assistant Attorney General)',
        description: 'Federal government that conducted warrantless electronic surveillance of Katz\'s public telephone conversations',
      },
    ],
  },
  {
    litigationSlug: 'privacy-data',
    name: 'Smith v. Maryland',
    citation: '442 U.S. 735 (1979)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1979,
    facts: 'On March 5, 1976, Patricia McDonough was robbed in Baltimore, Maryland. Shortly after the robbery, she began receiving threatening phone calls from a man who identified himself as her robber and who also drove past her home in a 1975 Monte Carlo. McDonough reported the calls and the car to police. Officers observed a man named Michael Lee Smith driving the Monte Carlo past McDonough\'s home. At the request of police and without obtaining a warrant, the telephone company installed a pen register at its central offices to record the numbers dialed from Smith\'s home phone. On March 17, 1976, the pen register recorded that Smith\'s phone had dialed McDonough\'s number. Armed with this and other evidence, officers obtained a warrant to search Smith\'s home, where they found a phone book with McDonough\'s page turned down and an entry next to her name. Smith was arrested and convicted of robbery.',
    keyLegalIssues: [
      'Whether the installation and use of a pen register to record numbers dialed from a home telephone constitutes a Fourth Amendment search',
      'Whether an individual has a reasonable expectation of privacy in the telephone numbers they dial',
      'Whether the third-party doctrine precludes Fourth Amendment protection for information voluntarily conveyed to a third party such as a telephone company',
      'Whether Katz v. United States\'s reasonable expectation of privacy test applies to dialing information shared with the phone company',
    ],
    plaintiffArguments: 'Smith argued that the warrantless installation of a pen register on his phone line violated the Fourth Amendment under the Katz reasonable expectation of privacy test. He contended that he had a subjective expectation of privacy in the phone numbers he dialed from his home, and that society would recognize such an expectation as reasonable. Smith asserted that dialing a phone number is an involuntary and necessary byproduct of using telephone service, not a voluntary disclosure to the phone company, and that the company uses the information only for billing purposes — not to share it with law enforcement.',
    defendantArguments: 'The government argued that Smith had no reasonable expectation of privacy in the numbers he dialed because he voluntarily conveyed those numbers to the telephone company when he used the phone. Relying on United States v. Miller, which held that bank records voluntarily shared with a bank lose Fourth Amendment protection, the government argued that the same third-party doctrine applied to numbers dialed. The government further contended that a pen register records only numbers dialed — not the content of communications — and therefore falls outside Fourth Amendment protection even under Katz.',
    proceduralHistory: 'Smith moved to suppress the pen register evidence in Maryland trial court; the motion was denied. He was convicted. The Maryland Court of Special Appeals and the Maryland Court of Appeals both affirmed the conviction. The Supreme Court granted certiorari to determine whether the Fourth Amendment governs government use of pen registers.',
    finalDecision: 'The Supreme Court affirmed Smith\'s conviction in a 5–3 decision authored by Justice Blackmun. The Court held that the installation and use of the pen register did not constitute a Fourth Amendment search because Smith lacked a reasonable expectation of privacy in the numbers he dialed.',
    judicialReasoning: 'Justice Blackmun applied Justice Harlan\'s two-part Katz test and concluded that Smith failed both prongs. First, the majority held that Smith could not have harbored a subjective expectation of privacy in the numbers dialed, because any telephone user knows that the numbers they dial are conveyed to and recorded by the phone company for billing purposes. Second, even if Smith held such a subjective expectation, society would not recognize it as reasonable because the phone company routinely exposes dialed numbers to its equipment and employees. Blackmun invoked the third-party doctrine from Miller: by voluntarily conveying the dialed numbers to the phone company, Smith assumed the risk that the company would reveal that information to police. The majority distinguished content of communications from mere addressing information, noting that a pen register captures only the latter. Justices Stewart, Brennan, and Marshall dissented, arguing that the majority erred in concluding Smith lacked a subjective expectation and that the voluntary-disclosure rationale was a fiction when telephone use is a practical necessity of modern life.',
    legalStandards: [
      'Reasonable expectation of privacy test (Katz v. United States)',
      'Third-party doctrine (United States v. Miller)',
      'Distinction between content of communications and addressing/routing information',
      'Voluntary assumption of risk in sharing information with third parties',
    ],
    keyPrecedents: [
      'Katz v. United States, 389 U.S. 347 (1967)',
      'United States v. Miller, 425 U.S. 435 (1976)',
      'Hoffa v. United States, 385 U.S. 293 (1966)',
      'On Lee v. United States, 343 U.S. 747 (1952)',
    ],
    evidenceAnalysis: 'The pen register installed by the telephone company recorded the phone numbers dialed from Smith\'s home but did not capture the content of any calls. The register recorded Smith\'s call to McDonough\'s number on March 17, 1976. This single pen register record, combined with evidence from the authorized search of Smith\'s home, was sufficient to support Smith\'s conviction. The Court noted that pen registers are limited instruments that generate no information about the substance of conversations.',
    alternativeOutcomes: 'Had the Court held that pen registers require a warrant, law enforcement would have faced significant obstacles in investigations relying on call records. A ruling requiring warrants for pen registers would have laid the groundwork for broader Third Amendment protections for metadata, potentially influencing later decisions about internet metadata and CSLI. The dissenting justices\' approach would have required courts to distinguish between different types of third-party records based on the sensitivity of the information.',
    lessonsLearned: [
      'Information voluntarily shared with a third party loses Fourth Amendment protection under the third-party doctrine',
      'There is a constitutional distinction between the content of communications and addressing or routing information',
      'The practical necessity of using a service does not necessarily transform the resulting data disclosures into constitutionally protected communications',
      'The third-party doctrine established in Smith has been subject to significant criticism and partial limitation in the digital age',
    ],
    bestPractices: [
      'Prosecutors should understand that Carpenter v. United States limits Smith\'s third-party doctrine for comprehensive digital tracking records',
      'Defense counsel should scrutinize whether challenged evidence constitutes mere metadata or reveals the substance of communications',
      'Privacy advocates should press for statutory protections for metadata that go beyond the constitutional floor set by Smith',
      'Courts applying Smith should carefully assess whether modern digital metadata is truly analogous to pen register data',
    ],
    significance: 'Smith v. Maryland established the third-party doctrine as a central feature of Fourth Amendment law and had an enormous practical impact on government surveillance capabilities. By holding that individuals surrender Fourth Amendment protection in information they share with third parties, Smith enabled decades of warrantless access to telephone records, bank records, and eventually internet metadata. The decision became a flashpoint in Fourth Amendment scholarship and was directly addressed — and partially overruled — by the Supreme Court in Carpenter v. United States (2018), which held that comprehensive digital location records fall outside Smith\'s logic. Smith remains the leading case articulating the third-party doctrine, and its continued vitality for non-comprehensive metadata records ensures it will remain relevant as courts grapple with government demands for digital data.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'Michael Lee Smith',
        role: 'PLAINTIFF',
        counsel: 'Public defender (name not recorded)',
        description: 'Robbery defendant whose dialed phone numbers were recorded by a pen register installed without a warrant at the request of police',
      },
      {
        name: 'State of Maryland',
        role: 'DEFENDANT',
        counsel: 'Gilbert Rosenthal (Maryland Assistant Attorney General)',
        description: 'State that used warrantless pen register records to help secure Smith\'s robbery conviction',
      },
    ],
  },
  {
    litigationSlug: 'privacy-data',
    name: 'Sorrell v. IMS Health Inc.',
    citation: '564 U.S. 552 (2011)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2011,
    facts: 'Vermont enacted the Prescription Confidentiality Law in 2007, which restricted the sale, disclosure, and use of pharmacy records that revealed prescriber-identifying information — specifically, data identifying the physician who wrote each prescription. The law prohibited pharmacies and data-mining companies from selling or using this prescriber data for marketing purposes without the prescriber\'s consent, but permitted its use for research, education, and other non-commercial purposes. IMS Health Incorporated and other data-mining and pharmaceutical companies challenged the law, arguing that it violated the First Amendment by restricting the sale and use of lawfully obtained speech (prescriber data) based on the viewpoint and content of the intended use. Vermont argued the law protected physician privacy and reduced the influence of pharmaceutical marketing on prescribing practices.',
    keyLegalIssues: [
      'Whether Vermont\'s Prescription Confidentiality Law violated the First Amendment by restricting the sale and use of prescriber data based on the speaker\'s identity and the content of the intended speech',
      'Whether the commercial sale and transfer of data constitutes protected speech under the First Amendment',
      'Whether content-based and speaker-based restrictions on data use must satisfy heightened First Amendment scrutiny',
      'Whether the state\'s interests in physician privacy and limiting pharmaceutical marketing justify restrictions on data sales',
    ],
    plaintiffArguments: 'IMS Health and the pharmaceutical companies argued that the Vermont law imposed an unconstitutional content-based and speaker-based restriction on protected speech. They contended that the sale and use of prescriber data constitutes speech and that the law singled out pharmaceutical marketers for disfavored treatment while allowing the same data to be used freely by academic researchers and others. The companies argued that the law could not survive heightened First Amendment scrutiny because Vermont\'s interests in physician privacy and healthcare cost control did not justify a speaker-specific and content-specific speech restriction.',
    defendantArguments: 'Vermont argued that prescriber data is commercial information subject to reduced constitutional protection, and that the state\'s interest in protecting physician privacy and reducing the distortive effect of targeted pharmaceutical marketing on medical decision-making provided sufficient justification for the law. The state contended that the law regulated commercial conduct — the sale of data — rather than speech itself, and that any incidental burden on speech was justified by the state\'s substantial interests. Vermont also argued that the law was a permissible restriction on commercial data transactions rather than on the content of any message.',
    proceduralHistory: 'IMS Health filed suit in the District of Vermont, which upheld the law. The Second Circuit Court of Appeals reversed, finding the law violated the First Amendment under heightened scrutiny. Vermont sought certiorari. The Supreme Court granted review and affirmed the Second Circuit in a 6–3 decision.',
    finalDecision: 'The Supreme Court affirmed the Second Circuit\'s judgment that the Vermont Prescription Confidentiality Law violated the First Amendment. Justice Kennedy\'s majority opinion held that the law imposed a content-based and speaker-based restriction on protected speech and that Vermont had not demonstrated the law survived heightened scrutiny.',
    judicialReasoning: 'Justice Kennedy\'s majority concluded that the Vermont law was both content-based and speaker-based: it restricted the use of prescriber data specifically when used for pharmaceutical marketing and specifically burdened certain speakers (pharmaceutical companies and data miners) while allowing others (researchers, educators) to use the same data freely. The majority held that such targeted restrictions on the use of lawfully obtained information constitute restrictions on speech subject to heightened First Amendment scrutiny. Kennedy rejected Vermont\'s argument that the law regulated only commercial conduct, finding that the creation and dissemination of data is itself a form of speech. The majority applied a form of intermediate-to-strict scrutiny and concluded that Vermont\'s privacy and cost-control interests, though substantial, were not served in a sufficiently direct or proportionate manner because the law\'s real aim was to limit the persuasive impact of pharmaceutical marketing. Justice Breyer dissented for three justices, arguing that the majority\'s approach threatened the government\'s ability to regulate commerce in data and that the law should have been evaluated under the lenient rational-basis standard applicable to economic regulation.',
    legalStandards: [
      'First Amendment protection for the sale and use of data as speech',
      'Content-based and speaker-based restriction analysis under heightened scrutiny',
      'Commercial speech doctrine and its relationship to data regulation',
      'Central Hudson test (discussed but not solely applied)',
    ],
    keyPrecedents: [
      'Central Hudson Gas & Electric Corp. v. Public Service Commission, 447 U.S. 557 (1980)',
      'Virginia Pharmacy Board v. Virginia Citizens Consumer Council, 425 U.S. 748 (1976)',
      'Bartnicki v. Vopper, 532 U.S. 514 (2001)',
      'Trans Union LLC v. FTC, 267 F.3d 1138 (D.C. Cir. 2001)',
    ],
    evidenceAnalysis: 'The parties presented evidence on the economic value of prescriber-identified data to pharmaceutical companies and the degree to which the law would impair the data-mining business model. Vermont introduced evidence of physician complaints about targeted pharmaceutical detailing and studies suggesting that physician-specific prescribing data enabled aggressive marketing tactics. The majority found this evidence showed only that Vermont sought to limit persuasive speech, not that privacy interests justified the restriction.',
    alternativeOutcomes: 'Had the Court upheld Vermont\'s law, states would have gained significant authority to restrict the commercial data trade by asserting privacy or consumer-protection interests. The ruling\'s application of heightened First Amendment scrutiny to data sales effectively limited states\' ability to enact comprehensive data-privacy statutes targeting commercial data flows. A ruling for Vermont might have opened the door to broader state regulation of personal data markets, including health and financial data.',
    lessonsLearned: [
      'The commercial sale and transfer of data constitutes protected speech under the First Amendment',
      'Content-based or speaker-based data restrictions face heightened constitutional scrutiny',
      'States seeking to regulate data for privacy reasons must tailor their laws carefully to avoid viewpoint or speaker discrimination',
      'The First Amendment can serve as a significant constraint on data-privacy legislation',
    ],
    bestPractices: [
      'Legislators drafting data-privacy statutes should ensure that restrictions apply neutrally across speakers and uses to minimize First Amendment vulnerability',
      'Companies challenging data regulations should analyze whether the restriction is content-based or speaker-specific',
      'Privacy advocates should consider whether their proposed data restrictions can survive First Amendment scrutiny under Sorrell',
      'Courts should apply Sorrell to evaluate whether digital data regulations impermissibly restrict commercial speech',
    ],
    significance: 'Sorrell v. IMS Health is a landmark decision at the intersection of data privacy and the First Amendment. By treating the sale and use of prescriber data as protected speech and applying heightened scrutiny to content-based and speaker-based data restrictions, the Supreme Court significantly constrained states\' and Congress\'s ability to regulate commercial data markets through privacy law. The decision has been widely cited by data brokers and technology companies to challenge state data-privacy regulations, including restrictions on targeted advertising and the sale of consumer data. Legal scholars have debated whether Sorrell effectively constitutionalizes data commerce in ways that undermine democratic efforts to protect personal privacy. The ruling sits in tension with growing legislative efforts — such as comprehensive state privacy laws — and raises profound questions about whether the First Amendment protects the exploitation of personal data at scale.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'IMS Health Incorporated',
        role: 'PLAINTIFF',
        counsel: 'Thomas C. Goldstein (Goldstein & Russell)',
        description: 'Data-mining company that compiled and sold prescriber-identified pharmaceutical data to drug manufacturers for marketing purposes',
      },
      {
        name: 'William H. Sorrell (Vermont Attorney General)',
        role: 'DEFENDANT',
        counsel: 'Bridget Asay (Vermont Assistant Attorney General)',
        description: 'Vermont Attorney General defending the state\'s Prescription Confidentiality Law restricting the sale and use of prescriber data for pharmaceutical marketing',
      },
      {
        name: 'Pharmaceutical Research and Manufacturers of America',
        role: 'INTERVENOR',
        description: 'Trade association representing pharmaceutical manufacturers that challenged the Vermont law alongside IMS Health',
      },
    ],
  },
];

export default cases;
