import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'tort',
    name: 'Palsgraf v. Long Island Railroad Co.',
    citation: '248 N.Y. 339, 162 N.E. 99 (1928)',
    jurisdiction: 'New York, United States',
    court: 'New York Court of Appeals',
    year: 1928,
    facts: 'On August 24, 1928, Helen Palsgraf was standing on a platform of the Long Island Railroad after purchasing a ticket to Rockaway Beach. Two railroad guards assisted a passenger who was running to board a moving train; one guard on the train pulled the man aboard while another guard on the platform pushed him from behind. During this assistance, the passenger dropped a package of fireworks, which exploded when it fell on the rails. The explosion caused a set of scales at the other end of the platform, some distance away, to fall and strike Palsgraf, injuring her. Palsgraf sued the railroad, arguing that its employees had acted negligently in helping the passenger board the train.',
    keyLegalIssues: [
      'Whether the railroad owed a duty of care to a bystander injured by a remote and unforeseeable chain of events',
      'How far the zone of foreseeable danger extends for purposes of negligence liability',
      'Whether proximate cause requires foreseeability of harm to the specific plaintiff',
      'The relationship between negligence, duty, and proximate cause in tort law',
    ],
    plaintiffArguments: 'Palsgraf argued that the railroad guards acted negligently in their haste to assist the passenger onto the moving train, and that this negligence was the proximate cause of her injuries. She contended that anyone on the platform was within the foreseeable zone of danger created by the guards\' conduct and that the railroad bore responsibility for any harm resulting from its employees\' careless acts. She further argued that the guards\' actions created a risk that should make the railroad liable for all resulting consequences.',
    defendantArguments: 'The Long Island Railroad argued that its employees\' actions were not negligent with respect to Palsgraf, because no reasonable person could have foreseen that helping a passenger board a train would cause injury to a person standing far down the platform. The railroad contended that negligence must be measured in relation to the plaintiff, not in the abstract, and that no duty was owed to Palsgraf because she was not within the foreseeable zone of danger. The railroad maintained that the chain of causation from the guards\' act to Palsgraf\'s injury was too attenuated to support liability.',
    proceduralHistory: 'Palsgraf brought suit in the trial court and obtained a verdict in her favor, with the jury finding the railroad liable for her injuries. The Appellate Division of the New York Supreme Court affirmed the verdict. The Long Island Railroad appealed to the New York Court of Appeals, the state\'s highest court, which reversed the lower courts\' rulings in a 4-3 decision authored by Chief Judge Benjamin Cardozo.',
    finalDecision: 'The New York Court of Appeals reversed and dismissed the complaint in a 4-3 decision. Chief Judge Cardozo, writing for the majority, held that the railroad employees were not negligent toward Palsgraf because she was not within the foreseeable zone of danger created by their actions. There was no duty owed to her, and therefore no negligence as to her.',
    judicialReasoning: 'Chief Judge Benjamin Cardozo held that negligence is a relational concept: one can only be negligent toward a specific person if a reasonable person in the defendant\'s position could have foreseen that their conduct posed a risk of harm to that person. Because nothing in the guards\' actions suggested that a distant bystander would be harmed, no duty ran to Palsgraf. Cardozo drew a sharp distinction between the act and its consequences, holding that the risk reasonably to be perceived defines the duty to be obeyed. Judge William Andrews dissented powerfully, arguing that negligence is a wrong to the world at large and that anyone harmed by a negligent act may recover regardless of whether the specific harm was foreseeable. The majority\'s foreseeability-based duty analysis became the dominant approach in American negligence law, while Andrews\' broader view shaped the proximate cause inquiry in many jurisdictions.',
    legalStandards: [
      'Duty of care limited to foreseeable plaintiffs within the zone of danger',
      'Negligence is relational: the risk reasonably to be perceived defines the duty to be obeyed',
      'Proximate cause and foreseeability as limiting principles of tort liability',
      'The reasonable person standard applied to the scope of foreseeable harm',
    ],
    keyPrecedents: [
      'Heaven v. Pender (1883) — early English formulation of duty of care',
      'Thomas v. Winchester (1852) — New York precedent on negligence and third-party harm',
      'Devlin v. Smith (1882) — application of negligence to imminently dangerous articles',
    ],
    evidenceAnalysis: 'The physical facts of the incident — a package dropped during a struggle, an explosion, and scales falling at the far end of the platform — were undisputed. The central evidentiary question was whether the guards knew or should have known the package contained fireworks; the evidence indicated the package appeared to be a bundle of newspapers and gave no outward sign of its dangerous contents. This factual finding was critical to the court\'s conclusion that harm to a distant bystander was not foreseeable.',
    alternativeOutcomes: 'Had Judge Andrews\' dissenting view prevailed, Palsgraf would have recovered damages and the scope of negligence liability in the United States would be significantly broader, tying liability to factual causation rather than foreseeability of harm to the specific plaintiff. Under the Andrews approach, the railroad\'s admitted negligence toward the running passenger would have been sufficient to support liability to anyone harmed in the chain of consequences. A ruling for Palsgraf would have aligned American law more closely with some English authorities of the era.',
    lessonsLearned: [
      'Duty of care in negligence is not universal but must be owed to the specific plaintiff',
      'Foreseeability of harm is the foundational test for both duty and proximate cause',
      'Courts limit negligence liability to prevent crushing liability for remote consequences',
      'The zone of danger concept remains central to analyzing bystander claims in tort',
    ],
    bestPractices: [
      'Identify the specific plaintiff and assess whether harm to that person was foreseeable before asserting a negligence claim',
      'Document all facts bearing on foreseeability at the time of the defendant\'s conduct',
      'Analyze proximate cause separately from factual causation when causal chains are complex',
      'Consider both the Cardozo and Andrews approaches when evaluating marginal negligence cases across jurisdictions',
    ],
    significance: 'Palsgraf v. Long Island Railroad Co. is one of the most celebrated and debated cases in American tort law, establishing the principle that a defendant owes a duty of care only to foreseeable plaintiffs within the zone of danger created by their conduct. Chief Judge Cardozo\'s majority opinion and Judge Andrews\' dissent together constitute the two dominant theories of negligence duty and proximate cause that law students and practitioners study to this day. The case fundamentally shaped how American courts analyze the scope of liability in negligence actions and continues to be cited in virtually every major discussion of duty, proximate cause, and the limits of tort liability. Its influence extends far beyond New York, having been adopted in modified form by courts and legislatures across the country.',
    outcome: 'Defendant Victory',
    isFeatured: true,
    parties: [
      {
        name: 'Helen Palsgraf',
        role: 'PLAINTIFF',
        counsel: 'Matthew W. Wood',
        description: 'Passenger injured on the Long Island Railroad platform when scales fell after a distant explosion',
      },
      {
        name: 'Long Island Railroad Co.',
        role: 'DEFENDANT',
        counsel: 'William McNamara',
        description: 'Railroad whose guards assisted a passenger boarding a moving train, triggering a chain of events injuring Palsgraf',
      },
    ],
  },
  {
    litigationSlug: 'tort',
    name: 'MacPherson v. Buick Motor Co.',
    citation: '217 N.Y. 382, 111 N.E. 1050 (1916)',
    jurisdiction: 'New York, United States',
    court: 'New York Court of Appeals',
    year: 1916,
    facts: 'Donald C. MacPherson purchased a Buick automobile from a dealer in 1910. The car had been manufactured by the Buick Motor Company, which had purchased the wooden wheels from a third-party supplier. One of the wheels collapsed while MacPherson was driving the car, causing the vehicle to overturn and injuring him. Inspection revealed that the wood in the wheel was defective and the defect could have been discovered by reasonable inspection. Buick had not inspected the wheels before installing them in the finished automobile. MacPherson sued Buick directly in tort, despite not having a contractual relationship with the manufacturer.',
    keyLegalIssues: [
      'Whether a manufacturer owes a duty of care in tort to a consumer who is not in privity of contract with the manufacturer',
      'Whether an automobile constitutes an imminently dangerous article requiring heightened duty of care',
      'How far the "imminently dangerous" exception to the privity rule extends',
      'Whether a manufacturer may delegate its duty of inspection to component suppliers',
    ],
    plaintiffArguments: 'MacPherson argued that Buick, as the manufacturer of the finished automobile, owed him a duty of reasonable care regardless of the absence of a direct contractual relationship. He contended that an automobile is inherently dangerous if defective, and that Buick knew or should have known the car would be used by persons other than its immediate purchaser. MacPherson further argued that Buick could not escape liability by relying on its supplier\'s workmanship without conducting its own inspection of critical components.',
    defendantArguments: 'Buick Motor Company argued that under the established common law rule set forth in Winterbottom v. Wright, a manufacturer\'s duty of care ran only to the immediate purchaser with whom it was in privity of contract. Since MacPherson bought the car from a dealer rather than Buick directly, no duty was owed to him in tort. Buick also argued that an automobile was not an inherently dangerous article — unlike poisons or explosives — and therefore did not fall within the recognized exception to the privity rule for items that are dangerous in their very nature.',
    proceduralHistory: 'MacPherson filed suit in the Saratoga County Supreme Court, which entered judgment in his favor. The Appellate Division affirmed the trial court\'s judgment. Buick Motor Company appealed to the New York Court of Appeals, arguing that the absence of privity barred the tort claim. The Court of Appeals, in an opinion by Judge Benjamin Cardozo, unanimously affirmed the judgments below in 1916.',
    finalDecision: 'The New York Court of Appeals unanimously affirmed the judgment in favor of MacPherson. Judge Cardozo held that Buick owed MacPherson a duty of care because it knew the automobile would be used by persons other than the immediate buyer, and an automobile with a defective wheel is dangerous to life. The privity rule was effectively abolished as a limitation on manufacturer liability for negligence.',
    judicialReasoning: 'Judge Cardozo reasoned that the distinction between inherently dangerous articles and other goods had become untenable: the true test is not the character of the thing in the abstract but whether the thing is reasonably certain to place life and limb in peril when negligently made. Because Buick knew the automobile would be used by someone other than the dealer, and because a negligently constructed car poses a serious danger to life, Buick had a duty to inspect and ensure the safety of its product. Cardozo elegantly demonstrated that prior cases, including Thomas v. Winchester and Devlin v. Smith, supported this result once their underlying rationale was correctly understood. The opinion effectively abolished the privity requirement in product liability negligence and laid the foundation for modern products liability law.',
    legalStandards: [
      'Manufacturer owes a duty of care to foreseeable users of its product, not merely to the immediate purchaser',
      'The "imminently dangerous" category extends to any article reasonably certain to be dangerous if negligently made',
      'A manufacturer cannot escape liability for its own negligence by relying on component suppliers without inspection',
      'Knowledge that the product will be used beyond the immediate buyer gives rise to duty of care to ultimate users',
    ],
    keyPrecedents: [
      'Winterbottom v. Wright (1842) — English case establishing the privity requirement in tort that MacPherson overruled',
      'Thomas v. Winchester (1852) — New York case allowing tort recovery for mislabeled poison without privity',
      'Devlin v. Smith (1882) — extended liability to negligently built scaffolding used by third parties',
    ],
    evidenceAnalysis: 'The physical evidence established that the wooden wheel that collapsed contained defective wood, and expert testimony confirmed that the defect was visible and detectable upon reasonable inspection. The evidence showed that Buick had a policy of not separately inspecting wheels purchased from its supplier before installing them in finished automobiles. This evidence was decisive: Buick knew or should have known of the defect had it conducted the inspection its duty required.',
    alternativeOutcomes: 'Had the court ruled for Buick and maintained the strict privity requirement, the development of American products liability law would have been substantially delayed. Consumers injured by defective manufactured goods would have been limited to claims against the retailers from whom they purchased products, often leaving them without meaningful recourse against the party best positioned to prevent harm. The evolution toward strict products liability in the 1960s might have followed a very different path without MacPherson\'s foundational abolition of the privity bar.',
    lessonsLearned: [
      'Contractual privity does not define the scope of a manufacturer\'s tort duty to users of its products',
      'Manufacturers must inspect and test components from suppliers when those components are critical to safety',
      'Foreseeability of use by persons beyond the immediate buyer is sufficient to create a duty of care',
      'The character of danger determines duty, not the abstract category of the product',
    ],
    bestPractices: [
      'Implement robust incoming inspection programs for all safety-critical components regardless of supplier reputation',
      'Document all quality control and inspection procedures to establish reasonable care in litigation',
      'Identify all foreseeable end users when assessing the scope of duty in manufacturing contexts',
      'Retain product testing records and supplier quality agreements as evidence of reasonable care',
    ],
    significance: 'MacPherson v. Buick Motor Co. is a cornerstone of American products liability law, abolishing the privity of contract requirement as a barrier to negligence claims against manufacturers. Judge Cardozo\'s opinion transformed the landscape of consumer protection by establishing that manufacturers owe a duty of care to all foreseeable users of their products, not merely to the immediate purchaser. The decision directly paved the way for the strict products liability doctrine articulated in Greenman v. Yuba Power Products (1963) and Restatement (Second) of Torts Section 402A (1965). MacPherson remains required reading in virtually every American torts course and is cited as the origin point of the modern law of products liability.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Donald C. MacPherson',
        role: 'PLAINTIFF',
        description: 'Purchaser of a Buick automobile injured when a defective wheel collapsed while driving',
      },
      {
        name: 'Buick Motor Co.',
        role: 'DEFENDANT',
        description: 'Automobile manufacturer that assembled vehicles using wheels purchased from a third-party supplier without independent inspection',
      },
    ],
  },
  {
    litigationSlug: 'tort',
    name: 'Liebeck v. McDonald\'s Restaurants',
    citation: 'No. CV-93-02419, 1994 WL 16777704 (N.M. Dist. Ct. Aug. 18, 1994)',
    jurisdiction: 'New Mexico, United States',
    court: 'Second Judicial District Court of New Mexico',
    year: 1994,
    facts: 'On February 27, 1992, Stella Liebeck, a 79-year-old woman, purchased a cup of coffee at a McDonald\'s drive-through in Albuquerque, New Mexico. While sitting in the passenger seat of a parked car and attempting to add cream and sugar, she placed the cup between her knees, and the cup tipped, spilling the coffee onto her lap. McDonald\'s served its coffee at temperatures between 180 and 190 degrees Fahrenheit, significantly hotter than coffee served by most competitors. Liebeck suffered third-degree burns over six percent of her body, including her inner thighs and groin area, requiring hospitalization for eight days and skin grafting procedures. She sought settlement from McDonald\'s for $20,000 to cover her medical expenses; McDonald\'s offered only $800, leading to litigation.',
    keyLegalIssues: [
      'Whether McDonald\'s coffee served at 180-190 degrees Fahrenheit was unreasonably dangerous to consumers',
      'Whether McDonald\'s had adequate notice of the burn risk posed by its coffee temperature policy',
      'The appropriate apportionment of comparative fault between a product manufacturer and a consumer',
      'Whether punitive damages are warranted where a company continues a dangerous practice despite actual knowledge of prior injuries',
    ],
    plaintiffArguments: 'Liebeck argued that McDonald\'s coffee was defective because it was served at a temperature capable of causing serious burns in seconds of exposure, making it unreasonably dangerous for its intended use. Her attorneys presented evidence that McDonald\'s had received more than 700 complaints of burn injuries from its coffee in the preceding decade and had nonetheless maintained its high-temperature policy. Liebeck contended that McDonald\'s consciously disregarded the safety of its customers in favor of a business preference for coffee taste and holding time, warranting both compensatory and punitive damages.',
    defendantArguments: 'McDonald\'s argued that its coffee temperature was consistent with industry standards and consumer preferences, as coffee is customarily served hot and many customers drink it immediately upon purchase. The company maintained that Liebeck\'s own carelessness in handling an open hot beverage was the primary cause of her injuries, and that the risk of spilling hot liquids is a commonly known hazard. McDonald\'s contended that warning labels on its cups were sufficient to discharge any duty to warn and that no design defect existed in serving coffee at industry-standard temperatures.',
    proceduralHistory: 'Liebeck filed suit in the Second Judicial District Court of Bernalillo County, New Mexico in 1993 after McDonald\'s refused to settle for her medical expenses. The case proceeded to trial before Judge Robert Scott in August 1994. Prior to trial, a mediator recommended a settlement of $225,000, which McDonald\'s rejected. The jury trial concluded on August 17, 1994. Judge Scott subsequently reduced the punitive damage award, and the parties settled confidentially before further appeals were resolved.',
    finalDecision: 'The jury found McDonald\'s 80% at fault and Liebeck 20% at fault, awarding $200,000 in compensatory damages (reduced to $160,000 after the comparative fault reduction) and $2.7 million in punitive damages, representing approximately two days of McDonald\'s coffee sales revenue. Judge Robert Scott reduced the punitive damages to $480,000 — three times the compensatory award. The parties reached a confidential settlement before the verdict was finalized on appeal.',
    judicialReasoning: 'The jury and court found that McDonald\'s had actual notice of the hazard posed by its coffee temperature policy, having received hundreds of burn complaints over years, and had made a deliberate business decision to maintain temperatures associated with serious burn injuries. The punitive damage award reflected the jury\'s conclusion that McDonald\'s conscious disregard for consumer safety warranted punishment beyond mere compensation. Judge Scott\'s reduction of punitive damages to three times the compensatory award applied an established judicial benchmark for proportionality. The case turned on the distinction between a known, accepted risk and a risk that is unreasonable given the company\'s superior knowledge of actual injury rates.',
    legalStandards: [
      'Products liability: a product is defective if unreasonably dangerous for its intended or foreseeable use',
      'Comparative fault: plaintiff\'s recovery reduced in proportion to their own negligence',
      'Punitive damages available where defendant acts with conscious disregard of known risk of harm',
      'Duty to warn: manufacturer must warn consumers of non-obvious dangers associated with its product',
    ],
    keyPrecedents: [
      'Greenman v. Yuba Power Products, 59 Cal.2d 57 (1963) — established strict products liability in tort',
      'Restatement (Second) of Torts Section 402A (1965) — strict liability for defective products unreasonably dangerous to users',
      'BMW of North America v. Gore, 517 U.S. 559 (1996) — later Supreme Court guidance on punitive damages proportionality',
    ],
    evidenceAnalysis: 'Plaintiff\'s expert Dr. Charles Baxter testified that coffee at 180 degrees can cause full-thickness burns in two to seven seconds, while coffee at 160 degrees requires twenty seconds — a critical safety margin. McDonald\'s own documents, produced in discovery, revealed 700 prior burn complaints and a deliberate corporate decision to maintain high temperatures for product quality reasons. Photographs of Liebeck\'s injuries — third-degree burns requiring skin grafting — were presented to the jury and were considered highly probative of the severity of harm the temperature policy could cause.',
    alternativeOutcomes: 'Had the jury found Liebeck\'s own carelessness more culpable and assigned her a majority of fault, she would have recovered nothing under New Mexico\'s contributory negligence rule. Had McDonald\'s settled for the mediator\'s recommended $225,000 before trial, the case would not have become the cultural touchstone it is today. If the full punitive award had been upheld on appeal, it would have provided a more powerful financial deterrent against companies that knowingly maintain dangerous product practices after receiving injury notice.',
    lessonsLearned: [
      'Prior notice of injuries is powerful evidence of a defendant\'s conscious disregard for safety',
      'Companies that ignore settlement recommendations risk substantially greater jury awards',
      'Consumer-facing products must be evaluated not only by industry custom but by the actual risk of injury to foreseeable users',
      'Punitive damages are calibrated to the defendant\'s financial resources to achieve deterrence',
    ],
    bestPractices: [
      'Maintain comprehensive records of customer complaints and demonstrate prompt remedial action taken in response',
      'Conduct regular product safety reviews when injury complaints exceed a threshold, documenting corrective measures',
      'Ensure warning labels are conspicuous and specifically describe the actual risk of harm in plain language',
      'Evaluate settlement demands against the full range of potential jury verdicts including punitive exposure',
    ],
    significance: 'Liebeck v. McDonald\'s Restaurants became one of the most publicized and misunderstood tort cases in American legal history, often cited as an example of frivolous litigation despite the documented severity of the plaintiff\'s injuries and McDonald\'s prior notice of hundreds of similar burns. The case sparked national debate about tort reform, jury awards, and the role of punitive damages in deterring corporate misconduct. It ultimately led McDonald\'s and many other food service chains to lower coffee serving temperatures and improve warning labels. The case is a landmark illustration of how product liability litigation can force safety improvements that regulatory action had not compelled, and it remains a standard reference in discussions of punitive damages, comparative fault, and the social function of tort law.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Stella Liebeck',
        role: 'PLAINTIFF',
        counsel: 'Reed Morgan',
        description: '79-year-old woman who suffered third-degree burns from McDonald\'s coffee served at dangerously high temperatures',
      },
      {
        name: 'McDonald\'s Restaurants',
        role: 'DEFENDANT',
        counsel: 'Tracy McGee',
        description: 'Fast food chain with a policy of serving coffee at 180-190 degrees Fahrenheit despite hundreds of prior burn complaints',
      },
    ],
  },
  {
    litigationSlug: 'tort',
    name: 'Tarasoff v. Regents of the University of California',
    citation: '17 Cal.3d 425, 551 P.2d 334 (1976)',
    jurisdiction: 'California, United States',
    court: 'Supreme Court of California',
    year: 1976,
    facts: 'In 1969, Prosenjit Poddar, a graduate student at the University of California, Berkeley, was being treated by Dr. Lawrence Moore, a psychologist at the university\'s student health service. Poddar told Dr. Moore that he intended to kill Tatiana Tarasoff, a young woman who had rejected his romantic advances. Dr. Moore consulted with colleagues and notified campus police, who briefly detained Poddar but released him when he appeared rational. Neither Tarasoff nor her family was warned of the threat. Two months later, Poddar carried out his stated intention and killed Tarasoff. Her parents sued the Regents of the University of California, the therapists, and the campus police, alleging a duty to warn Tarasoff of the danger posed by Poddar.',
    keyLegalIssues: [
      'Whether a therapist owes a duty of care to a third-party non-patient who has been identified as a target of a patient\'s threatened violence',
      'Whether the special relationship between therapist and patient creates an obligation to protect foreseeable victims',
      'How to balance the duty to protect third parties against the confidentiality interests of the patient-therapist relationship',
      'Whether governmental immunity bars claims against university therapists for failure to warn',
    ],
    plaintiffArguments: 'The Tarasoff family argued that the therapists, having received an explicit, specific threat against an identifiable victim, assumed a duty to warn Tatiana or her family of the danger. They contended that the therapist-patient relationship, like other special relationships recognized in law, imposes an affirmative obligation to act when the therapist knows of a serious threat of harm to a third party. The family further argued that the university could not hide behind governmental immunity where it had undertaken specific therapeutic services and where a specific, foreseeable victim could have been warned.',
    defendantArguments: 'The University and its therapists argued that the duty of care in tort runs only to patients and not to the world at large, and that imposing a duty to warn third parties would fundamentally compromise the confidentiality essential to effective psychotherapy. They contended that therapists cannot be expected to accurately predict which patient threats are genuine, and that imposing liability for failure to warn would cause therapists to hospitalize patients unnecessarily or to refuse to treat potentially dangerous patients at all. The defendants also raised governmental immunity as a bar to the negligence claim.',
    proceduralHistory: 'The Tarasoff family filed suit in Alameda County Superior Court, which sustained demurrers by the defendants and dismissed the complaint. The California Court of Appeal affirmed. The California Supreme Court granted review and in 1974 issued a first opinion (Tarasoff I) recognizing a duty to warn. On rehearing, the court issued a second opinion in 1976 (Tarasoff II) which broadened the duty from a duty to warn to a duty to protect, offering therapists more flexibility in the means by which they discharge the obligation.',
    finalDecision: 'The California Supreme Court reversed the dismissal and held that therapists who determine, or under applicable professional standards reasonably should determine, that their patient presents a serious danger of violence to an identifiable third person, bear a duty to exercise reasonable care to protect that person. The court held that this duty might be discharged through warning the intended victim, notifying police, or taking other reasonable steps to protect the foreseeable victim.',
    judicialReasoning: 'Justice Mathew Tobriner, writing for the majority, grounded the duty in the special relationship between the therapist and patient, which is analogous to the relationships recognized in prior California decisions as giving rise to affirmative duties to control the conduct of another. The court reasoned that the public interest in safety outweighs the confidentiality interest in the specific context where a serious threat to an identifiable victim has been disclosed. The majority dismissed the concern about confidentiality by noting that existing California law already permitted disclosure to prevent crime, and that the therapeutic relationship\'s integrity is better served by predictable rules than by leaving victims unprotected. Justice William Clark\'s dissent argued forcefully that the duty to warn would chill frank disclosure in therapy, ultimately making the public less safe by driving dangerous patients away from treatment.',
    legalStandards: [
      'Special relationship between therapist and patient gives rise to a duty to protect foreseeable third-party victims',
      'Duty to protect may be discharged by warning the victim, notifying police, or other reasonable protective steps',
      'Foreseeability and the existence of a special relationship are the twin foundations of an affirmative duty to act',
      'Confidentiality in the therapist-patient relationship yields to the duty to prevent serious imminent harm to identifiable third parties',
    ],
    keyPrecedents: [
      'Rowland v. Christian, 69 Cal.2d 108 (1968) — California Supreme Court adopted a general foreseeability test for duty',
      'Restatement (Second) of Torts Section 315 — special relationships giving rise to a duty to control the conduct of another',
      'Merchants National Bank & Trust Co. v. United States (1967) — federal precedent on therapist liability for third-party harm',
    ],
    evidenceAnalysis: 'The allegations accepted as true at the demurrer stage established that Poddar made an explicit, specific threat to kill an identified individual during a therapy session; that the therapist took some action (notifying campus police) but not the step of warning the victim; and that Poddar killed Tarasoff two months later as threatened. The specificity and identifiability of the victim distinguished this case from situations involving vague or generalized threats, and this factual predicate was critical to the court\'s willingness to recognize a legally cognizable duty.',
    alternativeOutcomes: 'If the court had declined to recognize a duty to warn, the Tarasoff case would have remained a tragic but legally unremarkable incident. The absence of a duty rule would have left therapists with no legal obligation to act on specific, credible threats of violence against identified victims. Conversely, had the court adopted the narrower duty to warn without the broader duty to protect, therapists would have had less flexibility and might have defaulted to routine disclosure rather than exercising professional judgment about the most effective protective measure.',
    lessonsLearned: [
      'Special relationships can impose affirmative duties to protect identifiable third parties from foreseeable harm',
      'Confidentiality in professional relationships is not absolute and yields to compelling public safety interests',
      'Therapists must document their threat assessments and the steps taken in response to maintain a defensible record',
      'Regulatory frameworks and professional standards must be developed alongside judicial doctrine to give practitioners clear guidance',
    ],
    bestPractices: [
      'Mental health professionals should implement written threat assessment protocols for managing patient disclosures of intent to harm',
      'Consult with colleagues and document the consultation process whenever a patient makes a specific threat against an identifiable victim',
      'Understand state-specific Tarasoff statutes, which vary in defining the trigger for and manner of discharging the duty to protect',
      'Maintain detailed contemporaneous records of all threat-related disclosures and the clinical reasoning behind the chosen response',
    ],
    significance: 'Tarasoff v. Regents of the University of California transformed mental health law and professional ethics across the United States by establishing that therapists owe a duty of care to identifiable third-party victims of their patients\' threatened violence. Following the decision, virtually every state adopted some form of the Tarasoff duty, either through judicial decision or legislation. The case sparked an ongoing debate about the tension between patient confidentiality and public safety that remains unresolved, and it fundamentally altered the practice of psychotherapy by compelling clinicians to consider their legal obligations to non-patients. Tarasoff is taught in law, medicine, psychology, and ethics courses as a defining moment in the intersection of professional responsibility and tort law.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'Vitaly Tarasoff and Lydia Tarasoff',
        role: 'PLAINTIFF',
        description: 'Parents of Tatiana Tarasoff, the murder victim, suing on behalf of her estate for failure to warn of the known threat to her life',
      },
      {
        name: 'Regents of the University of California',
        role: 'DEFENDANT',
        description: 'University system employing the therapists who treated Poddar and decided not to warn Tatiana Tarasoff of the threat against her',
      },
      {
        name: 'Dr. Lawrence Moore',
        role: 'DEFENDANT',
        description: 'University psychologist who treated Poddar, received the explicit threat, notified campus police, but did not warn the intended victim',
      },
    ],
  },
  {
    litigationSlug: 'tort',
    name: 'Donoghue v. Stevenson',
    citation: '[1932] AC 562 (HL)',
    jurisdiction: 'United Kingdom',
    court: 'House of Lords',
    year: 1932,
    facts: 'In August 1928, May Donoghue and a friend visited a cafe in Paisley, Scotland. Her friend purchased a bottle of ginger beer manufactured by David Stevenson and served it to Donoghue. The bottle was made of dark, opaque glass, making its contents invisible from the outside. After Donoghue had consumed part of the ginger beer, her friend poured the remainder of the bottle into her glass, and a decomposed snail floated out. Donoghue subsequently suffered gastroenteritis and severe shock, which she attributed to the contaminated ginger beer. Because Donoghue\'s friend had purchased the bottle — not Donoghue herself — Donoghue had no contract with the cafe or the manufacturer and could not sue in contract.',
    keyLegalIssues: [
      'Whether a manufacturer owes a duty of care in negligence to the ultimate consumer of its product in the absence of any contractual relationship',
      'The proper scope and limits of the neighbour principle as a general test for when a duty of care arises',
      'Whether Scots law and English law recognized a general duty of care outside contract for manufactured goods',
      'Whether the absence of privity of contract bars all tort claims by an injured consumer against the manufacturer',
    ],
    plaintiffArguments: 'Donoghue argued that Stevenson, as the manufacturer of the ginger beer, owed her a duty of reasonable care to ensure that his product was fit for consumption and free from defects likely to cause injury. She contended that a manufacturer who puts goods into circulation in packaging that prevents inspection before use is under a duty to take reasonable care that the goods do not cause harm to the ultimate consumer. Donoghue relied on the principle that persons who could foreseeably be harmed by one\'s negligent acts are owed a duty of care, regardless of whether they stand in a contractual relationship with the defendant.',
    defendantArguments: 'Stevenson argued that he owed no duty of care to Donoghue because she was not party to any contract for the purchase of the ginger beer; the only contractual relationships were between the manufacturer and the retailer, and between the retailer and Donoghue\'s friend. He contended that established common law required privity of contract as a precondition to recovery for defective goods, and that extending liability to all consumers of manufactured goods would expose manufacturers to unlimited and unpredictable liability. Stevenson also argued that the decomposed snail might have entered the bottle after it left the factory, and that the evidence of causation was insufficient.',
    proceduralHistory: 'Donoghue\'s claim was dismissed at first instance in Scotland by Lord Moncrieff, who held that no duty of care existed in the absence of a contract. The Scottish Court of Session affirmed the dismissal. Donoghue appealed to the House of Lords, which in 1932 reversed the lower courts by a 3-2 majority and held that Donoghue\'s claim disclosed a cause of action in negligence. The case was remitted to the Scottish courts for trial on the merits, but Stevenson died shortly thereafter and the case was settled.',
    finalDecision: 'The House of Lords, by a 3-2 majority, held that a manufacturer of products intended for consumption owes a duty of care to the ultimate consumer where the products are intended to reach the consumer in the form in which they are prepared, without reasonable possibility of intermediate examination. Lord Atkin articulated the neighbour principle as the general test for duty of care: persons who could reasonably be foreseen as likely to be affected by one\'s acts or omissions are one\'s "neighbours" in law to whom a duty of care is owed.',
    judicialReasoning: 'Lord Atkin\'s majority opinion formulated the neighbour principle as the conceptual foundation for the law of negligence: "You must take reasonable care to avoid acts or omissions which you can reasonably foresee would be likely to injure your neighbour. Who, then, in law is my neighbour? The answer seems to be persons who are so closely and directly affected by my act that I ought reasonably to have them in contemplation as being so affected when I am directing my mind to the acts or omissions which are called in question." Atkin held that this principle was consistent with the prior English and Scottish cases when they were properly understood, and that the manufacturer of an article of food in a sealed container clearly falls within it. Lords Thankerton and Macmillan concurred. Lords Buckmaster and Tomlin dissented vigorously, arguing that no such general principle existed and that the decision would expose manufacturers to ruinous liability.',
    legalStandards: [
      'The neighbour principle: a duty of care is owed to all persons who could reasonably be foreseen as likely to be affected by one\'s acts',
      'Manufacturers of consumer goods in sealed containers owe a duty of care to ultimate consumers who cannot inspect the product',
      'Negligence as an independent tort does not require privity of contract between plaintiff and defendant',
      'A product is defective in tort if it causes harm to the consumer due to lack of reasonable care in its manufacture',
    ],
    keyPrecedents: [
      'Heaven v. Pender (1883) — Lord Brett\'s earlier formulation of a general duty of care based on proximity',
      'Winterbottom v. Wright (1842) — the privity rule in contract that Donoghue effectively supplanted in tort',
      'George v. Skivington (1869) — English case allowing recovery against a manufacturer for a defective product without privity',
    ],
    evidenceAnalysis: 'The case was decided at the pleading stage, so the House of Lords accepted Donoghue\'s factual allegations as true for the purpose of determining whether she had a legally cognizable cause of action. The critical factual allegations were: (1) Stevenson manufactured the ginger beer and sealed it in opaque bottles; (2) the bottles were intended to reach consumers without intermediate examination; (3) a decomposed snail was present in the bottle; and (4) Donoghue suffered gastroenteritis as a result. The opaque bottle was central to the reasoning because it prevented the retailer or consumer from inspecting the contents before purchase and consumption.',
    alternativeOutcomes: 'Had the House of Lords affirmed the dismissal, English and Scots law would have remained confined by the privity doctrine in products liability contexts, and the development of a general negligence principle would have been delayed or taken a different doctrinal path. Commonwealth jurisdictions that followed English law would similarly have been denied the neighbour principle for decades. The consumer protection revolution of the twentieth century might have been forced to develop exclusively through legislation rather than common law development, producing a less flexible and potentially less protective legal framework.',
    lessonsLearned: [
      'The common law of negligence is capable of principled extension to new factual contexts through the application of general principles',
      'Privity of contract does not exhaust the legal relationships that give rise to obligations of care',
      'Manufacturers who design products to reach consumers without intermediate inspection bear responsibility for the safety of those products',
      'A general principle of foreseeability provides a more coherent basis for duty analysis than a catalogue of specific relationships',
    ],
    bestPractices: [
      'Manufacturers should implement end-to-end quality control covering all stages of production, including sealing and packaging',
      'Products intended for direct consumer consumption should be subject to the strictest inspection standards before distribution',
      'Legal counsel should assess the range of foreseeable users of any product when advising on the scope of a manufacturer\'s duty',
      'Document all quality assurance processes to demonstrate reasonable care was taken throughout the manufacturing chain',
    ],
    significance: 'Donoghue v. Stevenson is the foundational case of modern Anglo-Commonwealth negligence law, establishing the neighbour principle that remains the starting point for duty-of-care analysis in the United Kingdom, Australia, Canada, New Zealand, and other common law jurisdictions. Lord Atkin\'s formulation provided a principled and flexible framework for extending negligence to new situations without requiring specific precedent, enabling the law to adapt to changing social and technological conditions over the following century. The decision effectively abolished the privity barrier in products liability in tort and inspired parallel developments in American law, including the later adoption of strict products liability. Donoghue v. Stevenson is studied in every common law jurisdiction as the bedrock case from which the modern law of negligence springs.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'May Donoghue',
        role: 'PLAINTIFF',
        counsel: 'George Morton KC',
        description: 'Consumer who suffered gastroenteritis after drinking ginger beer from a sealed bottle containing a decomposed snail',
      },
      {
        name: 'David Stevenson',
        role: 'DEFENDANT',
        description: 'Manufacturer of ginger beer who sealed the product in opaque bottles that prevented inspection of the contents before consumption',
      },
    ],
  },
];

export default cases;
