import { CaseSeed } from './types';

const cases: CaseSeed[] = [
  {
    litigationSlug: 'white-collar-crime',
    name: 'Skilling v. United States',
    citation: '561 U.S. 358 (2010)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2010,
    facts: 'Jeffrey Skilling was the Chief Executive Officer of Enron Corporation, an energy company that collapsed in 2001 in one of the largest corporate bankruptcies in American history. Skilling was charged with conspiracy, securities fraud, making false representations to auditors, and insider trading in connection with Enron\'s financial downfall. The government alleged that Skilling and other executives engaged in a scheme to deceive investors and analysts about Enron\'s true financial condition through fraudulent accounting practices. Skilling was tried in Houston, Texas, where the Enron collapse had caused massive economic harm and generated intense pretrial publicity. The jury convicted Skilling on nineteen counts, and he was sentenced to twenty-four years and four months in prison.',
    keyLegalIssues: [
      'Whether the honest-services fraud statute, 18 U.S.C. § 1346, is unconstitutionally vague as applied to private-sector employees',
      'Whether pretrial publicity and community prejudice denied Skilling his Sixth Amendment right to an impartial jury',
      'Whether the scope of honest-services fraud extends beyond bribery and kickback schemes to encompass undisclosed self-dealing',
    ],
    plaintiffArguments: 'The government argued that Skilling\'s conduct constituted honest-services fraud because he deprived Enron\'s shareholders of his honest services as an executive by engaging in a scheme to mislead investors about the company\'s financial health. Prosecutors contended that the honest-services statute was not unconstitutionally vague because it provided adequate notice that deceiving one\'s employer for personal gain was criminal. The government also maintained that the jury selection process was sufficient to ensure an impartial panel despite the extensive pretrial publicity in Houston.',
    defendantArguments: 'Skilling argued that 18 U.S.C. § 1346\'s honest-services fraud provision was unconstitutionally vague because it lacked a clear limiting principle, giving prosecutors unbounded discretion to criminalize any workplace misconduct. The defense contended that the statute should be struck down as void for vagueness or, at minimum, limited to bribery and kickback schemes. Skilling further argued that the trial venue in Houston, combined with the enormous community anger over Enron\'s collapse, made it impossible to empanel an impartial jury, violating his Sixth Amendment rights.',
    proceduralHistory: 'Skilling was indicted in 2004 and tried in the Southern District of Texas, Houston Division. The district court denied his motion to transfer venue and his challenge to the honest-services counts. After conviction, Skilling appealed to the Fifth Circuit Court of Appeals, which affirmed the conviction. The Supreme Court granted certiorari and issued its decision in 2010, vacating in part and remanding for further proceedings on the honest-services counts.',
    finalDecision: 'The Supreme Court held unanimously that 18 U.S.C. § 1346 is limited to bribery and kickback schemes and does not cover undisclosed self-dealing. The Court vacated Skilling\'s honest-services fraud convictions and remanded for the Fifth Circuit to determine whether the error was harmless. The Court rejected Skilling\'s venue claim, finding the district court\'s voir dire sufficient.',
    judicialReasoning: 'Justice Ginsburg, writing for the majority, applied the constitutional avoidance canon to construe § 1346 narrowly, limiting honest-services fraud to schemes involving bribes or kickbacks to avoid striking down the statute as unconstitutionally vague. The Court reasoned that Congress enacted § 1346 to restore the pre-McNally honest-services doctrine, which courts had consistently applied to bribery and kickback cases. Because Skilling\'s alleged misconduct involved no bribery or kickbacks, his conduct fell outside the properly construed statute. On the venue question, the Court found that the district judge\'s extensive, individualized voir dire of prospective jurors was adequate to identify and exclude those with disqualifying bias, noting that difficulty in finding impartial jurors is not the same as impossibility.',
    legalStandards: [
      'Honest-services fraud under 18 U.S.C. § 1346 is limited to bribery and kickback schemes',
      'Constitutional avoidance canon requires narrowing construction to save statutes from vagueness challenges',
      'Sixth Amendment venue transfer requires showing actual juror bias, not merely presumed prejudice from publicity',
      'Void-for-vagueness doctrine requires fair notice and constraints on prosecutorial discretion',
    ],
    keyPrecedents: [
      'McNally v. United States, 483 U.S. 350 (1987) – limited mail fraud to money and property, prompting Congress to enact § 1346',
      'Cleveland v. United States, 531 U.S. 12 (2000) – narrowed property fraud statutes',
      'Neder v. United States, 527 U.S. 1 (1999) – established harmless-error review for federal fraud convictions',
    ],
    evidenceAnalysis: 'The government\'s case relied heavily on financial records, internal Enron documents, and testimony from cooperating witnesses including former executives who pleaded guilty. The defense challenged the credibility of cooperating witnesses, arguing they had strong incentives to fabricate or exaggerate testimony in exchange for reduced sentences. The documentary evidence showing Enron\'s accounting manipulations was largely uncontested; the key dispute was over Skilling\'s knowledge and intent.',
    alternativeOutcomes: 'Had the Court struck down § 1346 as unconstitutionally vague, the entire honest-services fraud doctrine would have collapsed, eliminating a widely used prosecutorial tool in public corruption and corporate fraud cases. Had the Court adopted a broader reading of the statute, it would have opened the door to prosecuting virtually any breach of fiduciary duty as a federal crime, dramatically expanding federal criminal jurisdiction.',
    lessonsLearned: [
      'Honest-services fraud charges must be grounded in identifiable bribery or kickback payments to withstand constitutional scrutiny',
      'Venue transfer motions require concrete evidence of juror bias rather than reliance on general community outrage',
      'Vague criminal statutes can be salvaged through narrowing constructions that preserve their core applications',
      'High-profile corporate fraud cases demand exceptional attention to jury selection procedures',
    ],
    bestPractices: [
      'Defense counsel should challenge honest-services counts at the outset by demanding the government identify the specific bribe or kickback alleged',
      'Pursue venue transfer early with detailed evidence of community prejudice, including surveys and media analysis',
      'File constitutional vagueness challenges to broad criminal statutes as a matter of course in white-collar prosecutions',
      'Thoroughly investigate and cross-examine cooperating witnesses on the specific benefits received for their cooperation',
    ],
    significance: 'Skilling v. United States dramatically curtailed the government\'s use of honest-services fraud, one of the most expansive tools in the federal prosecutor\'s arsenal. By limiting § 1346 to bribery and kickback schemes, the Supreme Court eliminated a decade of circuit court decisions that had stretched the doctrine to cover virtually any breach of fiduciary duty by private-sector employees. The decision forced prosecutors to rely on more traditional fraud theories requiring proof of a specific misrepresentation that caused financial harm. It remains the controlling authority on the scope of honest-services fraud and is routinely cited in corporate and public corruption prosecutions nationwide.',
    outcome: 'Partial Defendant Victory',
    isFeatured: true,
    parties: [
      {
        name: 'Jeffrey K. Skilling',
        role: 'DEFENDANT',
        counsel: 'Daniel Petrocelli (O\'Melveny & Myers)',
        description: 'Former Chief Executive Officer of Enron Corporation',
      },
      {
        name: 'United States',
        role: 'PLAINTIFF',
        counsel: 'Department of Justice Enron Task Force',
        description: 'Federal government prosecuting Enron-related fraud',
      },
    ],
  },
  {
    litigationSlug: 'white-collar-crime',
    name: 'United States v. O\'Hagan',
    citation: '521 U.S. 642 (1997)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1997,
    facts: 'James Herman O\'Hagan was a partner at the Minneapolis law firm Dorsey & Whitney, which represented Grand Metropolitan PLC in its planned tender offer for Pillsbury Company. O\'Hagan did not personally work on the Grand Metropolitan matter but learned of the confidential acquisition plans through his firm\'s representation. Using that non-public information, O\'Hagan purchased call options on Pillsbury stock and Pillsbury common shares before the public announcement of the tender offer. When Grand Met announced the tender offer in October 1988, Pillsbury\'s stock price rose dramatically, and O\'Hagan sold his securities for a profit of approximately $4.3 million. O\'Hagan was subsequently indicted on fifty-seven counts of mail fraud, securities fraud, and money laundering.',
    keyLegalIssues: [
      'Whether the misappropriation theory of insider trading satisfies the requirement of a "deceptive device" under Section 10(b) of the Securities Exchange Act of 1934',
      'Whether SEC Rule 14e-3(a), which prohibits trading on material nonpublic information in the tender offer context regardless of a duty to disclose, exceeds the SEC\'s rulemaking authority under Section 14(e)',
      'Whether a lawyer who trades on confidential client information owes a duty sufficient to support securities fraud liability',
    ],
    plaintiffArguments: 'The government argued that O\'Hagan committed securities fraud under the misappropriation theory, which holds that a person who misappropriates confidential information for securities trading purposes breaches a duty of trust and confidence owed to the source of the information, thereby engaging in fraud in connection with a securities transaction. Prosecutors contended that O\'Hagan\'s breach of his duty to his law firm and its client, Grand Met, constituted the deceptive conduct required under § 10(b). The government further argued that Rule 14e-3(a) was a valid prophylactic measure within the SEC\'s broad rulemaking authority over tender offer transactions.',
    defendantArguments: 'O\'Hagan argued that the misappropriation theory was not a valid basis for § 10(b) liability because he owed no duty to Pillsbury\'s shareholders — the counterparties to his securities trades — and therefore his trading was not "in connection with" a purchase or sale of securities in the sense contemplated by the statute. The defense maintained that only the classical theory of insider trading, which requires a corporate insider\'s breach of duty to the issuer\'s shareholders, satisfies the statutory requirement. O\'Hagan also challenged Rule 14e-3(a) as exceeding the SEC\'s authority because it dispenses with any duty element.',
    proceduralHistory: 'O\'Hagan was convicted in the District of Minnesota on all fifty-seven counts. The Eighth Circuit Court of Appeals reversed, holding that the misappropriation theory was not a valid basis for § 10(b) liability and that Rule 14e-3(a) exceeded the SEC\'s authority. The Supreme Court granted certiorari and reversed the Eighth Circuit\'s decision.',
    finalDecision: 'The Supreme Court held six-to-three that the misappropriation theory of insider trading satisfies § 10(b)\'s requirement of a "deceptive device" in connection with a securities transaction. The Court also upheld Rule 14e-3(a) as a valid exercise of the SEC\'s authority. O\'Hagan\'s convictions were reinstated and remanded for further proceedings.',
    judicialReasoning: 'Justice Ginsburg, writing for the majority, explained that misappropriation of information for securities trading purposes involves deception because the misappropriator pretends loyalty to the principal while secretly converting the principal\'s information for personal gain. This deception satisfies § 10(b)\'s requirement of a deceptive device because it occurs "in connection with" a securities transaction when the misappropriator uses the information to trade. The Court reasoned that the misappropriation theory advances the statute\'s purpose of ensuring honest markets by prohibiting trading on the basis of information that the trader has obtained through a breach of duty. On Rule 14e-3(a), the Court found that the SEC\'s authority under § 14(e) to define and prohibit acts as fraudulent is broad enough to encompass prophylactic rules that do not require proof of a specific duty.',
    legalStandards: [
      'Misappropriation theory: a person who trades on material nonpublic information misappropriated from a source to whom a duty is owed commits securities fraud under § 10(b)',
      'The "in connection with" requirement is satisfied when misappropriated information is used in a securities trade',
      'Rule 14e-3(a) validly prohibits trading on material nonpublic information in tender offer contexts without requiring proof of a traditional fiduciary duty',
      'Deception under § 10(b) includes concealment from a principal of the trader\'s intention to use confidential information for personal gain',
    ],
    keyPrecedents: [
      'Chiarella v. United States, 445 U.S. 222 (1980) – established classical theory requiring duty to issuer\'s shareholders',
      'Dirks v. SEC, 463 U.S. 646 (1983) – defined tippee liability and personal benefit test',
      'Santa Fe Industries, Inc. v. Green, 430 U.S. 462 (1977) – limited § 10(b) to deceptive conduct',
    ],
    evidenceAnalysis: 'The prosecution relied on trading records showing O\'Hagan\'s purchases timed precisely to his firm\'s receipt of confidential Grand Met information, brokerage account records establishing the volume and timing of trades, and firm records confirming O\'Hagan\'s access to the confidential tender offer information. O\'Hagan\'s own financial records showed he was in substantial debt before the trades and netted $4.3 million in profits, providing strong circumstantial evidence of motive.',
    alternativeOutcomes: 'If the Supreme Court had affirmed the Eighth Circuit and rejected the misappropriation theory, a significant category of insider trading by outsiders with access to confidential information — lawyers, bankers, accountants, and consultants — would have been effectively immunized from federal securities fraud liability. The decision\'s affirmance of Rule 14e-3(a) also preserved a critical prophylactic tool for protecting the integrity of the tender offer market.',
    lessonsLearned: [
      'Attorneys and other professionals with access to client confidential information face federal securities fraud liability if they trade on that information',
      'The misappropriation theory extends insider trading liability well beyond corporate insiders to anyone who breaches a duty of confidentiality to trade on nonpublic information',
      'Timing of trades relative to access to material nonpublic information is powerful circumstantial evidence of misappropriation',
      'Law firms must implement robust information barriers and trading blackout policies to prevent misappropriation by partners and employees',
    ],
    bestPractices: [
      'Defense counsel should scrutinize whether a genuine confidential relationship and attendant duty existed between the trader and the source of the information',
      'Challenge the government\'s evidence of the trader\'s actual knowledge that the information was both material and nonpublic',
      'Examine whether trading decisions were consistent with the defendant\'s pre-existing investment strategy before receiving the information',
      'Investigate alternative non-public sources through which the defendant could have independently obtained similar information',
    ],
    significance: 'United States v. O\'Hagan resolved a circuit split and firmly established the misappropriation theory as a valid basis for insider trading liability under § 10(b), dramatically expanding the reach of federal securities fraud law. The decision enabled the government to prosecute a broad class of professional outsiders — lawyers, investment bankers, accountants, and consultants — who obtain and trade on material nonpublic information in breach of a duty of confidence. It remains the foundational authority on the misappropriation theory and is central to every insider trading prosecution involving non-corporate-insider defendants.',
    outcome: 'Plaintiff Victory',
    parties: [
      {
        name: 'United States',
        role: 'PLAINTIFF',
        counsel: 'Office of the Solicitor General',
        description: 'Federal government prosecuting securities fraud and insider trading',
      },
      {
        name: 'James Herman O\'Hagan',
        role: 'DEFENDANT',
        counsel: 'Defense counsel at Dorsey & Whitney',
        description: 'Law firm partner who traded on confidential tender offer information',
      },
    ],
  },
  {
    litigationSlug: 'white-collar-crime',
    name: 'Yates v. United States',
    citation: '574 U.S. 528 (2015)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2015,
    facts: 'John Yates was a commercial fisherman and captain of the Miss Katie, a fishing vessel operating in the Gulf of Mexico off Florida. In August 2007, a Florida Fish and Wildlife Conservation Commission officer boarded the vessel and found seventy-two red grouper that appeared to be undersized, in violation of federal regulations. The officer instructed Yates to keep the fish segregated until the vessel returned to port. However, upon docking, federal agents discovered that only sixty-nine grouper remained, and those fish were larger than the ones initially measured, suggesting that Yates had thrown the undersized fish overboard and replaced them with larger ones during the return voyage. Yates was charged under 18 U.S.C. § 1519, enacted as part of the Sarbanes-Oxley Act of 2002, for destroying "any record, document, or tangible object" to impede a federal investigation.',
    keyLegalIssues: [
      'Whether fish constitute a "tangible object" within the meaning of 18 U.S.C. § 1519\'s prohibition on destroying or concealing tangible objects to impede a federal investigation',
      'Whether § 1519\'s catchall phrase "tangible object" must be read in light of the statute\'s context to apply only to objects used to record or preserve information',
      'Whether the rule of lenity requires construing the ambiguous phrase in favor of the criminal defendant',
    ],
    plaintiffArguments: 'The government argued that § 1519\'s plain text — prohibiting destruction of "any record, document, or tangible object" — encompasses fish because the word "any" before "tangible object" signals an expansive scope, and fish are unambiguously tangible objects. Prosecutors contended that Congress intended § 1519 as a broad anti-obstruction statute applicable to any physical evidence, not merely paper records, and that limiting it to record-keeping objects would frustrate its purpose. The government further argued that the statutory context did not justify departing from the text\'s ordinary meaning.',
    defendantArguments: 'Yates argued that "tangible object" in § 1519 must be read in context of the surrounding terms — "record" and "document" — which all relate to storing and preserving information, and therefore the phrase extends only to objects used as records. The defense invoked the noscitur a sociis canon, arguing that a word is known by the company it keeps, and the "tangible object" phrase should be limited by its association with information-storage objects. Yates also argued that the rule of lenity required resolving any ambiguity in his favor, and that applying Sarbanes-Oxley to fish far exceeded Congress\'s evident purpose in enacting the statute after Enron\'s financial fraud.',
    proceduralHistory: 'Yates was convicted in the Middle District of Florida after the district court rejected his motion to dismiss. The Eleventh Circuit Court of Appeals affirmed the conviction, holding that fish qualify as "tangible objects" under the statute\'s plain meaning. The Supreme Court granted certiorari and reversed in a plurality opinion.',
    finalDecision: 'A plurality of the Supreme Court reversed Yates\'s conviction, holding that § 1519\'s "tangible object" does not encompass fish because the term, read in context, is limited to objects used to record or preserve information. The Court applied the noscitur a sociis and ejusdem generis canons and the rule of lenity to construe the ambiguous provision narrowly.',
    judicialReasoning: 'Justice Ginsburg wrote the plurality opinion, joined by three other justices, applying the noscitur a sociis and ejusdem generis canons to hold that "tangible object" takes its meaning from the information-storage objects listed alongside it — records and documents. The plurality also relied on the rule of lenity, noting that when a criminal statute\'s scope is genuinely ambiguous, courts should interpret it in the defendant\'s favor. Justice Alito concurred in the judgment based solely on the rule of lenity, providing the fifth vote for reversal. The plurality emphasized that § 1519 was enacted in the wake of Enron\'s financial fraud and was targeted at the destruction of financial records and documents, not physical evidence such as fish.',
    legalStandards: [
      'Noscitur a sociis: a statutory term is interpreted in light of its surrounding terms',
      'Ejusdem generis: a general term following specific terms is limited to the same category as those specific terms',
      'Rule of lenity: ambiguous criminal statutes are construed in favor of the defendant',
      'Sarbanes-Oxley Act obstruction provisions are limited to information-recording objects rather than physical evidence generally',
    ],
    keyPrecedents: [
      'Arthur Andersen LLP v. United States, 544 U.S. 696 (2005) – narrowly construed Sarbanes-Oxley obstruction statute',
      'Begay v. United States, 553 U.S. 137 (2008) – applied ejusdem generis to limit broad criminal statute catchall',
      'United States v. Santos, 553 U.S. 507 (2008) – applied rule of lenity to ambiguous federal criminal statute',
    ],
    evidenceAnalysis: 'The prosecution presented the testimony of the federal officer who measured and tagged the fish, comparative measurements of the fish seized at docking versus those recorded at sea, and expert analysis confirming the discrepancy was inconsistent with natural variation. The physical evidence established that the grouper in the hold upon docking were different fish from those measured at sea, supporting the inference that Yates had ordered the fish thrown overboard during the return voyage.',
    alternativeOutcomes: 'Had the Court upheld the conviction, federal prosecutors would have gained an enormously broad obstruction tool applicable to virtually any physical object involved in a federal investigation, raising significant concerns about prosecutorial overreach. The case became a prominent illustration of prosecutorial charging decisions that courts found disproportionate to the underlying conduct, particularly given that Yates faced a maximum twenty-year sentence under § 1519 rather than the lesser penalties in fish conservation statutes.',
    lessonsLearned: [
      'Statutory interpretation canons — noscitur a sociis, ejusdem generis, and lenity — provide viable grounds for challenging overbroad federal criminal charges',
      'Prosecutors\' charging decisions that apply broad obstruction statutes to factually minor conduct risk judicial backlash and reversal',
      'The rule of lenity remains a viable defense tool in federal criminal cases involving ambiguous statutory language',
      'Legislative context and statutory purpose are important tools for limiting the reach of broadly worded criminal provisions',
    ],
    bestPractices: [
      'Conduct a thorough textual and contextual analysis of the specific statute charged to identify limiting canons of construction',
      'Research the legislative history of the charged statute to identify the specific evil Congress targeted and argue for a limiting construction',
      'Invoke the rule of lenity whenever there is genuine ambiguity in the scope of a criminal statute as applied to the defendant\'s conduct',
      'Challenge disproportionate charging decisions as evidence of government overreach in white-collar cases',
    ],
    significance: 'Yates v. United States is a landmark decision in statutory interpretation of federal criminal law, establishing that Sarbanes-Oxley\'s obstruction provision does not sweep in all tangible physical objects but is limited to those used for information storage. The case became a celebrated example of the rule of lenity and the limits of prosecutorial discretion in white-collar cases. It also triggered significant debate about the appropriate scope of federal obstruction statutes and whether the government\'s charging decision — applying a twenty-year-maximum Sarbanes-Oxley felony to an under-sized-fish dispute — reflected sound enforcement policy.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'John L. Yates',
        role: 'DEFENDANT',
        counsel: 'Sideman & Bancroft LLP',
        description: 'Commercial fisherman charged with destroying federal evidence',
      },
      {
        name: 'United States',
        role: 'PLAINTIFF',
        counsel: 'Department of Justice',
        description: 'Federal government prosecuting obstruction of a fishery investigation',
      },
    ],
  },
  {
    litigationSlug: 'white-collar-crime',
    name: 'United States v. Booker',
    citation: '543 U.S. 220 (2005)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 2005,
    facts: 'Freddie J. Booker was convicted by a jury of possessing with intent to distribute at least fifty grams of cocaine base. The jury found Booker responsible for ninety-two and a half grams based on the trial evidence. However, based on additional facts found by the sentencing judge — that Booker had possessed an additional 566 grams of cocaine and had obstructed justice — the district court applied the United States Sentencing Guidelines and sentenced Booker to thirty years in prison, far above the maximum of approximately twenty-one years that could have been imposed based solely on the jury\'s findings. Booker\'s case was consolidated with that of Ducan Fanfan, who faced similar guideline enhancements based on judicially found facts.',
    keyLegalIssues: [
      'Whether the Federal Sentencing Guidelines violate the Sixth Amendment by allowing judges to increase sentences based on facts not found by the jury beyond a reasonable doubt',
      'Whether the mandatory nature of the Sentencing Guidelines is severable from the guidelines\' substantive provisions',
      'What remedy is appropriate if the mandatory Guidelines scheme is found unconstitutional under Blakely v. Washington',
    ],
    plaintiffArguments: 'The government argued that the Federal Sentencing Guidelines were consistent with the Sixth Amendment because Congress permissibly designated facts for consideration at sentencing, and judicial factfinding at sentencing had a long historical pedigree. Prosecutors maintained that Blakely v. Washington did not apply to the federal guidelines because of their unique statutory basis and the careful deliberative process through which the Sentencing Commission developed them. The government also argued that if any constitutional defect existed, the proper remedy was to sever only the problematic provisions while keeping the Guidelines mandatory.',
    defendantArguments: 'Booker argued that under Blakely v. Washington, any fact that increases a defendant\'s sentence beyond the maximum authorized by the jury\'s verdict alone must be submitted to the jury and found beyond a reasonable doubt. The defense contended that the district court\'s reliance on judicially found drug quantities and obstruction of justice to dramatically increase the sentence violated the Sixth Amendment. Booker argued that the mandatory Guidelines were unconstitutional as applied and that the remedy should be to strike the entire mandatory sentencing structure.',
    proceduralHistory: 'Booker was sentenced in the Western District of Wisconsin. The Seventh Circuit Court of Appeals struck down the sentence under Blakely v. Washington. The Supreme Court granted expedited certiorari to resolve whether Blakely applied to the Federal Sentencing Guidelines, a question of enormous practical importance that had divided the circuits.',
    finalDecision: 'The Supreme Court held five-to-four that the mandatory Federal Sentencing Guidelines violated the Sixth Amendment insofar as they required judges to increase sentences based on facts not found by the jury. A separate five-to-four majority held that the remedy was to sever the provision making the Guidelines mandatory, rendering them advisory only. Judges must still calculate and consider the Guidelines range but may impose a sentence outside that range based on the 18 U.S.C. § 3553(a) factors.',
    judicialReasoning: 'Justice Stevens authored the merits opinion, relying on Apprendi v. New Jersey and Blakely v. Washington to hold that the Sixth Amendment jury trial right requires any fact other than a prior conviction that increases the sentence beyond the prescribed statutory maximum to be submitted to a jury. Because the mandatory Guidelines required judges to find facts that drove sentences higher than the jury\'s verdict alone would support, they violated this principle. Justice Breyer wrote the remedial opinion for a different majority, concluding that the proper remedy was to excise the provision making the Guidelines mandatory rather than strike the entire Guidelines scheme, preserving the Sentencing Commission\'s work while ensuring constitutional compliance. The remedial majority reasoned that Congress would have preferred an advisory Guidelines system to no guidelines at all.',
    legalStandards: [
      'Sixth Amendment requires any fact other than a prior conviction that increases sentence beyond the jury-verdict maximum to be found by a jury beyond a reasonable doubt',
      'Apprendi-Blakely rule applies to the Federal Sentencing Guidelines',
      'Remedy for unconstitutional mandatory Guidelines is to render them advisory, not to strike the entire Guidelines scheme',
      'Sentencing courts must calculate the Guidelines range and consider 18 U.S.C. § 3553(a) factors before imposing sentence',
    ],
    keyPrecedents: [
      'Apprendi v. New Jersey, 530 U.S. 466 (2000) – established that facts increasing sentence beyond statutory maximum must be jury-found',
      'Blakely v. Washington, 542 U.S. 296 (2004) – applied Apprendi to state sentencing guidelines',
      'Mistretta v. United States, 488 U.S. 361 (1989) – upheld the Sentencing Commission and mandatory Guidelines against non-delegation and separation-of-powers challenges',
    ],
    evidenceAnalysis: 'The sentencing judge relied on a preponderance-of-the-evidence standard to find that Booker possessed an additional 566 grams of cocaine beyond what the jury found, and separately found that Booker had obstructed justice by giving false testimony. These judicially found facts increased his Guidelines range from a maximum of approximately 262 months to 360 months to life. The disparity between the jury-found facts and the judicially found facts was central to the constitutional violation identified by the Court.',
    alternativeOutcomes: 'If the Court had struck down the mandatory Guidelines entirely rather than rendering them advisory, sentencing disparities between similarly situated defendants could have grown dramatically without the Guidelines\' anchoring effect. Conversely, if the Court had upheld the mandatory Guidelines against the Sixth Amendment challenge, defendants would have remained subject to substantial sentence increases based on facts never tested against the reasonable-doubt standard before a jury of their peers.',
    lessonsLearned: [
      'Defense counsel must object at sentencing to any upward adjustment based on facts not admitted by the defendant or found by the jury',
      'The advisory nature of the Guidelines post-Booker creates meaningful opportunities to argue for below-Guidelines sentences based on § 3553(a) factors',
      'Sentence advocacy has become a critical skill in white-collar defense, with courts now required to consider the full § 3553(a) framework',
      'The Booker remedial opinion created a system in which appellate courts review sentences for procedural and substantive reasonableness',
    ],
    bestPractices: [
      'Thoroughly document all § 3553(a) mitigating factors — history, characteristics, collateral consequences — to support below-Guidelines arguments',
      'Challenge any contested Guidelines enhancement that has not been admitted by the defendant or found by the jury',
      'Commission independent forensic analysis of disputed sentencing facts such as loss amounts, drug quantities, or victim counts',
      'Develop expert and character witness support to present the full human context of the defendant\'s conduct at sentencing',
    ],
    significance: 'United States v. Booker is one of the most consequential criminal procedure decisions in modern American jurisprudence. By rendering the Federal Sentencing Guidelines advisory, it fundamentally transformed federal sentencing, giving district judges meaningful discretion they had not possessed since the pre-Guidelines era. The decision unleashed a wave of litigation over sentencing reasonableness and provided white-collar defendants and their counsel with a powerful platform to argue for individualized sentences below the Guidelines range. It continues to shape federal sentencing practice in every white-collar case involving contested facts or guideline enhancements.',
    outcome: 'Partial Defendant Victory',
    parties: [
      {
        name: 'Freddie J. Booker',
        role: 'DEFENDANT',
        counsel: 'Federal Public Defender, Western District of Wisconsin',
        description: 'Defendant whose sentence was enhanced based on judicially found drug quantity',
      },
      {
        name: 'United States',
        role: 'PLAINTIFF',
        counsel: 'Office of the Solicitor General',
        description: 'Federal government defending the constitutionality of the mandatory Sentencing Guidelines',
      },
    ],
  },
  {
    litigationSlug: 'white-collar-crime',
    name: 'McNally v. United States',
    citation: '483 U.S. 350 (1987)',
    jurisdiction: 'Federal',
    court: 'Supreme Court of the United States',
    year: 1987,
    facts: 'James McNally was a Kentucky state official who participated in a scheme to select a certain insurance agency to service the state\'s workmen\'s compensation insurance and to ensure that the agency kicked back part of its commissions to a company controlled by McNally and his co-defendant. The scheme resulted in the state paying higher insurance premiums than necessary, and McNally and his co-conspirators received kickback payments funneled through the insurance agency. McNally and co-defendant Gray were indicted and convicted on multiple counts of mail fraud under 18 U.S.C. §§ 1341 and 1342. The jury instructions permitted conviction on the theory that the defendants had defrauded Kentucky citizens and the state government of their right to have the state\'s affairs conducted honestly, without requiring proof of any loss of money or property.',
    keyLegalIssues: [
      'Whether the federal mail fraud statute, 18 U.S.C. § 1341, extends beyond schemes to defraud victims of money or property to include schemes that deprive victims of their intangible right to honest government services',
      'Whether the honest-services theory of mail fraud was a valid basis for criminal liability under the pre-1988 statute',
      'Whether the Sixth Amendment requires the government to specify the particular theory of fraud upon which it relies in jury instructions',
    ],
    plaintiffArguments: 'The government argued that the mail fraud statute was broad enough to protect citizens\' intangible rights, including their right to the honest and impartial government services of public officials. Prosecutors relied on a line of circuit court decisions that had developed the honest-services doctrine to reach schemes by public officials who abused their positions for personal gain, even without identifiable monetary loss to the government. The government maintained that the statute\'s reference to "any scheme or artifice to defraud" encompassed the deprivation of intangible rights.',
    defendantArguments: 'McNally argued that the mail fraud statute was enacted to protect property rights, not to federalize all manner of public corruption. The defense contended that the statute\'s text — covering schemes to defraud "any person of money or property" — plainly required proof of a scheme targeting economic interests rather than vague intangible rights. McNally argued that extending the statute to cover the deprivation of honest services would make the law unconstitutionally vague and would inappropriately convert every state bribery and corruption offense into a federal crime.',
    proceduralHistory: 'McNally and his co-defendant Gray were convicted in the Eastern District of Kentucky. The Sixth Circuit Court of Appeals affirmed the convictions, relying on the honest-services doctrine. The Supreme Court granted certiorari to resolve the scope of the federal mail fraud statute and whether it reached deprivations of intangible rights.',
    finalDecision: 'The Supreme Court reversed the convictions seven-to-two, holding that the mail fraud statute is limited to the protection of property rights and does not encompass the deprivation of intangible rights such as the right to honest government services. Because the jury was instructed it could convict without finding a scheme to deprive the state of money or property, the conviction was reversed. Congress responded by enacting 18 U.S.C. § 1346 in 1988, restoring the honest-services theory.',
    judicialReasoning: 'Justice White wrote the majority opinion, holding that the mail fraud statute was "limited in scope to the protection of property rights." The Court applied the rule of lenity and emphasized that the statute\'s text, read in light of its origins protecting against property fraud, did not clearly encompass schemes targeting only intangible rights. The majority noted that expanding the statute to cover all forms of official misconduct would raise serious concerns about federalizing state ethics and corruption law without clear congressional authorization. The Court held that when Congress criminalizes a scheme it must speak clearly, and the mail fraud statute\'s text did not clearly reach deprivations of honest services. Justice Stevens dissented, arguing that the statute\'s broad language and long history of application to honest-services schemes reflected Congress\'s intent.',
    legalStandards: [
      'Federal mail fraud statute, 18 U.S.C. § 1341, protects money and property interests, not intangible rights to honest services',
      'Rule of lenity requires that ambiguous criminal statutes be read narrowly in the defendant\'s favor',
      'Congress must speak clearly when extending federal criminal liability to new categories of conduct',
      'Jury instructions must accurately reflect the legal theory required for conviction',
    ],
    keyPrecedents: [
      'Hammerschmidt v. United States, 265 U.S. 182 (1924) – early interpretation of mail fraud requiring scheme to defraud',
      'Shushan v. United States, 117 F.2d 110 (5th Cir. 1941) – early circuit precedent developing honest-services doctrine later rejected by McNally',
      'Skilling v. United States, 561 U.S. 358 (2010) – post-McNally decision limiting § 1346 to bribery and kickbacks',
    ],
    evidenceAnalysis: 'The government\'s evidence established the kickback arrangement through financial records, commission payment documentation, and testimony from participants in the scheme. The insurance commission records demonstrated that the selected agency received inflated commissions and that a portion was diverted to McNally\'s companies. The evidence was sufficient to establish a traditional property fraud had the jury been correctly instructed on that theory, but the jury instructions permitted conviction on the broader honest-services theory without requiring proof of property loss.',
    alternativeOutcomes: 'Had the Court upheld the honest-services theory, the federal mail fraud statute would have remained an extraordinarily broad tool for prosecuting state and local officials for any breach of fiduciary duty, potentially sweeping in conduct better left to state ethics enforcement. The Court\'s narrowing decision prompted immediate congressional action with the enactment of § 1346 in 1988, demonstrating that Congress endorsed the honest-services concept but sought to restore it on a clearer statutory footing.',
    lessonsLearned: [
      'Criminal statutes require clear textual authorization before courts will apply them to new categories of conduct',
      'The rule of lenity is a powerful tool for challenging expansive prosecutorial theories in white-collar cases',
      'Judicial decisions narrowing federal criminal statutes frequently prompt congressional responses that restore or expand liability',
      'Jury instruction errors in white-collar cases can be reversible even when underlying conduct is clearly wrongful',
    ],
    bestPractices: [
      'Carefully scrutinize jury instructions in white-collar cases for legally unsupported theories of liability',
      'Challenge any charging theory that lacks clear textual support in the applicable statute and invoke the rule of lenity',
      'Preserve all instructional error objections at trial to maintain appellate review rights',
      'Identify the specific legal theory the government is relying upon early in the case and demand precision in indictment and jury instructions',
    ],
    significance: 'McNally v. United States was a watershed decision that dramatically curtailed the federal mail fraud statute and eliminated, at least temporarily, the honest-services doctrine that prosecutors had used for decades to reach public corruption and private-sector disloyalty. The decision forced Congress to enact 18 U.S.C. § 1346 in 1988, explicitly restoring honest-services fraud as a federal crime, and set the stage for subsequent Supreme Court decisions interpreting and limiting that statute, most notably Skilling v. United States in 2010. McNally remains a landmark application of the rule of lenity and the principle that federal criminal statutes must be read to protect against the specific evils Congress targeted rather than serving as broad charters for federal prosecutorial intervention in state governance.',
    outcome: 'Defendant Victory',
    parties: [
      {
        name: 'James M. McNally',
        role: 'DEFENDANT',
        counsel: 'Retained criminal defense counsel',
        description: 'Kentucky state official who participated in insurance kickback scheme',
      },
      {
        name: 'United States',
        role: 'PLAINTIFF',
        counsel: 'United States Attorney, Eastern District of Kentucky',
        description: 'Federal government prosecuting mail fraud based on honest-services theory',
      },
    ],
  },
];

export default cases;
