import { GlossaryTermSeed } from './types';

const terms: GlossaryTermSeed[] = [
  {
    term: 'eDiscovery',
    definition: 'The process of identifying, collecting, processing, reviewing, and producing electronically stored information (ESI) in response to a legal demand such as litigation, investigation, or regulatory inquiry. eDiscovery has largely supplanted paper-based discovery and is governed by the Federal Rules of Civil Procedure as well as state equivalents.',
    category: 'Document Review & eDiscovery',
    example: 'A company gets sued and must hand over relevant emails. The process of finding, collecting, and delivering those emails electronically is eDiscovery.',
    relatedTerms: ['ESI', 'Litigation Hold', 'Collection', 'Processing'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'ESI',
    definition: 'Electronically Stored Information — any information created, stored, or transmitted in electronic form, including emails, word-processing documents, spreadsheets, databases, voicemail, instant messages, social media posts, and data residing on servers, laptops, mobile devices, or cloud platforms. ESI is explicitly addressed in FRCP Rule 34 as a discoverable category.',
    category: 'Document Review & eDiscovery',
    example: 'When a reviewer is asked to review emails, Slack messages, and Word documents for a case, all of those files are ESI.',
    relatedTerms: ['eDiscovery', 'Native File', 'Metadata', 'Custodian'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Litigation Hold',
    definition: 'A formal directive issued by an organization to relevant employees and IT personnel to suspend the routine deletion or alteration of documents and ESI that may be relevant to reasonably anticipated or pending litigation. Also called a legal hold, it triggers the duty to preserve and typically takes the form of a written notice.',
    category: 'Document Review & eDiscovery',
    example: 'A company receives a lawsuit threat on Monday. Lawyers immediately send a notice to employees saying "do not delete any emails related to Project X." That notice is a litigation hold.',
    relatedTerms: ['Legal Hold', 'Preservation', 'Spoliation', 'Custodian'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Legal Hold',
    definition: 'Synonymous with litigation hold, a legal hold is the documented suspension of an organization\'s normal document retention and destruction policies to preserve potentially relevant ESI and paper documents. Failure to implement a legal hold upon notice of litigation can expose a party to spoliation sanctions.',
    category: 'Document Review & eDiscovery',
    example: 'An employee receives an email from the legal team saying to keep all documents related to a certain project and not to delete anything. That email is the legal hold notice.',
    relatedTerms: ['Litigation Hold', 'Preservation', 'Spoliation', 'FRCP Rule 26'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Preservation',
    definition: 'The duty to maintain potentially relevant ESI and documents in their original, unaltered form once litigation is reasonably anticipated or begun. Preservation encompasses both the issuance of a legal hold and the technical steps (e.g., suspending auto-delete policies, capturing cloud data snapshots) necessary to prevent loss of data.',
    category: 'Document Review & eDiscovery',
    example: 'A company stops its automatic 90-day email deletion policy as soon as a lawsuit is filed. Keeping those emails safe and unchanged is preservation.',
    relatedTerms: ['Litigation Hold', 'Spoliation', 'Chain of Custody', 'Collection'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Spoliation',
    definition: 'The destruction, alteration, concealment, or failure to preserve evidence that a party knew or should have known was relevant to litigation. Courts may impose spoliation sanctions including adverse inference instructions, evidence preclusion, monetary penalties, or even default judgment against the offending party.',
    category: 'Document Review & eDiscovery',
    example: 'An employee deletes work emails after learning about an upcoming lawsuit. That destruction of potential evidence is spoliation, and the company could be penalized for it.',
    relatedTerms: ['Preservation', 'Litigation Hold', 'Adverse Inference', 'FRCP Rule 37(e)'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Collection',
    definition: 'The process of gathering potentially relevant ESI and documents from custodians and data sources identified during early case assessment. Collection may be performed forensically (bit-for-bit imaging of a device) or through targeted exports, and must maintain chain of custody to ensure data integrity and authenticity.',
    category: 'Document Review & eDiscovery',
    example: 'A forensics team copies all emails and files from a salesperson\'s laptop and email account so they can be reviewed for the lawsuit. That copying process is collection.',
    relatedTerms: ['Custodian', 'Chain of Custody', 'Data Mapping', 'Processing'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Processing',
    definition: 'The technical phase of eDiscovery in which collected ESI is ingested into a review platform, extracted from native formats, deduped, filtered by date or file type, and prepared for attorney review. Processing generates extracted text, metadata, and rendered images (TIFF or PDF) and produces a load file for import into a review tool.',
    category: 'Document Review & eDiscovery',
    example: 'After collecting 2 million raw files, a vendor runs them through software that strips out duplicates, converts them to a readable format, and loads them into the review tool. That preparation step is processing.',
    relatedTerms: ['Deduplication', 'Load File', 'Culling', 'Review Platform'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Culling',
    definition: 'The application of filters and criteria during or after processing to reduce the overall document population before attorney review, thereby lowering cost and review time. Common culling techniques include date-range filters, file-type exclusions, domain filters, deduplication, and keyword searching.',
    category: 'Document Review & eDiscovery',
    example: 'Out of 3 million collected files, the team applies a date filter and keyword search to cut the set down to 400,000 documents that actually need human review. Reducing that pile is culling.',
    relatedTerms: ['Deduplication', 'Keyword Search', 'Processing', 'Early Case Assessment'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Deduplication',
    definition: 'The process of identifying and removing exact duplicate documents from a review set based on matching hash values (typically MD5 or SHA-1). Deduplication can be performed globally (across all custodians) or per-custodian, and significantly reduces review volume without eliminating unique copies that may carry distinct metadata.',
    category: 'Document Review & eDiscovery',
    example: 'The same email was sent to 50 people and exists 50 times in the collected data. Deduplication removes 49 copies so reviewers only read it once.',
    relatedTerms: ['Hash Value', 'Near-Duplicate', 'Processing', 'Culling'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Near-Duplicate',
    definition: 'Documents that are not exact duplicates but share a high degree of textual similarity, such as successive drafts of a contract or lightly edited email chains. Review platforms identify near-duplicates using algorithms (e.g., shingling or fingerprinting) and group them for batched review, allowing reviewers to code similar documents consistently.',
    category: 'Document Review & eDiscovery',
    example: 'A contract has five versions with minor edits between them. The review platform groups all five together as near-duplicates so the reviewer can see them side by side and code them consistently.',
    relatedTerms: ['Deduplication', 'Email Threading', 'Predictive Coding', 'Review Platform'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Email Threading',
    definition: 'A review technique that organizes email messages into complete conversation threads, displaying each unique exchange in chronological order and identifying the inclusive email (the most recent message that contains all prior messages). Reviewers code only inclusive emails, reducing duplicative review of repeated message text.',
    category: 'Document Review & eDiscovery',
    example: 'A back-and-forth email chain of 10 messages is grouped as a single thread. The reviewer reads only the last email (which contains all prior messages) instead of all 10 separately.',
    relatedTerms: ['Near-Duplicate', 'Deduplication', 'Culling', 'Coding'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Responsiveness',
    definition: 'The determination of whether a document falls within the scope of a discovery request — i.e., whether it is relevant to the claims or defenses at issue and within the parameters of the request for production. Responsiveness coding is typically the first-level determination made during document review.',
    category: 'Document Review & eDiscovery',
    example: 'A reviewer is asked to find documents about a contract dispute from 2020. An email about the office holiday party is not responsive because it has nothing to do with the dispute.',
    relatedTerms: ['Responsive Document', 'Non-Responsive', 'Relevance', 'First-Level Review'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Responsive Document',
    definition: 'A document that falls within the scope of a discovery request and must be produced to the requesting party, subject to any applicable privilege or protection. Identifying responsive documents is the central task of document review.',
    category: 'Document Review & eDiscovery',
    example: 'In a case about a defective product, an internal engineering report discussing that product\'s known flaws is a responsive document — it must be turned over to the other side.',
    relatedTerms: ['Responsiveness', 'Non-Responsive', 'Production', 'Privilege Review'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Non-Responsive',
    definition: 'A document that does not fall within the scope of any discovery request and need not be produced to the opposing party. Non-responsive documents are withheld from production but must still be preserved in case their status is later challenged.',
    category: 'Document Review & eDiscovery',
    example: 'An employee\'s personal vacation photos stored on their work laptop have nothing to do with the lawsuit, so they are coded non-responsive and not included in the production.',
    relatedTerms: ['Responsiveness', 'Responsive Document', 'Culling', 'Coding'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Privilege',
    definition: 'A legal protection that shields certain communications or documents from compelled disclosure in discovery, most commonly attorney-client privilege and the work product doctrine. Privileged documents must be identified during review, withheld from production, and logged on a privilege log.',
    category: 'Document Review & eDiscovery',
    example: 'An email from an employee to the company\'s lawyer asking for legal advice is privileged — even if it\'s relevant to the case, it does not have to be handed over to the other side.',
    relatedTerms: ['Attorney-Client Privilege', 'Work Product', 'Privilege Log', 'Privilege Review'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Attorney-Client Privilege',
    definition: 'A legal privilege that protects confidential communications between an attorney and their client made for the purpose of seeking or providing legal advice. The privilege belongs to the client, who may waive it, and applies to both directions of communication. Documents coded privileged under attorney-client privilege must appear on a privilege log.',
    category: 'Document Review & eDiscovery',
    example: 'A CEO emails the company\'s lawyer asking "Is our new pricing plan legal?" That email is protected by attorney-client privilege and does not need to be produced.',
    relatedTerms: ['Privilege', 'Work Product', 'Privilege Log', 'Clawback'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Work Product',
    definition: 'Protection under the work product doctrine (FRCP Rule 26(b)(3)) that shields documents and tangible things prepared by or for a party or its representative in anticipation of litigation or trial. Unlike attorney-client privilege, work product can sometimes be overcome by a showing of substantial need and inability to obtain the equivalent by other means.',
    category: 'Document Review & eDiscovery',
    example: 'A lawyer writes a memo outlining their strategy for the upcoming trial. That memo is work product and is protected from being handed over to the opposing side.',
    relatedTerms: ['Privilege', 'Attorney-Client Privilege', 'Privilege Log', 'FRCP Rule 26'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Privilege Log',
    definition: 'A detailed list of documents withheld from production on grounds of privilege or protection, as required by FRCP Rule 26(b)(5). For each withheld document, the log typically identifies the date, author, recipients, general subject matter, and the basis for withholding, without revealing privileged content.',
    category: 'Document Review & eDiscovery',
    example: 'Instead of turning over a privileged email, the producing party lists it in a privilege log with the date, sender, recipient, and a short description like "Request for legal advice re: contract" so the other side knows it exists but can\'t read it.',
    relatedTerms: ['Privilege', 'Attorney-Client Privilege', 'Work Product', 'Redaction'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Clawback',
    definition: 'A procedure allowing a producing party to retrieve inadvertently produced privileged documents. Clawback agreements, often memorialized in a stipulated order under FRCP Rule 502(d), allow the producer to notify the receiving party of the inadvertent production and require return or destruction of the privileged document without waiver of the privilege.',
    category: 'Document Review & eDiscovery',
    example: 'A privileged email accidentally gets included in a document production. The producing attorney notices the mistake, notifies opposing counsel, and asks for the document back. That take-back process is a clawback.',
    relatedTerms: ['Privilege', 'Attorney-Client Privilege', 'Rule 502', 'Inadvertent Disclosure'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Redaction',
    definition: 'The process of obscuring or removing specific portions of a document — such as privileged content, personally identifiable information (PII), or confidential business information — before producing it to the requesting party. Redactions must be applied to the rendered image or PDF and should be permanent, not merely cosmetic.',
    category: 'Document Review & eDiscovery',
    example: 'A document is relevant to the case but contains the lawyer\'s private notes in the margin. The team blacks out those notes before producing the document. That blacking-out is redaction.',
    relatedTerms: ['Privilege Log', 'Confidentiality Designation', 'Production', 'Privilege'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Confidentiality Designation',
    definition: 'A label applied to produced documents indicating the level of protection afforded to sensitive information under a protective order (e.g., "Confidential," "Highly Confidential — Attorneys\' Eyes Only"). The designating party controls access to the designated materials, limiting who may view them.',
    category: 'Document Review & eDiscovery',
    example: 'A company produces its secret pricing formula but stamps it "Highly Confidential — Attorneys\' Eyes Only," meaning only the opposing lawyers can see it — not the opposing company itself.',
    relatedTerms: ['Protective Order', 'Redaction', 'Production', 'Privilege'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Bates Numbering',
    definition: 'A system of unique sequential identifiers stamped on each page of a produced document set, used to track, reference, and authenticate documents throughout litigation. A Bates number typically consists of a prefix (often the producing party\'s initials) followed by a zero-padded sequential number (e.g., ACME-000001).',
    category: 'Document Review & eDiscovery',
    example: 'Every page of a 10,000-page production gets a unique label like "ACME-000001" through "ACME-010000." When a lawyer says "look at ACME-000543 in your deposition," everyone knows exactly which page they mean.',
    relatedTerms: ['Production', 'Production Set', 'Load File', 'Redaction'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Load File',
    definition: 'A structured data file (commonly in DAT, OPT, or CSV format) that accompanies a document production and maps extracted metadata, document boundaries, and image paths so the receiving party can load the production into its review platform. Load files are essential for large-scale electronic productions.',
    category: 'Document Review & eDiscovery',
    example: 'Think of a load file as the table of contents for a production. It tells the receiving party\'s software where each document starts and ends and what its metadata fields are, so everything loads correctly into the review tool.',
    relatedTerms: ['Production', 'Bates Numbering', 'Processing', 'Review Platform'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Production',
    definition: 'The formal delivery of responsive, non-privileged documents to the requesting party in response to a request for production of documents or subpoena. Productions are typically delivered in an agreed format (native, image, or both) with a load file and cover letter identifying the Bates range.',
    category: 'Document Review & eDiscovery',
    example: 'After review is complete, the law firm sends 12,000 responsive documents to the opposing side on a secure file-sharing site. That delivery is the production.',
    relatedTerms: ['Production Set', 'Bates Numbering', 'Load File', 'Native File'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Production Set',
    definition: 'The complete collection of documents delivered in a single production event, including all responsive, non-privileged documents identified as of that production date, Bates-stamped and formatted according to the ESI protocol or court order.',
    category: 'Document Review & eDiscovery',
    example: 'The first production delivered 8,000 documents (pages ACME-000001 to ACME-008000). That batch of 8,000 documents is Production Set 1.',
    relatedTerms: ['Production', 'Bates Numbering', 'Load File', 'Responsive Document'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Native File',
    definition: 'A document produced in its original application format (e.g., .docx, .xlsx, .pst, .mp4) rather than as a rendered TIFF or PDF image. Native productions preserve embedded metadata and functionality but may require the receiving party to have the originating software to open the file.',
    category: 'Document Review & eDiscovery',
    example: 'Instead of producing a spreadsheet as a flat PDF image, the company produces the actual Excel file (.xlsx) so that the formulas and data remain interactive. That is a native file production.',
    relatedTerms: ['ESI', 'Metadata', 'Production', 'Image (TIFF/PDF)'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Image (TIFF/PDF)',
    definition: 'A static rendered representation of a document produced in TIFF (Tagged Image File Format) or PDF (Portable Document Format) rather than in its native application format. Images are commonly used for productions because they can be Bates-stamped and redacted, but they do not preserve native metadata or dynamic functionality.',
    category: 'Document Review & eDiscovery',
    example: 'A Word document is converted to a flat image (like a photograph of the page) before being produced so the receiving party cannot see revision history or track changes. That image is a TIFF or PDF production.',
    relatedTerms: ['Native File', 'Bates Numbering', 'Redaction', 'Load File'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Metadata',
    definition: 'Data that describes the attributes of a document or file, such as creation date, last modified date, author, file size, email headers (sender, recipients, subject), and file path. Metadata is critical in eDiscovery for establishing authenticity, timeline, and custodial information, and must often be produced alongside document content.',
    category: 'Document Review & eDiscovery',
    example: 'A document says it was written on January 1st, but the metadata shows it was actually created and last saved on March 15th. That behind-the-scenes information (dates, author, file location) is metadata.',
    relatedTerms: ['ESI', 'Native File', 'Chain of Custody', 'Hash Value'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Custodian',
    definition: 'An individual (typically an employee or former employee of a party) who possesses or controls potentially relevant documents or ESI. The identification of key custodians is a critical step in early case assessment, and legal holds are typically issued to custodians whose data is likely to be relevant.',
    category: 'Document Review & eDiscovery',
    example: 'In a contract dispute involving the sales team, the VP of Sales and the two account managers who negotiated the deal are custodians — their emails and files are collected for review.',
    relatedTerms: ['Litigation Hold', 'Collection', 'Data Mapping', 'Early Case Assessment'],
    difficulty: 'Beginner',
    isEssential: true,
  },
  {
    term: 'Data Mapping',
    definition: 'The process of inventorying an organization\'s data sources — including servers, cloud applications, mobile devices, and backup media — to understand where potentially relevant ESI resides. A data map informs custodian identification, collection scope, and ESI protocol negotiations.',
    category: 'Document Review & eDiscovery',
    example: 'Before collecting data, the legal team asks IT: "Where does our data live?" The answer — email servers, a cloud drive, a CRM system, and employee laptops — is the data map.',
    relatedTerms: ['Custodian', 'Collection', 'ESI Protocol', 'Early Case Assessment'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Keyword Search',
    definition: 'The use of specific words or phrases to identify potentially relevant documents within a large ESI population. Keyword searches are a foundational culling technique but can suffer from over-inclusion (false positives) and under-inclusion (false negatives), particularly where documents use synonyms or coded language.',
    category: 'Document Review & eDiscovery',
    example: 'Searching 500,000 emails for the word "kickback" returns only the emails that contain that word, cutting the pile down to 15,000 for human review.',
    relatedTerms: ['Boolean Search', 'Concept Search', 'Culling', 'Search Terms'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Search Terms',
    definition: 'The agreed list of words, phrases, and Boolean expressions used to cull a processed ESI population to a reviewable set. Parties often negotiate search terms in meet-and-confer conferences, and the hit counts and sampling results may be shared to demonstrate reasonableness.',
    category: 'Document Review & eDiscovery',
    example: 'Both sides agree that the review will include only documents that contain specific words like the CEO\'s name, the product code, and the deal nickname. That agreed list of words is the search terms.',
    relatedTerms: ['Keyword Search', 'Boolean Search', 'Meet and Confer', 'ESI Protocol'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Boolean Search',
    definition: 'A keyword search using logical operators (AND, OR, NOT, proximity connectors such as w/5 or near) to create complex search expressions that more precisely target relevant documents. Boolean searching allows reviewers to combine terms and exclude noise, producing more targeted hit sets than simple keyword searches.',
    category: 'Document Review & eDiscovery',
    example: 'Searching for "payment AND official NOT contract" finds documents that mention both "payment" and "official" but not "contract," narrowing results more precisely than a simple word search.',
    relatedTerms: ['Keyword Search', 'Search Terms', 'Concept Search', 'Culling'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Concept Search',
    definition: 'An analytics-driven search methodology that identifies documents based on conceptual meaning and semantic similarity rather than exact keyword matches. Concept searching uses machine learning or latent semantic indexing to surface documents that discuss a topic even when they do not contain the specific search terms.',
    category: 'Document Review & eDiscovery',
    example: 'A keyword search for "bribe" misses emails that discuss unofficial payments without using that word. A concept search finds those emails anyway because the software understands the meaning, not just the exact word.',
    relatedTerms: ['Keyword Search', 'Predictive Coding', 'Technology-Assisted Review', 'Culling'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Predictive Coding',
    definition: 'A technology-assisted review methodology in which attorneys code a sample of documents as relevant or non-relevant, and a machine learning algorithm uses those decisions to rank or classify the remaining document population. Also called computer-assisted review (CAR) or technology-assisted review (TAR), it can dramatically reduce review time and cost.',
    category: 'Document Review & eDiscovery',
    example: 'A lawyer reviews and labels 2,000 documents as relevant or not. The software learns from those decisions and predicts which of the remaining 1.5 million documents are likely relevant, so the team focuses on those first.',
    relatedTerms: ['Technology-Assisted Review', 'Continuous Active Learning', 'Seed Set', 'Quality Control'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Technology-Assisted Review',
    definition: 'An umbrella term for any review methodology that uses machine learning, analytics, or AI to assist attorneys in identifying relevant and privileged documents, including predictive coding (TAR 1.0) and continuous active learning (TAR 2.0/CAL). TAR has been accepted by courts as a defensible alternative to linear manual review.',
    category: 'Document Review & eDiscovery',
    example: 'Instead of having reviewers read every one of 2 million documents, a law firm uses TAR software to rank documents by likely relevance so humans only read the top-ranked ones, saving weeks of review time.',
    relatedTerms: ['Predictive Coding', 'Continuous Active Learning', 'Seed Set', 'Quality Control'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Continuous Active Learning',
    definition: 'A TAR workflow (TAR 2.0) in which the machine learning model is continuously retrained as reviewers code documents, with the system dynamically prioritizing the documents most likely to be relevant for human review. Unlike TAR 1.0, CAL does not require a separate training phase or validation protocol before production.',
    category: 'Document Review & eDiscovery',
    example: 'Every time a reviewer marks a document relevant or not, the software immediately gets smarter and re-ranks the remaining documents. Reviewers always see the most promising documents next — that ongoing learning loop is CAL.',
    relatedTerms: ['Predictive Coding', 'Technology-Assisted Review', 'Seed Set', 'Review Platform'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Seed Set',
    definition: 'In TAR 1.0 workflows, the initial set of documents coded by subject-matter attorneys to train the predictive coding algorithm on what constitutes a relevant document. The quality and representativeness of the seed set critically affects model accuracy.',
    category: 'Document Review & eDiscovery',
    example: 'Before turning on predictive coding, attorneys manually review 2,000 hand-picked documents and label each one relevant or not. Those 2,000 labeled documents are the seed set that teaches the software.',
    relatedTerms: ['Predictive Coding', 'Technology-Assisted Review', 'Continuous Active Learning', 'Quality Control'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Quality Control',
    definition: 'The systematic processes used during document review to detect and correct coding errors, ensure consistency across the review team, and validate the accuracy and completeness of the review before production. QC methods include statistically sampled review of coded batches, elusion testing, and senior attorney over-review.',
    category: 'Document Review & eDiscovery',
    example: 'A supervisor spot-checks 500 randomly chosen documents after the review team finishes to make sure reviewers coded them correctly. Finding and fixing mistakes before production is quality control.',
    relatedTerms: ['First-Level Review', 'Second-Level Review', 'Predictive Coding', 'Elusion Testing'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'First-Level Review',
    definition: 'The initial pass through a document set in which contract reviewers or junior associates make responsiveness, privilege, and sometimes issue coding decisions on every document. First-level review decisions are typically subject to quality control sampling and second-level review for complex calls.',
    category: 'Document Review & eDiscovery',
    example: 'A team of contract attorneys reads through 300,000 documents and marks each one responsive or non-responsive, privileged or not. That initial read-and-code pass is first-level review.',
    relatedTerms: ['Second-Level Review', 'Privilege Review', 'Quality Control', 'Coding'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Second-Level Review',
    definition: 'A supervisory review conducted by senior attorneys or specialized reviewers to verify, correct, or refine coding decisions made during first-level review. Second-level review commonly focuses on privilege calls, complex responsiveness determinations, and documents flagged for further analysis.',
    category: 'Document Review & eDiscovery',
    example: 'After junior reviewers code a batch, a senior attorney checks the hardest calls — especially the privilege decisions — and fixes any mistakes. That senior check is second-level review.',
    relatedTerms: ['First-Level Review', 'Privilege Review', 'Quality Control', 'Coding'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Privilege Review',
    definition: 'A specialized review focused on identifying documents protected from disclosure by attorney-client privilege, the work product doctrine, or other applicable privileges. Privilege review typically occurs at the second level, conducted by experienced attorneys who assess each document flagged as potentially privileged.',
    category: 'Document Review & eDiscovery',
    example: 'After first-level reviewers flag documents as "possibly privileged," experienced attorneys go through that subset to decide which ones are truly protected and which must be produced. That deeper look is privilege review.',
    relatedTerms: ['Privilege', 'Attorney-Client Privilege', 'Work Product', 'Privilege Log'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Coding',
    definition: 'The act of applying categorical designations — such as responsive/non-responsive, privileged/not privileged, or issue tags — to documents in a review platform. Coding decisions made by reviewers drive production and privilege log decisions.',
    category: 'Document Review & eDiscovery',
    example: 'A reviewer opens a document, decides it is relevant to the case and not privileged, then clicks "Responsive" and "Not Privileged" in the review software. That clicking and categorizing is coding.',
    relatedTerms: ['Tagging', 'Issue Coding', 'First-Level Review', 'Review Platform'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Tagging',
    definition: 'The application of descriptive labels or issue tags to documents in a review platform to categorize them by topic, issue, witness, or significance. Tagging supplements responsiveness and privilege coding and facilitates issue-based analysis and trial preparation.',
    category: 'Document Review & eDiscovery',
    example: 'A reviewer finds an email that is responsive and also relates to the fraud claim. They mark it "Responsive" and also apply an issue tag "Fraud" so attorneys can quickly pull all fraud-related documents later.',
    relatedTerms: ['Coding', 'Issue Coding', 'Review Platform', 'First-Level Review'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Issue Coding',
    definition: 'The assignment of specific legal or factual issue tags to responsive documents, enabling attorneys to build an issue-organized document set for use in depositions, motions, and trial. Issue coding typically occurs in conjunction with or after responsiveness coding.',
    category: 'Document Review & eDiscovery',
    example: 'Each responsive document gets an additional label indicating which legal issue it relates to — "breach," "damages," or "intent" — so the trial team can instantly pull all documents about damages when preparing for trial.',
    relatedTerms: ['Coding', 'Tagging', 'First-Level Review', 'Review Platform'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'FRCP Rule 26',
    definition: 'Federal Rule of Civil Procedure 26 governs general discovery obligations, including the duty to disclose certain information automatically, the scope of discovery (relevant and proportional to the needs of the case), and obligations to preserve, identify, and produce ESI. Rule 26(b)(5) specifically requires parties to log withheld privileged documents.',
    category: 'Document Review & eDiscovery',
    example: 'Rule 26 is the main federal rule that says what you must share with the other side in a lawsuit, how broad discovery can be, and how to handle privileged documents you are withholding.',
    relatedTerms: ['FRCP Rule 34', 'Proportionality', 'Privilege Log', 'Meet and Confer'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'FRCP Rule 34',
    definition: 'Federal Rule of Civil Procedure 34 governs requests for production of documents, ESI, and tangible things. Rule 34(b)(2)(E) addresses the form of production, requiring ESI to be produced in a reasonably usable form or in the form in which it is ordinarily maintained unless another form is specified or agreed upon.',
    category: 'Document Review & eDiscovery',
    example: 'When the opposing side sends a formal written request saying "give us all emails about the product defect from 2018 to 2021," that request is made under Rule 34.',
    relatedTerms: ['FRCP Rule 26', 'ESI Protocol', 'Native File', 'Production'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Rule 502',
    definition: 'Federal Rule of Evidence 502 limits the scope of privilege waiver arising from inadvertent disclosure of privileged materials in federal proceedings. A Rule 502(d) court order provides the strongest protection, preventing waiver even in other federal or state proceedings, and is commonly used to backstop clawback agreements in eDiscovery.',
    category: 'Document Review & eDiscovery',
    example: 'The parties ask the judge to sign a Rule 502(d) order at the start of the case. If a privileged document is accidentally produced later, that order ensures the privilege is not permanently lost — the document can be clawed back.',
    relatedTerms: ['Clawback', 'Attorney-Client Privilege', 'Inadvertent Disclosure', 'Privilege Log'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Meet and Confer',
    definition: 'A mandatory pre-discovery conference between opposing parties\' counsel, required under FRCP Rule 26(f), to discuss the nature of claims and defenses, ESI preservation and production, custodian identification, search terms, and case scheduling. The ESI-focused meet-and-confer is the foundation of an agreed ESI protocol.',
    category: 'Document Review & eDiscovery',
    example: 'Before either side can request documents, the opposing lawyers must have a phone call or meeting to agree on basics: which employees\' data to collect, what search terms to use, and how documents will be formatted for delivery.',
    relatedTerms: ['ESI Protocol', 'Search Terms', 'FRCP Rule 26', 'Proportionality'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'ESI Protocol',
    definition: 'A written agreement or court order that specifies the technical requirements for eDiscovery, including collection methods, processing specifications, production format (native vs. image), metadata fields to be produced, search term methodology, and dispute-resolution procedures. The ESI protocol is typically negotiated during or after the Rule 26(f) meet and confer.',
    category: 'Document Review & eDiscovery',
    example: 'Both sides sign a written agreement specifying: produce documents as PDF images, include 48 metadata fields, and deliver files in Relativity-compatible format. That written agreement is the ESI protocol.',
    relatedTerms: ['Meet and Confer', 'FRCP Rule 34', 'Load File', 'Production'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Proportionality',
    definition: 'The FRCP Rule 26(b)(1) principle that discovery must be proportional to the needs of the case, considering factors such as the amount in controversy, the importance of the issues, the parties\' relative resources, and whether the burden of discovery outweighs its likely benefit. Courts use proportionality to limit excessive or burdensome eDiscovery demands.',
    category: 'Document Review & eDiscovery',
    example: 'One side demands data from 200 employees for a $50,000 dispute. The judge says that is too burdensome for a case this small and limits collection to 5 employees. That limit is based on proportionality.',
    relatedTerms: ['FRCP Rule 26', 'Meet and Confer', 'ESI Protocol', 'Early Case Assessment'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Chain of Custody',
    definition: 'A documented record of the sequential custody, control, transfer, and handling of evidence — including ESI — from the moment of collection through production and trial. Maintaining an unbroken chain of custody is essential for establishing the authenticity and integrity of electronic evidence.',
    category: 'Document Review & eDiscovery',
    example: 'A log records that a laptop was seized by the forensics team on Monday, transferred to the lab on Tuesday, and imaged on Wednesday. That unbroken record of who had the laptop and when is the chain of custody.',
    relatedTerms: ['Collection', 'Hash Value', 'Preservation', 'Metadata'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Hash Value',
    definition: 'A fixed-length alphanumeric string generated by a cryptographic algorithm (such as MD5 or SHA-1) that uniquely identifies the contents of a file at a given point in time. Hash values are used to verify that collected ESI has not been altered, to identify exact duplicates during deduplication, and to authenticate documents.',
    category: 'Document Review & eDiscovery',
    example: 'Think of a hash value as a digital fingerprint for a file. If even one character in the file changes, the fingerprint changes completely — proving the file was altered.',
    relatedTerms: ['Deduplication', 'Chain of Custody', 'Collection', 'Metadata'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Early Case Assessment',
    definition: 'A preliminary analysis of the volume, content, and nature of potentially relevant ESI conducted at the outset of a matter to inform litigation strategy, estimate review costs, identify key custodians and issues, and assess risk before full-scale discovery begins.',
    category: 'Document Review & eDiscovery',
    example: 'Before committing to full discovery, the legal team runs a quick search to see how many documents exist, who the key people are, and roughly what it will cost to review everything. That early sizing-up is early case assessment.',
    relatedTerms: ['Custodian', 'Data Mapping', 'Proportionality', 'Culling'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Review Platform',
    definition: 'Software used to host, manage, and review document populations during eDiscovery, providing tools for searching, filtering, coding, tagging, quality control, analytics, and production. Leading platforms include Relativity, Everlaw, Catalyst, and Nuix Discover.',
    category: 'Document Review & eDiscovery',
    example: 'Reviewers log into a web-based tool like Relativity every day to open documents, read them, and click buttons to mark them responsive or privileged. That tool is the review platform.',
    relatedTerms: ['Predictive Coding', 'Technology-Assisted Review', 'Coding', 'Production'],
    difficulty: 'Beginner',
    isEssential: false,
  },
  {
    term: 'Inadvertent Disclosure',
    definition: 'The accidental production of privileged or protected documents during discovery. Inadvertent disclosure may or may not result in waiver of privilege depending on the applicable jurisdiction, the circumstances of the disclosure, and whether a clawback agreement or Rule 502(d) order is in place.',
    category: 'Document Review & eDiscovery',
    example: 'A privileged email accidentally slips into a large document production. The producing attorney did not intend to share it — that accidental slip is an inadvertent disclosure.',
    relatedTerms: ['Clawback', 'Rule 502', 'Privilege', 'Privilege Log'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Elusion Testing',
    definition: 'A quality control technique used in TAR workflows to estimate the prevalence of relevant documents in the population coded as non-relevant, validating that the review has achieved sufficient recall before production. A low elusion rate confirms that the non-produced population contains acceptably few responsive documents.',
    category: 'Document Review & eDiscovery',
    example: 'After TAR finishes, the team randomly samples 2,000 documents from the pile that was coded non-relevant and checks if any were actually relevant. Finding only 3 out of 2,000 confirms the review caught almost everything.',
    relatedTerms: ['Quality Control', 'Technology-Assisted Review', 'Predictive Coding', 'Recall'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Recall',
    definition: 'In the context of TAR and information retrieval, the proportion of all truly relevant documents in the collection that the review process has successfully identified. High recall indicates that few relevant documents were missed; courts and practitioners often target a recall rate of 70-80% or higher as a benchmark for a defensible TAR review.',
    category: 'Document Review & eDiscovery',
    example: 'If there are 10,000 truly relevant documents in a collection and the review found 7,800 of them, the recall rate is 78%. A high recall means fewer relevant documents were missed.',
    relatedTerms: ['Elusion Testing', 'Predictive Coding', 'Technology-Assisted Review', 'Quality Control'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Protective Order',
    definition: 'A court order that restricts the use and dissemination of sensitive information produced in discovery, including trade secrets, confidential business information, and personal data. Protective orders typically establish tiered confidentiality designations and specify who may access materials at each tier.',
    category: 'Document Review & eDiscovery',
    example: 'Before exchanging sensitive financial records, both sides ask the judge to sign a protective order limiting who can see those records and how they can be used. That court order is the protective order.',
    relatedTerms: ['Confidentiality Designation', 'Redaction', 'Production', 'Rule 502'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Adverse Inference',
    definition: 'A spoliation sanction in which the jury is instructed to presume that destroyed or unavailable evidence would have been unfavorable to the party responsible for its loss. An adverse inference instruction is among the most severe eDiscovery sanctions short of dismissal or default judgment.',
    category: 'Document Review & eDiscovery',
    example: 'A company failed to preserve emails and they were deleted. The judge tells the jury: "You may assume those missing emails contained evidence that hurt the company\'s case." That instruction is an adverse inference.',
    relatedTerms: ['Spoliation', 'Litigation Hold', 'Preservation', 'FRCP Rule 37(e)'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'FRCP Rule 37(e)',
    definition: 'The provision of the Federal Rules of Civil Procedure governing sanctions for failure to preserve ESI. Rule 37(e) permits courts to order curative measures or, upon finding intent to deprive the opposing party of evidence, impose severe sanctions including an adverse inference instruction, dismissal, or default judgment.',
    category: 'Document Review & eDiscovery',
    example: 'A party intentionally deletes key text messages after being notified of a lawsuit. The opposing party invokes Rule 37(e) and asks the judge to sanction them — up to telling the jury to assume the worst about what those messages said.',
    relatedTerms: ['Spoliation', 'Adverse Inference', 'Litigation Hold', 'Preservation'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Forensic Collection',
    definition: 'The use of specialized forensic tools and methodologies to collect ESI from devices and systems in a manner that preserves data integrity, captures deleted or hidden data, and maintains a verifiable chain of custody. Forensic collection is often used when data manipulation is suspected or when mobile devices and ephemeral data are involved.',
    category: 'Document Review & eDiscovery',
    example: 'When a company suspects an employee deleted important files, forensic specialists use specialized software to image the hard drive and recover those deleted files before they are permanently gone.',
    relatedTerms: ['Collection', 'Chain of Custody', 'Hash Value', 'Preservation'],
    difficulty: 'Advanced',
    isEssential: false,
  },
  {
    term: 'Rolling Production',
    definition: 'A method of producing documents in stages over time rather than in a single delivery, allowing the producing party to make materials available to the requesting party as they complete review of successive batches. Rolling productions are common in large cases where linear production would unreasonably delay access to critical documents.',
    category: 'Document Review & eDiscovery',
    example: 'Instead of waiting to finish reviewing all 500,000 documents before producing anything, the team produces 20,000 reviewed documents each month. That ongoing delivery schedule is a rolling production.',
    relatedTerms: ['Production', 'Production Set', 'Bates Numbering', 'Load File'],
    difficulty: 'Intermediate',
    isEssential: false,
  },
  {
    term: 'Precision',
    definition: 'In information retrieval and TAR, the proportion of documents retrieved or coded as relevant that are actually relevant, measuring how accurately the review process avoids false positives. High precision minimizes the volume of non-relevant documents included in a production; it is evaluated alongside recall for a complete picture of review quality.',
    category: 'Document Review & eDiscovery',
    example: 'If the TAR system flags 1,000 documents as relevant and 850 of them really are relevant, the precision is 85%. High precision means the system is not wasting reviewers\' time on irrelevant documents.',
    relatedTerms: ['Recall', 'Technology-Assisted Review', 'Quality Control', 'Elusion Testing'],
    difficulty: 'Advanced',
    isEssential: false,
  },
];

export default terms;
