import { GlossaryTermSeed } from './types';

const terms: GlossaryTermSeed[] = [
  {
    term: 'Plaintiff',
    definition: 'The party who initiates a civil lawsuit by filing a complaint against another party. The plaintiff bears the burden of proving the claims asserted in the lawsuit.',
    category: 'Litigation & Civil Procedure',
    example: 'Jane files a lawsuit against her former employer for wrongful termination, making her the plaintiff in the case.',
    relatedTerms: ['Defendant', 'Complaint', 'Standing', 'Cause of Action'],
  },
  {
    term: 'Defendant',
    definition: 'The party against whom a civil lawsuit is brought. The defendant must respond to the plaintiff\'s complaint within a court-specified deadline.',
    category: 'Litigation & Civil Procedure',
    example: 'After Jane filed her lawsuit, her former employer became the defendant and had 21 days to file an answer.',
    relatedTerms: ['Plaintiff', 'Answer', 'Counterclaim', 'Default Judgment'],
  },
  {
    term: 'Complaint',
    definition: 'The initial pleading filed by the plaintiff that formally commences a lawsuit. It sets out the facts, legal claims, and relief sought against the defendant.',
    category: 'Litigation & Civil Procedure',
    example: 'The complaint alleged three counts of breach of contract and sought $500,000 in damages.',
    relatedTerms: ['Plaintiff', 'Pleading', 'Answer', 'Summons'],
  },
  {
    term: 'Answer',
    definition: 'The defendant\'s formal written response to the plaintiff\'s complaint. The answer admits or denies each allegation and may assert affirmative defenses.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant\'s answer denied all allegations of negligence and raised the affirmative defense of contributory negligence.',
    relatedTerms: ['Complaint', 'Defendant', 'Affirmative Defense', 'Counterclaim'],
  },
  {
    term: 'Counterclaim',
    definition: 'A claim asserted by the defendant against the plaintiff in the same action. A compulsory counterclaim arises from the same transaction as the plaintiff\'s claim and must be raised or it is waived.',
    category: 'Litigation & Civil Procedure',
    example: 'The contractor sued for unpaid fees; the homeowner filed a counterclaim alleging the work was defective.',
    relatedTerms: ['Answer', 'Cross-Claim', 'Defendant', 'Plaintiff'],
  },
  {
    term: 'Cross-Claim',
    definition: 'A claim asserted by one co-party against another co-party on the same side of the litigation. Cross-claims must arise from the same transaction or occurrence as the original action.',
    category: 'Litigation & Civil Procedure',
    example: 'Two co-defendants both sued for a car accident; one filed a cross-claim against the other, alleging the other was actually at fault.',
    relatedTerms: ['Counterclaim', 'Joinder', 'Third-Party Claim', 'Defendant'],
  },
  {
    term: 'Pleading',
    definition: 'A formal written document filed with the court that sets forth a party\'s claims, defenses, or positions. Common pleadings include the complaint, answer, counterclaim, and reply.',
    category: 'Litigation & Civil Procedure',
    example: 'The court struck the plaintiff\'s pleading because it failed to state a claim with sufficient particularity.',
    relatedTerms: ['Complaint', 'Answer', 'Motion to Dismiss', 'Cause of Action'],
  },
  {
    term: 'Summons',
    definition: 'A court-issued document that notifies the defendant that a lawsuit has been filed against them and requires them to appear or respond within a specified time. It is served together with the complaint.',
    category: 'Litigation & Civil Procedure',
    example: 'A process server delivered the summons and complaint to the defendant at his home address.',
    relatedTerms: ['Service of Process', 'Complaint', 'Jurisdiction', 'Default Judgment'],
  },
  {
    term: 'Service of Process',
    definition: 'The procedure by which a party formally delivers legal documents—such as a summons and complaint—to the opposing party, providing them with legal notice of the action. Proper service is required for the court to have personal jurisdiction.',
    category: 'Litigation & Civil Procedure',
    example: 'Service of process was completed by certified mail in accordance with the state\'s long-arm statute.',
    relatedTerms: ['Summons', 'Personal Jurisdiction', 'Default Judgment', 'Complaint'],
  },
  {
    term: 'Subject-Matter Jurisdiction',
    definition: 'The authority of a court to hear cases of a particular type or category. Federal courts, for example, have subject-matter jurisdiction over federal question cases and cases involving diversity of citizenship.',
    category: 'Litigation & Civil Procedure',
    example: 'The federal court dismissed the case for lack of subject-matter jurisdiction because the parties were citizens of the same state and no federal question was involved.',
    relatedTerms: ['Personal Jurisdiction', 'Venue', 'Federal Question', 'Diversity Jurisdiction'],
  },
  {
    term: 'Personal Jurisdiction',
    definition: 'The court\'s authority over the parties to a lawsuit. A court must have personal jurisdiction over the defendant, which can be established through the defendant\'s presence, domicile, consent, or minimum contacts with the forum state.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant challenged personal jurisdiction, arguing he had no contacts with the forum state.',
    relatedTerms: ['Subject-Matter Jurisdiction', 'Service of Process', 'Venue', 'Long-Arm Statute'],
  },
  {
    term: 'Venue',
    definition: 'The geographic location or district in which a case is heard. Venue rules determine which court among those with proper jurisdiction is the appropriate place to file and try a case.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant moved to transfer venue because the plaintiff had filed in a distant district unconnected to the dispute.',
    relatedTerms: ['Subject-Matter Jurisdiction', 'Personal Jurisdiction', 'Forum Non Conveniens', 'Transfer of Venue'],
  },
  {
    term: 'Standing',
    definition: 'The legal right of a party to bring a lawsuit. To have standing, a plaintiff must show a concrete injury, a causal connection between the injury and the defendant\'s conduct, and a likelihood that a favorable decision will redress the injury.',
    category: 'Litigation & Civil Procedure',
    example: 'The court dismissed the environmental group\'s suit, finding it lacked standing because none of its members had suffered a direct injury.',
    relatedTerms: ['Plaintiff', 'Cause of Action', 'Ripeness', 'Mootness'],
  },
  {
    term: 'Cause of Action',
    definition: 'A legally recognized set of facts that entitles a party to seek judicial relief. Each cause of action has specific elements that must be alleged and ultimately proven to succeed in court.',
    category: 'Litigation & Civil Procedure',
    example: 'The complaint stated two causes of action: negligence and breach of warranty.',
    relatedTerms: ['Complaint', 'Standing', 'Pleading', 'Elements of a Claim'],
  },
  {
    term: 'Discovery',
    definition: 'The pre-trial process by which parties obtain evidence and information from each other and third parties. Discovery tools include interrogatories, depositions, requests for production, and requests for admission.',
    category: 'Litigation & Civil Procedure',
    example: 'During discovery, the plaintiff\'s attorneys reviewed thousands of emails produced by the defendant corporation.',
    relatedTerms: ['Interrogatories', 'Deposition', 'Request for Production', 'Subpoena'],
  },
  {
    term: 'Interrogatories',
    definition: 'Written questions submitted by one party to another party during discovery, which must be answered in writing under oath. Interrogatories are limited in number by court rules.',
    category: 'Litigation & Civil Procedure',
    example: 'The plaintiff served 25 interrogatories asking the defendant to identify all witnesses and describe the events leading to the accident.',
    relatedTerms: ['Discovery', 'Deposition', 'Request for Admission', 'Request for Production'],
  },
  {
    term: 'Deposition',
    definition: 'An out-of-court oral examination of a witness (deponent) taken under oath and recorded by a court reporter. Depositions can be used to gather information and to impeach a witness\'s trial testimony.',
    category: 'Litigation & Civil Procedure',
    example: 'The expert witness was deposed for five hours before trial; her deposition transcript was later used to challenge inconsistencies in her testimony.',
    relatedTerms: ['Discovery', 'Interrogatories', 'Subpoena', 'Witness'],
  },
  {
    term: 'Request for Production',
    definition: 'A discovery tool by which one party asks the other to produce documents, electronically stored information, or tangible items for inspection and copying.',
    category: 'Litigation & Civil Procedure',
    example: 'Counsel served a request for production seeking all contracts, emails, and financial records related to the disputed transaction.',
    relatedTerms: ['Discovery', 'Interrogatories', 'Subpoena', 'Request for Admission'],
  },
  {
    term: 'Request for Admission',
    definition: 'A discovery device by which one party asks another to admit or deny the truth of specific factual statements. Matters that are admitted are conclusively established for the litigation.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant admitted in its responses to requests for admission that the signature on the contract was genuine, removing that issue from trial.',
    relatedTerms: ['Discovery', 'Interrogatories', 'Request for Production', 'Stipulation'],
  },
  {
    term: 'Subpoena',
    definition: 'A court order compelling a person to appear for a deposition or trial (subpoena ad testificandum) or to produce documents (subpoena duces tecum). Failure to comply can result in contempt of court.',
    category: 'Litigation & Civil Procedure',
    example: 'The bank received a subpoena duces tecum requiring it to produce the defendant\'s account records.',
    relatedTerms: ['Discovery', 'Deposition', 'Contempt of Court', 'Witness'],
  },
  {
    term: 'Motion',
    definition: 'A formal request made to the court asking for a specific ruling or order. Motions may be made in writing or orally and are distinct from the pleadings that define the claims and defenses.',
    category: 'Litigation & Civil Procedure',
    example: 'Plaintiff\'s counsel filed a motion requesting a 60-day extension to complete expert discovery.',
    relatedTerms: ['Motion to Dismiss', 'Summary Judgment', 'Injunction', 'Order'],
  },
  {
    term: 'Motion to Dismiss',
    definition: 'A pre-answer motion asking the court to dismiss the case, or part of it, because of a legal defect such as lack of jurisdiction, improper service, or failure to state a valid claim. Under Federal Rule 12(b)(6), courts test whether the complaint states a plausible claim.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant filed a motion to dismiss, arguing the complaint failed to allege any facts supporting a breach of contract claim.',
    relatedTerms: ['Motion', 'Complaint', 'Pleading', 'Failure to State a Claim'],
  },
  {
    term: 'Summary Judgment',
    definition: 'A ruling by the court disposing of a case or a claim without a trial when there is no genuine dispute of material fact and the moving party is entitled to judgment as a matter of law.',
    category: 'Litigation & Civil Procedure',
    example: 'The court granted summary judgment for the defendant because the plaintiff produced no evidence supporting causation.',
    relatedTerms: ['Motion', 'Trial', 'Genuine Dispute of Material Fact', 'Burden of Proof'],
  },
  {
    term: 'Default Judgment',
    definition: 'A judgment entered against a party who fails to respond to or appear in a lawsuit. Before a default judgment is entered, a clerk\'s entry of default is typically required.',
    category: 'Litigation & Civil Procedure',
    example: 'Because the defendant never filed an answer, the plaintiff obtained a default judgment for the full amount claimed.',
    relatedTerms: ['Defendant', 'Answer', 'Summons', 'Judgment'],
  },
  {
    term: 'Voir Dire',
    definition: 'The process of questioning prospective jurors to determine their suitability to serve on a jury. Attorneys may challenge jurors for cause (unlimited) or use peremptory challenges (limited in number).',
    category: 'Litigation & Civil Procedure',
    example: 'During voir dire, counsel struck a juror who admitted to having a prior business relationship with the defendant.',
    relatedTerms: ['Jury Instruction', 'Peremptory Challenge', 'Challenge for Cause', 'Trial'],
  },
  {
    term: 'Jury Instruction',
    definition: 'Directions given by the judge to the jury explaining the applicable law and the standards the jury must apply when reaching a verdict. Both parties typically propose instructions, and the judge rules on which will be given.',
    category: 'Litigation & Civil Procedure',
    example: 'The judge read the pattern negligence instruction to the jury, explaining the elements plaintiffs must prove by a preponderance of the evidence.',
    relatedTerms: ['Voir Dire', 'Verdict', 'Trial', 'Burden of Proof'],
  },
  {
    term: 'Verdict',
    definition: 'The formal decision reached by a jury (or judge in a bench trial) on the factual issues submitted to it. In civil cases the most common verdict is a general verdict for plaintiff or defendant, often accompanied by a damages award.',
    category: 'Litigation & Civil Procedure',
    example: 'After three days of deliberation, the jury returned a verdict for the plaintiff and awarded $1.2 million in compensatory damages.',
    relatedTerms: ['Jury Instruction', 'Judgment', 'Trial', 'Damages'],
  },
  {
    term: 'Judgment',
    definition: 'The court\'s final determination of the rights and obligations of the parties in a lawsuit. A judgment may be entered after a trial, after a motion, or by stipulation of the parties.',
    category: 'Litigation & Civil Procedure',
    example: 'The court entered judgment on the jury\'s verdict and ordered the defendant to pay damages within 30 days.',
    relatedTerms: ['Verdict', 'Summary Judgment', 'Default Judgment', 'Appeal'],
  },
  {
    term: 'Appeal',
    definition: 'The process by which a party asks a higher court to review and reverse or modify a lower court\'s decision. Appeals are generally limited to legal errors, not factual reweighing.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant appealed the judgment, arguing the trial court improperly excluded key expert testimony.',
    relatedTerms: ['Appellant', 'Appellee', 'Remand', 'Judgment'],
  },
  {
    term: 'Appellant',
    definition: 'The party who files an appeal seeking review of a lower court\'s decision. The appellant bears the burden of demonstrating that the lower court committed reversible error.',
    category: 'Litigation & Civil Procedure',
    example: 'As appellant, the defendant filed an opening brief arguing three grounds for reversal.',
    relatedTerms: ['Appellee', 'Appeal', 'Remand', 'Brief'],
  },
  {
    term: 'Appellee',
    definition: 'The party who responds to an appeal, typically the party who prevailed in the lower court. The appellee argues that the lower court\'s decision was correct and should be affirmed.',
    category: 'Litigation & Civil Procedure',
    example: 'As appellee, the plaintiff filed a response brief defending the trial court\'s evidentiary rulings.',
    relatedTerms: ['Appellant', 'Appeal', 'Brief', 'Judgment'],
  },
  {
    term: 'Remand',
    definition: 'An appellate court\'s order sending a case back to the lower court for further proceedings consistent with the appellate court\'s ruling. Remand may be for a new trial, limited reconsideration, or entry of a corrected judgment.',
    category: 'Litigation & Civil Procedure',
    example: 'The appellate court reversed the dismissal and remanded the case for the trial court to conduct a full evidentiary hearing.',
    relatedTerms: ['Appeal', 'Appellant', 'Appellee', 'Reversal'],
  },
  {
    term: 'Stay',
    definition: 'A court order halting or suspending a judicial proceeding or the enforcement of a judgment, temporarily or until further order. Parties seeking a stay of a judgment pending appeal typically must post a supersedeas bond.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant obtained a stay of the injunction while the appeal was pending.',
    relatedTerms: ['Injunction', 'Appeal', 'Judgment', 'Motion'],
  },
  {
    term: 'Injunction',
    definition: 'A court order requiring a party to do or refrain from doing a specific act. A preliminary injunction preserves the status quo during litigation; a permanent injunction is issued after final judgment.',
    category: 'Litigation & Civil Procedure',
    example: 'The court issued a preliminary injunction preventing the defendant from selling the disputed intellectual property pending trial.',
    relatedTerms: ['Temporary Restraining Order', 'Stay', 'Motion', 'Irreparable Harm'],
  },
  {
    term: 'Temporary Restraining Order',
    definition: 'An emergency court order issued without full notice to the opposing party, directing a party to maintain the status quo for a brief period—typically until the court can hold a hearing on a preliminary injunction.',
    category: 'Litigation & Civil Procedure',
    example: 'The plaintiff obtained a temporary restraining order preventing the defendant from destroying evidence before a full hearing could be held.',
    relatedTerms: ['Injunction', 'Motion', 'Stay', 'Irreparable Harm'],
  },
  {
    term: 'Class Action',
    definition: 'A lawsuit brought by one or more plaintiffs on behalf of a larger group of people (the class) who share common legal claims. The class must be certified by the court before the case may proceed on a class-wide basis.',
    category: 'Litigation & Civil Procedure',
    example: 'Thousands of consumers who purchased the defective product were represented in a single class action against the manufacturer.',
    relatedTerms: ['Class Certification', 'Settlement', 'Joinder', 'Plaintiff'],
  },
  {
    term: 'Statute of Limitations',
    definition: 'The time period within which a lawsuit must be filed after a cause of action accrues. Filing after the limitations period expires bars the claim, regardless of its merits.',
    category: 'Litigation & Civil Procedure',
    example: 'The court dismissed the negligence claim because the plaintiff filed suit three years after the accident, one year beyond the applicable statute of limitations.',
    relatedTerms: ['Cause of Action', 'Affirmative Defense', 'Tolling', 'Laches'],
  },
  {
    term: 'Res Judicata',
    definition: 'The doctrine that a final judgment on the merits by a court of competent jurisdiction bars re-litigation of the same cause of action between the same parties or their privies. Also called claim preclusion.',
    category: 'Litigation & Civil Procedure',
    example: 'Because the plaintiff had already litigated and lost the contract dispute, the court dismissed the new lawsuit on res judicata grounds.',
    relatedTerms: ['Collateral Estoppel', 'Final Judgment', 'Privity', 'Cause of Action'],
  },
  {
    term: 'Collateral Estoppel',
    definition: 'The doctrine that once an issue of fact or law is actually litigated and necessarily decided, that determination is conclusive in subsequent litigation between the same parties, even on a different cause of action. Also called issue preclusion.',
    category: 'Litigation & Civil Procedure',
    example: 'The prior criminal conviction established the defendant\'s fraud, and collateral estoppel prevented him from re-litigating that issue in the civil suit.',
    relatedTerms: ['Res Judicata', 'Final Judgment', 'Issue Preclusion', 'Privity'],
  },
  {
    term: 'Joinder',
    definition: 'The procedural mechanism for adding parties or claims to a lawsuit. Compulsory joinder requires parties who are necessary for a just resolution to be included; permissive joinder allows parties with related claims to join voluntarily.',
    category: 'Litigation & Civil Procedure',
    example: 'The court ordered mandatory joinder of a third company that had contractual rights in the disputed asset.',
    relatedTerms: ['Cross-Claim', 'Counterclaim', 'Third-Party Claim', 'Class Action'],
  },
  {
    term: 'Interpleader',
    definition: 'A procedural device by which a party holding money or property claimed by two or more other parties (the stakeholder) deposits the asset with the court and asks the court to determine who is entitled to it.',
    category: 'Litigation & Civil Procedure',
    example: 'The insurance company filed an interpleader action because two parties claimed entitlement to the same life-insurance proceeds.',
    relatedTerms: ['Joinder', 'Stakeholder', 'Judgment', 'Motion'],
  },
  {
    term: 'Settlement',
    definition: 'A voluntary agreement between parties to resolve a lawsuit without a final court judgment. Most civil cases end in settlement, which typically includes a release of all claims and may include monetary payment.',
    category: 'Litigation & Civil Procedure',
    example: 'On the morning of trial, the parties reached a confidential settlement agreement for an undisclosed sum.',
    relatedTerms: ['Mediation', 'Arbitration', 'Consent Decree', 'Release'],
  },
  {
    term: 'Mediation',
    definition: 'A form of alternative dispute resolution in which a neutral third party (the mediator) facilitates negotiations between the parties to help them reach a voluntary settlement. The mediator has no authority to impose a decision.',
    category: 'Litigation & Civil Procedure',
    example: 'Before filing suit, the parties participated in a full-day mediation session that resulted in a written settlement agreement.',
    relatedTerms: ['Arbitration', 'Settlement', 'Alternative Dispute Resolution', 'Neutral'],
  },
  {
    term: 'Arbitration',
    definition: 'A form of alternative dispute resolution in which a neutral third party (arbitrator) hears evidence and arguments from the parties and renders a binding decision. Arbitration is typically faster and less formal than litigation.',
    category: 'Litigation & Civil Procedure',
    example: 'The employment contract required all disputes to be resolved through binding arbitration rather than in court.',
    relatedTerms: ['Mediation', 'Settlement', 'Alternative Dispute Resolution', 'Award'],
  },
  {
    term: 'Affirmative Defense',
    definition: 'A defense raised by the defendant that introduces new facts or legal theories that, even if the plaintiff\'s allegations are true, justify or excuse the defendant\'s conduct. Common examples include statute of limitations, waiver, and assumption of risk.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant\'s answer pleaded the affirmative defense of release, attaching a signed settlement agreement from the prior litigation.',
    relatedTerms: ['Answer', 'Statute of Limitations', 'Res Judicata', 'Waiver'],
  },
  {
    term: 'Burden of Proof',
    definition: 'The obligation of a party to prove a disputed allegation to the required standard. In civil cases, the plaintiff generally must prove each element of a claim by a preponderance of the evidence (more likely than not).',
    category: 'Litigation & Civil Procedure',
    example: 'The plaintiff bore the burden of proof and presented witnesses and documents to establish that the defendant breached the contract.',
    relatedTerms: ['Preponderance of the Evidence', 'Clear and Convincing Evidence', 'Jury Instruction', 'Elements of a Claim'],
  },
  {
    term: 'Preponderance of the Evidence',
    definition: 'The standard of proof required in most civil cases, meaning the plaintiff must show that a fact is more likely true than not—greater than a 50% probability. It is a lower threshold than "clear and convincing evidence" or "beyond a reasonable doubt."',
    category: 'Litigation & Civil Procedure',
    example: 'The jury found by a preponderance of the evidence that the defendant\'s negligence caused the plaintiff\'s injury.',
    relatedTerms: ['Burden of Proof', 'Clear and Convincing Evidence', 'Standard of Proof', 'Verdict'],
  },
  {
    term: 'Demurrer',
    definition: 'A pleading in some state court systems (analogous to a Rule 12(b)(6) motion to dismiss) that challenges the legal sufficiency of the opposing party\'s pleading, asserting that even if the facts alleged are true, they do not support a valid legal claim.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant filed a demurrer arguing that the facts alleged in the complaint did not constitute fraud as a matter of law.',
    relatedTerms: ['Motion to Dismiss', 'Pleading', 'Cause of Action', 'Answer'],
  },
  {
    term: 'Third-Party Claim',
    definition: 'A claim by a defendant (third-party plaintiff) against a non-party (third-party defendant) who may be liable for all or part of the plaintiff\'s claim against the defendant. This mechanism promotes judicial efficiency by resolving related claims in one action.',
    category: 'Litigation & Civil Procedure',
    example: 'The contractor sued for breach of contract then filed a third-party claim against its subcontractor, alleging the subcontractor was responsible for the defective work.',
    relatedTerms: ['Joinder', 'Cross-Claim', 'Counterclaim', 'Indemnification'],
  },
  {
    term: 'Indemnification',
    definition: 'A contractual or legal obligation by one party to compensate another for losses, damages, or liability arising from specified events. Indemnification clauses often determine which party bears the ultimate financial responsibility in litigation.',
    category: 'Litigation & Civil Procedure',
    example: 'The vendor\'s contract included an indemnification clause requiring it to defend and hold harmless the client from any product-liability claims.',
    relatedTerms: ['Third-Party Claim', 'Contribution', 'Settlement', 'Damages'],
  },
  {
    term: 'Damages',
    definition: 'The monetary compensation awarded to a party who has suffered loss or injury due to another\'s wrongful act. Types include compensatory (to make the plaintiff whole), consequential, punitive (to punish and deter), and nominal damages.',
    category: 'Litigation & Civil Procedure',
    example: 'The jury awarded $300,000 in compensatory damages for lost wages and medical expenses, plus $1 million in punitive damages.',
    relatedTerms: ['Verdict', 'Judgment', 'Compensatory Damages', 'Punitive Damages'],
  },
  {
    term: 'Punitive Damages',
    definition: 'Damages awarded in addition to compensatory damages to punish a defendant for egregious, malicious, or fraudulent conduct and to deter similar behavior in the future. They are not available in all cases and are subject to constitutional limits.',
    category: 'Litigation & Civil Procedure',
    example: 'The court upheld $2 million in punitive damages because the defendant knowingly concealed a safety defect for years.',
    relatedTerms: ['Damages', 'Compensatory Damages', 'Verdict', 'Burden of Proof'],
  },
  {
    term: 'Laches',
    definition: 'An equitable defense asserting that the plaintiff unreasonably delayed in bringing a claim and that the delay prejudiced the defendant. Unlike a statute of limitations, laches focuses on prejudice rather than a fixed time period.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant successfully raised laches because the plaintiff waited 12 years to file suit, during which time key witnesses died and evidence was lost.',
    relatedTerms: ['Affirmative Defense', 'Statute of Limitations', 'Equitable Relief', 'Waiver'],
  },
  {
    term: 'Forum Non Conveniens',
    definition: 'A discretionary doctrine allowing a court to dismiss a case when another court or jurisdiction would be a substantially more convenient forum for the parties and witnesses, even though the original court has proper jurisdiction.',
    category: 'Litigation & Civil Procedure',
    example: 'The court dismissed on forum non conveniens grounds because all witnesses, documents, and the accident site were located in a foreign country.',
    relatedTerms: ['Venue', 'Subject-Matter Jurisdiction', 'Transfer of Venue', 'Dismissal'],
  },
  {
    term: 'Declaratory Judgment',
    definition: 'A court\'s binding ruling that defines the legal rights and obligations of parties without ordering any specific act or awarding damages. Parties often seek declaratory judgments to resolve disputes before they ripen into full-blown litigation.',
    category: 'Litigation & Civil Procedure',
    example: 'The insurance company filed for a declaratory judgment that the policy did not cover the claimed losses.',
    relatedTerms: ['Judgment', 'Injunction', 'Standing', 'Ripeness'],
  },
  {
    term: 'Ripeness',
    definition: 'A justiciability doctrine requiring that a dispute be sufficiently developed and immediate before a court will hear it. A case is not ripe if it involves future or speculative harms that may never materialize.',
    category: 'Litigation & Civil Procedure',
    example: 'The court dismissed the challenge as not ripe because the regulation had been passed but not yet enforced against anyone.',
    relatedTerms: ['Standing', 'Mootness', 'Declaratory Judgment', 'Justiciability'],
  },
  {
    term: 'Mootness',
    definition: 'A doctrine that bars a court from deciding a case where the controversy has been resolved or no longer exists, rendering any judgment advisory. A case becomes moot if events occurring after filing deprive the court of the ability to grant effective relief.',
    category: 'Litigation & Civil Procedure',
    example: 'After the company paid the full amount owed, the court dismissed the collection lawsuit as moot.',
    relatedTerms: ['Standing', 'Ripeness', 'Justiciability', 'Declaratory Judgment'],
  },
  {
    term: 'Contempt of Court',
    definition: 'A willful disobedience of or disrespect toward a court order or the court\'s authority. Civil contempt is typically coercive—designed to compel compliance—while criminal contempt is punitive.',
    category: 'Litigation & Civil Procedure',
    example: 'The court held the witness in contempt of court and fined her $1,000 per day until she complied with the subpoena.',
    relatedTerms: ['Subpoena', 'Injunction', 'Order', 'Sanction'],
  },
  {
    term: 'Sanctions',
    definition: 'Penalties or disciplinary measures imposed by the court on a party or attorney for misconduct, such as filing frivolous claims, abusing discovery, or violating court orders. Sanctions can include fines, adverse inferences, or dismissal.',
    category: 'Litigation & Civil Procedure',
    example: 'The court imposed monetary sanctions on the defendant\'s counsel for repeatedly failing to produce documents ordered in discovery.',
    relatedTerms: ['Contempt of Court', 'Discovery', 'Motion', 'Frivolous Claim'],
  },
  {
    term: 'Bench Trial',
    definition: 'A trial in which a judge, rather than a jury, decides both factual and legal questions and renders the verdict. Parties may waive their right to a jury trial and elect a bench trial by agreement.',
    category: 'Litigation & Civil Procedure',
    example: 'Given the complex financial issues involved, the parties agreed to a bench trial and waived their right to a jury.',
    relatedTerms: ['Jury Instruction', 'Voir Dire', 'Verdict', 'Trial'],
  },
  {
    term: 'Pretrial Conference',
    definition: 'A meeting between the judge and the parties\' attorneys, held before trial, to narrow issues, establish schedules, explore settlement, and handle procedural matters. The resulting pretrial order controls the course of trial.',
    category: 'Litigation & Civil Procedure',
    example: 'At the final pretrial conference, the judge issued a scheduling order and ruled on pending motions in limine.',
    relatedTerms: ['Motion in Limine', 'Discovery', 'Settlement', 'Trial'],
  },
  {
    term: 'Motion in Limine',
    definition: 'A pretrial motion asking the court to exclude or admit specific evidence at trial. These motions prevent the jury from hearing potentially prejudicial or inadmissible evidence before the court has ruled on its admissibility.',
    category: 'Litigation & Civil Procedure',
    example: 'The plaintiff filed a motion in limine to exclude the defendant\'s prior arrest record as unfairly prejudicial.',
    relatedTerms: ['Pretrial Conference', 'Evidence', 'Admissibility', 'Trial'],
  },
  {
    term: 'Expert Witness',
    definition: 'A witness qualified by knowledge, skill, training, or experience to offer opinion testimony in a specialized field beyond the ken of lay jurors. The admissibility of expert testimony in federal court is governed by the Daubert standard.',
    category: 'Litigation & Civil Procedure',
    example: 'The plaintiff retained an orthopedic surgeon as an expert witness to testify that the injury was caused by the accident.',
    relatedTerms: ['Deposition', 'Motion in Limine', 'Daubert Standard', 'Discovery'],
  },
  {
    term: 'Consent Decree',
    definition: 'A negotiated agreement between parties that is entered as a court order and is enforceable as such. Consent decrees are common in civil rights, antitrust, and environmental cases, often requiring the defendant to take specific remedial steps.',
    category: 'Litigation & Civil Procedure',
    example: 'The city entered a consent decree requiring it to overhaul its use-of-force policies under federal court supervision.',
    relatedTerms: ['Settlement', 'Injunction', 'Judgment', 'Compliance'],
  },
  {
    term: 'Long-Arm Statute',
    definition: 'A state law that permits a state court to exercise personal jurisdiction over a non-resident defendant who has sufficient minimum contacts with the state, such as doing business or committing a tort within the state.',
    category: 'Litigation & Civil Procedure',
    example: 'Under the state\'s long-arm statute, the court asserted jurisdiction over the out-of-state company because it had solicited business and entered contracts in the forum state.',
    relatedTerms: ['Personal Jurisdiction', 'Service of Process', 'Venue', 'Minimum Contacts'],
  },
  {
    term: 'Diversity Jurisdiction',
    definition: 'Federal court subject-matter jurisdiction based on the parties being citizens of different states and the amount in controversy exceeding $75,000. Diversity jurisdiction allows federal courts to hear state-law disputes.',
    category: 'Litigation & Civil Procedure',
    example: 'Because the plaintiff was a Texas citizen, the defendant was a New York corporation, and damages exceeded $75,000, the case was filed in federal court under diversity jurisdiction.',
    relatedTerms: ['Subject-Matter Jurisdiction', 'Federal Question', 'Removal', 'Venue'],
  },
  {
    term: 'Removal',
    definition: 'The procedure by which a defendant transfers a case filed in state court to federal court. Removal is available when the federal court would have had original jurisdiction over the action.',
    category: 'Litigation & Civil Procedure',
    example: 'The defendant filed a notice of removal within 30 days of being served, transferring the case to the federal district court.',
    relatedTerms: ['Diversity Jurisdiction', 'Federal Question', 'Remand', 'Subject-Matter Jurisdiction'],
  },
  {
    term: 'Admissibility',
    definition: 'The quality of evidence that allows it to be received and considered by the trier of fact. Evidence must be relevant, and its probative value must outweigh any unfair prejudice, confusion, or waste of time.',
    category: 'Litigation & Civil Procedure',
    example: 'The judge ruled on the admissibility of the text messages, finding they were authentic and relevant to the central issue.',
    relatedTerms: ['Motion in Limine', 'Expert Witness', 'Hearsay', 'Relevance'],
  },
  {
    term: 'Hearsay',
    definition: 'An out-of-court statement offered in evidence to prove the truth of the matter asserted. Hearsay is generally inadmissible unless it falls within a recognized exception, such as excited utterance, business records, or an opposing party\'s admission.',
    category: 'Litigation & Civil Procedure',
    example: 'The witness was not allowed to testify about what she heard someone else say, because that testimony was excluded as hearsay.',
    relatedTerms: ['Admissibility', 'Evidence', 'Motion in Limine', 'Trial'],
  },
  {
    term: 'Continuance',
    definition: 'A court-ordered postponement of a scheduled hearing, trial, or other proceeding to a later date. Continuances may be granted by stipulation of the parties or by court order for good cause.',
    category: 'Litigation & Civil Procedure',
    example: 'Counsel requested a continuance of the trial date because a key expert witness was unavailable due to a medical emergency.',
    relatedTerms: ['Pretrial Conference', 'Motion', 'Scheduling Order', 'Trial'],
  },
];

export default terms;
