export const litigationTypes = [
  {
    name: 'Civil Rights Litigation',
    slug: 'civil-rights',
    category: 'Constitutional',
    description: 'Civil rights litigation encompasses lawsuits brought to remedy violations of constitutionally protected rights — including equal protection, due process, and First and Fourth Amendment guarantees — most often when those violations are committed by government actors. In the real world these disputes arise when a police officer uses excessive force against a citizen, when a public school system maintains racially discriminatory policies, or when a municipality retaliates against a resident for speaking at a city council meeting. The stakes are high on both sides: prevailing plaintiffs can obtain injunctions that reshape government institutions, compensatory and punitive damages, and attorney\'s fees under 42 U.S.C. § 1988. These cases matter because they serve as the primary mechanism by which the judiciary enforces constitutional limits on state power and vindicates the dignity of individuals harmed by government overreach.',
    purpose: 'To protect individuals from unlawful discrimination and vindicate fundamental constitutional rights through judicial process.',
    typicalIssues: ['Equal protection violations', 'Due process deprivation', 'First Amendment claims', 'Fourth Amendment search and seizure', 'Discriminatory government action'],
    commonEvidence: ['Government records and policies', 'Statistical evidence of disparate impact', 'Witness testimony', 'Electronic communications', 'Expert testimony on systemic discrimination'],
    courtProcess: 'Civil rights cases typically begin with filing in federal district court under 42 U.S.C. § 1983 or specific statutes. Discovery includes depositions of officials, document production, and expert reports. Cases often involve motions for summary judgment based on qualified immunity. Trial includes both fact and expert witnesses.',
    keyPrinciples: ['Section 1983 liability', 'Qualified immunity doctrine', 'Monell liability for municipalities', 'Deliberate indifference standard', 'Equal protection analysis'],
    practicalExamples: ['Police brutality and excessive force claims', 'Employment discrimination by government employers', 'School desegregation', 'Voting rights violations'],
    icon: 'Scale',
    color: '#1e3a5f',
    difficulty: 'Advanced',
    estimatedStudyHours: 15,
  },
  {
    name: 'Commercial Litigation',
    slug: 'commercial',
    category: 'Business',
    description: 'Commercial litigation is the body of adversarial proceedings that arise when business relationships fracture — covering everything from broken supply agreements and corporate governance disputes to allegations of fraud in mergers and acquisitions. In practice, a commercial case might involve a software company suing a former partner for misappropriating trade secrets, or shareholders suing directors for approving a sale at an inadequate price. Discovery in these matters is typically voluminous, with millions of pages of emails, financial records, and board minutes reviewed by teams of attorneys before a single deposition is taken. These disputes matter because commerce depends on enforceable promises, and the courts serve as the backstop that gives commercial actors confidence their agreements will be honored.',
    purpose: 'To resolve complex business disputes efficiently and enforce commercial agreements, protecting economic interests of parties.',
    typicalIssues: ['Breach of contract', 'Fraud and misrepresentation', 'Corporate governance disputes', 'Partnership dissolution', 'Non-compete enforcement'],
    commonEvidence: ['Contracts and amendments', 'Financial statements and records', 'Email correspondence', 'Board minutes and resolutions', 'Expert financial testimony'],
    courtProcess: 'Commercial cases often begin in state courts or federal courts with diversity jurisdiction. Extensive document discovery is typical. Many commercial contracts include arbitration clauses. Cases may involve temporary restraining orders or injunctions to preserve business status quo.',
    keyPrinciples: ['Contract formation and enforceability', 'Implied covenant of good faith', 'UCC Article 2 for goods', 'Statute of frauds', 'Mitigation of damages'],
    practicalExamples: ['Supply chain contract disputes', 'Shareholder derivative actions', 'M&A transaction disputes', 'Licensing agreement breaches'],
    icon: 'Briefcase',
    color: '#2d5a27',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Intellectual Property Litigation',
    slug: 'intellectual-property',
    category: 'IP',
    description: 'Intellectual property litigation protects the legally recognized exclusive rights that individuals and organizations hold over their inventions, creative works, brand identifiers, and confidential business information — rights embodied in patents, copyrights, trademarks, and trade-secret law. In the modern economy these disputes can reshape entire industries: the smartphone patent wars between Apple and Samsung generated billions of dollars in damages claims and courtroom battles on four continents, while pharmaceutical patent litigation determines when affordable generic drugs reach patients. A trade-secret case might hinge on whether a departing engineer emailed herself source code on her last day of work. These cases are consequential because they strike the balance between rewarding innovation through temporary exclusivity and ensuring that knowledge eventually enriches the public domain.',
    purpose: 'To protect innovation and creative works while balancing public access to knowledge and competition.',
    typicalIssues: ['Patent infringement', 'Copyright infringement', 'Trademark dilution', 'Trade secret misappropriation', 'DMCA violations'],
    commonEvidence: ['Patent claim charts', 'Prior art references', 'Technical expert testimony', 'Source code comparisons', 'Sales and market data for damages'],
    courtProcess: 'Patent cases must be filed in federal district court. A Markman hearing determines claim construction before trial. ITC proceedings available for import violations. Post-grant proceedings at USPTO (IPR, PGR) run parallel to litigation. Damages include lost profits and reasonable royalty.',
    keyPrinciples: ['Claim construction doctrine', 'Doctrine of equivalents', 'Fair use doctrine', 'Inevitable disclosure', 'TRIPS agreement compliance'],
    practicalExamples: ['Smartphone patent wars', 'Software copyright disputes', 'Brand infringement in e-commerce', 'Pharmaceutical patent challenges'],
    icon: 'Lightbulb',
    color: '#7b2d8b',
    difficulty: 'Expert',
    estimatedStudyHours: 25,
  },
  {
    name: 'Employment Litigation',
    slug: 'employment',
    category: 'Labor',
    description: 'Employment litigation encompasses the full range of legal disputes that arise out of the employment relationship, from individual claims of wrongful termination and sexual harassment to class actions alleging that an employer systematically underpaid thousands of workers. Consider a warehouse employee who is fired days after reporting a safety violation to OSHA: her retaliation claim will require her to show a causal link between protected activity and the adverse action, often through suspicious timing and shifting explanations from the employer. These disputes matter because work is the foundation of economic security for most people, and the threat of litigation creates powerful incentives for employers to adopt and actually enforce anti-discrimination policies, pay workers what they are owed, and maintain safe workplaces.',
    purpose: 'To enforce workplace rights, ensure fair treatment, and maintain a balance between employer prerogatives and employee protections.',
    typicalIssues: ['Discrimination based on protected characteristics', 'Sexual harassment', 'Wrongful termination', 'Wage and hour violations', 'FMLA retaliation'],
    commonEvidence: ['Personnel files and performance reviews', 'Employment contracts and handbooks', 'Email and communications', 'Comparator employee data', 'Payroll records'],
    courtProcess: 'Employment claims typically require EEOC charge filing before federal lawsuit. Cases involve extensive discovery of comparator employees. Class actions common in wage and hour cases. Mixed-motive cases analyze both legitimate and discriminatory reasons. Arbitration agreements may divert claims.',
    keyPrinciples: ['McDonnell Douglas burden-shifting', 'Pretext analysis', 'Hostile work environment standard', 'FLSA overtime requirements', 'At-will employment doctrine'],
    practicalExamples: ['Gender pay gap class actions', 'Age discrimination in tech industry', 'COVID-related termination disputes', 'Gig economy worker classification'],
    icon: 'Users',
    color: '#c47c2b',
    difficulty: 'Intermediate',
    estimatedStudyHours: 15,
  },
  {
    name: 'Environmental Litigation',
    slug: 'environmental',
    category: 'Regulatory',
    description: 'Environmental litigation uses the courts to enforce the web of statutes — the Clean Air Act, Clean Water Act, CERCLA, and dozens more — that govern how individuals, corporations, and governments may interact with the natural world. These cases range from a federal enforcement action against a factory illegally discharging mercury into a river, to a citizen suit seeking to force an agency to act on stalled regulations, to a toxic tort class action brought by a community downwind of a petrochemical plant. The Deepwater Horizon spill spawned litigation that took more than a decade to resolve, ultimately resulting in tens of billions of dollars in fines, penalties, and damages. Environmental cases matter because the harms at stake — contaminated water, degraded air, destroyed ecosystems — are often irreversible and fall disproportionately on communities least able to absorb them.',
    purpose: 'To enforce environmental laws, hold polluters accountable, and ensure sustainable use of natural resources for future generations.',
    typicalIssues: ['Clean Air Act violations', 'Clean Water Act compliance', 'CERCLA Superfund liability', 'NEPA environmental review', 'Toxic tort claims'],
    commonEvidence: ['Environmental sampling data', 'Agency records and permits', 'Expert toxicology testimony', 'Epidemiological studies', 'Corporate internal documents'],
    courtProcess: 'Environmental cases often involve both citizen suits and government enforcement. Agencies like EPA are often parties. Cases may be in federal or state court. Complex technical evidence requires specialized experts. Long discovery phases for scientific evidence. Class actions for affected communities.',
    keyPrinciples: ['Superfund joint and several liability', 'Chevron deference to agency expertise', 'National Environmental Policy Act review', 'Precautionary principle', 'Natural resource damages'],
    practicalExamples: ['Flint water crisis litigation', 'BP Deepwater Horizon claims', 'Climate change nuisance suits', 'PFAS contamination cases'],
    icon: 'Leaf',
    color: '#1a6b1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Class Action Litigation',
    slug: 'class-action',
    category: 'Procedural',
    description: 'Class action litigation is a procedural mechanism that allows one or a handful of named plaintiffs to sue on behalf of a much larger group of people who share common legal claims — transforming what would otherwise be thousands of uneconomic individual cases into a single, coordinated proceeding. Imagine that a bank quietly charged millions of customers an unauthorized monthly fee of $4.99: each individual harm is too small to justify hiring a lawyer, but consolidated into a class action the aggregate damages may run into hundreds of millions of dollars. Class certification is the pivotal battleground, because a certified class dramatically increases a defendant\'s exposure and leverage shifts sharply toward plaintiffs. These cases matter because they are often the only realistic mechanism for delivering compensation to consumers, employees, and investors harmed at scale by corporate misconduct.',
    purpose: 'To provide efficient resolution of numerous similar claims, deter widespread wrongdoing, and provide access to justice for individuals with small damages.',
    typicalIssues: ['Rule 23 certification requirements', 'Adequacy of class counsel', 'Predominance of common questions', 'Class notice and opt-out rights', 'Settlement approval'],
    commonEvidence: ['Class-wide statistical evidence', 'Corporate policy documents', 'Common form contracts', 'Aggregate damages models', 'Named plaintiff testimony'],
    courtProcess: 'Class certification is the pivotal early motion. Classes may be certified for liability only, with damages individualized. CAFA expanded federal jurisdiction. Settlement requires court approval and fairness hearing. Objectors have right to contest settlements.',
    keyPrinciples: ['Numerosity, commonality, typicality, adequacy', 'Predominance requirement', 'Superiority requirement', 'Daubert standard for class experts', 'Ascertainability requirement'],
    practicalExamples: ['Consumer product defect class actions', 'Data breach class suits', 'Securities fraud class actions', 'Wage theft class cases'],
    icon: 'Group',
    color: '#8b4513',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Criminal Defense Litigation',
    slug: 'criminal-defense',
    category: 'Criminal',
    description: 'Criminal defense litigation pits an individual accused of a crime against the full investigative and prosecutorial power of the state, and its defining principle is that every person is presumed innocent until proven guilty beyond a reasonable doubt by a unanimous jury. The defense attorney\'s role spans the entire arc of the case: challenging the lawfulness of a traffic stop that led to a drug arrest, cross-examining eyewitnesses whose identifications are notoriously unreliable, moving to suppress a confession obtained without Miranda warnings, and advocating for a proportionate sentence if conviction follows. These cases matter profoundly because the consequences — loss of liberty, employment, family, and civil rights — are irreversible, and history is filled with wrongful convictions that underscore how vigilant defense representation serves as a necessary check on prosecutorial overreach.',
    purpose: 'To ensure fair treatment, prevent wrongful convictions, and uphold constitutional protections for all accused persons.',
    typicalIssues: ['Fourth Amendment suppression motions', 'Fifth Amendment self-incrimination', 'Sixth Amendment right to counsel', 'Brady material disclosure', 'Ineffective assistance of counsel'],
    commonEvidence: ['Physical evidence chain of custody', 'Witness credibility challenges', 'Forensic expert testimony', 'Law enforcement misconduct records', 'Alibi evidence'],
    courtProcess: 'Criminal cases follow strict constitutional procedural protections. Arraignment, preliminary hearing, grand jury, discovery under Brady. Suppression hearings before trial. Jury selection (voir dire) crucial. Beyond reasonable doubt standard. Post-conviction remedies including habeas corpus.',
    keyPrinciples: ['Presumption of innocence', 'Beyond reasonable doubt standard', 'Exclusionary rule', 'Right to confrontation', 'Double jeopardy prohibition'],
    practicalExamples: ['White collar crime defense', 'Drug trafficking cases', 'Cybercrime prosecutions', 'Police misconduct defenses'],
    icon: 'Shield',
    color: '#4a1a1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Securities Litigation',
    slug: 'securities',
    category: 'Financial',
    description: 'Securities litigation addresses fraud, manipulation, and regulatory violations in the capital markets — the arenas where companies raise money from the public and investors trade stocks, bonds, and derivatives. A classic securities fraud case involves corporate officers who knew their flagship drug was about to fail a clinical trial but continued to tout its prospects publicly, artificially inflating the stock price until the truth emerged and shareholders suffered massive losses. Under the fraud-on-the-market theory, every investor who bought shares during the inflationary period is presumed to have relied on the integrity of market prices, enabling large class actions. These cases matter because investor confidence in honest disclosure is the foundation of functioning capital markets, and accountability for securities fraud directly protects the retirement savings and economic security of millions of ordinary investors.',
    purpose: 'To maintain investor confidence, ensure market integrity, and hold corporations and executives accountable for securities law violations.',
    typicalIssues: ['Rule 10b-5 fraud', 'Section 11 and 12 liability', 'Insider trading', 'RICO claims', 'Proxy fraud'],
    commonEvidence: ['Trading records and patterns', 'Corporate disclosures and filings', 'Internal emails and memos', 'Expert testimony on materiality', 'Event study analysis'],
    courtProcess: 'Securities class actions governed by PSLRA. Lead plaintiff appointed early. Scienter pleading requirements are stringent. Loss causation and damages are contested issues. SEC parallel investigations common. FINRA arbitration for broker-dealer disputes.',
    keyPrinciples: ['Fraud on the market theory', 'Materiality standard', 'Scienter requirement', 'Loss causation requirement', 'Bespeaks caution doctrine'],
    practicalExamples: ['Enron and WorldCom fraud', 'Options backdating scandals', 'SPACs and disclosure failures', 'Meme stock market manipulation'],
    icon: 'TrendingUp',
    color: '#1a3a5f',
    difficulty: 'Expert',
    estimatedStudyHours: 25,
  },
  {
    name: 'Antitrust Litigation',
    slug: 'antitrust',
    category: 'Regulatory',
    description: 'Antitrust litigation enforces the laws — principally the Sherman Act and the Clayton Act — that prohibit businesses from conspiring to fix prices, dividing markets among competitors, or using monopoly power to crush rivals and exploit consumers. The most vivid illustration is a price-fixing cartel: when executives from competing airlines secretly agree on fuel surcharge amounts, they effectively rob every business traveler and every family on vacation. Government enforcers can prosecute criminally and seek fines and imprisonment, while private plaintiffs can sue for treble damages. In the modern economy, antitrust litigation has expanded to challenge the gatekeeper power of digital platforms, with ongoing cases asking whether dominant search engines and app stores illegally exclude competitors and overcharge users.',
    purpose: 'To preserve competition, protect consumers from monopolistic pricing, and maintain free market dynamics.',
    typicalIssues: ['Horizontal price-fixing conspiracies', 'Monopolization and attempted monopolization', 'Predatory pricing', 'Exclusive dealing agreements', 'Merger challenges'],
    commonEvidence: ['Market share data and analysis', 'Internal pricing communications', 'Economic expert testimony', 'Consumer harm analysis', 'Econometric modeling'],
    courtProcess: 'DOJ and FTC lead government enforcement. Private plaintiffs can sue for treble damages. Market definition is a critical contested issue. Expert economists central to both sides. Discovery of confidential business data. Consent decrees as alternative to trial.',
    keyPrinciples: ['Rule of reason vs. per se analysis', 'Relevant market definition', 'Lerner index and HHI', 'Essential facilities doctrine', 'Chicago School vs. Neo-Brandeis approaches'],
    practicalExamples: ['Big Tech antitrust investigations', 'Pharmaceutical price-fixing', 'Airline hub monopoly cases', 'Hospital merger challenges'],
    icon: 'BarChart',
    color: '#2c1a5f',
    difficulty: 'Expert',
    estimatedStudyHours: 25,
  },
  {
    name: 'Constitutional Litigation',
    slug: 'constitutional',
    category: 'Constitutional',
    description: 'Constitutional litigation tests whether a law enacted by a legislature or an action taken by an executive branch official is permitted by the Constitution — the supreme law that defines and limits the powers of government in the United States. When a state bans certain categories of speech or requires religious organizations to fund activities that violate their beliefs, those affected may sue to have the law declared unconstitutional and enjoined. The outcome of a single constitutional case can immediately nullify legislation in every state, affect the lives of millions of people, and reshape the relationship between citizens and their government for generations. These cases are uniquely significant because they operate not just as remedies for individual grievances but as authoritative statements about the meaning of the foundational document that governs American public life.',
    purpose: 'To enforce constitutional limitations on government power and protect fundamental rights against overreach.',
    typicalIssues: ['First Amendment free speech', 'Second Amendment gun rights', 'Due process challenges', 'Commerce Clause limitations', 'Separation of powers'],
    commonEvidence: ['Legislative history', 'Government administrative records', 'Expert constitutional scholars', 'Statistical evidence of impact', 'Comparative constitutional analysis'],
    courtProcess: 'Constitutional cases often begin in federal district courts with 3-judge panels for certain claims. Expedited appeals available. Cert petitions to Supreme Court. Amicus briefs play large role. Facial vs. as-applied challenges. Preliminary injunctions while appeal pending.',
    keyPrinciples: ['Strict scrutiny test', 'Intermediate scrutiny', 'Rational basis review', 'Overbreadth doctrine', 'Vagueness doctrine'],
    practicalExamples: ['Voting rights challenges', 'Religious freedom cases', 'Executive order challenges', 'State marijuana law preemption'],
    icon: 'BookOpen',
    color: '#5f1a1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Tort Litigation',
    slug: 'tort',
    category: 'Civil',
    description: 'Tort litigation is the legal system\'s mechanism for compensating people who have been harmed by the wrongful acts of others, whether through careless conduct (negligence), intentional wrongdoing, or activities so dangerous that liability attaches regardless of fault (strict liability). A driver who runs a red light and injures a pedestrian, a surgeon who operates on the wrong limb, a manufacturer who sells a crib whose slats are dangerously spaced — each has committed a tort, and each may face civil liability to the injured party. The injured plaintiff must prove that the defendant owed a duty, breached it, caused the harm, and that the harm is quantifiable in monetary terms. Tort law matters because it both compensates victims and sends price signals to potential wrongdoers: when negligence is expensive, rational actors invest in safety.',
    purpose: 'To compensate injured parties and deter wrongful conduct through civil liability.',
    typicalIssues: ['Negligence and duty of care', 'Causation (actual and proximate)', 'Damages calculation', 'Comparative fault', 'Statute of limitations'],
    commonEvidence: ['Medical records and bills', 'Accident reconstruction reports', 'Expert testimony on causation', 'Economic loss calculations', 'Photographs and video evidence'],
    courtProcess: 'State court jurisdiction typically. Demand letters before filing. Discovery of medical records and accident details. Expert depositions critical. Mediation often required. Jury trial for damages. Post-verdict motions for judgment notwithstanding verdict.',
    keyPrinciples: ['Duty, breach, causation, damages', 'Reasonable person standard', 'Foreseeability requirement', 'Res ipsa loquitur', 'Assumption of risk'],
    practicalExamples: ['Medical malpractice cases', 'Product liability suits', 'Slip and fall claims', 'Automotive accident litigation'],
    icon: 'AlertTriangle',
    color: '#8b1a1a',
    difficulty: 'Beginner',
    estimatedStudyHours: 10,
  },
  {
    name: 'Real Estate Litigation',
    slug: 'real-estate',
    category: 'Property',
    description: 'Real estate litigation encompasses the disputes that arise whenever interests in land, buildings, or the agreements surrounding them are contested — from a buyer who discovers the seller concealed a crumbling foundation, to neighbors warring over a fence that encroaches six inches into an adjoining lot, to a commercial tenant locked out of its space by a landlord claiming rent default. Property rights are among the oldest and most intensely contested interests in law because land is finite, permanent, and often represents the most significant asset an individual or business owns. Title insurance, survey records, and chains of deeds stretching back decades all become crucial exhibits in these disputes, and courts must sometimes untangle conflicting property interests created by instruments drafted generations ago.',
    purpose: 'To resolve property ownership disputes and enforce real estate transaction obligations.',
    typicalIssues: ['Title disputes', 'Breach of purchase agreements', 'Landlord-tenant evictions', 'Construction defects', 'Easement and boundary disputes'],
    commonEvidence: ['Deeds and title records', 'Survey maps', 'Construction plans and reports', 'Inspection reports', 'Lease agreements'],
    courtProcess: 'State court proceedings. Lis pendens filed to cloud title during litigation. Quiet title actions. Unlawful detainer procedures for evictions. Construction defect cases require expert contractors. CERCLA issues for contaminated properties.',
    keyPrinciples: ['Covenant of quiet enjoyment', 'Implied warranty of habitability', 'Recording acts priority', 'Adverse possession elements', 'Specific performance remedy'],
    practicalExamples: ['Commercial lease disputes', 'HOA enforcement actions', 'Eminent domain challenges', 'Real estate fraud cases'],
    icon: 'Home',
    color: '#5f3a1a',
    difficulty: 'Intermediate',
    estimatedStudyHours: 12,
  },
  {
    name: 'Family Law Litigation',
    slug: 'family-law',
    category: 'Personal',
    description: 'Family law litigation addresses the most personal and emotionally charged disputes that courts encounter — the dissolution of marriages, the allocation of parental rights over children, the enforcement of support obligations, and the protection of family members from domestic violence. Unlike purely commercial disputes, family cases require judges to make forward-looking determinations about what will serve a child\'s best interests over years and decades, often in the face of bitter parental conflict and competing expert opinions from psychologists, social workers, and custody evaluators. A high-asset divorce might require forensic accountants to trace hidden offshore funds, while a custody dispute might turn on which parent has been the primary caregiver in the child\'s daily life. These cases matter because their outcomes shape the formative years of children and the long-term financial security of families.',
    purpose: 'To resolve family disputes with focus on child welfare and equitable distribution of marital assets.',
    typicalIssues: ['Child custody and visitation', 'Property division', 'Alimony and spousal support', 'Child support enforcement', 'Domestic violence protective orders'],
    commonEvidence: ['Financial disclosure statements', 'Tax returns', 'Custody evaluations', 'Parenting plans', 'School and medical records'],
    courtProcess: 'Family courts have specialized procedures. Mandatory disclosures of finances. Guardian ad litem for children. Psychological evaluations ordered. Mediation often required. Modified res judicata for ongoing issues. Interstate custody under UCCJEA.',
    keyPrinciples: ['Best interests of the child standard', 'Equitable distribution vs. community property', 'Nexus between conduct and property division', 'Parental alienation considerations', 'Support modification standards'],
    practicalExamples: ['High-asset divorce cases', 'International child abduction', 'Same-sex couple rights', 'Grandparent visitation rights'],
    icon: 'Heart',
    color: '#8b1a5f',
    difficulty: 'Intermediate',
    estimatedStudyHours: 12,
  },
  {
    name: 'Bankruptcy Litigation',
    slug: 'bankruptcy',
    category: 'Financial',
    description: 'Bankruptcy litigation takes place in the specialized federal court system established by the Bankruptcy Code and governs the legal process by which individuals and businesses that cannot pay their debts seek an orderly resolution — either a fresh start through liquidation or a restructured repayment plan that lets a viable enterprise survive. When a retailer files for Chapter 11 protection, the automatic stay instantly halts all creditor collection actions, including lawsuits, foreclosures, and repossessions, creating a breathing period during which the debtor negotiates a plan of reorganization with secured lenders, unsecured creditors, and equity holders. Within that framework, adversary proceedings litigate specific disputes: whether a payment made to a favored creditor ninety days before filing can be "avoided" and recovered for the estate, or whether a particular debt — like one arising from fraud — can survive the debtor\'s discharge. Bankruptcy law matters because it allows productive economic activity to resume after financial failure while distributing losses among creditors in a legally predictable priority order.',
    purpose: 'To provide debtors relief from unmanageable debt while ensuring fair treatment of creditors.',
    typicalIssues: ['Preference and fraudulent transfer avoidance', 'Plan confirmation disputes', 'Automatic stay violations', 'Claims allowance', 'Discharge exceptions'],
    commonEvidence: ['Financial statements and projections', 'Transfer records', 'Creditor claims', 'Valuation reports', 'Business plans'],
    courtProcess: 'Federal Bankruptcy Court exclusive jurisdiction. Automatic stay immediately upon filing. Adversary proceedings for contested matters. Plan of reorganization for Chapter 11. Trustee appointed in Chapter 7. Multiple committee representation in large cases.',
    keyPrinciples: ['Automatic stay protection', 'Absolute priority rule', 'Preference period lookback', 'Section 363 sales', 'Discharge injunction'],
    practicalExamples: ['Chapter 11 corporate reorganizations', 'Mass tort bankruptcies', 'Municipal bankruptcies', 'Individual Chapter 13 cases'],
    icon: 'DollarSign',
    color: '#1a5f3a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Immigration Litigation',
    slug: 'immigration',
    category: 'Administrative',
    description: 'Immigration litigation encompasses the legal proceedings in which non-citizens contest government decisions about their right to enter, remain in, or become citizens of the United States — proceedings that can determine whether a person is separated from their family, returned to a country where they fear persecution, or permitted to build a life in the country they have called home for years. A Salvadoran mother who fled gang violence and filed for asylum must prove before an immigration judge that she faces persecution on account of a legally recognized ground — such as membership in a particular social group — a standard whose application has generated enormous litigation in the circuit courts. Because the consequences of losing are deportation, immigration cases carry profound human stakes even when they hinge on technical procedural requirements like the one-year asylum filing deadline. These cases collectively shape the composition and character of American society.',
    purpose: 'To enforce immigration laws while protecting due process rights of non-citizens seeking entry or residency.',
    typicalIssues: ['Removal and deportation proceedings', 'Asylum and refugee claims', 'Visa denials', 'Naturalization denials', 'Detention challenges'],
    commonEvidence: ['Country condition reports', 'Personal declarations', 'Police and court records from home country', 'Medical evidence of torture', 'Expert testimony on country conditions'],
    courtProcess: 'Immigration courts within DOJ. BIA appeals. Federal circuit court review. Habeas corpus for detention. Class actions challenging policies. Asylum affirmative and defensive processes. One-year filing deadline for asylum.',
    keyPrinciples: ['Nexus to protected ground', 'Particular social group definition', 'Firm resettlement bar', 'Aggravated felony deportation', 'Convention Against Torture protection'],
    practicalExamples: ['Gang violence asylum claims', 'DACA litigation', 'Travel ban challenges', 'Family separation cases'],
    icon: 'Globe',
    color: '#1a3a8b',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'Healthcare Litigation',
    slug: 'healthcare',
    category: 'Regulatory',
    description: 'Healthcare litigation spans the full spectrum of legal disputes that arise from the delivery, financing, and regulation of medical services — from a patient who suffered a preventable surgical complication and sues for malpractice, to a whistleblower who alerts the government that a hospital chain has been systematically upcoding Medicare claims for years. In a medical malpractice case, the central question is whether the treating physician\'s conduct fell below the standard of care that a reasonably competent specialist would have applied under similar circumstances, a determination that requires battle-tested medical experts on both sides. Healthcare fraud cases under the False Claims Act can result in enormous government recoveries and life-altering qui tam bounties for the whistleblowers who report them. These cases matter because both patient safety and the fiscal integrity of public health programs depend on legal accountability.',
    purpose: 'To ensure quality healthcare delivery, compensate patients harmed by negligence, and combat healthcare fraud.',
    typicalIssues: ['Medical malpractice standard of care', 'Hospital liability', 'Informed consent violations', 'HIPAA breaches', 'False Claims Act violations'],
    commonEvidence: ['Medical records and charts', 'Expert medical testimony', 'Clinical guidelines and protocols', 'Billing records', 'FDA approval documentation'],
    courtProcess: 'Certificate of merit requirements in many states. Medical review panels. Expert discovery extensive. Daubert challenges to medical experts. caps on damages in some states. Government qui tam cases for Medicare/Medicaid fraud. HIPAA enforcement by HHS.',
    keyPrinciples: ['Standard of care analysis', 'Causation in medical cases', 'Informed consent doctrine', 'Respondeat superior for hospitals', 'FCA False Claims standards'],
    practicalExamples: ['Surgical error malpractice', 'Pharmaceutical fraud cases', 'Nursing home abuse litigation', 'COVID-19 liability cases'],
    icon: 'Heart',
    color: '#8b1a3a',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'Insurance Litigation',
    slug: 'insurance',
    category: 'Business',
    description: 'Insurance litigation arises when policyholders and insurance companies disagree about whether a claim is covered, how much should be paid, or whether the insurer has handled the claim in good faith — disputes that can arise after a hurricane destroys a home, a data breach triggers a cyber policy, or a company faces a lawsuit that its directors-and-officers policy should defend. Insurance policies are contracts of adhesion drafted entirely by the insurer, and courts in most jurisdictions resolve ambiguities against the insurer and in favor of coverage under the reasonable expectations doctrine. The bad faith tort is a powerful remedy: when an insurer unreasonably denies a valid claim or drags out payment to gain leverage, the policyholder may recover not just the policy benefits but also consequential damages, attorney\'s fees, and in egregious cases punitive damages. These disputes matter because insurance is the mechanism by which individuals and businesses transfer catastrophic risk, and the value of that transfer depends entirely on whether the insurer honors its promise.',
    purpose: 'To ensure policyholders receive contracted benefits and insurers act in good faith.',
    typicalIssues: ['Coverage disputes', 'Bad faith claims handling', 'Subrogation rights', 'Rescission for misrepresentation', 'Excess judgment claims'],
    commonEvidence: ['Insurance policies and endorsements', 'Claims files', 'Underwriting records', 'Expert coverage opinions', 'Claim investigation records'],
    courtProcess: 'State insurance law governs. Declaratory judgment actions for coverage. Bad faith allows extra-contractual damages. Stacking of policies. Third-party bad faith claims. Assignment of bad faith claims. Interpleader for competing claimants.',
    keyPrinciples: ['Duty to defend vs. indemnify', 'Bad faith standard', 'Reasonable expectations doctrine', 'Efficient proximate cause', 'Reservation of rights'],
    practicalExamples: ['Hurricane property damage disputes', 'Directors and officers liability', 'Cyber insurance claims', 'Business interruption COVID claims'],
    icon: 'Shield',
    color: '#3a5f1a',
    difficulty: 'Intermediate',
    estimatedStudyHours: 12,
  },
  {
    name: 'Products Liability',
    slug: 'products-liability',
    category: 'Civil',
    description: 'Products liability law holds manufacturers, distributors, and retailers legally responsible when a defective product causes injury or death — a doctrine that transformed American industry by requiring companies to internalize the safety costs of the goods they bring to market. A defect can arise in three ways: a flaw introduced during the manufacturing process (only one item in a batch is defective), a design that is inherently unsafe as conceived (the entire product line poses the same risk), or a failure to provide adequate warnings about known dangers. The litigation over recalled vehicles whose accelerators stuck, pharmaceutical drugs that caused birth defects, and medical implants that failed prematurely has shaped product design, testing protocols, and warning-label practices across entire industries. These cases matter because they create financial accountability for the harms that mass-produced products can inflict at scale on consumers who have no practical ability to inspect or evaluate those products before purchase.',
    purpose: 'To protect consumers from dangerous products and provide manufacturers incentives to ensure product safety.',
    typicalIssues: ['Manufacturing defects', 'Design defects', 'Failure to warn', 'Strict liability vs. negligence', 'Consumer expectations test'],
    commonEvidence: ['Product design documents', 'Manufacturing quality records', 'Similar incident reports', 'Expert engineering testimony', 'Internal risk assessments'],
    courtProcess: 'State court with multi-state complex litigation consolidation. MDL for federal cases. Rigorous Daubert challenges to causation experts. Punitive damages claims require willfulness. Market share liability where manufacturer unknown. Successor liability for acquired companies.',
    keyPrinciples: ['Restatement (Third) of Torts products', 'Risk-utility balancing', 'Consumer expectations test', 'Learned intermediary doctrine', 'Component parts doctrine'],
    practicalExamples: ['Automotive defect recalls', 'Pharmaceutical MDL litigation', 'Medical device defects', 'Tobacco litigation'],
    icon: 'Package',
    color: '#5f1a3a',
    difficulty: 'Intermediate',
    estimatedStudyHours: 15,
  },
  {
    name: 'Administrative Law Litigation',
    slug: 'administrative-law',
    category: 'Administrative',
    description: 'Administrative law litigation challenges the rules, orders, and decisions issued by the vast apparatus of federal and state agencies — the EPA, FDA, FCC, CFPB, and hundreds of others — that regulate nearly every aspect of modern life from the safety of prescription drugs to the rates charged by electric utilities. When an agency issues a new rule restricting carbon emissions from power plants, affected industries may challenge it in federal court by arguing that the agency exceeded its statutory authority, failed to follow required notice-and-comment procedures, or reached a conclusion so unsupported by the record that it is arbitrary and capricious. The 2024 Supreme Court decision in Loper Bright Enterprises overruled the longstanding Chevron doctrine, fundamentally shifting judicial deference away from agencies and toward courts on questions of statutory interpretation. These cases matter because they determine how much discretion unelected administrators have to set national policy on issues ranging from financial regulation to workplace safety.',
    purpose: 'To ensure agencies act within their statutory authority and follow required procedures.',
    typicalIssues: ['Arbitrary and capricious review', 'Chevron deference challenges', 'Procedural APA violations', 'Agency statutory authority', 'Constitutional delegation'],
    commonEvidence: ['Agency administrative record', 'Rulemaking comments', 'Agency expert reports', 'Cost-benefit analyses', 'Congressional history'],
    courtProcess: 'Federal court review of agency action under APA. Exhaustion of administrative remedies required. Review on administrative record. Highly deferential Chevron standard now challenged. Loper Bright decision limiting Chevron. Vacatur vs. remand without vacatur.',
    keyPrinciples: ['Arbitrary and capricious standard', 'Chevron two-step (historical)', 'Major questions doctrine', 'Nondelegation doctrine', 'Standing for regulated entities'],
    practicalExamples: ['EPA climate regulations', 'FDA drug approval challenges', 'FCC telecommunications rules', 'CFPB financial regulations'],
    icon: 'Building',
    color: '#3a1a5f',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'Construction Litigation',
    slug: 'construction',
    category: 'Business',
    description: 'Construction litigation resolves the disputes that are almost inevitable in large, complex building projects where the owner, general contractor, dozens of subcontractors, and design professionals must coordinate over months or years under contracts negotiated long before conditions on the ground are fully known. A multi-year hospital construction project might generate claims from the general contractor for extended overhead costs caused by the owner\'s design changes, cross-claims from subcontractors who were delayed by the general contractor\'s scheduling failures, and a separate professional liability suit against the architect whose drawings contained coordination errors. Mechanics\' lien rights add another layer of complexity, allowing unpaid subcontractors and suppliers to encumber the owner\'s property even if they have no direct contract with the owner. These cases matter because construction drives a massive share of economic activity, and the financial consequences of project failures ripple through multiple tiers of the industry.',
    purpose: 'To resolve complex multi-party construction disputes and enforce construction contracts.',
    typicalIssues: ['Construction defects', 'Delay and disruption claims', 'Change order disputes', 'Payment bond claims', 'Design professional liability'],
    commonEvidence: ['Construction contracts and drawings', 'Change order logs', 'Daily reports and schedules', 'Expert engineering testimony', 'Cost accounting records'],
    courtProcess: 'Multi-party litigation involving owners, contractors, subcontractors, designers. Statutory lien rights. Surety bond claims. Arbitration common in AIA contracts. Expert testimony on standard of care. Delay damages calculation complex.',
    keyPrinciples: ['No damages for delay clauses', 'Concurrent delay analysis', 'Substantial completion doctrine', 'Spearin doctrine (design warranty)', 'Mechanic\'s lien priority'],
    practicalExamples: ['Skyscraper construction disputes', 'Public infrastructure claims', 'Residential construction defects', 'Green building specification disputes'],
    icon: 'Building2',
    color: '#5f3a1a',
    difficulty: 'Intermediate',
    estimatedStudyHours: 15,
  },
  {
    name: 'International Arbitration',
    slug: 'international-arbitration',
    category: 'International',
    description: 'International arbitration provides a neutral, enforceable forum for resolving cross-border commercial and investment disputes outside the domestic court systems of any single country — an essential mechanism in a global economy where a party from Brazil may have contracted with a company from Germany to supply equipment manufactured in South Korea, and no party wants to litigate in the courts of the other\'s home jurisdiction. A claimant in investor-state arbitration under a bilateral investment treaty might argue that the host government\'s sudden regulatory reversal effectively expropriated its multi-billion-dollar mining investment without compensation. Arbitral awards rendered under the ICSID Convention or New York Convention can be enforced in over 160 countries, giving them a global reach that no domestic court judgment can match. These proceedings matter because they underpin the legal infrastructure of international trade and investment, and the quality of that infrastructure directly affects whether capital flows to developing economies.',
    purpose: 'To provide neutral, enforceable resolution of international disputes outside domestic court systems.',
    typicalIssues: ['Arbitration clause interpretation', 'Jurisdictional challenges', 'Choice of law', 'Recognition and enforcement', 'Investment treaty claims'],
    commonEvidence: ['International contracts', 'Corporate structure evidence', 'Economic damages analysis', 'Industry custom and usage', 'Expert country law reports'],
    courtProcess: 'ICC, ICSID, LCIA, AAA/ICDR rules. Seat of arbitration determines court support. Interim measures possible. Document production under IBA rules. Enforcement under New York Convention. Investment arbitration under BITs and ICSID.',
    keyPrinciples: ['Kompetenz-Kompetenz principle', 'Separability doctrine', 'New York Convention enforcement', 'Most favored nation in investment', 'Margin of appreciation'],
    practicalExamples: ['Oil and gas investment disputes', 'Pharmaceutical patent arbitration', 'Sports federation disputes', 'State contract claims'],
    icon: 'Globe',
    color: '#1a5f5f',
    difficulty: 'Expert',
    estimatedStudyHours: 25,
  },
  {
    name: 'Privacy and Data Litigation',
    slug: 'privacy-data',
    category: 'Technology',
    description: 'Privacy and data litigation addresses the legal consequences when organizations collect, use, or fail to protect personal information in ways that violate statutes, regulations, or the reasonable expectations of the individuals whose data is at stake. A data breach exposing the Social Security numbers and financial records of 150 million people — like the 2017 Equifax hack — triggers class actions in multiple jurisdictions, regulatory investigations by the FTC and state attorneys general, and complex questions about whether the affected individuals have suffered a legally cognizable injury even if they have not yet been victimized by identity theft. The Illinois Biometric Information Privacy Act has generated thousands of lawsuits over companies\' use of facial-recognition technology without obtaining informed written consent, demonstrating how statutory damages can create massive liability for common practices. These cases matter because they are the primary legal mechanism shaping the norms around data collection and security in an economy that runs on personal information.',
    purpose: 'To protect individual privacy rights and hold organizations accountable for data security failures.',
    typicalIssues: ['Data breach notification violations', 'CCPA and GDPR compliance', 'Biometric data collection', 'Section 230 immunity', 'Electronic surveillance'],
    commonEvidence: ['System logs and forensic analysis', 'Privacy policies and disclosures', 'Data flow documentation', 'Security audit reports', 'Expert cybersecurity testimony'],
    courtProcess: 'Article III standing for data breach cases contested. State AG enforcement actions. FTC enforcement authority. Class actions for statutory damages. GDPR enforcement by data protection authorities. Cy pres settlements for small damages.',
    keyPrinciples: ['Concrete injury requirement', 'Contextual integrity', 'Privacy by design', 'Proportionality in data processing', 'Right to be forgotten'],
    practicalExamples: ['Equifax breach litigation', 'Facebook Cambridge Analytica', 'Illinois BIPA biometric cases', 'TikTok data transfer cases'],
    icon: 'Lock',
    color: '#1a1a5f',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Government Contracts Litigation',
    slug: 'government-contracts',
    category: 'Administrative',
    description: 'Government contracts litigation encompasses the disputes that arise when private companies and the federal government disagree about the procurement, performance, pricing, or termination of contracts covering everything from fighter jets and satellite systems to information technology infrastructure and janitorial services. Because the federal government is the single largest buyer of goods and services in the world, the rules governing these contracts — the Federal Acquisition Regulation, the Competition in Contracting Act, the Contract Disputes Act — constitute a specialized body of law administered by specialized tribunals. A disappointed bidder who believes an agency improperly awarded a multibillion-dollar cloud computing contract may protest to the Government Accountability Office and obtain a detailed written opinion within 100 days. These cases matter because public procurement decisions affect both taxpayer value and the viability of the companies, large and small, whose business models depend on government work.',
    purpose: 'To provide contractors fair access to government markets and ensure taxpayer money is properly spent.',
    typicalIssues: ['Bid protest proceedings', 'Contract termination claims', 'Equitable adjustment claims', 'Defective pricing claims', 'Small business set-aside violations'],
    commonEvidence: ['Solicitation documents', 'Proposal and evaluation records', 'Cost accounting records', 'CAS compliance documents', 'Technical evaluation reports'],
    courtProcess: 'GAO bid protests. Court of Federal Claims jurisdiction. ASBCA for defense contracts. Armed Services Contract Adjustment Board. CDA claim certification requirements. Six-year statute of limitations. Strict standing requirements.',
    keyPrinciples: ['Competition in Contracting Act', 'Truth in Negotiations Act (TINA)', 'Christian doctrine', 'Cardinal change doctrine', 'Actual knowledge test for implied duty'],
    practicalExamples: ['Defense IT system protests', 'COVID contract claims', 'International arms contracts', 'Space program procurement disputes'],
    icon: 'Flag',
    color: '#1a4a1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'Mass Tort Litigation',
    slug: 'mass-tort',
    category: 'Civil',
    description: 'Mass tort litigation arises when a single product, substance, or event injures thousands or even hundreds of thousands of people in similar ways — think asbestos insulation that caused mesothelioma in shipyard workers across the country, or an opioid painkiller aggressively marketed to physicians while concealing its addictive potential. Unlike a class action, mass tort cases preserve individual causation and damages questions because each plaintiff\'s exposure history and medical circumstances differ; instead, they are coordinated for efficiency through multidistrict litigation where common issues of law, general causation, and corporate conduct are litigated jointly. A bellwether trial — a handful of representative cases tried before the MDL judge — gives both sides a realistic benchmark for settlement and shapes the resolution of the broader inventory of tens of thousands of claims. These cases are consequential because they represent the legal system\'s primary mechanism for achieving accountability when corporate misconduct causes diffuse, widespread harm.',
    purpose: 'To efficiently resolve widespread harm caused by a single tortfeasor through consolidated proceedings.',
    typicalIssues: ['General and specific causation', 'MDL management', 'Bellwether trial selection', 'Aggregate settlement allocation', 'Future claimants trust'],
    commonEvidence: ['Epidemiological studies', 'Internal corporate documents on known risks', 'Individual plaintiff medical records', 'Regulatory submissions', 'Marketing materials'],
    courtProcess: 'MDL consolidation in federal court. Bellwether trials to assess verdict range. PSC (Plaintiffs Steering Committee) structure. Common benefit fee allocation. Section 524(g) bankruptcy trusts for asbestos. Cy pres and fluid recovery.',
    keyPrinciples: ['Daubert gatekeeping for mass tort experts', 'Specific causation requirements', 'Learned intermediary defense', 'Punitive damages as ratio of compensatory', 'Statutes of limitations discovery rule'],
    practicalExamples: ['Opioid epidemic litigation', 'Asbestos mesothelioma claims', 'Roundup herbicide cases', '3M earplug MDL'],
    icon: 'Users',
    color: '#5f1a1a',
    difficulty: 'Expert',
    estimatedStudyHours: 25,
  },
  {
    name: 'White Collar Crime Defense',
    slug: 'white-collar-crime',
    category: 'Criminal',
    description: 'White collar crime defense addresses the representation of individuals and corporations targeted by federal and state prosecutors for financial crimes — fraud, bribery, money laundering, insider trading, tax evasion, and violations of specialized statutes like the Foreign Corrupt Practices Act — crimes defined not by violence but by deceit, breach of trust, and the abuse of professional or organizational position. A government investigation typically unfolds over years before any charges are filed: grand jury subpoenas for documents arrive, cooperating witnesses are flipped by promises of leniency, and target letters signal that prosecutors believe they have enough evidence to indict. The defense attorney must simultaneously manage the criminal exposure, parallel civil investigations by regulators like the SEC, and the reputational and employment consequences that can be as devastating as a conviction. These cases matter because they test whether complex financial wrongdoing — which can cause catastrophic harm to investors, employees, and the public — is prosecuted vigorously and fairly, and whether the accused receives the constitutional protections to which every defendant is entitled.',
    purpose: 'To ensure fair prosecution of complex financial crimes while protecting constitutional rights of defendants.',
    typicalIssues: ['Wire and mail fraud', 'Securities fraud', 'Money laundering', 'FCPA violations', 'Health care fraud'],
    commonEvidence: ['Financial records and transactions', 'Electronic communications', 'Corporate documents', 'Cooperating witness testimony', 'Expert forensic accounting'],
    courtProcess: 'Federal prosecution by DOJ and U.S. Attorneys. Grand jury investigations. Target letters and proffer agreements. Parallel civil SEC investigation. Deferred and non-prosecution agreements. Corporate monitors. Sentencing guidelines calculation.',
    keyPrinciples: ['Conscious avoidance doctrine', 'Honest services fraud', 'McNally limits on mail fraud', 'Extraterritoriality of FCPA', 'Individual accountability (Yates Memo)'],
    practicalExamples: ['Enron executives prosecution', 'SAC Capital insider trading', 'VW emissions fraud', 'COVID PPP fraud prosecutions'],
    icon: 'AlertCircle',
    color: '#1a1a3a',
    difficulty: 'Expert',
    estimatedStudyHours: 22,
  },
  {
    name: 'Energy and Natural Resources',
    slug: 'energy-natural-resources',
    category: 'Regulatory',
    description: 'Energy and natural resources litigation governs the legal conflicts that arise from the extraction, transportation, sale, and regulation of the fuels and raw materials that power the modern economy — oil, natural gas, coal, uranium, and an expanding portfolio of renewable energy sources. A dispute over royalties owed to a landowner under an oil-and-gas lease might turn on whether natural gas liquids extracted at a processing plant were "produced at the wellhead," a technical question whose answer can be worth hundreds of millions of dollars when multiplied across an entire producing formation. At the regulatory end, a challenge to a FERC order setting the rate that a natural gas pipeline may charge shippers is litigated before a specialized administrative body using economic modeling and rate-of-return analysis. These cases matter because energy policy is inseparable from environmental, economic, and national security policy, and the courtroom is where competing interests — producers, consumers, regulators, landowners, and communities — resolve their most fundamental conflicts.',
    purpose: 'To resolve competing interests in energy development, environmental protection, and public utility regulation.',
    typicalIssues: ['Oil and gas royalty disputes', 'Pipeline siting challenges', 'FERC rate proceedings', 'Renewable energy permitting', 'Mineral rights conflicts'],
    commonEvidence: ['Lease agreements and documents', 'Geological and engineering reports', 'Regulatory filings and orders', 'Environmental impact statements', 'Market pricing data'],
    courtProcess: 'FERC administrative proceedings. State utility commissions. Federal district courts for NEPA challenges. Specialized oil and gas courts in Texas and Oklahoma. Indian land rights in tribal courts. Export control proceedings.',
    keyPrinciples: ['Rule of capture for oil and gas', 'Correlative rights doctrine', 'Filed rate doctrine', 'Prudent operator standard', 'PURPA qualifying facility rights'],
    practicalExamples: ['Fracking water rights disputes', 'Solar farm permitting challenges', 'LNG export terminal approvals', 'Tribal oil rights cases'],
    icon: 'Zap',
    color: '#5f4a1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Sports and Entertainment Law',
    slug: 'sports-entertainment',
    category: 'Business',
    description: 'Sports and entertainment law litigation addresses the disputes that arise in industries built on talent, celebrity, and intellectual property — from an NFL player challenging a league disciplinary ruling, to a recording artist seeking to reclaim the master recordings of her early albums, to a college athlete asserting that the NCAA\'s limits on compensation violate federal antitrust law. These industries sit at the intersection of labor law, intellectual property, contract law, and constitutional free expression, making them a uniquely complex practice area where the personalities involved are known to millions and the public scrutiny is intense. The emergence of name, image, and likeness rights for college athletes has generated a wave of contract, antitrust, and constitutional litigation that is reshaping the economics of college sports. These cases matter not just to the parties involved but because they define the boundaries of creative freedom, fair compensation, and market competition in industries that reflect and shape popular culture.',
    purpose: 'To protect creative rights, enforce entertainment contracts, and regulate sports competition.',
    typicalIssues: ['Athlete contract disputes', 'Defamation claims', 'Right of publicity', 'Antitrust in sports', 'NIL (Name, Image, Likeness)'],
    commonEvidence: ['Agent and player contracts', 'Media agreements', 'Social media evidence', 'Expert valuation of celebrity rights', 'League governance documents'],
    courtProcess: 'Sports disputes often in arbitration under league rules. Labor arbitration for player-management disputes. Federal courts for antitrust. California courts for entertainment. Injunctive relief in free agency disputes.',
    keyPrinciples: ['Right of publicity vs. First Amendment', 'Single entity doctrine in sports', 'Non-statutory labor exemption', 'Options in entertainment contracts', 'Moral rights in creative works'],
    practicalExamples: ['Tom Brady deflategate arbitration', 'NIL college athlete cases', 'Music streaming royalties', 'Film production disputes'],
    icon: 'Trophy',
    color: '#5f1a5f',
    difficulty: 'Intermediate',
    estimatedStudyHours: 12,
  },
  {
    name: 'Banking and Finance Litigation',
    slug: 'banking-finance',
    category: 'Financial',
    description: 'Banking and finance litigation encompasses the disputes that arise from lending, deposit-taking, trading, and the full range of financial products and services offered by banks, credit unions, broker-dealers, and other financial institutions. When a national bank forecloses on thousands of homes using faulty affidavits signed by employees who never reviewed the underlying loan files — a practice that became known as "robo-signing" — the resulting litigation involves state attorneys general, federal regulators, class-action plaintiffs\' lawyers, and the banks themselves in a multi-front legal war that produced the $25 billion National Mortgage Settlement. At the wholesale end of the market, disputes over complex derivative instruments like interest-rate swaps and credit-default swaps can turn on the interpretation of a single line of a 300-page ISDA Master Agreement. These cases matter because financial institutions occupy a uniquely leveraged position in the economy, and their misconduct — whether in consumer lending or capital markets — can destabilize the broader financial system and devastate ordinary borrowers.',
    purpose: 'To regulate the financial system, protect consumers, and resolve disputes arising from banking transactions.',
    typicalIssues: ['Loan default and foreclosure', 'TILA and RESPA violations', 'Fair lending discrimination', 'Credit card dispute resolution', 'Derivative contract disputes'],
    commonEvidence: ['Loan documents and correspondence', 'Credit reports and underwriting files', 'Trading confirmations', 'ISDA master agreements', 'Bank examination reports'],
    courtProcess: 'State foreclosure procedures vary widely. Federal court for national bank claims. OCC, Federal Reserve, FDIC enforcement. CFPB enforcement actions. Bank secrecy act proceedings. ISDA dispute resolution protocols.',
    keyPrinciples: ['National Bank Act preemption', 'TILA rescission rights', 'Fair Housing Act disparate impact', 'Good faith and fair dealing in lending', 'Netting in derivative insolvency'],
    practicalExamples: ['2008 mortgage crisis litigation', 'Wells Fargo fake accounts settlement', 'LIBOR manipulation cases', 'Cryptocurrency exchange disputes'],
    icon: 'DollarSign',
    color: '#1a5f1a',
    difficulty: 'Advanced',
    estimatedStudyHours: 20,
  },
  {
    name: 'Labor and Union Litigation',
    slug: 'labor-union',
    category: 'Labor',
    description: 'Labor and union litigation enforces the National Labor Relations Act and related statutes that govern the collective rights of workers to organize, bargain, and engage in concerted activity — rights that have shaped the economic and social landscape of the United States since the New Deal era. When workers at a warehouse distribute union leaflets in the parking lot and the employer responds by firing the most vocal organizers and scheduling mandatory anti-union meetings, the NLRB\'s regional office may issue a complaint alleging unfair labor practices, triggering a hearing before an administrative law judge. Unions and employers also litigate the meaning of collective bargaining agreements in arbitration, with courts deferring to arbitrators\' interpretation under the labor trilogy cases. These cases matter because the balance of power between labor and management — over wages, benefits, working conditions, and job security — is still fought out in courtrooms and agency proceedings as vigorously as it ever was on the picket line.',
    purpose: 'To protect workers right to organize and balance collective bargaining power between labor and management.',
    typicalIssues: ['Unfair labor practice charges', 'Union election objections', 'Duty of fair representation', 'Arbitration of grievances', 'Successorship obligations'],
    commonEvidence: ['NLRB election records', 'Employer communications to workers', 'Union authorization cards', 'Collective bargaining agreements', 'Arbitration awards'],
    courtProcess: 'NLRB regional offices investigate ULP charges. ALJ hearings. NLRB board decisions. Court of Appeals enforcement. Section 301 suits for CBA violations. Norris-LaGuardia Act limits on injunctions. Boys Markets exception.',
    keyPrinciples: ['Protected concerted activity', 'Appropriate bargaining unit determination', 'Weingarten rights', 'Garmon preemption', 'Successorship doctrine'],
    practicalExamples: ['Amazon union organizing campaigns', 'NFL player strikes', 'Hospital union elections', 'Gig worker organizing'],
    icon: 'Users',
    color: '#5f1a3a',
    difficulty: 'Intermediate',
    estimatedStudyHours: 15,
  },
  {
    name: 'Elder Law and Estate Litigation',
    slug: 'elder-estate',
    category: 'Personal',
    description: 'Elder law and estate litigation addresses disputes over wills, trusts, guardianships, conservatorships, and the financial abuse of elderly or incapacitated individuals — a practice area whose importance grows as the population ages and the wealth held by older Americans becomes an increasingly significant target for exploitation. A will contest might allege that a 90-year-old testator who changed her estate plan three months before death, cutting out her children and leaving everything to a new caregiver, lacked the mental capacity to execute a valid will or was subjected to undue influence that overcame her independent judgment. Proving or disproving these claims requires medical records, psychiatric evaluations, testimony from the witnesses to the will, and sometimes forensic handwriting analysis. These cases matter because they determine whether a person\'s final wishes are honored or overridden, and whether vulnerable elderly individuals are protected from the predatory conduct that can strip them of a lifetime\'s savings.',
    purpose: 'To protect vulnerable elderly persons and ensure their wishes are honored in estate planning and administration.',
    typicalIssues: ['Will contests for lack of capacity', 'Undue influence claims', 'Trust disputes', 'Guardianship and conservatorship', 'Elder financial abuse'],
    commonEvidence: ['Medical records on mental capacity', 'Estate planning documents', 'Financial transaction records', 'Witness testimony on testator condition', 'Expert psychiatric evaluation'],
    courtProcess: 'Probate court jurisdiction. Supervised and unsupervised administration. Will contest trial with jury possible. Guardian ad litem for incapacitated persons. APS (Adult Protective Services) involvement. Conservatorship hearings.',
    keyPrinciples: ['Testamentary capacity standard', 'Undue influence elements', 'Breach of fiduciary duty', 'Anti-contest clause enforcement', 'Revocable trust administration'],
    practicalExamples: ['Celebrity estate disputes', 'Elder financial abuse cases', 'International estate conflicts', 'Digital assets in estates'],
    icon: 'Users',
    color: '#3a3a5f',
    difficulty: 'Intermediate',
    estimatedStudyHours: 12,
  },
  {
    name: 'Cybercrime and Digital Forensics',
    slug: 'cybercrime',
    category: 'Criminal',
    description: 'Cybercrime and digital forensics litigation addresses criminal and civil cases in which computers, networks, and digital infrastructure are either the instrument or the target of unlawful conduct — ranging from a teenager who gains unauthorized access to a school\'s grade database, to a state-sponsored group that deploys ransomware to extort hundreds of hospitals, to a dark-web marketplace that facilitates the sale of fentanyl and stolen financial data to thousands of customers worldwide. Digital evidence presents unique evidentiary challenges: metadata can establish when a file was created or accessed, blockchain records can trace the flow of cryptocurrency across wallets and exchanges, and network logs can narrow attribution to a specific IP address — but all of these require expert forensic analysis and careful attention to chain-of-custody protocols to be admissible. The Fourth Amendment jurisprudence governing digital searches is still rapidly developing, with courts grappling with questions like whether law enforcement can compel a suspect to provide a biometric unlock of a smartphone without implicating the Fifth Amendment. These cases matter because the increasing digitization of crime demands sophisticated legal frameworks that balance effective law enforcement with robust civil liberty protections.',
    purpose: 'To prosecute digital crimes and protect individuals and organizations from cyber threats.',
    typicalIssues: ['Computer Fraud and Abuse Act violations', 'Ransomware prosecution', 'Digital evidence admissibility', 'Attribution challenges', 'Darknet criminal enterprises'],
    commonEvidence: ['Digital forensic analysis', 'Network logs and metadata', 'Cryptocurrency transaction records', 'IP address attribution', 'Expert cybersecurity testimony'],
    courtProcess: 'DOJ Computer Crime Section prosecution. FBI digital forensics. International cooperation with Mutual Legal Assistance Treaties. Fourth Amendment digital search standards. Chain of custody for digital evidence. Expert testimony on technical matters.',
    keyPrinciples: ['Particularity requirement for digital searches', 'Plain view doctrine digital limitations', 'Carpenter ruling on location data', 'CFAA exceeds authorized access', 'Attribution standards'],
    practicalExamples: ['Colonial Pipeline ransomware prosecution', 'Silk Road prosecution', 'Election interference investigations', 'Corporate espionage cases'],
    icon: 'Monitor',
    color: '#1a1a5f',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'International Trade Litigation',
    slug: 'international-trade',
    category: 'International',
    description: 'International trade litigation encompasses the administrative proceedings, specialized court cases, and multilateral dispute settlement mechanisms that govern how goods and services move across national borders — including antidumping and countervailing duty investigations, customs classification disputes, and challenges to tariffs imposed under national security or safeguard provisions. When the U.S. Department of Commerce determines that a foreign steel producer is selling products in the American market at less than fair value, the resulting antidumping order can add a duty of 200 percent or more to the cost of every ton imported, reshaping competitive dynamics across an entire industry. WTO dispute settlement was the world\'s primary forum for resolving government-to-government trade conflicts until the Appellate Body lost its quorum in 2019, leaving the system in crisis and pushing trade disputes back toward bilateral negotiation and unilateral retaliation. These cases matter because the rules of international trade directly determine which industries survive, which workers keep their jobs, and which countries can participate on fair terms in the global economy.',
    purpose: 'To enforce trade agreements, protect domestic industries from unfair competition, and facilitate legitimate trade.',
    typicalIssues: ['Anti-dumping proceedings', 'Countervailing duty investigations', 'Section 232 national security tariffs', 'WTO dispute settlement', 'Country of origin determinations'],
    commonEvidence: ['Cost of production data', 'Sales and pricing records', 'Import and export documentation', 'Technical product specifications', 'Government subsidy programs'],
    courtProcess: 'ITC and Commerce Department administrative proceedings. CIT (Court of International Trade) judicial review. CAFC appeals. WTO Appellate Body (now dysfunctional). USMCA dispute panels. Customs classification protests.',
    keyPrinciples: ['Less than fair value standard', 'Material injury threshold', 'Circumvention determinations', 'National treatment principle', 'Most favored nation obligation'],
    practicalExamples: ['China steel dumping cases', 'Solar panel tariff disputes', 'Boeing-Airbus WTO dispute', 'USMCA auto content rules'],
    icon: 'Ship',
    color: '#1a3a3a',
    difficulty: 'Expert',
    estimatedStudyHours: 22,
  },
  {
    name: 'Defamation and Media Law',
    slug: 'defamation-media',
    category: 'Civil',
    description: 'Defamation and media law litigation adjudicates the tension between freedom of the press and the right of individuals to protect their reputations from false and damaging statements — a tension that the Supreme Court in New York Times v. Sullivan resolved in favor of robust press freedom by requiring public officials to prove that a defendant acted with "actual malice," meaning knowledge of falsity or reckless disregard for the truth. The $787.5 million settlement that Fox News paid to Dominion Voting Systems in 2023, days before trial, illustrated both the enormous financial stakes of defamation litigation and how internal communications — texts, emails, and deposition testimony revealing what on-air personalities actually believed about the claims they were broadcasting — can become the most damaging evidence in a media law case. Anti-SLAPP statutes in many states allow defendants to seek early dismissal and attorney\'s fees when sued for speech on matters of public concern, providing a powerful tool against the use of litigation to silence critics. These cases matter because the outcome shapes the practical boundaries of what journalists, commentators, and ordinary citizens can say about powerful individuals and institutions without facing ruinous liability.',
    purpose: 'To balance First Amendment press freedom against individual rights to reputation and privacy.',
    typicalIssues: ['Defamation per se and per quod', 'Public figure actual malice standard', 'Invasion of privacy torts', 'False light claims', 'Anti-SLAPP motions'],
    commonEvidence: ['Publication records', 'Editorial process documents', 'Source credibility evidence', 'Truth defense documentation', 'Expert testimony on reputation harm'],
    courtProcess: 'Anti-SLAPP statutes provide early dismissal in many states. Discovery of journalists\' sources contested. Actual malice standard for public figures requires clear and convincing evidence. Retraction as mitigation. Shield laws protect sources.',
    keyPrinciples: ['Actual malice for public officials (NYT v. Sullivan)', 'Substantial truth defense', 'Opinion vs. fact distinction', 'Section 230 internet immunity', 'Neutral reportage privilege'],
    practicalExamples: ['Fox News Dominion Voting settlement', 'Johnny Depp-Amber Heard defamation', 'Nick Sandmann CNN settlement', 'Alex Jones Sandy Hook trial'],
    icon: 'Newspaper',
    color: '#3a1a5f',
    difficulty: 'Intermediate',
    estimatedStudyHours: 15,
  },
  {
    name: 'Environmental Justice Litigation',
    slug: 'environmental-justice',
    category: 'Constitutional',
    description: 'Environmental justice litigation challenges the documented pattern by which environmental harms — industrial pollution, hazardous waste facilities, contaminated water supplies, and toxic air emissions — are disproportionately concentrated in low-income communities and communities of color, whose residents lack the political and economic resources to resist the siting decisions that impose these burdens on them. The Cancer Alley corridor along the Mississippi River between New Orleans and Baton Rouge, home to dozens of petrochemical plants and some of the highest cancer rates in the nation, has become a focal point for litigation that combines Title VI civil rights complaints to the EPA, state court nuisance actions, and federal constitutional equal protection claims. Proving discriminatory intent — as opposed to disparate impact — is a formidable legal hurdle that has limited the success of some claims, driving advocates toward Title VI administrative remedies and the growing body of state environmental justice statutes that require agencies to consider cumulative impacts in permitting decisions. These cases matter because they represent the intersection of civil rights and environmental law, and their outcomes determine whether the promise of equal protection extends to protection from the physical environment in which people live, work, and raise their children.',
    purpose: 'To ensure equal protection from environmental harms and provide access to environmental benefits for all communities.',
    typicalIssues: ['Title VI environmental discrimination', 'EJ considerations in permitting', 'Cumulative impact analysis', 'Community benefit agreements', 'Climate justice claims'],
    commonEvidence: ['Demographic and health data', 'Pollution mapping data', 'Permit application records', 'Community testimony', 'Expert epidemiological analysis'],
    courtProcess: 'Administrative complaints to EPA under Title VI. Federal court civil rights actions. State court nuisance claims. Participation in regulatory proceedings. Citizen suit provisions in environmental statutes.',
    keyPrinciples: ['Environmental justice executive orders', 'Disparate impact under Title VI', 'Cumulative risk assessment', 'Meaningful involvement requirement', 'National Environmental Justice Advisory Council'],
    practicalExamples: ['Flint Michigan lead water crisis', 'Cancer Alley Louisiana refinery cases', 'Port truck driver air quality suits', 'Standing Rock pipeline protests'],
    icon: 'Leaf',
    color: '#1a4a2a',
    difficulty: 'Advanced',
    estimatedStudyHours: 18,
  },
  {
    name: 'Court Hierarchy & Jurisdiction',
    slug: 'court-hierarchy',
    category: 'Foundational',
    description: 'Court hierarchy and jurisdiction describe the structured, multi-tiered architecture of the American judicial system — a system in which trial courts first find the facts and apply the law, intermediate appellate courts review those decisions for legal error, and courts of last resort (supreme courts) resolve the most consequential and contested legal questions with finality and binding authority. The United States operates two parallel court systems — a federal system created by Article III of the Constitution and the fifty separate state systems — each with its own trial courts, intermediate appellate courts, and supreme court, though the U.S. Supreme Court sits atop both systems as the final arbiter of federal and constitutional law. Jurisdiction is the threshold question in every lawsuit: a court must have both subject-matter jurisdiction (authority over the type of dispute) and personal jurisdiction (authority over the parties) before it can adjudicate a case, and a judgment entered without either is void. Understanding how a case travels upward through the hierarchy — from trial court through discretionary review in a supreme court that grants certiorari to fewer than two percent of petitions — is essential to predicting where litigation will be fought and how far it can go.',
    purpose: 'Understanding the structure and hierarchy of courts — including which court hears which disputes, how appellate review works, and how binding precedent flows — is the foundational framework upon which every other area of litigation is built. Without this knowledge, practitioners cannot determine where to file, what law applies, which rulings are binding, or how to advise clients about their options on appeal.',
    typicalIssues: ['Subject-matter jurisdiction', 'Personal jurisdiction and minimum contacts', 'Original vs. appellate jurisdiction', 'Federal vs. state court selection', 'Standard of review on appeal'],
    commonEvidence: ['Record on appeal', 'Jurisdictional statements and briefs', 'Certificates of service and filing', 'Court dockets and case management orders', 'Trial transcripts and exhibits'],
    courtProcess: 'A civil or criminal case begins in a trial court of general or limited jurisdiction, where a judge (and sometimes a jury) resolves disputed facts and applies the law to render a judgment. A party aggrieved by the judgment may appeal as of right to an intermediate appellate court, which reviews the trial record for legal error — not to retry facts — and issues a written opinion that becomes binding precedent in that jurisdiction. If the intermediate court affirms or reverses, the losing party may petition a supreme court for further review; most supreme courts, including the U.S. Supreme Court, have discretionary certiorari jurisdiction and accept only a small fraction of petitions, typically those presenting issues of broad legal importance or conflicting lower-court decisions. The supreme court\'s ruling becomes the highest binding authority in the system, controlling every lower court in the jurisdiction unless and until the constitution is amended or the court overrules its own precedent.',
    keyPrinciples: ['Stare decisis — courts must follow precedent', 'Vertical vs. horizontal precedent', 'Finality of judgments', 'Exhaustion of remedies before appellate review', 'Binding vs. persuasive authority'],
    practicalExamples: ['A state criminal conviction appealed through state courts and then to the U.S. Supreme Court on a federal constitutional question', 'A civil lawsuit removed from state court to federal court based on diversity of citizenship', 'A circuit court split on a statutory question resolved by Supreme Court certiorari', 'A habeas corpus petition challenging a federal conviction in the district court of conviction'],
    icon: 'Landmark',
    color: '#3b3b6d',
    difficulty: 'Beginner',
    estimatedStudyHours: 8,
  },
];
